### ISSUE TITLE
Bug: Google Voice Service: Dark Mode

### ISSUE THREAD

**Issue by thwaller** [ferdium/ferdium-app#1005]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-beta.1

### What Operating System are you using?

Other Linux

### Operating System Version

Fedora 36

### What arch are you using?

x64

### Expected Behavior

Dark mode to work as it does on other services.

### Actual Behavior

Dark mode does not properly apply itself. IT is dark only in some areas, mainly dialer buttons.

### Steps to reproduce

1. Set the service to enable dark mode
2. Toggle dark mode in the UI
3. View the Voice service

### Additional information

installed via Flatpak.

**Comment by vraravam** [comment]
@thwaller - thanks for trying out Ferdium, but:
1. Please specify which service is causing the issue
2. Please log all service-specific issues in the https://github.com/ferdium/ferdium-recipes/issues board

**Comment by thwaller** [comment]
It appears it did not add a title, interesting. Sorry about that. The service is Google Voice.

**Comment by thwaller** [comment]
@vraravam thanks for transferring.

**Comment by elderlabs** [comment]
Any progress on this? Dark reader works properly with Google Voice in a Chrome-based browser, but not in Ferdium. I've tried creating custom CSS files to remedy this, but Ferdium appears to cut the background at around half the viewport's height -- while the rest of the custom CSS works as expected (which may be a recipe you're looking for). That issue would seem to be a Ferdium bug, as I've noticed a custom website's native CSS that works properly in a Chrome-based browser does not behave properly in Ferdium. My question is what Ferdium's doing to the background/body element of the page that's breaking it.

This reply could probably be its own issue, but the relevant details are here and the issue _does_ have an effect on the Google Voice page/theme, so building here in hopes of a solution. At the very least, I can share the CSS I'm using from DarkReader that _works_ with Google Voice -- though again, Ferdium's breaking it on the bottom half mid-page vertically.

Thanks.

**Comment by oc013** [comment]
This has been annoying me far too long!

darkmode.css for anyone else that feels the same:
https://gist.github.com/oc013/4f9358915f35d12f6dd96355b0abb7cd

N.B. I didn't cover the settings page or anything like that, just the texts and calls 

I created a PR to the recipes repo: https://github.com/ferdium/ferdium-recipes/pull/449

**Comment by ylluminate** [comment]
This also appears to now be resolved for me as of recently somehow. It was not working before some recent update to Ferdium iteself.

**Comment by oc013** [comment]
> This also appears to now be resolved for me as of recently somehow. It was not working before some recent update to Ferdium iteself.

@ylluminate Yes, I made a custom darkmode.css https://github.com/ferdium/ferdium-recipes/pull/449
