### ISSUE TITLE
Unable to set custom background picture in MS Teams

### ISSUE THREAD

**Issue by alfureu** [ferdium/ferdium-app#1011]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22enhancement+%3Asparkles%3A%22) for a feature request that matches the one I want to file, without success.

### Problem Description

I am unable to set a custom background in MS Teams calls, and the default ones are not acceptable

### Proposed Solution

Maybe there is a solution how to upload a custom background picture to load it for the calls?

### Alternatives Considered

N/A

**Comment by vraravam** [comment]
I dont think this is possible in the web version of teams. Ferdium only renders a web page for each configured service.
