### ISSUE TITLE
Ferdium services display wrong timezone

### ISSUE THREAD

**Issue by aquohn** [ferdium/ferdium-app#1012]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.2.4 (Flatpak)

### What Operating System are you using?

Other Linux

### Operating System Version

Linux 6.1.12-0-lts #1-Alpine SMP PREEMPT_DYNAMIC Thu, 16 Feb 2023 15:34:29 +0000 x86_64 Linux

### What arch are you using?

x64

### Expected Behavior

I expect the timestamps in my services to be presented in my device's timezone.

### Actual Behavior

Timestamps in my services are presented in UTC.

### Steps to reproduce

1. Open a WhatsApp or Telegram chat.
2. The timestamps are in UTC.

### Additional information

I'm using Sway, and Alpine uses OpenRC, if that's relevant.

**Comment by vraravam** [comment]
Ferdium only renders web pages. If the contents within that web page are incorrect, there's nothing Ferdium can do.
