### ISSUE TITLE
[RECIPE] Gitlab Broken

### ISSUE THREAD

**Issue by OskarEichler** [ferdium/ferdium-app#1019]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+%3Abookmark_tabs%3A%22+label%3A%22bug+%3Abeetle%3A%22+) for a bug report that matches the one I want to file, without success.

### Ferdium Version

6.2.5-nightly.9

### Recipe Name

Gitlab

### Recipe Version

1.3.1

### Steps to reproduce

When loading Gitlab it just hangs on the screen that says:

```
Checking your browser before accessing gitlab.com.
```

### Expected Behavior

Usually this screens stays there for a few seconds and then Gitlab loads.

### Actual Behavior

For the past few weeks it just hangs and never completes the browser check.

### Screenshots

![Screenshot 2023-02-23 at 14 18 43](https://user-images.githubusercontent.com/62393985/220833671-d653a17f-9fd8-4be9-8abc-485b6355be6a.jpg)

**Comment by OskarEichler** [comment]
Would be great if someone can take a look! 🙏🏼

**Comment by Arthur-Huan** [comment]
@OskarEichler I don't experience this when I try GitLab right now, can you confirm if this is still an issue for you?

**Comment by OskarEichler** [comment]
This is fixed in the latest versions!
