### ISSUE TITLE
Flatpak version won't respect gnome dark theme

### ISSUE THREAD

**Issue by rmeissn** [ferdium/ferdium-app#1020]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.2.4

### What Operating System are you using?

Other Linux

### Operating System Version

Fedora 37

### What arch are you using?

x64

### Last Known Working Ferdium version

none

### Expected Behavior

When I set my gnome-shell to dark theme, ferdium should also change to a dark theme. Other flatpak apps (like easyeffects) do this.

### Actual Behavior

Setting gnome-shell to dark theme isn't triggering something on the ferdium side. A freshly started ferdium won't respect the dark theme either.
I tested this with manual theme change and also automatic theme changes based on time of day by an extension.

### Steps to reproduce

1. Install  ferdium from flathub
2. Activate that it respects the dark theme of the system
3. Change to dark theme in system settings

**Comment by deadmeu** [comment]
I'm experiencing this as well after switching to the Flatpak. Anyone have any ideas as to which theme related desktop properties are not being read correctly?

**Comment by mcmxcdev** [comment]
Cannot reproduce this on Ubuntu 23.04 using GNOME 44 with Ferdium 6.5.1 flatpak version:

[Screencast from 2023-10-22 11-56-48.webm](https://github.com/ferdium/ferdium-app/assets/16797721/8c345f0b-789d-4bd4-8bf5-09ac9d1e1229)

**Comment by rmeissn** [comment]
Yeah, seems to work by now - also confirmed with some services (e.g. RocketChat).
