### ISSUE TITLE
Ubuntu Freezes After Opening Ferdium from System Tray

### ISSUE THREAD

**Issue by Arthur-Huan** [ferdium/ferdium-app#1026]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.2.4

### What Operating System are you using?

Ubuntu

### Operating System Version

Ubuntu 22.04 LTS

### What arch are you using?

Other (specify in Additional information section)

### Expected Behavior

Expected behaviour is that after opening Ferdium by clicking "Show Ferdium" from the system tray, I will be able to continue to use my computer normally.

### Actual Behavior

This is for both the deb and flatpak. After opening through the system tray, it lags for a few seconds before the window is loaded. After this, Ubuntu freezes. I can still use the Ferdium app, and any programs already running are still running. However:

- The dock (Ubuntu dock or dash-to-dock) becomes unusable.
- Alt-Tab does nothing
- Alt-F2 (in Xorg) does nothing
- Shortcut to open a terminal doesn't work
- Power button to suspend doesn't work
- Ctrl-Alt-F1 does work, but if I log back in to the account, it will still only be the Ferdium app in the foreground with nothing else working.

The only ways I get out of this is to reboot by doing a power reset.

### Steps to reproduce

1. Open Ferdium and load some services (I have three)
2. Close Ferdium (with the setting to minimize to systme tray instead of exiting selected)
3. Wait about half a minute
4. Click the Ferdium system tray icon and click "Show Ferdium"

**Comment by mcmxcdev** [comment]
Cannot reproduce this on Ubuntu 23.04, but I am using the AppImage, so maybe thats why.

Is this still a probem?
