### ISSUE TITLE
web.thndr.app is broken.

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [ferdium/ferdium-app#1028]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+%3Abookmark_tabs%3A%22+label%3A%22bug+%3Abeetle%3A%22+) for a bug report that matches the one I want to file, without success.

### Ferdium Version

6.2.4

### Recipe Name

Thndr

### Recipe Version

idk

### Last Known working version of the recipe

idk

### Steps to reproduce

1. Add custom service (https://web.thndr.app/invest)
2. Load it
3. Login, in send security notification screen the site crashes.

### Expected Behavior

The page stays and not crashes?

### Actual Behavior

the page crashes and ferduim tells me it will auto restart but it crash again

### Screenshots

https://user-images.githubusercontent.com/28893833/221942536-1028a2da-d062-4e15-918b-cb522ede88d8.mp4

**Comment by mcmxcdev** [comment]
Can you still reproduce this? Is there any error message when the screen crashes?

**Comment by EsmailELBoBDev2** [comment]
no it works fine now
