### ISSUE TITLE
Launch on start doesn't work

### ISSUE THREAD

**Issue by deadmeu** [ferdium/ferdium-app#1038]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.2.4

### What Operating System are you using?

Other Linux

### Operating System Version

Linux 6.2.2-arch1-1

### What arch are you using?

x64

### Expected Behavior

"Launch Ferdium on start" should add Ferdium to the Autostart list.

### Actual Behavior

Ferdium is not being added to the Autostart list.

### Steps to reproduce

1. Enable the "Launch Ferdium on start" toggle in Settings
2. Restart or Log out & in
3. Observer that Ferdium has not started

### Additional information

This is likely due to the scenario I am running Ferdium in, which is under KDE Plasma (Wayland) installed from Flathub.

**Comment by vraravam** [comment]
Please try with the latest version and revert back if this is still a problem

**Comment by deadmeu** [comment]
After further testing it looks like this was due to me denying the Flatpak access to my home directory, so it couldn't access the `~/.config/autostart` directory. I'm not sure if there's a Flatpak portal to allow modifying the system's auto-start entries (maybe org.freedesktop.portal.Background?) but I'm happy to close this ticket.

Likely related to https://github.com/ferdium/ferdium-app/issues/1121 and https://github.com/flathub/org.ferdium.Ferdium/issues/24
