### ISSUE TITLE
Absence of yml files in download folder breaks the updater.

### ISSUE THREAD

**Issue by meiphoo7-Mae** [ferdium/ferdium-app#1040]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.2.5-nightly.7

### What Operating System are you using?

Ubuntu

### Operating System Version

23.04

### What arch are you using?

x64

### Expected Behavior

The updater should be able to install an already downloaded update file (Appimage) even if it is not able to search for new updates.

### Actual Behavior

When there are no yml files in the same folder on the download server as where the latest update resides the updater produces an error and is not even able to install an already downloaded update file (Appimage) that is available locally in the updater folder.

Updater error even while there's an already downloaded update file available.
![Screenshot_20230307_052607](https://user-images.githubusercontent.com/95827976/223322255-ff00b27c-bdfa-42dd-8da1-3c625e15d704.png)

The console shows that there's a problem retrieving the correct yml file.
As the left part of the picture shows there's indeed no yml file in the download folder.
![Screenshot_20230307_052158](https://user-images.githubusercontent.com/95827976/223322458-57bf5426-c695-43f5-a4cd-b4a0384a5e38.png)

### Steps to reproduce

There's nothing special required except the situation described above.

### Additional information

I'm aware that this is a corner case if not a race condition but I feel the updater not being able to install an already downloaded file because of a very minor problem is something that is worth to mention.

**Comment by vraravam** [comment]
This in-app-update behavior is coming from the [electron-updater](https://www.electron.build/auto-update) package which is part of the electron-builder tool. Please raise a bug against that package and they can provide workarounds or a mechanism/process to follow for your intended behavior.
