### ISSUE TITLE
Logged out of session upon app start

### ISSUE THREAD

**Issue by Hellmark** [ferdium/ferdium-app#1041]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.2.4

### What Operating System are you using?

Ubuntu

### Operating System Version

22.10

### What arch are you using?

x64

### Expected Behavior

Automatically launch with last session upon start.

### Actual Behavior

Upon start, I am at the screen giving me the options to log into the server, or start without server. Doesn't matter which I used last, each start it goes to that screen.

### Steps to reproduce

1. Have Ferdium running.
2. Exit.
3. Restart app.

### Additional information

Another oddity is that the Settings option under the File menu is always greyed out, but the Gear button will let me access the settings.

**Comment by vraravam** [comment]
Please upgrade to the latest version of Ferdium. We will not be able to support older versions.
