### ISSUE TITLE
Screen sharing causes a crash on Wayland

### ISSUE THREAD

**Issue by ElJeffe** [ferdium/ferdium-app#1044]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.2.5.nightly.10

### What Operating System are you using?

Other Linux

### Operating System Version

arch linux

### What arch are you using?

x64

### Expected Behavior

Screen sharing works

### Actual Behavior

Ferdium crashes

### Steps to reproduce

1. Create a 'custom website' service with website https://www.webrtc-experiment.com/Pluginfree-Screen-Sharing
2. click the 'Share Your Screen'

### Additional information

This used to work, I do not know when it stopped working (I tested 6.2.4 and it also crashes)
I start ferdium with 
`ferdium --ozone-platform=wayland --enable-features=UseOzonePlatform,WebRTCPipeWireCapturer`

Tried on Sway and Hyprland with xdg-desktop-portal-wlr and xdg-desktop-portal-hyprland-git seperately.

**Comment by ElJeffe** [comment]
I just tried it on 6.2.6.nightly.1 and it is still present.

**Comment by hadogenes** [comment]
It looks like elecron bug (electron/electron#36660). eg. jitsi-meet uses older elecron (jitsi/jitsi-meet-electron#829)

**Comment by hadogenes** [comment]
for me last good version was 6.2.3

**Comment by ElJeffe** [comment]
> for me last good version was 6.2.3

yes indeed, this version works.

**Comment by hadogenes** [comment]
yeah elecron version is the problem - when I changed elecron version to latest 21 (21.4.2) in _package.json_ screen sharing works

**Comment by dan-myles** [comment]
I'm still getting crashes on electron version 22.3.3 and ferdium 6.2.6-1

**Comment by bshamanov** [comment]
Getting crashes here. Wayland on Fedora 37. Any plans to fix that? I am using Ferdium for Teams and screen share not working is very problematic!

Version: 6.2.6
Server: No Server
Electron: 23.2.0
Chrome: 110.0.5481.192
Node.js: 18.12.1
Platform: Linux 6.2
Arch: x64
Build date: Thu Mar 30 2023 04:48:19 GMT+0300 (Eastern European Summer Time)
Git SHA: 28d1f763
Git branch: release

**Comment by gza** [comment]
There is valuable info here about the potential root cause and solutions https://github.com/electron/electron/issues/36660

As the origin of the problem seems to be in Chromium, I don't fully understand why Teams (for example) is impacted in electron and not in recent Chromium (the patch is 9 months old)

**Comment by digrouz** [comment]
I face the same issue with flatpak 6.3.0 on wayland on Opensuse Tumbleweed.

**Comment by ElJeffe** [comment]
This seems to be fixed since https://github.com/ferdium/ferdium-app/releases/tag/v6.4.1-nightly.4
