### ISSUE TITLE
Problems and New features to be implemented.

### ISSUE THREAD

**Issue by Nickyg001** [ferdium/ferdium-app#1045]
### Your issue

I have version 6.2.4.

1. The bar at the top file, edit, etc. has disappeared... how do I get it back?
2. it is possible to set a Default folder where to save the downloaded documents (whatsapp, gmail..etc.) "e.g. Desktop"
3. Having a 4K monitor the font-size is very small. is there any way to enlarge it?
Or insert a new functionality where it is possible to resize, enlarge the UI ... now everything is really small ...

**Comment by ElJeffe** [comment]
>     1. The bar at the top file, edit, etc. has disappeared... how do I get it back?
Press ALT :)

**Comment by Nickyg001** [comment]
> > ```
> > 1. The bar at the top file, edit, etc. has disappeared... how do I get it back?
> > ```
> 
> Press ALT :)

nothing happens if I press ALT!!! :'(

**Comment by vraravam** [comment]
hi @Nickyg001 :
1. Please do not post multiple issues/requests in the same ticket. We cannot manage them collectively.
2. please use the issue template to describe your environment (machine, OS, etc as requested in the template)
