### ISSUE TITLE
Mac OS X - Close to Menu Bar (hide dock item)

### ISSUE THREAD

**Issue by zeknoss** [ferdium/ferdium-app#1051]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22enhancement+%3Asparkles%3A%22) for a feature request that matches the one I want to file, without success.

### Problem Description

Hi,
There is no multi-platform communication app with menu bar icon but Ferdium that is close to my requirements.

### Proposed Solution

I want to use the Ferdium only via menu bar icon on top of my Mac UI. I don't want to see the app icon in the dock at all. Single click to show, single click to hide it to menu bar, that is all.

Thank you very much for your time.

### Alternatives Considered

I tried nearly every single competitor on the market. Some of them didn't even have a menu bar icon support, and those who had it isn't utilizing the menu bar icon at all.

Ferdium is closest to my requirements.

**Comment by mcpent** [comment]
I would like that too, if possibile: an option to hide the icon from the dock, like you may hide the icon from the menu bar.

Anyway thanks for the effort, Ferdium is just great!

Marco

**Comment by vraravam** [comment]
According to [this post](https://superuser.com/questions/217649/show-hide-application-icon-in-dock), this needs a change in the `Info.plist` file. But, based on our codebase and build steps, such a tweak is not possible to be exposed as a user-preference. For those users who want this behavior, you will have to do this manually following the steps in the above link. Closing the ticket for now.
