### ISSUE TITLE
Google Tasks please

### ISSUE THREAD

**Issue by EngDavidMead** [ferdium/ferdium-app#1058]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22enhancement+%3Asparkles%3A%22) for a feature request that matches the one I want to file, without success.

### Problem Description

Im always frustrated that google tasks are missing here cuz I am forced to use the sidebar from the chrome extension called Manganum. And the fact that your tool cant be a sidebar

### Proposed Solution

PLease implement the google tasks in the tool as well as the option to be always up as a sidebar or if I scroll in a part of the screen, the tool to show up. THank you

### Alternatives Considered

Manganum

**Comment by vraravam** [comment]
you can use Google Tasks in the Todos panel.
<img width="659" alt="Screenshot 2023-05-28 at 10 17 20 PM" src="https://github.com/ferdium/ferdium-app/assets/69629/19516b77-aa6c-4298-ac8f-8f322bb6337a">
