### ISSUE TITLE
Bug: Linux ferdium.desktop file is broken after PR98

### ISSUE THREAD

**Issue by cedricroijakkers** [ferdium/ferdium-app#106]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.27

### What Operating System are you using?

Other Linux

### Operating System Version

Arch, btw

### What arch are you using?

x64

### Last Known Working Ferdium version

6.0.0-nightly.26

### Expected Behavior

The `.desktop` file now has a multi-line Comment block:

```
[Desktop Entry]
Name=Ferdium
Exec=/usr/bin/ferdium %U
Terminal=false
Type=Application
Icon=ferdium
StartupWMClass=Ferdium
Comment=Ferdium is your messaging app / former heir to the throne of Austria-Hungary and combines chat & messaging services into one application.
Ferdium currently supports Slack, WhatsApp, Gmail, Facebook Messenger, Telegram, Google Hangouts, GroupMe, Skype and many more.
You can download Ferdium for free for Mac, Windows, and Linux.
For enabling webcam access you need to connect "camera" plug to snap, and for microphone with PulseAudio - "pulseaudio" plug.
This can be done in Snap GUI or via command: `snap connect ferdium:camera; snap connect ferdium:pulseaudio`.

MimeType=x-scheme-handler/ferdium;
Categories=Network;InstantMessaging;
```

This is not allowed, and happened after https://github.com/ferdium/ferdium-app/pull/98

### Actual Behavior

This should be a single line.

### Steps to reproduce

Install 6.0.0-nightly.27 via the `.deb` package.

### Additional information

I will submit a PR to fix it.

**Comment by cedricroijakkers** [comment]
Will test after next nightly to make sure the issue is solved.

**Comment by vraravam** [comment]
@cedricroijakkers - were you able to test this?

**Comment by cedricroijakkers** [comment]
@vraravam Yes, and test succeeded. Issue can be closed.
