### ISSUE TITLE
Drag and Drop files in Telegram on MacOS does not work

### ISSUE THREAD

**Issue by martin-braun** [ferdium/ferdium-app#1065]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+%3Abookmark_tabs%3A%22+label%3A%22bug+%3Abeetle%3A%22+) for a bug report that matches the one I want to file, without success.

### Ferdium Version

6.2.4

### Recipe Name

Telegram

### Recipe Version

3.3.5

### Steps to reproduce

Try to drag and drop a file in a chat. Nothing happens.

### Expected Behavior

I can upload a file via drag and drop.

### Actual Behavior

The hover action of the cursor with the file is ignored.

### Screenshots

![2023-03-20 1 40 49 AM](https://user-images.githubusercontent.com/24259245/226221467-f927d2b1-2b23-40d0-a0dd-b4c9c8b2222f.gif)

### Additional Information

It works on WhatsApp. It also worked on Telegram@Ferdi where I am coming from.

**Comment by thehunmonkgroup** [comment]
I can confirm drag and drop is broken for Telegram in Ferdium on Ubuntu 22.04 as well.

**Comment by martin-braun** [comment]
@thehunmonkgroup I totally forgot about this issue, it worked again on the next day, so things work as expected. It's not reproducable for me anymore. Can you try to see if restarting Ferdium solves it?

**Comment by thehunmonkgroup** [comment]
Restarting Ferdium does not fix it. However, I'm noticing there are other programs on my system that aren't working for drag and drop, either -- both Chromium and Opera don't work.

Curiously, Firefox works fine.

I thought maybe it was an issue with Flatpak and Snap installed apps, but I have Opera browser installed from .deb package, and that doesn't work, either.

Also, drag and drop worked perfectly fine in Ferdium until about a week or two ago.

**Comment by martin-braun** [comment]
@thehunmonkgroup I think both of us have/had problems that aren't related to Ferdium, so I gonna close this. Unfortunately, I don't know what fixed it for me and even if I would knew, it most likely is not related to your issue.

Good luck finding the root cause of this.
