### ISSUE TITLE
Missing 6.2.5 release ?

### ISSUE THREAD

**Issue by Gaibhne** [ferdium/ferdium-app#1070]
### Your issue

I noticed nightlies have moved from 6.2.5 to 6.2.6, yet stable is still as 6.2.4. Was 6.2.5 intentionally not published to the stable branch, or am I missing something ? I have updates enabled, yet it still claims 6.2.4 is the latest version. Or am I misunderstanding how releases work with Ferdium ?

**Comment by vraravam** [comment]
hmm - interesting, i hadn't noticed this at all!

**Comment by vraravam** [comment]
Closing this since we can't resurrect an older version (the build scripts have changed since then)
