### ISSUE TITLE
I use Whatsapp and I could not find a way to mute its notification sounds

### ISSUE THREAD

**Issue by leoheck** [ferdium/ferdium-app#1071]
### Your issue

Is there any way of doing that for each service or maybe for the whole application?

Currently using
```
Version: 6.2.6-nightly.8
Server: No Server
Electron: 23.1.4
Chrome: 110.0.5481.192
Node.js: 18.12.1
Platform: Linux 5.19
Arch: x64
Build date: Mon Mar 20 2023 23:44:47 GMT-0300 (Brasilia Standard Time)
Git SHA: b3a11591
Git branch: nightly
```

**Comment by kishaningithub** [comment]
@leoheck I had that annoying problem to, in this case feridum is not at fault. The solution is to disable the notification sound in the setting of the whatsapp web (screenshots below)


1. In whatsapp web to to settings.
<img width="204" alt="image" src="https://user-images.githubusercontent.com/763760/231353578-8aa174a7-be24-4203-bdf5-5496e59470f6.png">

2. Inside notification uncheck the last option "sounds" as i have done below
<img width="459" alt="image" src="https://user-images.githubusercontent.com/763760/231353514-b6310994-1307-4ba5-a0a1-f79c43df5b12.png">

**Comment by leoheck** [comment]
Thanks, @kishaningithub, it took me some time, but I found this. Thanks.
Now, this should be disabled by default, those sounds are annoying as fuck.
