### ISSUE TITLE
The globalShortcut is not working on Mac

### ISSUE THREAD

**Issue by irvin** [ferdium/ferdium-app#1073]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.2.4

### What Operating System are you using?

macOS

### Operating System Version

macOS 13.2.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

When clicking `alt-x` the Ferdium app should be hidden.

### Actual Behavior

Nothing happened.

### Steps to reproduce

- Turn on "Enable Global shortcut to hide Ferdium" in settings
- Restart Ferdium
- Try different combination of option-x / control-x / command-x / fn-x, nothing work as hiding Ferdium.

### Additional information

According to the code below, we should able to hide the ferdium window with `alt-x`. 
However, it doesn't work here, as well as `command-x`, `option-x`, `fn-x`, `control-x`, cannot find any combination that can successfully show/hide the app.  
Had tried toggle "Enable Global shortcut to hide Ferdium" in the setting to on or off and neither does affect it. 
https://github.com/ferdium/ferdium-app/blob/23290bb51c2945ebf37ad5f347e2380c6fd66302/src/index.ts#L434

Also found a similar issue* on Reddit that the option is not clear that how it works.
https://www.reddit.com/r/ferdium/comments/11c9k0v/what_is_this_option_enable_global_shortcut_to/

**Comment by vraravam** [comment]
I'm able to hide Ferdium using `Option+x` on macos. I'm running ventura on an m1. Please confirm with the latest nightly and revert back if this is still an issue.

**Comment by irvin** [comment]
confirmed work correctly on 6.3.0 / Ventura / M1, thanks.
