### ISSUE TITLE
LINE Works:  chat and group-ware service for enterprise

### ISSUE THREAD

**Issue by miurahr** [ferdium/ferdium-app#1077]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+request+%3Asparkles%3A%22) for a recipe request that matches the one I want to file, without success.

### Name of the service

LINE WORKS

### URL of the service

https://line.worksmobile.com/jp/en/

### GitHub URL to a recipe that has already been created by someone else or you

https://github.com/miurahr/ferdium-recipes/tree/topic/miurahr/new/line-works

### Features you want implemented

- Open LINE WORKS chat site
- Show notification of messages

**Comment by atb79** [comment]
this would be nice
