### ISSUE TITLE
Bug: overly verbose and inappropriate Comment in installed .desktop file

### ISSUE THREAD

**Issue by philclifford** [ferdium/ferdium-app#1079]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.2.4

### What Operating System are you using?

Ubuntu

### Operating System Version

Ubuntu Mate 22.04.2

### What arch are you using?

x64

### Expected Behavior

After installing from github latest release .deb via `deb-get` the DE Menu item (classic and Brisk) on hover should display a minimal informative comment or nothing

### Actual Behavior

The ferdium menu item shows a huge tool-tip on hover (from the .desktop file comment ? - nothing else shows the Comment though ...), including blurb that it can be downloaded for free ( I know, I just did and even installed it!) , that it supports lots of platforms (but I only care at this moment that it supports the one I'm running, and since it is in the menus now I hope that is the case), and that I need to fix up some snap permissions for audio etc - except it is not the snap but the deb so is not confined ....

Please could you provide appropriate Comment= text for the .desktop file (and whatever else is needed) depending on whether the app has been installed via apt / dpkg from a .deb or using the snap

### Steps to reproduce

Install the latest 6.2.4 release .deb  from github on  ubuntu-mate
search ferdium in the brisk or classic menu
hover over the Ferdium desktop entry

**Comment by marie-bnl** [comment]
> Ferdium is your messaging app / former heir to the throne of Austria-Hungary and combines chat & messaging services into one application. Ferdium currently supports Slack, WhatsApp, Gmail, Facebook Messenger, Telegram, Google Hangouts, GroupMe, Skype and many more. You can download Ferdium for free for Mac, Windows, and Linux. For enabling webcam access you need to connect "camera" plug to snap, and for microphone with PulseAudio - "audio-record" plug. This can be done in Snap GUI or via command: `snap connect ferdium:camera; snap connect ferdium:audio-record`.

This is much too verbose a description indeed! I suggest we use the repository’s description:

>  All your services in one place, built by the community

Or the synopsis:

> Messaging app for WhatsApp, Slack, Telegram, Gmail, Hangouts and many many more.
