### ISSUE TITLE
Have web based version

### ISSUE THREAD

**Issue by weblot** [ferdium/ferdium-app#1080]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22enhancement+%3Asparkles%3A%22) for a feature request that matches the one I want to file, without success.

### Problem Description

Would be great to have a browser based solution instead of needing to have a computer to install the app to

### Proposed Solution

Have the ability to login but its in the browser / cloud based

### Alternatives Considered

Setting up a custom server

**Comment by vraravam** [comment]
This app is based on electron - which is a thick client. Such a browser-based app is not in the cards.
