### ISSUE TITLE
MS Teams 2.0 (WebView)

### ISSUE THREAD

**Issue by alfureu** [ferdium/ferdium-app#1083]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22enhancement+%3Asparkles%3A%22) for a feature request that matches the one I want to file, without success.

### Problem Description

Using MS Teams is a pain, and I fully recognize the difficulties for the devs to provide support for it in Ferdium. 

Recently the news broke out about Teams 2.0 with WebView2, apparently, with the positive side-effect of using lesser resources overall: https://www.theverge.com/2023/3/27/23657938/microsoft-teams-overhaul-performance-improvements-ui-design-changes-features

I understand from the documentation that Ferdium is based on electron and chromium, may I kindly ask for clarification how does this move affect us the users, will we see any benefits of this change?

### Proposed Solution

N/A

### Alternatives Considered

N/A

**Comment by marie-bnl** [comment]
Is your issue just a question about how MS Teams’ new interface could improve the user experience? This isn’t exactly the most appropriate place to ask, I suggest you rather use the Discussions tab or the Discord server. To answer your question however, this isn’t related to Ferdium. Chances are the benefits of this update will be the same as when using Teams on your web browser. The question whether or not it brings actual big performance improvements however, is a whole other debate that has nothing to do with Ferdium.
