### ISSUE TITLE
portable version unchanged after update

### ISSUE THREAD

**Issue by maurerr** [ferdium/ferdium-app#1087]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.2.6

### What Operating System are you using?

Windows

### Operating System Version

Windows 10 Pro 22H2

### What arch are you using?

x64

### Last Known Working Ferdium version

6.2.4

### Expected Behavior

So I'm using the portable version for obvious reasons and after last update/replacing the binary I still get the old version in about and the update banner. 
Name: Ferdium-win-Portable-6.2.6-x64.exe
Size: 85942456 bytes (81 MiB)
SHA256: 8a0c4f7fe67cbad72c2094e8c6194b4dbe26eb012850f7f79de0e68fd7de074b

### Actual Behavior

Version: 6.2.4
Server: No Server
Electron: 22.1.0
Chrome: 108.0.5359.179
Node.js: 16.17.1
Platform: Windows 10
Arch: x64
Build date: Sat Jan 28 2023 01:34:50 GMT+0200 (Eastern European Standard Time)
Git SHA: 68e85c3e
Git branch: release

### Steps to reproduce

1. Download version from https://github.com/ferdium/ferdium-app/releases/download/v6.2.6/Ferdium-win-Portable-6.2.6-x64.exe 
2. delete old binary (6.2.4)
3. launch new binary Ferdium-win-Portable-6.2.6-x64.exe
4. about version shows 6.2.4

**Comment by Alphrag** [comment]
Hi @maurerr thanks for logging this issue. It is weird indeed that the binary you get still contains the old version. I will have a look at it and come back to you (possibly at some point this weekend).

**Comment by Alphrag** [comment]
Hi @maurerr I have just downloaded the portable version from the url you gave (and can confirm that as I get the same SHA for the file), and there is no problem for me, I indeed get the latest version 6.2.6:
![image](https://user-images.githubusercontent.com/34252790/229291014-789efdc4-7507-444d-8497-1f405ae3df11.png)

Can you verify that the previous version was fully stopped before starting the new portable version. It should unpack in the folder `%TEMP%/Ferdium-Unpacked`, so you can verify which executable is running there, and if there is any other file present than the executable, that means Ferdium is still running.

**Comment by maurerr** [comment]
thank you very much for taking the time to verify this  - I can confirm the version is correct a proper app restart
