### ISSUE TITLE
Cannot create new discussion

### ISSUE THREAD

**Issue by ipilcher** [ferdium/ferdium-app#1090]
### Your issue

I am unable to create a new discussion at https://github.com/ferdium/ferdium-app/discussions.  Maybe some sort of permissions issue?

**Comment by Alphrag** [comment]
It seems that there were some permission settings that we didn't see to enable it. Could you please try now to verify if this is working as expected?

**Comment by ipilcher** [comment]
**New discussion** button is there now, so looks good.  Thanks!
