### ISSUE TITLE
iMessage suppourt

### ISSUE THREAD

**Issue by zeussesions** [ferdium/ferdium-app#1096]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22enhancement+%3Asparkles%3A%22) for a feature request that matches the one I want to file, without success.

### Problem Description

The first reaction when downloading Fermium is wow this is amazing! The one and only thing that kills me is the lack of iMessage support. I'm not even sure if it's possible or if it's been tried before, but I looked through the issues and pull requests and it hasn't even been mentioned before. 

### Proposed Solution

I'm a rather inexperienced developer, I'm self-taught and only have been doing this for a year or so, so I don't know that I could implement it myself. I'm willing to do some research and figure it out though.

### Alternatives Considered

I don't think there is a way to forward messages anywhere, so that option isn't available. I would just love to see that feature added.

**Comment by vraravam** [comment]
iMessage doesn't have a web-based ui. There are steps that you can follow to do this, but its not straightforward for Ferdium to support it. One such process/setup is outlined here: https://www.digitbin.com/imessage-web/
