### ISSUE TITLE
For Custom web site, the imported logo does not appear in the sidebar

### ISSUE THREAD

**Issue by mycanaletto** [ferdium/ferdium-app#110]
In custom web site, the imported logo does not appear in the sidebar, regardless of its size ....
![image](https://user-images.githubusercontent.com/45459269/167154886-ee766ea1-c243-4555-b2ca-814ac03d4a92.png)

**Comment by vraravam** [comment]
I'm unable to reproduce this error.
<img width="66" alt="Screenshot 2022-05-06 at 11 09 06 AM" src="https://user-images.githubusercontent.com/69629/167170957-9224c094-8e4c-4a85-951b-9123f5d747ff.png">


I am on macos, I added a new Custom Service, added an image (png), and I see that in the sidebar as capture up above.

**Comment by mycanaletto** [comment]
No logo : 
![image](https://user-images.githubusercontent.com/45459269/167171956-0face6e1-a0cd-4432-a259-a2371393b007.png)

Logo
![image](https://user-images.githubusercontent.com/45459269/167172087-0c35dfab-b034-4923-bba6-a16c0b9c36ea.png)

**Comment by vraravam** [comment]
@mycanaletto - can you please add the image that you are trying to use? As I said in my earlier comment, this is working for me. So, my current guess would be to check the image that you are using.

**Comment by mycanaletto** [comment]
OK, I think this image is the problem. I'm sorry, I tried with another image and it works.

![Home_Assistant_Logo svg](https://user-images.githubusercontent.com/45459269/167225119-af54c168-2b72-4d3a-893d-38a3e7fbc00d.png)

**Comment by vraravam** [comment]
Can you please close this ticket please?

**Comment by vraravam** [comment]
Closing as per 

> OK, I think this image is the problem. I'm sorry, I tried with another image and it works.
>
