### ISSUE TITLE
Bug: Cannot login or reset password

### ISSUE THREAD

**Issue by RoryNesbitt** [ferdium/ferdium-app#111]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0.nightly.27-1

### What Operating System are you using?

Other Linux

### Operating System Version

EndeavourOS

### What arch are you using?

x64

### Expected Behavior

To be able to log in or reset password to my account

### Actual Behavior

When either Sign in or Submit buttons are pressed there is a quick loading icon that appears on the button that only lasts a split second then nothing happens. I do not get an email after pressing submit either.

### Steps to reproduce

Open Ferdium
Click login to your account
Enter details
Click Sign in

Click reset password
Enter email
Click Submit

**Comment by RoryNesbitt** [comment]
I also cannot create a new account with the email. Presumably because it's checking that it exists but not giving that error

**Comment by RoryNesbitt** [comment]
Same issues when trying via https://api.ferdium.org, although it does say my password is wrong and that it has sent an email, but the email doesn't arrive

**Comment by SpecialAro** [comment]
Hey @RoryNesbitt, thank you for raising this issue. Can you please try to login in the official API?
https://api.ferdium.org/user/login

Also, try to reset the password through there, please. If you don't receive an e-mail, feel free to comment on this issue again, please.

**Comment by SpecialAro** [comment]
This issue is related to the e-mail server. It needs fixing.

**Comment by SpecialAro** [comment]
This is solved on the official server. This issue was due to a mismatch on the email server configuration and the mailnode configuration.

Solved by this commit on the ferdium-server repo: https://github.com/ferdium/ferdium-server/commit/f47d1c05f9433c2b5a2c7b35530fea65085b81f2

![image](https://user-images.githubusercontent.com/37463445/167257856-7c0bde26-c0e5-4a9f-bad7-24d79f7a2a33.png)

**Comment by RoryNesbitt** [comment]
Glad to see this sorted and thanks again for fixing my personal issue of it over discord :)

**Comment by kingsizeportugal-collab** [comment]
SIMPLES E FÁCIL VEJA O VIDEO. Recupera a senha do ferdium facilmente sem stress basta seguir os passos do vídeo
praticamente ensina a tirar a senha e pronto! problema resolvido para todos

[https://www.youtube.com/watch?v=sGcw8594L6s]
