### ISSUE TITLE
Ferdium inhibits power management while playing videos

### ISSUE THREAD

**Issue by paulstodghill** [ferdium/ferdium-app#1115]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.2.6

### What Operating System are you using?

Other Linux

### Operating System Version

Debian 11

### What arch are you using?

x64

### Last Known Working Ferdium version

Unknown

### Expected Behavior

The expected behavior is the Ferdium does _not_ block power management, thus allowing the screensaver and other display-related tasks to function correctly.

### Actual Behavior

According to XFCE4's Power Manager Plugin, Ferdium is inhibiting power management. This prevents the screen saver from starting, and appears to prevent a laptop from suspending when the lid is closed.

### Steps to reproduce

I am unable to provide robust steps to reproduce. I am experiencing the problem intermittently on a desktop and constantly on a laptop. On the desktop, restarting Ferdium appears to clear the problem; on the laptop it does not.

I have had intermittent problems with my screensaver not starting on several computers over the past several year, but never noticed that Franz, Ferdi, Ferdium was inhibiting power managements until today.

### Screenshots

![Screenshot_2023-04-17_11-52-37](https://user-images.githubusercontent.com/40493573/232543452-f8efb5cb-2907-4994-a67b-d328342c71a8.png)

### Additional information

I have found other unresolved bug reports that Google Chrome or Chromium might cause the same problem on other XFCE4/Debian systems. 

~~~
Version: 6.2.6
Server: No Server
Electron: 23.2.0
Chrome: 110.0.5481.192
Node.js: 18.12.1
Platform: Linux 5.10
Arch: x64
Build date: Wed Mar 29 2023 21:48:19 GMT-0400 (Eastern Daylight Time)
Git SHA: 28d1f763
Git branch: release
~~~

~~~
System:    Host: allium Kernel: 5.10.0-21-amd64 x86_64 bits: 64 Console: tty 1 Distro: Debian GNU/Linux 11 (bullseye) 
Machine:   Type: Laptop System: Dell product: Latitude 7280 v: N/A serial: <superuser required> 
           Mobo: Dell model: 0KK5D1 v: A00 serial: <superuser required> UEFI: Dell v: 1.30.0 date: 12/21/2022 
Battery:   ID-1: BAT0 charge: 33.6 Wh condition: 33.6/60.0 Wh (56%) 
CPU:       Info: Dual Core Intel Core i5-6300U [MT MCP] speed: 878 MHz min/max: 400/3000 MHz 
Graphics:  Device-1: Intel Skylake GT2 [HD Graphics 520] driver: i915 v: kernel 
           Device-2: Microdia Integrated_Webcam_HD type: USB driver: uvcvideo 
           Display: server: X.org 1.20.11 driver: loaded: modesetting unloaded: fbdev,vesa tty: 211x56 
           Message: Advanced graphics data unavailable in console. Try -G --display 
Network:   Device-1: Intel Ethernet I219-LM driver: e1000e 
           Device-2: Intel Wireless 8265 / 8275 driver: iwlwifi 
Drives:    Local Storage: total: 953.87 GiB used: 695.94 GiB (73.0%) 
Info:      Processes: 221 Uptime: 3d 22h 15m Memory: 15.52 GiB used: 1.88 GiB (12.1%) Init: systemd runlevel: 5 Shell: Bash 
           inxi: 3.3.01 
~~~

**Comment by marie-bnl** [comment]
Could you link those issues you saw about Chrome inhibiting power management as well?

**Comment by paulstodghill** [comment]
https://unix.stackexchange.com/questions/451413/disabling-chromium-xfce-power-management-inhibition

https://www.reddit.com/r/linuxquestions/comments/4pvxx3/dbus_policy_to_deny_chrome_from_inhibiting_power/

HTH. Thanks.

**Comment by marie-bnl** [comment]
When I start Ferdium I don’t see any request to inhibit power management in dbus-monitor. Thus I think it might come from one of your services. In order to debug that, I suggest you remove all of your services and see if you still have this issue, and then add them back one by one so you can identify which one is causing it.

**Comment by paulstodghill** [comment]
Yup. Disabling the Facebook Messenger service appears to resolve the issue. Disable it - the inhibition disappears. Enable it - the inhibition reappears. Disable it - it disappears. Etc.

**Comment by marie-bnl** [comment]
Great! What is strange is I can’t reproduce it. Do you know at what step the issue occurs? For instance, is power management inhibited as soon as you start Ferdium? When you click the service? Or when you do something particular in Messenger?

**Comment by paulstodghill** [comment]
I start Ferdium "Always show Ferdium in System Tray" and "Start minimized" selected. I.e., no window. The Power Management Inhibition (hereafter, PMI) does not appear when Ferdium is first started. Leaving Ferdium minimized to the system tray, I check for PMI every second or so. PMI does no appear until about 5 seconds after starting Ferdium. My guess (unverified) is that this corresponds to when the Messenger service finishes loading.

I deleted the Messenger service entirely. I then started the process of re-adding it, while watching for PMI. There was no PMI through the entire process of re-adding the service and re-authenticating with Facebook. However, as soon as the Messenger's Chat screen finished loading, PMI reappeared.

**Comment by marie-bnl** [comment]
The thing is I don’t know why Messenger would need to inhibit power management. My best bet is it would be useful during calls, as you don’t want your computer to get suspended while calling someone. However, while not in a call, I can’t figure out what causes the inhibition (given that on my side, with a blank account with no chats, as I don’t use Messenger, it doesn’t occur). In my opinion, as it doesn’t happen on a blank account, it must come from a specific feature of Messenger, and what is to figure out now is which feature causes that. The only trouble is that debugging that is a time-consuming process; I think it would involve creating two accounts and trying to send all sort of messages, and trying every feature with the other one, to see when power management gets inhibited.

**Comment by paulstodghill** [comment]
Apparently, the problem is not specific to Ferdium.

When I open Messenger in Brave (Chromium-derived), I see PMI by Brave as well. The weird thing is that when I switch to another tab, PMI disappears. Switch back to the Messenger tab, PMI reappears. Close Brave or the Messenger tab, PMI disappears for good.

PMI does not appear when loading Messenger in Firefox ESR.

So it really does appear to be a Chromium issue. Digging further, I used `dbus-monitor` to monitor the PMI (actualy ScreenSaver Inhibition) as I switched between Messenger and blank tabs in Brave. Here are the results,

~~~
buttercup$ dbus-monitor --session interface=org.freedesktop.ScreenSaver
signal time=1682085070.714122 sender=org.freedesktop.DBus -> destination=:1.3710 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.3710"
signal time=1682085070.714152 sender=org.freedesktop.DBus -> destination=:1.3710 serial=4 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.3710"
method call time=1682085073.690417 sender=:1.3711 -> destination=org.freedesktop.ScreenSaver serial=5 path=/org/freedesktop/ScreenSaver; interface=org.freedesktop.ScreenSaver; member=Inhibit
   string "/opt/brave.com/brave/brave"
   string "Video Wake Lock"
method call time=1682085074.829816 sender=:1.3711 -> destination=org.freedesktop.ScreenSaver serial=8 path=/org/freedesktop/ScreenSaver; interface=org.freedesktop.ScreenSaver; member=UnInhibit
   uint32 4148751630
method call time=1682085075.773908 sender=:1.3712 -> destination=org.freedesktop.ScreenSaver serial=5 path=/org/freedesktop/ScreenSaver; interface=org.freedesktop.ScreenSaver; member=Inhibit
   string "/opt/brave.com/brave/brave"
   string "Video Wake Lock"
method call time=1682085076.740926 sender=:1.3712 -> destination=org.freedesktop.ScreenSaver serial=8 path=/org/freedesktop/ScreenSaver; interface=org.freedesktop.ScreenSaver; member=UnInhibit
   uint32 3251688123
~~~

I happen to have active video previews in one of my chat streams. If I switch to a different chat stream without videos, the PMI dissappears! If I scroll in the original chat stream so that no video previews are present, the PMI disappears!

I repeated all of these steps in Ferdium and observed the same behavior.

This isn't a Ferdium bug.

**Comment by marie-bnl** [comment]
I’m glad you figured out where it came from! At the end of the day it is not a bug but an expected behaviour, right? If so, I guess we can deem this issue fixed?

Also I’d rename it something along the lines of “Messenger is inhibiting power management” to make it clearer for further research.

**Comment by paulstodghill** [comment]
From https://chromium.googlesource.com/chromium/src.git/+/refs/heads/main/third_party/blink/renderer/modules/wake_lock#Inside-Blink

> Video playback via the `<video>` tag currently uses a screen wake lock behind the scenes to prevent the screen
> from turning off while a video is being played. 

Yes, this does appear to be intentional behavior.

Yes, I think you should close this issue.

Yes, you should change the title, but I think you can make it even more general, e.g., "Messenger and other services with active videos may inhibit power management and screen savers". A bit long that. :-)

Searching for "chromium Video Wake Lock" would suggest that the problem is not specific to Messenger, Chromium or even Linux.

**Comment by marie-bnl** [comment]
I am not a maintainer of Ferdium, just a contributor, and as such I can’t close the issue nor change its title :p. So I let you do both. I think “Ferdium inhibits power management while playing videos” is a good title (no need to specify “on some services” as it probably does with all of them).

**Comment by paulstodghill** [comment]
Done. Thanks for your help with this issue.
