### ISSUE TITLE
Ferdium not start automatically

### ISSUE THREAD

**Issue by vampywiz17** [ferdium/ferdium-app#1121]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.2.6

### What Operating System are you using?

Other Linux

### Operating System Version

Deepin 20.9

### What arch are you using?

x64

### Expected Behavior

If i check autostart in Ferdium menu, i would like that is start automatically if i start my computer.

### Actual Behavior

Need to start the program manually.

### Steps to reproduce

1. Install Ferdium via Flatpak
2. Set autostart in menu
3. Restart computer

### Additional information

It working with deb package, i think the problem is the flatpak.

**Comment by marie-bnl** [comment]
When enabling this option, Ferdium creates a `ferdium.desktop` file in `~/.config/autostart/`. I suggest you first check if this file exists

**Comment by vampywiz17** [comment]
> When enabling this option, Ferdium creates a `ferdium.desktop` file in `~/.config/autostart/`. I suggest you first check if this file exists

It help me :) yes i think the problem that flatpak can not gererate this file. So i install deb version, it generate the file i edit it a bit and delete deb. after it work well with flatpak version :)

here the edited file:

```
[Desktop Entry]
Type=Application
Version=1.0
Name=ferdium
Comment=ferdiumstartup script
Exec=/usr/bin/flatpak run org.ferdium.Ferdium
StartupNotify=false
Terminal=false

```

**Comment by vraravam** [comment]
Closing since this seems to be an issue specific to an OS which Ferdium doesn't have control over.
