### ISSUE TITLE
Allow Login with Windows Account

### ISSUE THREAD

**Issue by pieroavola** [ferdium/ferdium-app#1127]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22enhancement+%3Asparkles%3A%22) for a feature request that matches the one I want to file, without success.

### Problem Description

Some applications at my job can only be used when logging in with the current Windows/Microsoft Account. The login using only the username and password is blocked, I need to logged into Windows with the account. In Chrome this can be achieved by installing [an extension](https://chrome.google.com/webstore/detail/windows-accounts/ppnbnpeolgkicgegkbkbjmhlideopiji).

Since Ferdium doesn't include the extension, the login is impossible.

### Proposed Solution

Include the Chrome extension in Ferdium. If I understand correctly this is already done with Dark Reader.

### Alternatives Considered

There are no alternatives that I know of. Our old SSO could be enabled by launching Ferdium or Chrome with a parameter, but I don't think that's an option for the MS Login when it checks your Windows user.

**Comment by marie-bnl** [comment]
I think that rather than making Ferdium support logging in with windows account specifically, the best solution is to make it possible to use the extension you linked. This is planned, see https://github.com/ferdium/ferdium-app/issues/135

**Comment by pieroavola** [comment]
I agree that would be the best solution, but I suspect it'd take a long time until this would actually be available.

**Comment by marie-bnl** [comment]
Indeed, you’d need to find a workaround. Nonetheless it seems more complicated than just using Chrome for the websites that require this.

**Comment by vraravam** [comment]
Closing as not planned in favor of #135
