### ISSUE TITLE
Trojan found

### ISSUE THREAD

**Issue by bwyyoung** [ferdium/ferdium-app#1133]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

Version: 6.2.6
Server: No Server
Electron: 23.2.0
Chrome: 110.0.5481.192
Node.js: 18.12.1
Platform: Windows 11
Arch: x64
Build date: Thu Mar 30 2023 09:53:46 GMT+0800 (Singapore Standard Time)
Git SHA: 28d1f763
Git branch: release

### What Operating System are you using?

Windows

### Operating System Version

Microsoft Windows 11 Pro

### What arch are you using?

x64

### Last Known Working Ferdium version

6.2.6

### Expected Behavior

A trojan was found in a service worker via virus scan.

### Actual Behavior

n/a

### Steps to reproduce

Scan with Windows Defender

### Screenshots

![Screenshot_042723_100720_AM](https://user-images.githubusercontent.com/1365439/234741654-eb53bd3d-31b8-42a1-99fe-4121dd4df87e.jpg)

**Comment by marie-bnl** [comment]
If you open the `Cookies` file in the service’s partition folder, you might be able to identify which service this is.

![image](https://user-images.githubusercontent.com/39555268/234840165-e581d649-9984-4383-875d-c33a812c68b1.png)

For instance, it’s Messenger here.

**Comment by bwyyoung** [comment]
It is Telegram.

![Screenshot_042823_093111_AM](https://user-images.githubusercontent.com/1365439/235032877-64a26f34-796b-4ed1-956f-fcbce84ac0ef.jpg)

**Comment by bwyyoung** [comment]
Its ok. I found out it was from a file that someone sent. Deleted the file. Windows Defender seems smart enough to scan Ferdium for files and attachments.
