### ISSUE TITLE
Feature: Add Sponsoring feature to the project

### ISSUE THREAD

**Issue by MurzNN** [ferdium/ferdium-app#114]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I was a happy Ferdi sponsor and want to continue sponsoring his resurrection as Ferdium, but where to send my money?? I can't afford to sponsor a lot of money yet, but several $ per month is better than nothing, I guess.

### Proposed Solution

Maybe return the "Sponsoring" Github feature to the Ferdium project, and other ways to sponsor like opencollective.com?

### Alternatives Considered

Alternatively we can send money via post :)

**Comment by nathanaelhoun** [comment]
GitHub Sponsors have been enabled on the [Ferdium org](https://github.com/ferdium) :tada:
