### ISSUE TITLE
Bug: macOS Dock icon not correct according to Apple Human Interface Guidelines

### ISSUE THREAD

**Issue by hansdampff** [ferdium/ferdium-app#116]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.28

### What Operating System are you using?

macOS

### Operating System Version

macOS 12

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

The Ferdium-Dock Icon under macOS should looks like all the other Apps with the exact same shape.

### Actual Behavior

Ferdium icon is displayed round.

Apple Human Interface Guideline:
https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/

Template:
https://developer.apple.com/design/resources/#macos-apps

### Steps to reproduce

Visually immediately visible

### Screenshots

<img width="346" alt="Bildschirmfoto 2022-05-07 um 15 48 14" src="https://user-images.githubusercontent.com/88364141/167257159-929100c8-d981-4255-a029-6b567da139be.png">

**Comment by SpecialAro** [comment]
Although I totally agree to follow the guideline - just for me to get better knowledge on this - is this a strict requirement? 

For instance, just noticed that Spotify and Stremio don't follow the guideline (but yeah, we should!):

<img width="679" alt="image" src="https://user-images.githubusercontent.com/37463445/167271618-7e231f03-5282-4454-a3fd-fb846bec9ff5.png">

**Comment by BrianGilbert** [comment]
> Although I totally agree to follow the guideline - just for me to get better knowledge on this - is this a strict requirement?
> 
> For instance, just noticed that Spotify and Stremio don't follow the guideline (but yeah, we should!):
> 
> <img alt="image" width="679" src="https://user-images.githubusercontent.com/37463445/167271618-7e231f03-5282-4454-a3fd-fb846bec9ff5.png">

Doesn't "guideline" say it all?
