### ISSUE TITLE
[complete new & different project] Use LibreWolf as base (instead of chrome/electron)

### ISSUE THREAD

**Issue by jwmh** [ferdium/ferdium-app#1163]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22enhancement+%3Asparkles%3A%22) for a feature request that matches the one I want to file, without success.

### Problem Description

librewolf is a security- and privacy-hardened fork of Firefox.
https://librewolf.net
By default, it has multiple privacy- and resist-fingerprinting features turned on & built-in.
.
Granted:
This will break many apps/websites.
.
However.
For those tech nerds who understand the tradeoffs,
and are able to toggle the switches / configurations appropriately
(maybe on a per-instance / per-app basis??! as with --ProfileManager )
...
I think this could be really great.
Better way to approach for some reasons??

### Proposed Solution

.

### Alternatives Considered

.

**Comment by vraravam** [comment]
Unfortunately, we are not going to do a complete rewrite of Ferdium to remove electron. Closing this ticket.
