### ISSUE TITLE
Default Downloads Directory

### ISSUE THREAD

**Issue by jimmylad** [ferdium/ferdium-app#1164]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22enhancement+%3Asparkles%3A%22) for a feature request that matches the one I want to file, without success.

### Problem Description

When I download something I am always prompted for a directory to save in

### Proposed Solution

Add the ability for the user to specify a default downloads folder (via the preferences UI). For each download, if such a preference has been setup, then use that always so the user is not prompted each time.

### Alternatives Considered

I have searched documentation and settings

**Comment by Nickyg001** [comment]
I was about to ask the same request.
Every time I have to download some attachment (be it google mail, whatsapp etc) I have to manually change the save folder.
It would be useful to be able to define a specific folder defined by the user where to always save the attachments (eg Desktop).

**Comment by faustocintra** [comment]
I also second that.

**Comment by SpecialAro** [comment]
Quick update: I've looked into this issue when I implemented the Download Manager feature. But ever since I've been coding to update the Ferdium Server Adonis dependency (which is a big dependency that needed update) so, I will resume investigating this when that is merged 😊

**Comment by azizly** [comment]
UP for this it is really annoying specially with WhatsApp, i want to download multiple images and i have to close the prompt each time

**Comment by SpecialAro** [comment]
Ok I'll take a look at this today 😁

**Comment by jimmylad** [comment]
Thank you
