### ISSUE TITLE
fix/improve Ferdium upgrades to include better Service-upgrades

### ISSUE THREAD

**Issue by jwmh** [ferdium/ferdium-app#1168]
It seems that certain steps -- at least in my upgrade path -- don't occur until a while later after the ferdium upgrade itself:
1. detect that a Service has been upgraded;
2. upgrade the service;
3. give user a pop-up message saying so & with a big obvious button to reload the service.

Q: could this please be made to happen earlier & more automagically in the process.

#####

 via https://github.com/ferdium/ferdium-app/issues/1064#issuecomment-1546933633_

> For a newbie,
> This has NOT been fixed for "Google CALENDAR"
> i.e. maybe it was fixed for "Classroom" only?
> 
> I installed via https://ferdium.org/download
> using the .debi file:
> Alternative Downloads
> DEB
> amd64 deb
> [website download page links to: ]
> https://github.com/ferdium/ferdium-app/releases/download/v6.2.7/Ferdium-linux-6.2.7-amd64.deb
> 
> After installing on top of 6.2.6,
> 6.2.7. then gave me a [very minimal] little red dot in Settings, which led me to "Reload Services."
> {Sidebar: I think the UI isnt ready for nontechheads just yet...} ... so I reloaded services.
> (still no joy after manually going to Settings -> reloading services!)
>
> then I also deleted my GoogleCalendar services completely.
> Then re-added them.
> I've also tried quitting & restarting the app.
> 
> None of this fixes this issue #1064 for me:
> It still insists on opening the login page in my primary web browser (as described above by others).
> 

half an hour *after* giving up on this 
 -- 
and then fiddling around with an unrelated issue later...

> EDIT:
> OK, some new stuff happened.
> *Please Read Below*
> 
> I:
> 1. tried to clear the ferdium cache (for an unrelated issue);
> 2. said "couldn't clear all cache", so i:
> 3. disabled every single service;
> 4. cleared cache again;
> 5. still didn't clear all cache (i guess that's impossible? but so then i) killed the ferdium browser process, which quit ferdium entirely;
> 6. restarted ferdium;
> 7. cleared cache *again*;
> 8. and *now* i [redundantly??? since i'd already done it before????] get a pop-up saying "Some of your services have been updated" with a big "Reload Services" button (which supposedly i had already done);
> 9. did so [again];
> 
> ... 
> and now it's working.
> 
> I'm opening a new issue around this.
> It shouldn't take this much hassle to update GCalendar -- or any other module/service --
> and there should be an automatic process to handle all of it built-in -- immediately upon upgrade...
> (maybe in the 'running post-installation scripts' portion?)
> 
> ... so
> 1. users don't get confused; and
> 2. y'all dont get pinged with lots of messages like this from people like me lol

_Originally posted by @jwmh in https://github.com/ferdium/ferdium-app/issues/1064#issuecomment-1546933633_
            
It seems that certain steps -- at least in my upgrade path -- don't occur until a while later after the ferdium upgrade itself:
1. detect that a Service has been upgraded;
2. upgrade the service;
3. tell the user to reload the service.

This should happen earlier & automatically in the process.

**Comment by vraravam** [comment]
There's already a [discussion thread](https://github.com/ferdium/ferdium-app/discussions/824) for enhancing the recipe upgrade process. Closing this ticket.

**Comment by jwmh** [comment]
That discussion thread doesn't cover this issue, which I maintain is a BUG (not a feature-request), because it negatively impacts the user experience in potentially breaking ways.

**Comment by SpecialAro** [comment]
This issue might be OS related. This never happened to me neither on my macOS, nor my Windows 11. Whenever I update Ferdium, I get a message after 15-30 seconds (tops!) to reload my Services and update them

**Comment by vraravam** [comment]
@jwmh - irrespective of whether its a bug or a feature request, we would like to collate all such pertinent information in that discussion thread - so that any solution will cater to all scenarios. Please add any constructive information or requirements into that thread.
