### ISSUE TITLE
Add new service "DeepL"

### ISSUE THREAD

**Issue by vraravam** [ferdium/ferdium-app#1169]
### Discussed in https://github.com/ferdium/ferdium-app/discussions/1098

<div type='discussions-op-text'>

<sup>Originally posted by **pacihak** April  6, 2023</sup>
This is my working custom build, you can add it to regular services.

Name: **DeepL**
Custom server: **https://www.deepl.com/translator**
Custom icon: **https://play-lh.googleusercontent.com/0IH4L3pX-jqQXKYCDmxTM5t3Tvak2cb_zUuIs9nKCHPeOqkaRJ_bRTq1qKawsSvunw**</div>

**Comment by Alphrag** [comment]
The recipe was added in https://github.com/ferdium/ferdium-recipes/pull/333, so I think this could be closed, no?
