### ISSUE TITLE
[Microsoft Teams] MS Teams with SSO logging out the session every day

### ISSUE THREAD

**Issue by MurzNN** [ferdium/ferdium-app#1171]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+%3Abookmark_tabs%3A%22+label%3A%22bug+%3Abeetle%3A%22+) for a bug report that matches the one I want to file, without success.

### Ferdium Version

6.2.7

### Recipe Name

Microsoft Teams

### Recipe Version

3.2.1

### Steps to reproduce

1. Disable any hibernation in the Microsoft Teams app.
2. Log in to Microsoft Teams using any SSO provider.
3. Keep the activity, then go to sleep.
4. Wake up and open the Microsoft Teams tab in Ferdium.
5. See that you're asked to log in again.

7. Do the same on a full browser (eg Firefox) and see that you're not logged out every day.

### Expected Behavior

The session should be kept.

### Actual Behavior

The session is logging out every day, sometimes even several times per day, even sometimes in the middle of the conference call!

### Additional Information

Seems this is related to third-party cookies: https://learn.microsoft.com/en-us/answers/questions/254061/persistent-browser-session-issues-with-chrome
But I can't find a way how to check or enable this in Ferdium.

**Comment by MurzNN** [comment]
And the same is with Microsoft Outlook.

**Comment by vraravam** [comment]
As described in the link from the original description, the issue with the persistent cookies is not something that Ferdium can control. Please try different combinations of user-agent strings to try to fix this issue. Closing this ticket.

**Comment by MurzNN** [comment]
So, Ferdium can't control the third-party cookies settings in Chromium instance?

Here is what we should do to fix this issue: https://learn.microsoft.com/en-us/microsoftteams/troubleshoot/teams-sign-in/sign-in-loop#resolution

> 

    In the Chrome Settings window, open the Privacy and security tab, and then select Cookies and other site data.

    Under Sites that can always use cookies, select Add, and then select the Including third-party cookies on this site checkbox.

    Add the following sites:
        [*.]microsoft.com
        [*.]microsoftonline.com
        [*.]teams.skype.com
        [*.]teams.microsoft.com
        [*.]sfbassets.com
        [*.]skypeforbusiness.com


Is it possible?

**Comment by MurzNN** [comment]
If I'm setting the older Chrome User Agent - I can't log in at all:
![image](https://github.com/ferdium/ferdium-app/assets/336662/67aa00c0-2d94-47f3-b25e-947190daa151)

**Comment by vraravam** [comment]
> Is it possible?

No, this is not possible in Ferdium

**Comment by MurzNN** [comment]
Posted a question about 3rd party cookies in Electron webview: https://stackoverflow.com/questions/76428943/how-to-allow-third-party-cookies-or-configure-trusted-domains-in-a-webview-of-an

**Comment by MurzNN** [comment]
No response to the comment there, so I've filled a separate issue about this: https://github.com/electron/electron/issues/39021

**Comment by TiZ-HugLife** [comment]
It looks like Electron closed the issue without really looking at it, and asked it to be resubmitted as an enhancement request. Do you think we'd have any luck if one of the main contributors here opens an issue as an enhancement request? It looks like they close issues very very eagerly, like electron/electron#36922, electron/electron#19825. Someone working directly with the project **might** have more luck filing an issue than someone using an app made with it.

I would love to see this fixed; my ADHD is getting me in trouble at work over this because I keep forgetting to log back in.
