### ISSUE TITLE
Twitter uses Google login and always opens in the default browser

### ISSUE THREAD

**Issue by luke358** [ferdium/ferdium-app#1177]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

Version: 6.2.7

### What Operating System are you using?

macOS

### Operating System Version

macOS Ventura 13.0

### What arch are you using?

x64

### Last Known Working Ferdium version

Version: 6.2.7

### Expected Behavior

Don't open the default browser.

like this:
<img width="800" alt="image" src="https://github.com/ferdium/ferdium-app/assets/48149577/00013224-5837-4e11-9fa8-01514177efad">

### Actual Behavior

Open the default browser, and throw an error.
<img width="600" alt="image" src="https://github.com/ferdium/ferdium-app/assets/48149577/bc8f2d66-9860-4da1-b4ef-cbef4d34f191">

### Steps to reproduce

1. Add Twiter Service.
2. Sign in with Google
3. Auto open default browser

### Screenshots

<img width="1164" alt="image" src="https://github.com/ferdium/ferdium-app/assets/48149577/01da1e9e-562e-46a5-b538-4792d61244aa">
![image](https://github.com/ferdium/ferdium-app/assets/48149577/06eef6d1-dbb7-4292-8cca-6feb443b7a66)

**Comment by Arthur-Huan** [comment]
Is the “Open URLs within Ferdium” option selected? It's in the “Edit” menu for each service.
