### ISSUE TITLE
[Solved] Login with Google not working with multiple services "Couldn't sign you in" "app may not be secure" message

### ISSUE THREAD

**Issue by anguy079** [ferdium/ferdium-app#1179]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.2.7

### What Operating System are you using?

Windows

### Operating System Version

Windows 11 Education Version 22H2

### What arch are you using?

x64

### Expected Behavior

1. Open a service that uses Google to login (todoist, google keep, etc)
2. Click login using Google 
3. Service refreshes and logs in or creates an account using Google information

### Actual Behavior

1. Click 'Login using Google'
2. Service refreshes and shows 'Couldn't sign you in. This browser or app may not be secure. Try using a different browser.'

### Steps to reproduce

1. Open Todoist or Google Keep
2. Click Login using Google
3. Page refreshes and displays browser/app not secure.

### Screenshots

<img width="279" alt="unsecure app" src="https://github.com/ferdium/ferdium-app/assets/41588564/cd8813f6-ac44-4320-8e55-3eaea87a0ec7">

### Additional information

Solved. Found two solutions.

**Solution 1 (works with most services)**
1.  Right click service in navigation bar
2. Click 'Edit'
3. Under 'User Agent' put: https://accounts.google.com/
4. Click 'Save service'
5. Right click service in navigation bar and click 'Reload'. Give it a few seconds to reload, might need to click reload a few times or disable and re-enable service. 
6. Click 'Login using Google' and it should work now. 
7. After successfully logging in, edit the service again, remove the User Agent previously inputted, Save Service, reload service again.

Account should be successfully logged in using google and remain logged in. If you don't remove the User Agent after logging in the service may ban you until you remove it OR service may not work with all its intended features.

**_Solution 2_** 
1. Services like Todoist allows you to make an account on their native website/application by logging in with google. 
2. THEN add a password via profile settings after verifying your email. 
3. In ferdium, you can then login using your email/username and password you created. The Login with google button will not work but at least your google account is linked.

**Comment by vraravam** [comment]
Yes, and this is the reason why we exposed the ability for the user to set the user agent in a global manner as well as each individual service-level.
This issue will recur each time Google changes their detection algorithm to try to mandate users switching to Chrome browser. We do not have any control on this however and the only consistent workaround has been to spoof the user agent.

**Comment by azizly** [comment]
after lost of hustle, changed the global user agent to accounts.google.com  allowed me to log in to google tasks in the todos, then i went back to regular user agent

thanks alot

**Comment by dwichers** [comment]
The same issue occurs when enabling 'Todos' with Todoist as the selected service. When the side panel opens, logging in with Google results in the 'app may not be secure' error. Setting the user agent in the general settings doesn't resolve this. Additionally, enabling Todoist as a regular service (instead of using the built-in Todos function) doesn't help. Even setting the user agent for Todoist does not fix the issue of logging in with Google. 

However, I can confirm that adding a password to my Todoist account did work.

**Comment by BetaMaxHeadroom** [comment]
> after lost of hustle, changed the global user agent to accounts.google.com allowed me to log in to google tasks in the todos, then i went back to regular user agent
> 
> thanks alot

You're pretty lucky. I am not getting the same result. I receive an error at the top stating that the browser version is no longer supported.
