### ISSUE TITLE
No whatsapp notifications on win 10 desktop and mac

### ISSUE THREAD

**Issue by lawyer88** [ferdium/ferdium-app#1182]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.2.7 portable

### What Operating System are you using?

Windows

### Operating System Version

19045.2965

### What arch are you using?

x64

### Last Known Working Ferdium version

6.2.6 portable

### Expected Behavior

I want to receive notifications from whatsapp on my desktop

### Actual Behavior

For reasons I don't understand, notifications from WhatsApp have stopped appearing in the notification panel (screenshot below), while the number of messages received is not displayed in the program itself (screenshot below).
For example, notifications from telegrams come to the desktop and the number of new messages is displayed on the icons in the program.
There is a red circle on the tray icons that there are new messages, but there are no notifications: (how to fix this problem?
Through the browser, all permissions are there, notifications from the browser (Chrome) come.
Notifications also come if you use the Ram box.
Chrome is portable.
Previously, everything worked without problems, from some point notifications stopped coming:(

### Steps to reproduce

1. A new message arrives in whatsapp
2. A blue circle appears on the WhatsApp icon without specifying the number of new messages, a red circle about a new message appears on the tray icon. At the same time, there is no notification on the desktop in "manage notifications".
An example is visible in the screenshots

### Debug link

https://debug.ferdium.org/79866fdd-fc50-4c54-bbac-d92bccffe5f5

### Screenshots

in this form, information about the received messages is displayed now
![Ferdium_PdJlbKUdy7](https://github.com/ferdium/ferdium-app/assets/134001549/837f54cb-1dc7-4272-ab77-f7f142031b41)
notifications on the desktop do not come, they used to be in this form:
![4bWCeDduAP0WdN38](https://github.com/ferdium/ferdium-app/assets/134001549/3ad49529-c99f-4b26-9b86-8e0f79194096)
At the same time, telegram works well, messages are visible, notifications are coming

**Comment by cjiang39** [comment]
I have the same issue on MacOS 13.2.1. WhatsApp banner notifications no longer appear, although there is an unread message count badge for new messages on the Ferdium app icon in the dock. Banner notifications still appear for Slack. I also installed the WhatsApp desktop app and am receiving banner notifications there. 

I actually first experienced this issue a few days ago in Ferdi. I found Ferdium because I was looking for an alternative to Ferdi, hoping that it wouldn't be an issue here.

**Comment by akatarmo** [comment]
Hi, same here. Windows 10 Desktop. Ferdium v6.2.6 (same issue with v6.2.7) **Suddenly**, last monday, the notifications stopped appearing in the task bar at the bottom right. 

I thought it was a Windows problem and I was **thoroughly** reviewing the notification settings but everything is fine.

**Comment by cjiang39** [comment]
> I have the same issue on MacOS 13.2.1. WhatsApp banner notifications no longer appear, although there is an unread message count badge for new messages on the Ferdium app icon in the dock. Banner notifications still appear for Slack. I also installed the WhatsApp desktop app and am receiving banner notifications there.
> 
> I actually first experienced this issue a few days ago in Ferdi. I found Ferdium because I was looking for an alternative to Ferdi, hoping that it wouldn't be an issue here.

This is working for me now -- I'm getting desktop banner notifications from WhatsApp in Ferdium.

**EDIT**: One day later (May 25), I'm once again not getting desktop banner notifications from WhatsApp.

**Comment by MPSCardoso** [comment]
Having the same issue in Windows 11. The only notification that is working ok is the reactions notifications.

**Comment by akatarmo** [comment]
Today for about 2 hours the notifications have **worked again**. Ok, I thought, the problem has fixed itself. But no, now I'm back without notifications. It's a bit strange.

**Comment by chnikel** [comment]
Same problem on Ubuntu 22.04.2.

**Comment by apexnationz** [comment]
Same Issue Windows 11 Pro, 22h2

**Comment by lawyer88** [comment]
На установленной версии также не работают уведомления. Неделю назад переустанавливал виндовс - тоже никаких изменений, уведомлений нет :(
Уважаемые разработчики - исправьте баги, невозможно пользоваться программой без нормальный уведомлений о сообщениях :(

**Comment by lawyer88** [comment]
Notifications also don't work on the installed version. I reinstalled Windows a week ago - there are no changes either, there are no notifications:(
Dear developers - fix the bugs, it is impossible to use the program without normal notification messages:(

**Comment by abdullahgira** [comment]
Same on KDE Neon 5.27

**Comment by yyounes75** [comment]
Same on Ferdium 6.3.0

**Comment by RahKapoor** [comment]
Anyone else? Fix it please

**Comment by skeelkat** [comment]
Same here on Windows 11 Pro 22H2 - 22621.1702

Version: 6.3.0
Server: Ferdium Server
Electron: 25.0.1
Chrome: 114.0.5735.45
Node.js: 18.15.0
Platform: Windows 11
Arch: x64
Build date: Sat Jun 03 2023 19:41:07 GMT+0200 (South Africa Standard Time)
Git SHA: 815f9c03
Git branch: release

**Comment by sedatabase** [comment]
any news?

**Comment by cjiang39** [comment]
This is still a problem for me on Mac. Like someone else said above, I only get banner notifications for reactions, not for messages.

**Comment by PingWeb** [comment]
Same here, MacOS 13.4 / Ferdium 6.3.0

**Comment by lawyer88** [comment]
Sorry developers, I have to go to competitors :(Have a good and speedy solution to the problem!

**Comment by akatarmo** [comment]
> Sorry developers, I have to go to competitors :(Have a good and speedy solution to the problem!

Which is the app that you have chosen?. I also need an alternative while this **notification problem** in Ferdium is fixed

**Comment by lawyer88** [comment]
> > Sorry developers, I have to go to competitors :(Have a good and speedy solution to the problem!
> 
> Which is the app that you have chosen?. I also need an alternative while this **notification problem** in Ferdium is fixed

I used to use the Rumbox, then switched to Ferdium as the most convenient for me, although the +- functionality matches. Now I have returned to the Rambox again, no complaints, everything works fine (previously, he also did not fail in terms of work). The only drawback is the lack of a portable version, the data is stored in the cloud, after logging into your account everything resumes.

**Comment by apexnationz** [comment]
Please no, i swiched because of notifications issues in the last 3 years from Rambox to Ferdi to Ferdium... Please some dev just have a look at this...

**Comment by gschafra** [comment]
It seems like the `archive` attribute of WhatsApps IndexDB chat model/entity does no longer exist, so that https://github.com/ferdium/ferdium-recipes/blob/b21abf5ec30c35773890382869ee9d9ab8f4acec/recipes/whatsapp/webview.js#L42 always evaluate to false:
```js
            if (chat.muteExpiration === 0 && chat.archive === false) { // Always evaluated to false
              unreadCount += chat.unreadCount;
            } else {
              unreadMutedCount += chat.unreadCount;
            }
```

![grafik](https://github.com/ferdium/ferdium-app/assets/3999582/63a6b114-8d92-42d3-ac9c-ce98697074fc)


I've changed it manually to (no clue, if `isAutoMuted` is correctly interpreted here... any clues), and it seems to work:

```js
            if (chat.muteExpiration === 0 && chat.isAutoMuted === false) {
              unreadCount += chat.unreadCount;
            } else {
              unreadMutedCount += chat.unreadCount;
            }
```

I try to prepare a PR within the next few days.... but feel free to try it yourself

**Comment by akatarmo** [comment]
_> It seems like the `archive` attribute of WhatsApps IndexDB chat model/entity does no longer exist, so that https://github.com/ferdium/ferdium-recipes/blob/b21abf5ec30c35773890382869ee9d9ab8f4acec/recipes/whatsapp/webview.js#L42 always evaluate to false:
.
.
> I try to prepare a PR within the next few days.... but feel free to try it yourself_

I have modified the **webview.js** file according to your instructions and this patch certainly seems to fix the problem of the number of **unread messages** in Whatsapp. But... the main problem right now is that Ferdium **doesn't show any notification** on the taskbar when a new WhatsApp message comes in.

**Comment by gschafra** [comment]
> But... the main problem right now is that Ferdium doesn't show any notification on the taskbar when a new WhatsApp message comes in.

Sorry, for me it's working (using Ferium v6.4.0-nightly.6):

![grafik](https://github.com/ferdium/ferdium-app/assets/3999582/35bb361e-7844-4a45-b7f9-c31a9556ea3c)

using this settings:

![grafik](https://github.com/ferdium/ferdium-app/assets/3999582/b1c8ef76-8a49-4532-babc-ac060b470702)

Please ensure, that the "Show unread message badges" is enabled. At the time I made the change to the code, for some reason I don't understand, the option was disabled, although it was active before.

**Comment by apexnationz** [comment]
Thanks @gschafra for looking into this.

I updated to:
![grafik](https://github.com/ferdium/ferdium-app/assets/118275998/16c9a770-b861-437e-96d4-4ce13de1a2d3)

But had no luck:
![grafik](https://github.com/ferdium/ferdium-app/assets/118275998/5ab60f39-c323-4de0-a75f-2835f072ac11)

The button is set:
![grafik](https://github.com/ferdium/ferdium-app/assets/118275998/78e51948-0708-4200-92f3-c2ac4a87b3bd)

I hear the notification sound, but the message count is missing everywhere.

**Comment by RahKapoor** [comment]
The notification does not popup on Desktop ethier. Ferdium is not sending notification to Windows 11 or Macbook. The number is fine, the main issue is having a sound without the popup notification showing...

**Comment by skeelkat** [comment]
Strangely enough, since yesterday the odd notification does pop-up but then all of a sudden no longer after a while, and then one or two times later and then again only sound notification.

6.4.0-nightly.6

**Comment by yyounes75** [comment]
Still no notification on stable release 6.4.0

**Comment by gschafra** [comment]
According to #1105, Ferdium by itself does not send notifications, but the underlying (web) service/site/app, i.e. WhatsApp web, should do:

> Ferdium by itself does not send notifications. Thus you can only get notifications from services that send them, i.e. services you get notifications from on the web browser. If a website does not send web notifications, Ferdium can’t do it for it. This is because it has no system to read the messages’ sender information and content.

So I think, we should separate the message count (badge) problem, which seems to be fixed or will be fixed (PR) by https://github.com/ferdium/ferdium-app/issues/1182#issuecomment-1596060470#issuecomment-1596060470 from the notification problem. I will post a comment referring to this thread on/at #1105.

**Comment by RahKapoor** [comment]
When will this get fixed? Maybe time to move to Rambox?

**Comment by PingWeb** [comment]
Still not fixed? It is one of the most important features for me.

**Comment by marie-bnl** [comment]
As stated above in https://github.com/ferdium/ferdium-app/issues/1182#issuecomment-1608924837, this issue got a bit messy and discussions now seem to be directed towards two different issues. Thus, I fixed the count issue in https://github.com/ferdium/ferdium-recipes/pull/390 and I’m closing this issue in favour of https://github.com/ferdium/ferdium-app/issues/1105 for the notifications part.

**Comment by Cozynezz** [comment]
I have the same problem here
