### ISSUE TITLE
Hide context menu

### ISSUE THREAD

**Issue by xmha97** [ferdium/ferdium-app#1187]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22enhancement+%3Asparkles%3A%22) for a feature request that matches the one I want to file, without success.

### Problem Description

I want to hide the context menu.
![image](https://github.com/ferdium/ferdium-app/assets/23485114/b2a8fc4a-1d99-4dba-81d8-e8967cd10b9d)
Please add this feature.

### Proposed Solution

-

### Alternatives Considered

-

**Comment by Arthur-Huan** [comment]
That looks like the menu that you open when you right-click, does it not go away when you left-click somewhere else?

**Comment by xmha97** [comment]
> That looks like the menu that you open when you right-click, does it not go away when you left-click somewhere else?

No, the menu function is completely correct.
But I want to disable the menus completely.
It means that nothing happened with right-clicking.

**Comment by vraravam** [comment]
Please provide a valid usecase for hiding the menu.

**Comment by githubxnoob** [comment]
if this gets implemented atleast add on option to enable this. because its a very useful feature. i dont want it hidden.

**Comment by mcmxcdev** [comment]
Don't see the point in implementing a "hide context menu" functionality. One solution would be not to right-click.
