### ISSUE TITLE
When switching workspaces, the accounts logged in aren't being changed/logged changeable

### ISSUE THREAD

**Issue by lasersPew** [ferdium/ferdium-app#1193]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.2.7

### What Operating System are you using?

Windows

### Operating System Version

Windows 11 version 22H2

### What arch are you using?

x64

### Last Known Working Ferdium version

6.2.7

### Expected Behavior

When switching from one workspace to another given the same services for each workspace, it should haven't had the account.

### Actual Behavior

When switching from one workspace to another given the same services for each workspace, the account is still logged in

### Steps to reproduce

1. Create 2 workspaces
2. Add same services to both workspaces
3. Log onto a service on Workspace 1
4. Switch workspace 2

### Debug link

https://debug.ferdium.org/e721dd23-fb8a-425a-a998-e764a726f9e2

### Additional information

I don't know if this is a feature but my use case for it is to use a workspace with multiple accounts for multiple services.

**Comment by Arthur-Huan** [comment]
Someone can confirm this, but I think that's how it's intended to work.

To achieve what you want, you can add another instance of the same service, log in with a different account, and then assign the services to different workspaces.

**Comment by vraravam** [comment]
As @Arthur-Huan  said - this is how its supposed to work.  And yes, if you want 2 instances of the same service in 2 different workspaces, they will not share the login / session info.

**Comment by lasersPew** [comment]
I know this would make this project complicated but can it at least have a toggle to be like that instead of creating multiple instances?

**Comment by mateus3c** [comment]
> To achieve what you want, you can add another instance of the same service, log in with a different account, and then assign the services to different workspaces.

how can I do this? I downloaded Ferdium literally because I thought that was what it was supposed to do in the first place lol
