### ISSUE TITLE
Feature: Setting a slim sidebar issues with the window Close/Minimise/Maximise icons.

### ISSUE THREAD

**Issue by tnaseem** [ferdium/ferdium-app#120]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.29

### What Operating System are you using?

macOS

### Operating System Version

12.3.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Setting the sidebar size to something smaller than 'Normal' should do something with the Close/Minimise/Maximise window furniture - Maybe remove them and show on hover? Not even sure if this is possible.

### Actual Behavior

When resizing the sidebar to something smaller than 'Normal' with the draggable area set to 'Off', the title window close, minimise, and maximise icons bleed into the main section:

![2022-05-08_15-34-28](https://user-images.githubusercontent.com/1317345/167280688-af6f0e17-f7de-4c00-b17f-67250775d085.png)

Also, on a related note, when 'Show draggable area' is set to 'On', the same icons are not centralised vertically:

![2022-05-08_15-38-45](https://user-images.githubusercontent.com/1317345/167280728-d69401f0-74d9-4791-82fc-fb2ed87117bd.png)

Not sure what you can do about the first point, but if we can fix the second, and also allow the user to change the colour of the 'draggable' title bar to something other than the accent colour (feature request!) that would be better.

### Steps to reproduce

1. Go to **Settings/Appearance**.
2. Set Sidebar width to **Slim sidebar**, **Very slim sidebar**, or **Extremely slim sidebar**.
3. Set and unset **Show draggable area on window** to see the effects.

**Comment by SpecialAro** [comment]
Hello @tnaseem,

Thank you for raising this issue. I've check with nightly 10 (and also with Ferdi) and this issue is still present in both versions.

I think this is a feature request rather than a bug, so I'm changing the labels and the request title to match that, ok?

**Comment by tnaseem** [comment]
Sure, no worries!

**Comment by vraravam** [comment]
I dont think we have control over the size/position/placement of the 3 buttons that you refer to. This is at the macOS level, and apps cannot change that afaik. I would close this issue based on this reason. @tnaseem - please chime in.

**Comment by tnaseem** [comment]
I thought that might be the case. That's why I thought if you could allow the user to be able to set a different colour, other than the accent colour, for the dragable area, and maybe resize it so that the icons are vertically centred, that would allow for a cleaner, more subdued, look.

Would this work?

**Comment by vraravam** [comment]
The accent color can be implemented as an enhancement as already called out by @SpecialAro .

The shape/size/placement of the close/minimize/maximize buttons cannot be controlled by Ferdium.

If you still want to continue in this same ticket, I would request that you cleanup the original description and title to only talk/descibe about the accent color of the draggable area.

**Comment by vraravam** [comment]
Closing due to no response (and that I don't think this is controllable by the app - its an OS behavior)

**Comment by tnaseem** [comment]
Sorry, I didn't reply sooner. I have been in transit from NZ to the UK!

I understand about not being able to control the size of the icons. I was actually referring to the size of the draggable area. ie, making it bigger so that the icons are vertically centralised.

**Comment by vraravam** [comment]
So, if I understand you correctly, you are not looking to move the 3 OS-controlled buttons at all, is that right?

Isn't that already possible to have wider sidebar? There are quite a few options available in the sidebar options dropdown:
<img width="663" alt="Screenshot 2022-05-17 at 5 54 55 PM" src="https://user-images.githubusercontent.com/69629/168925245-251e6ba4-28ec-4fb5-bf0c-391bf882082c.png">

**Comment by tnaseem** [comment]
Yes, you can have a wider sidebar. But that's not the point. The point is that when you opt to have a slimmer one, it messes up the look with the icons 'hanging off', as explained before. To get around this, we have t enabled the draggable area. However, the icons are not centralised vertically with this enabled, as you can see from the screenshots I've supplied.

You can do nothing about the icons, so I suggested increasing the vertical height of the draggable area, so at least the icons are vertically centralised, which improves the look.

**Comment by vraravam** [comment]
ok - so, this is more of increasing the height of the draggable area - such that the OS-buttons are vertically centered. Got it. reopening this ticket.
