### ISSUE TITLE
Unwanted 'undefined' command shortcut shown in service tooltip

### ISSUE THREAD

**Issue by Alphrag** [ferdium/ferdium-app#1210]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.2.3-nightly.15

### What Operating System are you using?

Ubuntu

### Operating System Version

Ubuntu 20.04

### What arch are you using?

x64

### Last Known Working Ferdium version

6.3.0-nightly.12

### Expected Behavior

When hovering over a service in the sidebar, its name appears together with a command shortcut if there is a valid one.

### Actual Behavior

If the service index is higher that 10 in your sidebar (e.g. facebook is the 11th service on my workspace), then only the name of the service should appear in the tooltip. Instead, "undefined" appears after the name as if it were a valid command shortcut (e.g. it appears as `facebook undefined` as shown in the screenshot below). 

This problem has been introduced in #1201 and happens in the sidebar, but not in the menu.

### Steps to reproduce

1. Add at least 11 services.
2. Hover over the 11th one.
3. See that the tooltip shows `<name> undefined`

### Screenshots

![Screenshot from 2023-05-31 14-39-32](https://github.com/ferdium/ferdium-app/assets/34252790/5252be61-c6d6-468c-804a-3989d9292cb5)

### Additional information

In my opinion, these lines: 
https://github.com/vraravam/ferdium-app/blob/e9fec82e1e93dd3f52d7ddc38fea0355cce0ec68/src/components/services/tabs/TabItem.tsx#L362-L365
should write the accelerator only if it does not return `undefined`. @vraravam what do you think?

**Comment by vraravam** [comment]
im taking this up
