### ISSUE TITLE
Ferdium causing Instagram to detect automated behaviour?

### ISSUE THREAD

**Issue by RJVB** [ferdium/ferdium-app#1218]
### Your issue

Since a few days I get a warning message opening Instagram (in Ferdium or another browser or even in the app on my iPhone), about automated behaviour that has supposedly been detected.

I don't use any of the tools they suggest (why would I...) and I've already changed my password so the only thing I can imagine is that reloading their web interface too often is seen as automated behaviour. I've already disabled the "wake up" feature in Ferdium so there *should* be no auto-reloading behind my back but apparently that wasn't enough.

Any ideas?

**Comment by vraravam** [comment]
Are you sure that no one is trying to brute-force their access into your account? I dont know if this is necessarily related to Ferdium per se

**Comment by RJVB** [comment]
>Are you sure that no one is trying to brute-force their access into your account? I dont know if this is necessarily related to Ferdium per se

I don't see any evidence of that in the activity log Meta provides, and I'm a nobody esp. on IG which I only use to follow a couple of artists and luthiers and keep in contact with a few people who prefer it that way. Besides, you'd hope they don't suspend or ban accounts under the accusation that they are the targets of hacking attempts; the warning mentions bot activity to leave likes or "send it to @XX" comments.

Ferdium's hibernate/wake-up scheme is the only automated behaviour I can think of that has actual access to my account. I know it just reloads the inbox page but even that could raise eyebrows given how the majority of IG users will use an official app that doesn't require you to refresh anything automatically.

Is there a better place to raise this interrogation and see how many "me too" reactions it gets?

**Comment by RJVB** [comment]
Another possibility: IG could be detecting that Ferdium is not a standard web browser (I seem to recall there are other ways to do that than just the UserAgent string alone, harder to spoof)?

**Comment by vraravam** [comment]
> Another possibility: IG could be detecting that Ferdium is not a standard web browser (I seem to recall there are other ways to do that than just the UserAgent string alone, harder to spoof)?

yes that is a definite possibility as well. In which case, you will have to try with different user-agent strings till you can fix the problem. Again, in this case, we can't do naught in Ferdium - its left upto the user to try various combinations of User-agent string values and see what works best for your OS and browser combinations

**Comment by marie-bnl** [comment]
> the warning mentions bot activity to leave likes or "send it to @XX" comments

Then you can check [your interactions](https://www.instagram.com/your_activity/interactions/likes) just to make sure all are yours.

**Comment by RJVB** [comment]
First thing I did of course.

I've deactivated the periodic wake-up for IG and haven't seen the warning since. That is of course no proof that that is what was causing the problem...

**Comment by SpecialAro** [comment]
Hi @RJVB, do you still experience this issue?

**Comment by RJVB** [comment]
No, it must have been some kind of temporary glitch. They're good at that...
