### ISSUE TITLE
Self signed SSL certificate issue

### ISSUE THREAD

**Issue by owlysk** [ferdium/ferdium-app#1227]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.3.0

### What Operating System are you using?

Ubuntu

### Operating System Version

Ubuntu 22.04.2 LTS

### What arch are you using?

x64

### Last Known Working Ferdium version

i don't know

### Expected Behavior

I have a lot of self hosted services with self signed certificate. If I try to connect to e.g. self hosted Gitea, which has own self signed SSL certificate, shows me a white blank page.
I expected to show service page.

### Actual Behavior

Show only blank page.

### Steps to reproduce

1) Add new service
2) Set url to custom webpage with self signed certificate
3) Save and load service

### Additional information

If I use only HTTP, page is loaded. I guess there is missing ability to accept self signed certificates.
Can you please add this ability to app, or maybe a option to settings to allow self signed certificate?
Thanks

In console is this error message:
```
node:electron/js2c/renderer_init:2 Uncaught (in promise) Error: Error invoking remote method 'GUEST_VIEW_MANAGER_CALL': Error: Script failed to execute, this normally means an error was thrown. Check the renderer console for the error.
    at t.ipcRendererInternal.invoke (node:electron/js2c/renderer_init:2:11867)
    at async Promise.all (index 2)
    at async WebViewElement.<anonymous> (/snap/ferdium/278/re…s/Service.js:1:8395)
```

**Comment by Sudrien** [comment]
If these sites are internet-facing, Let's Encrypt / Certbot is definitely preferred - But self-signed does have it's merits.

trusting (or allowing override for) domainless and possibly hostname-domain (read: `hostname -A`) certs would be nice.

(I have tabs for klipper and pihole)

**Comment by mitchelljfranklin** [comment]
Would love for this to be resolved, services like TPlink omada controllers etc. come pre done with self singed and not being able to load due to not having the ability to turn off the check means this and other local services using self signed can be accessed

**Comment by C-Duv** [comment]
I guess adding a forward-proxy could be a fast workaround but maybe not as simple as adding `NODE_EXTRA_CA_CERTS` support (or similar)?

I see electron has a related issue: https://github.com/electron/electron/issues/10257

**Comment by Joe1962** [comment]
I also would love this resolved, by a commandline parameter or configuration. We have a lot of internal services and internet access only through a parent proxy, no real external ip address, so using Let's Encrypt is difficult for us. We use self-signed certificates signed by our own root certificate and key.

Just tested and "ferdium --ignore-certificate-errors" works, but it's hardly ideal.

**Comment by SpecialAro** [comment]
I think I'll be able to implement something like "Trusted Certificates" where you would need to upload (or maybe Ferdium could popup and ask to save) the self-signed certificate. I'm thinking that this Setting would not be enabled by default and you would have to enable it to get the feature to bypass (and save/manage) certain certificates. Would something like this work for you?

Note to myself (so I remember tomorrow when I try to implement it): https://stackoverflow.com/questions/38986692/how-do-i-trust-a-self-signed-certificate-from-an-electron-app

**Comment by Joe1962** [comment]
> Would something like this work for you?
> 

If it's easier than using the OS trusted certificates, then I would be cool with that. If possible, allow adding not just a specific server certificate, but the root certificate used to sign them (the public root cert, of course)? If not, still good...

**Comment by SpecialAro** [comment]
@Joe1962 I just tested by adding the root CA of badssl to the "Trusted Root Certification Authorities" on mmc.exe (on Windows) and I am able to see the page without any issue.

![image](https://github.com/ferdium/ferdium-app/assets/37463445/cf7388d0-d48b-4449-a5c8-959324a416aa)

Nevertheless, for specific self-signed certificates (without a Root CA added to the trusted list) I can maybe make a simple cert store (if certificate is present, proceed, else dont proceed).

**Comment by Joe1962** [comment]
> @Joe1962 I just tested by adding the root CA of badssl to the "Trusted Root Certification Authorities" on mmc.exe (on Windows) and I am able to see the page without any issue.
> 

Hmm... it doesn't seem to work on Linux though. I added the rootCA according to the normal procedure.

**Comment by SpecialAro** [comment]
> > @Joe1962 I just tested by adding the root CA of badssl to the "Trusted Root Certification Authorities" on mmc.exe (on Windows) and I am able to see the page without any issue.
> 
> Hmm... it doesn't seem to work on Linux though. I added the rootCA according to the normal procedure.

Did you restart Ferdium after that? Maybe on linux it doesn't work indeed.

Nevertheless, I added the option of self-signed certificates in this PR https://github.com/ferdium/ferdium-app/pull/1545 . Lets wait for approval for another maintainer so I can move to merge it.

**Comment by Joe1962** [comment]
> > > @Joe1962 I just tested by adding the root CA of badssl to the "Trusted Root Certification Authorities" on mmc.exe (on Windows) and I am able to see the page without any issue.
> > 
> > 
> > Hmm... it doesn't seem to work on Linux though. I added the rootCA according to the normal procedure.
> 
> Did you restart Ferdium after that? Maybe on linux it doesn't work indeed.
> 

Oh, yes, many times since.

> Nevertheless, I added the option of self-signed certificates in this PR #1545 . Lets wait for approval for another maintainer so I can move to merge it.

Thanks!

**Comment by Muzosh** [comment]
> If these sites are internet-facing, Let's Encrypt / Certbot is definitely preferred - But self-signed does have it's merits.

Sites from a server running https://caddyserver.com/ (which obtains Let's Encrypt server certificates) are not loading for me either now.
