### ISSUE TITLE
Release notes links open inside Ferdium

### ISSUE THREAD

**Issue by FANMixco** [ferdium/ferdium-app#1228]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.3.0

### What Operating System are you using?

Windows

### Operating System Version

Windows 11 22H2

### What arch are you using?

x64

### Expected Behavior

If you open any links from the following list:

<img width="506" alt="image" src="https://github.com/ferdium/ferdium-app/assets/1666156/981730a0-c277-48ce-b711-0c8c805cb311">

They should open in the regular browser.

### Actual Behavior

The links open inside Ferdium and you cannot go back:

<img width="1128" alt="image" src="https://github.com/ferdium/ferdium-app/assets/1666156/631c6132-cbe5-49f4-af55-44442bbb8c69">

### Steps to reproduce

1. Open Ferdium.
2. Open Settings.
3. Choose Release Notes.
4. Do click on any link.

**Comment by vraravam** [comment]
This is the expected behavior - that the release notes open within Ferdium itself. I think there's either an 'X' on the top right, or the escape key or the Cmd+Left arrow will take you back to the previous screen. (im not at my laptop right now, and can't check). Closing this ticket.
