### ISSUE TITLE
Release notes links open inside Ferdium

### ISSUE THREAD

**Issue by FANMixco** [ferdium/ferdium-app#1229]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.3.0

### What Operating System are you using?

Windows

### Operating System Version

Windows 11 22H2

### What arch are you using?

x64

### Last Known Working Ferdium version

6.3.0

### Expected Behavior

If you open any links from the following list:

https://user-images.githubusercontent.com/1666156/243218151-981730a0-c277-48ce-b711-0c8c805cb311.png

They should open in the regular browser or have an X to close it.

### Actual Behavior

The links open inside Ferdium and you cannot go back:

![ezgif-5-d3b0c47529](https://github.com/ferdium/ferdium-app/assets/1666156/2c01ca27-0b49-4649-a334-d001c03cf1eb)

### Steps to reproduce

- Open Ferdium.
- Open Settings.
- Choose Release Notes.
- Do click on any link.

**Comment by Alphrag** [comment]
Since I started discussing this problem in #1232 before seeing your issue, I will close this one as a duplicate to move all the discussion there.
