### ISSUE TITLE
Changelog Link opens in Ferdium and blocks it

### ISSUE THREAD

**Issue by francwalter** [ferdium/ferdium-app#1232]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.4.0-nightly.2

### What Operating System are you using?

Windows

### Operating System Version

Windows 10 (64-Bit) Version 22H2

### What arch are you using?

x64

### Last Known Working Ferdium version

Never hit that link before.

### Expected Behavior

When I click the Link for Full Changelog under Settings > Release notes I expect that the changelog opens in my browser but not in Ferdium. And if it opens in Ferdium, I should be able of going back to my services.
The Menu bar should not be disabled, especially when I have it not disabled. Keyboard Shortcuts should still work.

### Actual Behavior

I open in Ferdium the Changelog under:

Settings > Release Notes > Full Changelog (Link)

and Ferdium opens in his whole window (fullscreen, I guess) the changelog on Github. Now I am trapped in that page, no Menubar anymore, no service, no Shortcut is working (e.g. Reload Ferdium), I have to Quit Ferdium and reopen Ferdium by SystemTray menu (in the Ferdium Window I cant, no menu anymore, only Github page).

### Steps to reproduce

1. Go to Ferdium Settings
2. Open Release Notes
3. Click the Github-Link under Full Changelog
4. Try to use again Ferdiums Services etc.

### Screenshots

![grafik](https://github.com/ferdium/ferdium-app/assets/927269/f229bd5b-9d9b-4ac8-ae75-10a9f08ce8c7)

This is the whole Ferdium Window after hitting the changelog link.

### Additional information

I guess this is not only related to the Changelog Link, but I hadnt such behaviour before. Normally a extern Link should **not** open in Ferdium, maybe it is the only "buggy" link.

**Comment by Arthur-Huan** [comment]
To open links in Ferdium, or not to, that is the question.
Whether 'tis better for the user to suffer
The slings and arrows of unwanted webpages in-app,
Or to have web links open externally in the browsers,
And by doing so cause bugs: to freeze, to voice call
No more; And to have unresponsive download links.


I can confirm the page also opens within Ferdium on my Linux v6.3.0 version.
I usually set links to open within Ferdium, and use the context menu to open certain links in the browser. Though, this link doesn't have a context menu, perhaps because it's not in a webpage but the app itself. Yet, some other links in the Settings, like in the About Ferdium section, do open externally.

**Comment by francwalter** [comment]
The issue is not that it is opening in Ferdium, but that this is making Ferdium unusable.

**Comment by Alphrag** [comment]
Hi @francwalter well done for spotting that. We are using a listener to block these events from opening in Ferdium and to open in the usual browser as follows:
https://github.com/ferdium/ferdium-app/blob/4bf2fe30c1f58fbd97670876b974f488a40218aa/src/components/settings/releaseNotes/ReleaseNotesDashboard.tsx#L57-L65
This was working at some point before, so it appears that something in electron has changed without us noticing which makes our handling of the click fail. 
@SpecialAro would you have the time to look into it at some point?

**Comment by Alphrag** [comment]
@FANMixco do you know of a previous version in which this was working and actually opening the links in the browser?

**Comment by SpecialAro** [comment]
Hey! 💪

I can try to make some time to look into it. I think this might be related to a PR that changed the default behaviour of links "target" attribute. I remember seeing something about it.

**Comment by FANMixco** [comment]
> @FANMixco do you know of a previous version in which this was working and actually opening the links in the browser?

I don't know. I found it by accident when I was checking the changelog.

**Comment by SpecialAro** [comment]
Hello @francwalter, I've tried to reproduce this issue on my local (in 6.4.0-nightly.4 on Windows 11) and I don't seem to see any issue whatsover. Would you be able to provide some screenshots please?
Settings > Release Notes:
![image](https://github.com/ferdium/ferdium-app/assets/37463445/f952c5d3-bded-4750-a3ea-84b0a59f3d98)

What is new (if there is an update):
![image](https://github.com/ferdium/ferdium-app/assets/37463445/c9b3543b-0346-45b7-9843-3ca6220870da)

Help > Changelog:
![image](https://github.com/ferdium/ferdium-app/assets/37463445/f818c4f6-2258-4a29-934f-64f0478abe3a)
