### ISSUE TITLE
Feature: Creation of homebrew taps

### ISSUE THREAD

**Issue by kishaningithub** [ferdium/ferdium-app#124]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Currently there are no homebrew packages available. I (as many others) install all the programs on my mac with homebrew. While i understand putting this in hombrew-core would need more criterias to be met, i do propose the following solution to ensure the same user experience without the hombrew-core dependency.

### Proposed Solution

I would like to propose we create a separate homebrew tap repository (example - https://github.com/kishaningithub/homebrew-tap) to ensure homebrew users can install ferdium (both beta and stable versions) from the tap.

Given there wont be any dependency with hombrew-core the CI/CD pipelines can ensure a new version is available as soon as we tag a release.

The user experience would also remain the the same i.e. the instead of brew install ferdium the user can either `do brew install ferdium/tap/ferdium` or `brew tap ferdium/tap && brew install ferdium`

### Alternatives Considered

Download the package directly from releases.

### Additional Information

If you agree with this. Can you kindly create a repository named `homebrew-tap` within this organization? i can help create PRs into both this repo and also on the CI/CD pipelines.

**Comment by vraravam** [comment]
I have already created this repo - and tested this @kishaningithub . Thanks for the offer.

The repo is: https://github.com/ferdium/homebrew-ferdium/
