### ISSUE TITLE
Bug when login with chatgpt

### ISSUE THREAD

**Issue by ghost** [ferdium/ferdium-app#1246]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+%3Abookmark_tabs%3A%22+label%3A%22bug+%3Abeetle%3A%22+) for a bug report that matches the one I want to file, without success.

### Ferdium Version

the last one (17 june 2023)

### Recipe Name

ChatGPT

### Recipe Version

the last one (17 june 2023)

### Steps to reproduce

1. Log In
2. Log in with google
3. Enter Email
4. Impossible de vous connecter
Ce navigateur ou cette application ne sont peut-être pas sécurisés. [En savoir plus](https://support.google.com/accounts/answer/7675428?hl=fr)
Essayez dans un autre navigateur. Si vous utilisez déjà un navigateur compatible, vous pouvez réessayer de vous connecter.

### Expected Behavior

Need input to log in to my google account

### Actual Behavior

Impossible de vous connecter
Ce navigateur ou cette application ne sont peut-être pas sécurisés. [En savoir plus](https://support.google.com/accounts/answer/7675428?hl=fr)
Essayez dans un autre navigateur. Si vous utilisez déjà un navigateur compatible, vous pouvez réessayer de vous connecter.

(french version)

### Screenshots

![image](https://github.com/ferdium/ferdium-app/assets/89699409/529d1744-edc0-481d-93a4-87bdd2a5c30a)

https://github.com/ferdium/ferdium-app/assets/89699409/529d1744-edc0-481d-93a4-87bdd2a5c30a

### Additional Information

N/A

**Comment by eaganlai** [comment]
Same result.

![image](https://github.com/ferdium/ferdium-app/assets/74284983/e4e36e1e-d5e7-4810-98d8-ce9d8e5d6798)

**Comment by Arthur-Huan** [comment]
I think this is not a ChatGPT-related issue, rather you are unable to use Google as login. This probably would happen if you tried this with any other service.

You can perhaps try allowing external URLs in the options for that service. The Google login will be opened in your default browser instead.

**Comment by sigau** [comment]
@Arthur-Huan I got the same problem but i can use my google account to connect to other service maybe the problem come from somewhere else
