### ISSUE TITLE
flatpak is still stuck in v6.2.7

### ISSUE THREAD

**Issue by ahjolinna** [ferdium/ferdium-app#1250]
### Your issue

so it seems flatpak version is still stuck on v6.2.7 after 3 weeks of the release, this was already reported 2 days ago in flathub: https://github.com/flathub/org.ferdium.Ferdium/issues/30

PS. if possible maybe add to beta channel the nightly builds for those who want to test the latest changes

**Comment by deadmeu** [comment]
The Flatpak build is now on 6.3.0
