### ISSUE TITLE
Verify Flatpak ownership

### ISSUE THREAD

**Issue by deadmeu** [ferdium/ferdium-app#1257]
### Your issue

Flathub now offers the ability for app owners to [verify the ownership of Flatpaks](https://flathub.org/about). This lets users feel more confident that they are downloading an official and safe release. It would be great if Ferdium was recognised as a verified release on the website.

Upstreamed from https://github.com/flathub/org.ferdium.Ferdium/issues/23 to garner further attention.

**Comment by lhw** [comment]
Done
