### ISSUE TITLE
Telegram Call won't connect

### ISSUE THREAD

**Issue by gaylie** [ferdium/ferdium-app#1259]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.4.1-nightly.3

### What Operating System are you using?

Windows

### Operating System Version

Windows 11 22H2

### What arch are you using?

x64

### Expected Behavior

I call someone on Telegram and when they pick up it connects.

### Actual Behavior

I call someone on Telegram and when they pick up it's stuck endlessly in the "Connecting..." screen. Issue remains if I switch between "WebRTC IP Handling Policy" options.

### Steps to reproduce

1) Open Telegram
2) Call someone

### Debug link

https://debug.ferdium.org/88433dc0-a7cd-498d-8542-c1528adae6e8

**Comment by gaylie** [comment]
Update: It works now... I didn't change anything. The workings of Ferdium and Telegram are a real mystery to me.

**Comment by SpecialAro** [comment]
After changing the WebRTC police have you restarted Ferdium?

If not, once you restarted it probably started working 😁
