### ISSUE TITLE
Workspace need to have separated sessions

### ISSUE THREAD

**Issue by alexander9306** [ferdium/ferdium-app#1262]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22enhancement+%3Asparkles%3A%22) for a feature request that matches the one I want to file, without success.

### Problem Description

It would make the app awesome to support separated sessions for workspaces. Currently, If I have two separate WhatsApp, one for work, other for business and I can not use the app for that. 

### Proposed Solution

Add separated information for workspaces. 

### Alternatives Considered

rambox.app

**Comment by alexander9306** [comment]
feature already implemented

**Comment by cmantsch** [comment]
I also would like to have a feature to have separate sessions active simultaneously, how did you manage to do so? Can't find it in the settings
