### ISSUE TITLE
Skiff

### ISSUE THREAD

**Issue by Dominiquini** [ferdium/ferdium-app#1264]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+request+%3Asparkles%3A%22) for a recipe request that matches the one I want to file, without success.

### Name of the service

Skiff

### URL of the service

https://app.skiff.com/mail/inbox

### Features you want implemented

Add Skiff to Ferdium as a new service.

**Comment by Dominiquini** [comment]
webview.js:

```
module.exports = Ferdium => {
  const getMessages = () => {
    let unreadCount = 0;
    // Loop over all displayed counters and take the highest one (from the "Inbox" folder)
    for (const counterElement of document.querySelectorAll('.sc-60811559-3')) {
      const unreadCounter = Ferdium.safeParseInt(counterElement.textContent);
      unreadCount = Math.max(unreadCount, unreadCounter);
    }

    Ferdium.setBadge(unreadCount);
  };

  Ferdium.loop(getMessages);
};
```

**Comment by marie-bnl** [comment]
I don’t have any `.sc-60811559-3` on my inbox page. So either it got updated since you made it, or it’s different for each account, page view or something else. In all cases, I think we need to figure out another method to get the unread messages count.

**Comment by marie-bnl** [comment]
~Parsing the tab title seems like a pretty good way to do so.~ (it actually doesn’t work because it’s only the count of the opened folder)

I suggest we get the elements by using the following selector: `div[href="/mail/inbox"]`

**Comment by Dominiquini** [comment]
> ~Parsing the tab title seems like a pretty good way to do so.~ (it actually doesn’t work because it’s only the count of the opened folder)
> 
> I suggest we get the elements by using the following selector: `div[href="/mail/inbox"]`

I don't feel qualified to implement this! If you do something, post it here for me to try.

Thanks.

**Comment by marie-bnl** [comment]
Don’t worry I tried it myself and I’m making a pull request!
