### ISSUE TITLE
Bard

### ISSUE THREAD

**Issue by heuzef** [ferdium/ferdium-app#1271]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+request+%3Asparkles%3A%22) for a recipe request that matches the one I want to file, without success.

### Name of the service

Google Bard

### URL of the service

https://bard.google.com

### Features you want implemented

This new service of Google can be added to Ferdium ?

**Comment by quantumxx** [comment]
Bard sucks though, why?

**Comment by heuzef** [comment]
> Bard sucks though, why?

What's suck ? The politics of Google ? Yes for sur, it's not new.

**Comment by marie-bnl** [comment]
Can you test it by adding the “bard” folder to `USER_DATA/Ferdium/recipes/dev/` please?

[bard.zip](https://github.com/ferdium/ferdium-app/files/12081475/bard.zip)

> **Note**
>
> `USER_DATA`'s location depends on your platform:
>
> - **Windows**: `%APPDATA%`
> - **Linux**: `$XDG_CONFIG_HOME` or `~/.config/`
> - **MacOS**: `~/Library/Application Support`

**Comment by heuzef** [comment]
It's work :) Thanks
