### ISSUE TITLE
Perplexity

### ISSUE THREAD

**Issue by quantumxx** [ferdium/ferdium-app#1272]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+request+%3Asparkles%3A%22) for a recipe request that matches the one I want to file, without success.

### Name of the service

Perplexity

### URL of the service

https://www.perplexity.ai/

### Features you want implemented

Add this website to Ferdium

**Comment by meiphoo7-Mae** [comment]
I was also thinking about asking for a recipe for Perplexity, however I didn't see any special features that require a recipe. For example: there's no counter or whatsoever, so no need for a badge. Also the website provides an immediate result for the question asked, so nothing special needed for that too.
Therefore I decided to try the 'custom website' option and it worked, using the URL you mentioned.

**Comment by quantumxx** [comment]
It's stuck on Cloudflare for me. Did you do something different?

**Comment by meiphoo7-Mae** [comment]
No, I did not do something special.
What happens when you activate the navigation bar in Ferdium (if you didn't do that already) and type the URL and then press ENTER.
Cloudflare can be really picky. If they've flagged your IP address for some reason then you're in trouble. They also reject certain browsers for various reasons, but Ferdium (current nightly) is apparently acceptable as it works for me.

**Comment by marie-bnl** [comment]
> I was also thinking about asking for a recipe for Perplexity, however I didn't see any special features that require a recipe. For example: there's no counter or whatsoever, so no need for a badge. Also the website provides an immediate result for the question asked, so nothing special needed for that too.

If you take a look at the recipes, a lot of recipes like what you are describing are present though, for example ChatGPT’s. It’s just more convenient for users don’t have to type in the URL, set an icon, etc.

**Comment by quantumxx** [comment]
Thanks, @victorbnl. Can I ask how do I access Perplexity service now? I tried updating Ferdium and searching it under all services again.

**Comment by marie-bnl** [comment]
I am not a maintainer of Ferdium, thus I have only made a pull request, now you have to wait for Ferdium’s maintainers to accept it. And even after that, it may take some time for Ferdium to update its recipes. So maybe try a day after the PR has been accepted, if it gets accepted (it probably will).

**Comment by quantumxx** [comment]
Thanks for contributing.

**Comment by quantumxx** [comment]
I saw you provide a zip for Bard recipe, so if you can do this for Perplexity as well, it would be great @victorbnl.

**Comment by marie-bnl** [comment]
Sure, here you go

[perplexity.zip](https://github.com/ferdium/ferdium-app/files/12089154/perplexity.zip)
