### ISSUE TITLE
[Telegram] Links "t.me" are opened in external browser instead if processing internally

### ISSUE THREAD

**Issue by don-andruha** [ferdium/ferdium-app#1275]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.4.0

### Recipe Name

Telegram, ver 3.3.5

### What Operating System are you using?

Other Linux

### Operating System Version

Linux Mint 21.1 Cinnamon [Linux 5.15.0-76-generic #83-Ubuntu SMP Thu Jun 15 19:16:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux]

### What arch are you using?

x64

### Last Known Working Ferdium version

Ferdi 5.8.1, Telegram recipe 2.3.4

### Expected Behavior

We should be redirected to the target chat inside **Ferdium** with ability to view message

### Actual Behavior

Link like `https://t.me/channel_name/12345` is opened in an external browser instead.
Even if I turn on option "Open URLs within **Ferdium**" can't fix this behavior.

### Steps to reproduce

1. Receive link like this: https://t.me/telegram/237 in Telegram as an incoming message or send it to yourself in "Saved messages" (or just "Telegram")
2. Click on it.

### Additional information

Similar issue here: https://github.com/ferdium/ferdium-app/issues/1027

**Comment by marie-bnl** [comment]
This is because those link have `target="_blank"` so one could argue this is expected behaviour. There is the “Open URLs within Ferdium” option which works, but it also opens any other links in Ferdium. Note this issue happens on other services as well such as Reddit.

I guess making all links on `web.telegram.org` and `t.me` open within Ferdium, from the service’s webview.js, would be a good solution.

**Comment by don-andruha** [comment]
@victorbnl it is a pity, but it did not help.
I updated the recipe.
Now the link opens in **Ferdi**, but in the inner browser, and not in the Telegram messenger inside Ferdi

**Comment by marie-bnl** [comment]
It’s strange, it works on my side

![image](https://github.com/ferdium/ferdium-app/assets/39555268/c0a39fb0-3445-4acb-aa82-11b82eb93171)

**Comment by marie-bnl** [comment]
Are you sure you’re using the latest Telegram recipe, that is, version 3.3.6?

**Comment by don-andruha** [comment]
> Are you sure you’re using the latest Telegram recipe, that is, version 3.3.6?

Yeah.
I'll try to record screencast today to explain what i tell about

**Comment by marie-bnl** [comment]
That will be helpful, thank you!

**Comment by don-andruha** [comment]
Sorry for my absence for a few weeks.

This is **Ferdium 6.4.0** and there is 2 ways of opening links:
- **t.me** links always open message in external app
- clicking the button is opening message inside the app

Screencast here: https://www.veed.io/view/bb958488-0e57-44be-8dc9-cbc4e895e335?panel=share
<br>

This is **Ferdi 5.8.1** and it`s open **t.me** links this way:
- Both click methods open message directly inside the app.

Screencast here: https://www.veed.io/view/cd16ee15-e639-4cc6-af34-36325c2f3847?panel=share

@victorbnl I'll hope it be helpful for you.

**Comment by marie-bnl** [comment]
What happens if you try it from the web browser?

**Comment by don-andruha** [comment]
> What happens if you try it from the web browser?

It always try to open an external Telegram app.

**Comment by marie-bnl** [comment]
Well, Ferdium is designed to be a web browser. That is a bad design made by Telegram and I don’t think it’s Ferdium’s job to try to work around it. So let’s wait for an answer from the developers, but for me I don’t know if we should do something about it.

**Comment by don-andruha** [comment]
In general I agree with you.
But the bug i described make barrier to use Telegram inside of **Ferdium**.

For example - I have one account (1) in desktop app and other (2) inside **Ferdium**.
If i want send request to join channel from second account -  I can`t do it for the indicated reason.

**Comment by SpecialAro** [comment]
From what I can see, whenever we click inside the webview link, it tries to open it in a default app installed on Windows (since I dont have one, I get a popup to install it from Microsoft store).

![image](https://github.com/ferdium/ferdium-app/assets/37463445/b618ed38-28d4-469e-8681-3a7d419fa6cd)

Basically what you are asking is to prevent the deep linking that happens whenever we click a link (it generates a protoUrl -> window.protoUrl that is then used to try to navigate from deep link).

I'm investigating if I can write a workaround for this.

**Comment by don-andruha** [comment]
Thanks a lot! It works like a charm for me!
