### ISSUE TITLE
Can’t paste large images

### ISSUE THREAD

**Issue by marie-bnl** [ferdium/ferdium-app#1285]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.4.0

### What Operating System are you using?

Other Linux

### Operating System Version

Arch

### What arch are you using?

x64

### Expected Behavior

Pasting a large image on a service works.

### Actual Behavior

Pasting a 4K image on any service make it freeze for one second, and result in a corrupted image.

### Steps to reproduce

1. Copy a 4K image ([here’s one](https://the-peak.ca/wp-content/uploads/2020/10/duo4.jpg))
2. Try to paste it on a service

### Debug link

https://debug.ferdium.org/1a643e2a-8246-4522-9586-f830f7118cfb

### Screenshots

**Discord**

![image](https://github.com/ferdium/ferdium-app/assets/39555268/bc744036-9c3d-45fc-bcc7-6ac138349864)

**WhatsApp**

![image](https://github.com/ferdium/ferdium-app/assets/39555268/da6dc331-75eb-430d-95d7-a0313119ffa7)

### Additional information

It happened on Discord, Instagram and WhatsApp and I think it happens on basically any service. It doesn’t happen with those on Firefox.

**Comment by marie-bnl** [comment]
After further testing, I noticed it happens on Chromium as well. Should we thus close the issue for being out of the scope of Ferdium?

**Comment by SpecialAro** [comment]
@victorbnl if this happens on Chromium as well, I don't think we could fix it until they do... So I'm closing the issue. But let me know if we should re-open it
