### ISSUE TITLE
Bug: Discord has White Bar

### ISSUE THREAD

**Issue by amangalampalli** [ferdium/ferdium-app#129]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.30

### What Operating System are you using?

macOS

### Operating System Version

macOS Monterey 12.3.1

### What arch are you using?

x64

### Last Known Working Ferdium version

N/A

### Expected Behavior

Normal menu option without a white bar on the side.

### Actual Behavior

There seems to be a white bar on the text box towards the right-hand side. 

### Steps to reproduce

Sign into the Discord service.in to

### Debug link

https://debug.ferdium.org/cf0d400d-7db6-4513-b57d-6a0a4fab62ac

### Screenshots

There seems to be a white bar when using Discord on Ferdium whereas it doesn't seem to exist when checking the Discord web version:
![](https://cdn.discordapp.com/attachments/963841911376982046/973463297972117504/Screen_Shot_2022-05-09_at_10.54.39_PM.png)
This is how the web version looks
![](https://cdn.discordapp.com/attachments/963841911376982046/973463443015340043/Screen_Shot_2022-05-09_at_10.56.02_PM.png)

**Comment by vraravam** [comment]
Please move this into the `ferdim-recipes` repository.
<img width="960" alt="Screenshot 2022-05-14 at 6 52 39 AM" src="https://user-images.githubusercontent.com/69629/168424518-7fbfbc67-d57c-4fa6-b02e-a1adfa8ffe40.png">
