### ISSUE TITLE
Cannot access internal web server in browser

### ISSUE THREAD

**Issue by mjeveritt** [ferdium/ferdium-app#1298]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.4.0

### What Operating System are you using?

Ubuntu

### Operating System Version

Ubuntu LTS 18.04

### What arch are you using?

x64

### Expected Behavior

I am presently running Ferdi 2.8.1 (last release) and wanted to migrate over to Ferdium (and take advantage of updated recipes and fixed bugs) but following the migration process, I cannot access the Ferdium internal web server. All I get is a 403 forbidden message (Access Denied).

### Actual Behavior

Adding services manually, a red warning briefly pops up, but the service appears to load, and it does persist over a restart.

I would however, like to migrate all my settings over, to save me setting up everything individually, and to have the facility to migrate in the future.

This isn't a problem, however, for the existing Ferdi install, which displays correctly (and has allowed me to Export my data as suggested) !!

### Steps to reproduce

Install Ferdium.
Go to Help/Import-Export
Browser is spawned - Access Forbidden / Denied is displayed (403).

### Debug link

https://debug.ferdium.org/defcbfa5-cb65-4b5a-89c1-10688e2c15be

### Screenshots

![image](https://github.com/ferdium/ferdium-app/assets/11815838/67e735fb-0b78-4d26-9ee8-dc2125835b79)

**Comment by mjeveritt** [comment]
By contrast here is Ferdi's:
![image](https://github.com/ferdium/ferdium-app/assets/11815838/3e1d303d-8049-426b-b1c1-563a61db4797)

**Comment by Alphrag** [comment]
Hi @mjeveritt, I have never had this problem, so I suppose that this might be because of some extension that you have in your browser which removes the token passed into the url before charging the page. In order to account for that, you can either manually set the token in your cookies, or try to disable the problematic extension. 
Since this token is generated randomly at startup, you will find it written at the bottom of the `Advanced` tab in the `Settings`.

**Comment by mjeveritt** [comment]
> Hi @mjeveritt, I have never had this problem, so I suppose that this might be because of some extension that you have in your browser which removes the token passed into the url before charging the page. In order to account for that, you can either manually set the token in your cookies, or try to disable the problematic extension. Since this token is generated randomly at startup, you will find it written at the bottom of the `Advanced` tab in the `Settings`.

Aha excellent - yes I see the URL at the bottom of the Settings/Advanced tab, and sure enough it has allowed me into the webserver to import settings.
I shall continue to do a little more debugging to see if I can pinpoint the issue, but for now I think my problem is solved! Thanks for the tip!

**Comment by Alphrag** [comment]
> I shall continue to do a little more debugging to see if I can pinpoint the issue, but for now I think my problem is solved! Thanks for the tip!

Great I'll close this issue then, but feel free to add your findings here, it can always be useful for someone else at another point ;-)
