### ISSUE TITLE
Microsoft Outlook always loses credentials

### ISSUE THREAD

**Issue by awilliansd** [ferdium/ferdium-app#1301]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

v6.4.0

### What Operating System are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

It always have credentials in initialization

### Actual Behavior

Microsoft Outlook always loses my credentials and if I try to put my credentials, it reinitializes the service. So, I need to delete and insert the service again to work.

### Steps to reproduce

No apply

**Comment by jtrosper** [comment]
I was able to work around this for Office 365 Outlook by correcting the URL. That URL points to https://outlook.live.com/mail - which is not the correct endpoint for hosted O365. I changed it to https://outlook.office.com/ and now it works.

**Comment by awilliansd** [comment]
It works. Thanks

**Comment by Woynert** [comment]
Thank you so much! This was driving me crazy

**Comment by jtrosper** [comment]
> I was able to work around this for Office 365 Outlook by correcting the URL. That URL points to https://outlook.live.com/mail - which is not the correct endpoint for hosted O365. I changed it to https://outlook.office.com/ and now it works.

I issued a pull request on ferdium-recipes to correct this.

**Comment by Glitch3dPenguin** [comment]
> I was able to work around this for Office 365 Outlook by correcting the URL. That URL points to https://outlook.live.com/mail - which is not the correct endpoint for hosted O365. I changed it to https://outlook.office.com/ and now it works.

I ran into this myself and this fixed it for me as well! Thank you!

**Comment by aith85** [comment]
Same trick for Microsoft To-Do, if needed.
From `https://to-do.live.com/tasks` to `https://to-do.office.com/tasks/today`

**Comment by xgrind** [comment]
> > I was able to work around this for Office 365 Outlook by correcting the URL. That URL points to https://outlook.live.com/mail - which is not the correct endpoint for hosted O365. I changed it to https://outlook.office.com/ and now it works.
> 
> I issued a pull request on ferdium-recipes to correct this.

It was the only solution that actually worked. Thank you.
