### ISSUE TITLE
Whatsapp shows badges/unread for "silent" conversations

### ISSUE THREAD

**Issue by kennyeni** [ferdium/ferdium-app#1303]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+%3Abookmark_tabs%3A%22+label%3A%22bug+%3Abeetle%3A%22+) for a bug report that matches the one I want to file, without success.

### Ferdium Version

6.4

### Recipe Name

WhatsApp

### Recipe Version

3.4.10

### Last Known working version of the recipe

-

### Steps to reproduce

1. Have a "silenced conversation"
2. Receive a message on that conversation
3. App badge gets shown on sidebar, and dock (I'm on Mac)

### Expected Behavior

Silenced conversations should only be shown on the actual app, app integration should skip those.

### Actual Behavior

App badge gets shown on sidebar, and dock (I'm on Mac)

**Comment by kikislater** [comment]
Same for me in archlinux, ferdium 6.4.1, recipe 3.5.1, electron25

It was working as expected before 6.4.1
![image](https://github.com/ferdium/ferdium-app/assets/13238064/13fe9ce5-3f89-4831-a711-1d6cab9bdcad)

**Comment by kikislater** [comment]
I need to try, but it seems to come from this
https://github.com/ferdium/ferdium-recipes/commit/a2b4ae56466acedde758de8e0c14475bbf3fa9f0

or that 
https://github.com/ferdium/ferdium-recipes/commit/fd169b7b2ad80abce5b044909d5234f0ea6a1c27

**Comment by gmurdocca** [comment]
This small (naive - read on), one-line patch to the whatsapp recipe seemed to fix the issue. Caution: I am completely unfamiliar with how the `dbCache` or IndexedDB works. I expected to see the usual DOM querySelector stuff present to evaluate unread counts but noticed the move away from it in [this commit](https://github.com/ferdium/ferdium-recipes/commit/8e2492648b7d320f417ac416106b0baf8568f8ed). Inspecting the variables and updating the below condition to succeed when `chat.muteExpiration == -1` seemed to work.

```diff
diff --git a/recipes/whatsapp/webview.js b/recipes/whatsapp/webview.js
index 26f2a3a..dabecc5 100644
--- a/recipes/whatsapp/webview.js
+++ b/recipes/whatsapp/webview.js
@@ -18,7 +18,7 @@ module.exports = Ferdium => {
       query.onsuccess = event => {
         for (const chat of event.target.result) {
           if (chat.unreadCount > 0) {
-            if (chat.muteExpiration > 0 || chat.isAutoMuted) {
+            if (chat.muteExpiration != 0 || chat.isAutoMuted) {
               unreadMutedCount += chat.unreadCount;
             } else {
               unreadCount += chat.unreadCount;
```

**Comment by kikislater** [comment]
Thanks ! 
This is working => 
```
      query.onsuccess = event => {
        for (const chat of event.target.result) {
          if (chat.unreadCount > 0) {
            if (chat.muteExpiration == -1 || chat.isAutoMuted) {
              unreadMutedCount += chat.unreadCount;
            } else {
              unreadCount += chat.unreadCount;
            }
          }
        }
```

May be you could send a PR ?

**Comment by gmurdocca** [comment]
working through the PR process now.

**Comment by SpecialAro** [comment]
I'm closing this issue as complete now, given the PR being merged to the codebase 😁 

Thank you everyone!
