### ISSUE TITLE
Whatsapp new update loop

### ISSUE THREAD

**Issue by mkozjak** [ferdium/ferdium-app#1310]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+%3Abookmark_tabs%3A%22+label%3A%22bug+%3Abeetle%3A%22+) for a bug report that matches the one I want to file, without success.

### Ferdium Version

6.4.0

### Recipe Name

WhatsApp

### Recipe Version

3.4.10

### Steps to reproduce

1. Open Ferdium with WhatsApp enabled and configured

### Expected Behavior

To not be notified of a new update after I did the update.

### Actual Behavior

It shows "Update available" all the time.

### Screenshots

<img width="357" alt="image" src="https://github.com/ferdium/ferdium-app/assets/3506172/162f486a-4479-4568-87ec-ee07382b87a9">

### Additional Information

I'm running Ferdium on macOS Ventura.

**Comment by RJVB** [comment]
I had something similar yesterday, with the service getting stuck on the loading progress bar (WA's) and then coming back to the "update available" message. That went away after disabling/reenabling the service a few times. Which seems logical because reloading the page should give you the latest version...

**Comment by SpecialAro** [comment]
@mkozjak can you update to the latest stable (3.4.1) and make sure to Reload Services (to update them) ?

You stated you are on version 3.4.10 of Whatsapp service, but the current version is 3.5.1, so you are far behind a few versions.

**Comment by mkozjak** [comment]
> @mkozjak can you update to the latest stable (3.4.1) and make sure to Reload Services (to update them) ?
> 
> You stated you are on version 3.4.10 of Whatsapp service, but the current version is 3.5.1, so you are far behind a few versions.

 This indeed helped. Thanks!

**Comment by trausch2001** [comment]
Also still in version 6.4.1

**Comment by trausch2001** [comment]
After click on Update see also https://github.com/ferdium/ferdium-app/issues/1155

**Comment by trausch2001** [comment]
With new Version of Chrome (stable) Version 116.0.5845.140 it works again.
