### ISSUE TITLE
v6.4.1 tag has no binaries

### ISSUE THREAD

**Issue by binarweb** [ferdium/ferdium-app#1314]
### Your issue

As the title states, the [v6.4.1](https://github.com/ferdium/ferdium-app/releases/tag/v6.4.1), which has been launched yesterday, has no attached binaries.

**Comment by vraravam** [comment]
Its not yet been published - the tag got created as part of our build process. We are still testing internally for stability before releasing it. Please wait for a few hours

**Comment by binarweb** [comment]
I see. Thank you!
