### ISSUE TITLE
Issues with 6.5.0-nightly.1 Pre-release

### ISSUE THREAD

**Issue by leoheck** [ferdium/ferdium-app#1316]
### Your issue

Latest nightly is loading a blank screen.

When I start Ferdium, it loads everything, but right after 1 or 2s, this blank screen covers everything then I cannot use Ferdium anymore.
![image](https://github.com/ferdium/ferdium-app/assets/1277920/02c61456-d670-4a8d-a586-460cf04fa2d2)

Cannot get info from `Help > About Version`, nothing appears.

**Comment by vraravam** [comment]
Can you please use the issue template when logging tickets? We need that info to check what might be wrong

**Comment by leoheck** [comment]
I cannot get any other info. The window is blank and the menus don't launch any other windows.

**Comment by vraravam** [comment]
we need other info, like OS, etc - which are useful for us to categorize and focus effort on specific areas

**Comment by leoheck** [comment]
@vraravam It was reported alredy, didn't find it?
