### ISSUE TITLE
Unusable - 6.4.1 and 6.5.0-nightly.1 

### ISSUE THREAD

**Issue by leoheck** [ferdium/ferdium-app#1317]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.5.0-nightly.1 Pre-release (from the github since nothing works anymore)

### What Operating System are you using?

Ubuntu

### Operating System Version

Ubuntu 23.04

### What arch are you using?

x64

### Last Known Working Ferdium version

One before of this one.

### Expected Behavior

Launch Ferdium to normal use.

### Actual Behavior

This window, with the menus that do not work either. 
[6.5.0-nightly.1](https://github.com/ferdium/ferdium-app/releases/tag/v6.5.0-nightly.1) Pre-release

### Steps to reproduce

Launch Ferdium, wait until it loads, and then, the blank screen happens

### Debug link

This does not work for this version

### Screenshots

The only screenshot of the interface was added above.

### Additional information

nope.

**Comment by leoheck** [comment]
The screenshot did not work.
Here it is.
![image](https://github.com/ferdium/ferdium-app/assets/1277920/bb29ad51-ee0e-45c9-bfd3-007493b8deaf)

**Comment by Alphrag** [comment]
Can you please tell us through which means this has been installed? And also, can you give us what appears in the console (a `ctrl+alt+I` should bring the developer tools) or when launching it through a terminal?
I have been running the AppImage version all day on my ubuntu 20.04 and didn't get any problems whatsoever (and I am currently running it on Windows 10 as well), so we would need a few more details to be able to figure out what went wrong on your end.

**Comment by leoheck** [comment]
Definitely, I can do all that. This template of issue I used did not ask me anything like that.

> Can you please tell us through which means this has been installed?

It was installed manually using de nightly AppImage, and it was updated after Ferdium issued a new nightly version, manually by clicking the blue button that appears at the bottom of the window.

Using the `ctrl+alt+I` (which uppercase `I`) as in `Ctrl+Alt+Shit+I` did not do anything. 
The same happens when using `Ctrl+Alt+I` (lowercase `I`)

Alright, launching it from the terminal gave us a better hint of the issue. Thanks for the suggestion.
```bash
~/Applications …
➜ ./Ferdium-linux-Portable-6.5.0-nightly.1-x86_64.AppImage                                 
libva error: dlopen of /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so failed: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so: undefined symbol: _ZN6GmmLib16GmmClientContext27CreateCustomResInfoObject_2EP33GMM_RESCREATE_CUSTOM_PARAMS_2_REC
libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed
```

**Comment by leoheck** [comment]
Found this https://askubuntu.com/questions/1395620/chrome-libva-error-usr-lib-x86-64-linux-gnu-dri-ihd-drv-video-so-init-failed, And then tried this...
```bash
sudo apt-get install --reinstall $(dpkg -l | grep ^ii | grep -i intel | awk '{print $2}')
```

Then now, I got something more detailed but the same blank screen happens.
Ah, just to make it clear. Ferdium starts, the services start too... and then after 1s, the blank screen covers the whole Ferdium window.

![image](https://github.com/ferdium/ferdium-app/assets/1277920/56c94c0d-2c7f-4352-a13d-a0e97622f8e3)

Text mode here
```bash
~/Applications …
➜ ./Ferdium-linux-Portable-6.5.0-nightly.1-x86_64.AppImage 
libva error: dlopen of /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so failed: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so: undefined symbol: _ZN6GmmLib16GmmClientContext27CreateCustomResInfoObject_2EP33GMM_RESCREATE_CUSTOM_PARAMS_2_REC
libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed
[MobX] Since strict-mode is enabled, changing (observed) observable values without using an action is not allowed. Tried to modify: Settings@13.store
Ferdium Migration:  🧙‍  Running database migration wizard
info: serving app on http://localhost:46569
Ferdium Migration:  🔧  Nothing to migrate, already on the newest version
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94361)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at BrowserWindow.<anonymous> (/tmp/.mount_FerdiuCRQA44/resources/app.asar/electron/ipc-api/focusState.js:1:692)
    at BrowserWindow.emit (node:events:525:35)
sendToFrame() failed: Error: Render frame was disposed before WebFrameMain could be accessed
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: SettingsStore.js:1:2117
Remote event names: blur
sendToFrame() failed: Error: Render frame was disposed before WebFrameMain could be accessed
sendToFrame() failed: Error: Render frame was disposed before WebFrameMain could be accessed
```

**Comment by TJonCooper** [comment]
Identical issue here. Ubuntu 22.04.3 LTS - Ferdium 6.5.0-nightly.1 (installed and used via the AppImage). Nothing but a blank screen when opening the app (after 1s of normal screen and service loading).

**Comment by leoheck** [comment]
The same issue happens with `6.4.1`, it is also not usable. 
Also, why do they have this `Portable` string in the filename? How does this improve something?

**Comment by leoheck** [comment]
@TJonCooper After installing this `sudo apt install vainfo`, Ferdium `6.4.1` (but not `6.5.0`) started fine again without the blank screen.
But I also ran this yesterday
```
sudo apt-get install --reinstall $(dpkg -l | grep ^ii | grep -i intel | awk '{print $2}')
```

Console log
```
~ took 3.0s …
➜ sudo apt install vainfo
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  vainfo
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
Need to get 13.8 kB of archives.
After this operation, 54.3 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu lunar/universe amd64 vainfo amd64 2.12.0+ds1-1 [13.8 kB]
Fetched 13.8 kB in 3s (5,029 B/s)                   
Selecting previously unselected package vainfo.
(Reading database ... 494838 files and directories currently installed.)
Preparing to unpack .../vainfo_2.12.0+ds1-1_amd64.deb ...
Unpacking vainfo (2.12.0+ds1-1) ...
Setting up vainfo (2.12.0+ds1-1) ...
Processing triggers for man-db (2.11.2-1) ...

~ took 8.3s …
➜ Ferdium-linux-Portable-6.4.1-x86_64_97759269be20caf23b753b291edb9c10.AppImage 
libva error: dlopen of /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so failed: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so: undefined symbol: _ZN6GmmLib16GmmClientContext27CreateCustomResInfoObject_2EP33GMM_RESCREATE_CUSTOM_PARAMS_2_REC
libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed
[MobX] Since strict-mode is enabled, changing (observed) observable values without using an action is not allowed. Tried to modify: Settings@13.store
Ferdium Migration:  🧙‍  Running database migration wizard
info: serving app on http://localhost:46569
Ferdium Migration:  🔧  Nothing to migrate, already on the newest version
[521742:0818/141144.862357:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.NotSupported: This method is not implemented
Checking for update
Found version 6.5.0-nightly.1 (url: Ferdium-linux-Portable-6.5.0-nightly.1-x86_64.AppImage, Ferdium-linux-6.5.0-nightly.1-amd64.deb, Ferdium-linux-6.5.0-nightly.1.rpm)
Downloading update from Ferdium-linux-Portable-6.5.0-nightly.1-x86_64.AppImage, Ferdium-linux-6.5.0-nightly.1-amd64.deb, Ferdium-linux-6.5.0-nightly.1.rpm
updater cache dir: /home/lheck/.cache/ferdium-updater
Cached update file doesn't exist
rRjk/YOuST1VGBPJI7DlZYe4 duplicated in blockmap (same size), it doesn't lead to broken differential downloader, just corresponding block will be skipped)
6AX86RPVYTRJDUcTuYwbWu9o duplicated in blockmap (same size), it doesn't lead to broken differential downloader, just corresponding block will be skipped)
FiTLca6WciXQ7oBqGPM6nTZc duplicated in blockmap (same size), it doesn't lead to broken differential downloader, just corresponding block will be skipped)
dZHI+Tvc6ewImaGku2qoa9sf duplicated in blockmap (same size), it doesn't lead to broken differential downloader, just corresponding block will be skipped)
7ba4cuT7oFjf04/+3a7GJ7Xc duplicated in blockmap (same size), it doesn't lead to broken differential downloader, just corresponding block will be skipped)
```

**Comment by Alphrag** [comment]
> The same issue happens with `6.4.1`, it is also not usable. 

Thanks for the report details, I will try to fire up some VMs to see where does this happen, because there has been no problems on my debian, fedora or ubuntu 20.04, which makes me think this might be coming from an update on your end. The fact that `6.4.1` does not work would also lead towards that direction, since there has been virtually no changes since the beginning of August on the 6.4.1-nightlies (and the fact that you updated to the `6.5.0-nightly.1` immediately after release makes me understand that you were on nightlies before as well). Thus, if your previous nightlies were working (which one exactly was your last working one?), there is no reason under which the stable version should not.

> Also, why do they have this `Portable` string in the filename? How does this improve something?

The "Portable" keyword in the name is simply there to make it easier for the users to differentiate between a version which will work directly after downloading compared to a `.deb` or `.rpm` product that needs to be installed via a package manager.

**Comment by TJonCooper** [comment]
@Alphrag I can confirm that on my system (Ubuntu 22.04.3 LTS) - 6.4.1 works fine and as expected. I reverted from 6.5.0-nightly.1 back to this version. 6.5.0-nightly.1 does not work on any of my linux devices.

**Comment by leoheck** [comment]
@Alphrag this makes me question the usability of the AppImage, then. It was created to run away from system dependencies. Now you are telling me the system has something missing. This doesn't make sense. The AppImage has to contain everything needed otherwise it is not portable as you are calling it.

**Comment by leoheck** [comment]
Another annoying thing. After putting this `6.4.1` to work by installing a missing software (wtf?, Appimage is all contained/portable or not?)... and Ferdium keeps asking me to upgrade it. WHY if there is not another stable version? Come one?!

Stable Ferdium should advertise only stable versions.
Nightly should advertise only nighties.

**Comment by leoheck** [comment]
A jump to the nightlies should not be advertised when using a stable version.

Also, a button to deny the next release to remove the annoying bottom bar temporarily would be welcome. 

![image](https://github.com/ferdium/ferdium-app/assets/1277920/8482f707-37ae-4a54-bc44-8267103ae631)

**Comment by Alphrag** [comment]
@leoheck  I haven't had the time to look into it yet (been working to submit my thesis today) but yes, I want to understand what is wrong and where because `AppImage` should not be problematic. This means one of three things: i) either `electron` is not playing nice with some things on linux, or ii) `electron-builder` is not including everything necessary to make it fully portable, or iii) we need to force some additional dependencies on our end when building the app.
Since `6.5.0-nightly.1` broke it for you, it means that `electron` has a lot to do about this. Do you have any other electron apps that use the latest version by any chance (to see the difference in setup)?

**Comment by Alphrag** [comment]
> Stable Ferdium should advertise only stable versions. Nightly should advertise only nighties.

No, that is completely intended: it is your role to decide if you want to toggle nightlies or not in the settings. Otherwise it would mean having to reinstall simply to switch from one to the other.
![Screenshot from 2023-08-21 17-01-49](https://github.com/ferdium/ferdium-app/assets/34252790/61d33a4d-8a6d-44a1-81c4-4dee199c108d)

**Comment by leoheck** [comment]
This is user control, ok.
I am reinstalling each version manually.
If I install the stable version, I want this thing disabled by default. If I am installing the nightly it could be enabled by default. Now, it looks like the stable and the nightly are using the same settings... and this looks silly because then I cannot have the stable version working, and also test the nightly when it is released.

**Comment by leoheck** [comment]
> I haven't had the time to look into it yet (been working to submit my thesis today) 

Oh, great, what is the subject?

> Want to understand what is wrong and where because... 

Sure, when you have time, we can continue on this, I don't like to use the stable version. I want the bleeding edged haha.

**Comment by srwi** [comment]
I have the same problem on Ubuntu 22.04.3 with the same nightly. I installed it using the .deb file downloaded directly from the Github releases. 

I do not have this problem with 6.4.1 via Ubuntu software store.

![image](https://github.com/ferdium/ferdium-app/assets/17520641/5c37c516-cbe4-4ee3-9558-f4fae618576b)


<details><summary>Full console output</summary>
<p>

```
❯ /opt/Ferdium/ferdium --ozone-platform=wayland --enable-features=UseOzonePlatform,WebRTCPipeWireCapturer,WaylandWindowDecorations
[16409:0822/185508.255066:ERROR:browser_main_loop.cc(274)] Gtk: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
[16409:0822/185509.748433:ERROR:browser_main_loop.cc(274)] Gtk: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
[MobX] Since strict-mode is enabled, changing (observed) observable values without using an action is not allowed. Tried to modify: Settings@13.store
[16409:0822/185510.189814:ERROR:browser_main_loop.cc(274)] Gtk: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
[16409:0822/185510.211644:ERROR:browser_main_loop.cc(274)] Gtk: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94361)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at BrowserWindow.<anonymous> (/opt/Ferdium/resources/app.asar/electron/ipc-api/focusState.js:1:692)
    at BrowserWindow.emit (node:events:525:35)
sendToFrame() failed: Error: Render frame was disposed before WebFrameMain could be accessed
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: SettingsStore.js:1:2117
Remote event names: blur
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94361)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at BrowserWindow.<anonymous> (/opt/Ferdium/resources/app.asar/electron/ipc-api/focusState.js:1:608)
    at BrowserWindow.emit (node:events:525:35)
sendToFrame() failed: Error: Render frame was disposed before WebFrameMain could be accessed
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: SettingsStore.js:1:2349
Remote event names: focus
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94361)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at BrowserWindow.<anonymous> (/opt/Ferdium/resources/app.asar/electron/ipc-api/focusState.js:1:692)
    at BrowserWindow.emit (node:events:525:35)
sendToFrame() failed: Error: Render frame was disposed before WebFrameMain could be accessed
sendToFrame() failed: Error: Render frame was disposed before WebFrameMain could be accessed
sendToFrame() failed: Error: Render frame was disposed before WebFrameMain could be accessed
sendToFrame() failed: Error: Render frame was disposed before WebFrameMain could be accessed
sendToFrame() failed: Error: Render frame was disposed before WebFrameMain could be accessed
sendToFrame() failed: Error: Render frame was disposed before WebFrameMain could be accessed
sendToFrame() failed: Error: Render frame was disposed before WebFrameMain could be accessed
sendToFrame() failed: Error: Render frame was disposed before WebFrameMain could be accessed
sendToFrame() failed: Error: Render frame was disposed before WebFrameMain could be accessed
sendToFrame() failed: Error: Render frame was disposed before WebFrameMain could be accessed
sendToFrame() failed: Error: Render frame was disposed before WebFrameMain could be accessed
sendToFrame() failed: Error: Render frame was disposed before WebFrameMain could be accessed
sendToFrame() failed: Error: Render frame was disposed before WebFrameMain could be accessed
sendToFrame() failed: Error: Render frame was disposed before WebFrameMain could be accessed
sendToFrame() failed: Error: Render frame was disposed before WebFrameMain could be accessed

``` 

</p>
</details> 

-------------

```
sendToFrame() failed: Error: Render frame was disposed before WebFrameMain could be accessed
```

Gets spammed a few times after a delay of 5-10 seconds after the screen turns purple.

--------------

```
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94361)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at BrowserWindow.<anonymous> (/opt/Ferdium/resources/app.asar/electron/ipc-api/focusState.js:1:692)
    at BrowserWindow.emit (node:events:525:35)
sendToFrame() failed: Error: Render frame was disposed before WebFrameMain could be accessed
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: SettingsStore.js:1:2117
Remote event names: blur
```

Gets logged when focusing and unfocusing the window.

**Comment by mcmxcdev** [comment]
For me the same thing on Ubuntu: 6.4.1 works fine but all the releases after which use electron 26.0.0 are breaking, so I am suspecting we should downgrade. 

cc @vraravam

**Comment by vraravam** [comment]
ok - am downgrading that version of electron now

**Comment by srwi** [comment]
Electron 26 includes a fix for screen sharing in Linux using Wayland. https://github.com/electron/electron/pull/39264

According to my understanding this fix is not backported to older versions of electron.

**Comment by leoheck** [comment]
Alright, this latest nightly is working again, thank you, guys.

```
Version: 6.5.0-nightly.5
Server: No Server
Electron: 25.5.0
Chrome: 114.0.5735.289
Node.js: 18.15.0
Platform: Linux 6.2
Arch: x64
Build date: Sat Sep 02 2023 22:28:44 GMT-0300 (Brasilia Standard Time)
Git SHA: f9c9932b
Git branch: nightly
```
