### ISSUE TITLE
Add Viber messaging service recipe

### ISSUE THREAD

**Issue by meanzzzzz** [ferdium/ferdium-app#1319]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+request+%3Asparkles%3A%22) for a recipe request that matches the one I want to file, without success.

### Name of the service

Viber

### URL of the service

https://www.viber.com/

### Features you want implemented

messaging service + calls if possible

**Comment by SpecialAro** [comment]
Hello @meanzzzzz , thank you for logging this recipe request.

I'm afraid that viber (the messaging service) doesn't have a web app. Therefore, this won't be able to be supported by Ferdium, sorry!

**Comment by ko5tas** [comment]
@SpecialAro is the https://account.viber.com/en/login URL new since that comment in 2023?
