### ISSUE TITLE
Bug: Change in Settings resets Password to blank (portable Win10 only?)

### ISSUE THREAD

**Issue by pbalog5154** [ferdium/ferdium-app#132]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

Ferdium-6.0.0-nightly.10.exe (portable, not Setup!)

### What Operating System are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Ferdium version

never (I started to use Ferdi 5.7.0, it existed)

### Expected Behavior

Preserve value of Password.

### Actual Behavior

'Password' value reset to blank when any change happen on any subsection of 'Settings' section

### Steps to reproduce

01 Ferdium-6.0.0-nightly.10.exe (portable, not Setup!)
02 Open Settings interface > 'Settings' section > 'Privacy' subsection > enable 'Password Lock' + enter a 'Password' value
03 Close Settings (Password memorized at this moment?)
04 Hit 'Lock Ferdium' icon
05 Locked screen > Enter 'Password' value > Ferdium opens
06 Open Settings > 'Settings' section > 'Privacy' subsection > please note 'Password' field is blank / not populated (no asterisks?)
07 Go to another subsection (any, e.g. 'General') > change any value, e.g. at 'General' subsection > 'Keep Ferdium in background...'
08 Close 'Settings' (probably blank Password memorized?)
09 Hit 'Lock Ferdium' icon
10 Locked screen > Enter 'Password' value > error: "Password invalid"
11 Locked screen > delete 'Password' value (blank field) > hit Enter / Unlock button > Ferdium opens

### Screenshots

![ferdium_01](https://user-images.githubusercontent.com/105302694/167669159-619408df-8282-4cdb-9a19-7153f6ae1780.jpg)
![ferdium_02](https://user-images.githubusercontent.com/105302694/167669195-9bca8e91-d632-4857-bcb3-9ae82cae30dd.jpg)
![ferdium_03](https://user-images.githubusercontent.com/105302694/167669225-eba8922c-b260-49e7-a5bd-3a87a58ff3b9.jpg)

### Additional information

Please note this Bug discovered in the portable Windows (.exe) version only. Other versions haven't been tested on this matter.

**Comment by SpecialAro** [comment]
Thank you for submitting this bug!

I was able to reproduce this bug locally in a dev environment. Needs fixing.

**Comment by vraravam** [comment]
I am unable to reproduce this bug on macos.

On a side note, the password field remaing blank doesn't mean that the password itself has been removed. If you look in your `<FerdiumProfileFolder>/config/settings.json`, there will be an entry for `lockedPassword` - this is the encrypted value of the password. If this value is set, then the password is still retained.

**Comment by vraravam** [comment]
I have also tested with both the TouchID and manually entering the password - and both of them work. (Im able to login back into Ferdium with either of them)

**Comment by pbalog5154** [comment]
Thank you for looking into this!

I monitored the behavior of "lockedPassword" value during the 'Steps to reproduce' described above. I can confirm:

01 The value of "lockedPassword" is changing every time as soon I open the Settings interface and touch any other value at any subsection (e.g. General > Start minimized, etc.). It is reverted to: "lockedPassword": "47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=" which allows me to unlock using the blank password.

02 Maybe helps: when I return to the Settings > Privacy subsection and set up the Password value again, it changes the settings.json > "lockedPassword" value right away - as soon as I remove the focus from that field -, and still keeps it regardles I make further changes at other settings or not (till I won't open the Setting interface again and make a change on any other setting next time, see 01 above).

Please note: this instance of Ferdium is on Windows and standalone/portable. I use this variant at all versions all the time (currently 'Ferdium-6.0.0-nightly.10.exe').

Thank you!

**Comment by pbalog5154** [comment]
Reproduced on v6.0.0-nightly.34

1. Download 'Ferdium-6.0.0-nightly.34.exe' from https://github.com/ferdium/ferdium-app/releases
2. Launch it in an empty folder (Win10 x64)
3. 'Use Ferdium without an Account'
4. 'Get Started'
5. Add some services, e.g. 'Messenger' and 'Android Messages' > 'Save Service' with their default settings
6. Go 'Settings' > 'Privacy' > 'Enable Password Lock' = ON
7. Enter 'Password' = 1234
8. Close 'Settings' window
9. 'Lock Ferdium'
10. Enter 'Password' = 1234 > Unlock > works as expected
11. Go 'Settings' > 'General' > 'Start minimized' = ON (or you can change any settings on any Settings subsection...)
12. Close 'Settings' window
13. 'Lock Ferdium'
14. Enter 'Password' = 1234 > Unlock > "Password invalid"
15. Delete content of 'Password' field > Unlock > interface unlocks

At the Step 11 above, the content of file 'settings.json' altered with:
- writing the intentionally changed setting (e.g. 'Start minimized' = ON causes "startMinimized": true) as expected
- also: changing the "lockedPassword" value to "47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=" unexpectedly every time

Thank you!

**Comment by vraravam** [comment]
@pbalog5154 - thanks for the detailed steps. @SpecialAro and myself were able to reproduce this behavior and have implemented + merged a fix. Please revert back with the next nightly and tell us if the fix works now!

**Comment by pbalog5154** [comment]
Thank you @Vraravam and @SpecialAro for hunting this down! Will test the next nightly and report back! Cheers!
