### ISSUE TITLE
Google Hangouts Chat unable to signin

### ISSUE THREAD

**Issue by timwsuqld** [ferdium/ferdium-app#1323]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+%3Abookmark_tabs%3A%22+label%3A%22bug+%3Abeetle%3A%22+) for a bug report that matches the one I want to file, without success.

### Ferdium Version

6.4.1

### Recipe Name

Hangouts Chat

### Recipe Version

1.7.0

### Steps to reproduce

1. Create a new service with Google Hangouts Chat (or have an existing on that has gotten signed out, same effect)
2. End up at the "Google Chat" product page (https://workspace.google.com/products/chat/)
3. Click "Sign in"
4. Link opens in browser

### Expected Behavior

Link should open in Ferdium so we can sign in

### Actual Behavior

Link opens in browser instead of Ferdium

### Additional Information

I have tried enabling "Open URLs within Ferdium" to force the links in Feridum, same result, link still opens in browser

Element 'Sign in' still has target _blank.
```
<gws-button href="https://accounts.google.com/ServiceLogin?continue=https://chat.google.com/?referrer=2" label="Sign in to Google Workspace to use Chat " data-g-event="chat: hero" data-g-label="https://accounts.google.com/ServiceLogin?continue=https%3A%2F%2Fchat.google.com%2F%3Freferrer%3D2" data-g-action="sign in" target="_blank">Sign in</gws-button>
```

**Comment by cmoulliard** [comment]
I also confirm that I have the same issue since this morning  :-( using our enterprise Google account at Red hat

**Comment by wiktor-karczewski** [comment]
I have this issue since friday, ubuntu 22, ferdium installed from .deb package

**Comment by jvalkonen** [comment]
A workaround is to right-click on the sign in button and select "Open Link in Ferdium"

**Comment by cmeissner** [comment]
My hacky workaround is to change the `serviceURL`  in `~/.config/Ferdium/recipes/hangoutschat/package.json` (Fedora 38, can differ in other distributions). 

```
{
  "id": "hangoutschat",
  "name": "Hangouts Chat",
  "version": "1.6.0",
  "license": "MIT",
  "aliases": [
    "google-chat",
    "gChat"
  ],  
  "config": {
    "serviceURL": "https://mail.google.com/chat/u/0/#onboarding",
    "hasNotificationSound": true,
    "hasIndirectMessages": true
  }
}
```

May be it is worth to say, I also use kerberos tickets for authentication, so no extra login is needed in my case.

**Comment by wiktor-karczewski** [comment]
> A workaround is to right-click on the sign in button and select "Open Link in Ferdium"

Worked for me, however it didn't work for original poster.

**Comment by jvalkonen** [comment]
> > A workaround is to right-click on the sign in button and select "Open Link in Ferdium"
> 
> Worked for me, however it didn't work for original poster.

I don't think he tried that but configured on the service settings instead the option for opening URLs in Ferdium.
![image](https://github.com/ferdium/ferdium-app/assets/22853226/6985a803-79ed-4b9d-96b0-7c1ceb59d596)

I tried that too and it didn't work but the right-click did the trick.

**Comment by techlead95** [comment]
Yep, right click and open link in Ferdium worked

**Comment by ipilcher** [comment]
> Yep, right click and open link in Ferdium worked

Just hit this.  I can't find the "open link in Ferdium" setting, and I don't know what I'm supposed to right-click.  Can anyone clarify?

EDIT: Never mind.  All I had to do was right-click on the "Log In" button and select "open link in Ferdium".  No need to change any settings in my case.

**Comment by stacksjb** [comment]
Same issue here too!

**Comment by timwsuqld** [comment]
For anyone coming to comment about having the issue too, check if your recipe has updated to 1.8.0 that should be fixed. If you are on 1.8.0 and still have the issue, please open a new issue with details.
