### ISSUE TITLE
CSS overhead in custom service (is it a bug or wanted feature ?)

### ISSUE THREAD

**Issue by LoucIsZbib** [ferdium/ferdium-app#1326]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+%3Abookmark_tabs%3A%22+label%3A%22bug+%3Abeetle%3A%22+) for a bug report that matches the one I want to file, without success.

### Ferdium Version

6.4.1

### Recipe Name

Custom Website

### Recipe Version

1.4.0

### Last Known working version of the recipe

-

### Steps to reproduce

1. create a new Custom Website service
2. Configure to a personal rainloop webmail instance
3. Observe that CSS background is absent (it is present when website is opened with Firefox)

### Expected Behavior

CSS background should be present

### Actual Behavior

No CSS background

### Screenshots

![NORMAL](https://github.com/ferdium/ferdium-app/assets/3252398/5612c4fb-30e0-4b07-8433-c137f24d5fe9)
![ISSUE](https://github.com/ferdium/ferdium-app/assets/3252398/7e4e5530-db35-43fa-be51-b287ba00af89)

### Additional Information

The content of the file "style.css" is : 
`html {
  background: #FFFFFF;
}`

I suppose it is for debug purpose. 
Nevertheless, it overheads the CSS of rainloop and background is absent, which looks weird when font color is clear/white.

SOLUTION : I comment this css line with "background: #FFFFFFFF", and it is working as expected.
It needs to be done after an update of Ferdium (AUR package on archlinux).

If this is a wanted behavior, please tell me and close this issue (and sorry for inconvenience), I can live with this behavior now that I know a workaround to fit my wanted behavior

**Comment by SpecialAro** [comment]
@vraravam I'm tagging you because you are in the project for a long time. I don't think this is a "feature" (wanted behaviour) so I'm raising a PR to fix it. Otherwise, if it is, I'll gladly close my PR!

Thank you @LoucIsZbib for pointing this out!

**Comment by vraravam** [comment]
thanks for tagging me @SpecialAro - yes, looks like this should be removed. The `custom-website` recipe should not override the CSS and should be generic enough for any website
