### ISSUE TITLE
After updating to 6.4.1 on Linux/KDE Ferdium does not start

### ISSUE THREAD

**Issue by paulknulst** [ferdium/ferdium-app#1327]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.4.1

### What Operating System are you using?

Other Linux

### Operating System Version

Garuda Linux

### What arch are you using?

x64

### Last Known Working Ferdium version

before 6.4.1

### Expected Behavior

The app should start without an error.

### Actual Behavior

After updating Ferdium to the new version I get an error if starting it by using the .desktop file

The error states:
```
execvp: exec format error
```

### Steps to reproduce

1. Update Ferdium
2. Try to start Ferdium

### Additional information

I already fixed the error by adjusting the created bash script `/usr/bin/ferdium`. The file which was touched within the update had the following input:
![image](https://github.com/ferdium/ferdium-app/assets/5755794/764184d8-1475-4e7d-88dc-fc6b04358b80)

As you might see there are 4 spaces before the shebang. I adjusted it and it works:
![image](https://github.com/ferdium/ferdium-app/assets/5755794/2e5add8b-0a47-4c78-8e25-4579ead8cdf3)

**Comment by SpecialAro** [comment]
Probably duplicated of https://github.com/ferdium/ferdium-app/issues/1317 (closing as duplicate but gladly to open it up again if it isn't)

**Comment by paulknulst** [comment]
The mentioned other issue and this have nothing in common. 
It says: `Launch Ferdium, wait until it loads, and then, the blank screen happens`

In this issue, Ferdium does not start at all. not even a blank screen.

Also, as I described it, it is fixed by removing the 4 spaces within the script located at /usr/bin/ferdium

**Comment by SpecialAro** [comment]
@paulknulst thank you! I'm sorry for closing. I'm reopening it 😄

**Comment by miela** [comment]
I have the same issue. Removed and installed again then started working.
After that I clicked "update" and now the same issue :P

**Comment by paulknulst** [comment]
Just remove the spaces in the file. It will work again. I guess there is some small bug in the creation of that script.

**Comment by leoheck** [comment]
This seems to be the same problem reported here, before, https://github.com/ferdium/ferdium-app/issues/1327

**Comment by AfroMonkey** [comment]
I'm assuming you are using the AUR package, It seems that the error is no from ferdium itself, but from the SO package.

https://aur.archlinux.org/packages/ferdium-bin#comment-930588

The errors seems to be currently addressed

**Comment by paulknulst** [comment]
Oh, I did not know that it is not related to Ferdium. I just want to report it and provide the fix I already found. Thanks for posting the link to the AUR package info.

**Comment by mcmxcdev** [comment]
It seems this issue was related to the AUR packaging of Ferdium rather than an issue with Ferdium itself.

Can we close this issue to avoid having contributors look over it?

**Comment by paulknulst** [comment]
sure why not, It will be fixed. Also, as I said before, I just wanted to report it and provide a solution to fix this error for everyone with the same issue.

**Comment by SpecialAro** [comment]
Thank you @paulknulst for providing this fix 😊

I'm closing this issue now.
