### ISSUE TITLE
Files uploaded in the Skype chat cannot be downloaded

### ISSUE THREAD

**Issue by ippoliti** [ferdium/ferdium-app#1333]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.4.1

### What Operating System are you using?

macOS

### Operating System Version

MacOS 12.6.8

### What arch are you using?

x64

### Expected Behavior

When somebody uploads a file in the Skype chat, the file can be downloaded by clicking on the corresponding "Download" link. 

### Actual Behavior

Clicking on the "Download" link triggers the opening of a tab on the default browser, which in turn triggers the download of an empty file called "original".

### Steps to reproduce

1. Ask somebody to upload a file (I tested in PDF files) on a Skype chat.
2. Click on the corresponding "Download" link

**Comment by SpecialAro** [comment]
Hi @ippoliti, thanks for logging this issue.

Have you tried to toggle the "Open links in Ferdium" option by editing the Skype service on Ferdium? After reloading the service it should work.

Let me know if this doesn't work, please 🙏

Thank you very much!

**Comment by ippoliti** [comment]
Hello @SpecialAro, 

I didn't notice that toggle! Yes, that works perfectly. 

Thank you very much.

**Comment by ippoliti** [comment]
Hi, 

I would like to reopen this issue because I have just discovered that if I toggle "Open URLs in Ferdium" option to solve the problem of downloading files posted on the Skype chat, I introduce an unwanted behaviour: any link, including the one of a website will be opened within Ferdium. I was in a Skype call and a person passed me a website link on the chat. I clicked on the link and the **call stopped**, skype disappeared from the main Ferdium window and the website opened in that window in place of Skype. Of course this should not occur: I want to keep the video call on Ferdium and open the link on a tab of my browser, as it happens when the toggle "Open URLs in Ferdium" is disabled. Is there a way to make the Skype service in Ferdium to behave as the Skype app both for a file to download and a link of a website?

**Comment by Arthur-Huan** [comment]
Created a PR with a fix to this: https://github.com/ferdium/ferdium-recipes/pull/418

**Comment by ippoliti** [comment]
Thank you @Arthur-Huan. I saw that your fix in the ferdium-recipes has been already approved. 
As a simple user, should I wait for the next Ferdium release to test it or is there something else I can do in advance to test your 3.6.2 version of the Skype service in place of the 3.6.1 currently installed on my laptop (also after updating Ferdium to the pre-release 6.5.0-nightly.6)?

**Comment by Arthur-Huan** [comment]
@ippoliti You can manually edit the recipes locally (this is how I tested my code). I see you're a Mac user, so the recipes should be at `~/Library/Application Support/Ferdium/recipes/`. Just replace the `webview.js` file in the corresponding folder, relaunch Ferdium, and the behavior should be changed.

**Comment by ippoliti** [comment]
@Arthur-Huan Thank you for the hint about how to test the new version and sorry for the late answer. I tested your changes on the Skype recipe and they work perfectly.
