### ISSUE TITLE
LinkedIn always starting in Messages but Hompage

### ISSUE THREAD

**Issue by hirschferkel** [ferdium/ferdium-app#1334]
### Your issue

How can I force LinkedIn inside Ferdium-app to start with the homepage tab and not in messages while opening Ferdium? I did not find a way and it is a bit annoying to se LinkedIn starting in messages tab each time Ferdium starts ... 
best, hirschferkel

**Comment by hirschferkel** [comment]
Just for those who want to change the Window URL / Start page of one app in Ferdium, here is the code how to do it. Edit user.js of the specific app and add following code.
The function is necessary, otherwise Ferdium will reload the page endless:

```
module.exports = (config, Ferdium) => {
  // Write your scripts here
  // console.log("Hello", config);

function load_newurl(param) {
    var url = window.location.href;
    if (window.location.href.indexOf("search_for_some_String_of_new_URL_here") == -1) {
    url = param;
    window.location.href = url;}
}
load_newurl("new_URL_here");

};
```

**Comment by Arthur-Huan** [comment]
You can also just edit `serviceURL` in the `package.json` for your LinkedIn recipe locally. Right now it's https://www.linkedin.com/messaging/, but when I change it to https://www.linkedin.com/, it starts on the homepage.

It might be a good idea to make this the default for LinkedIn on Ferdium, and create a new recipe called LinkedIn Messages that starts in messages, but I'm not sure what other users want.

**Comment by mcmxcdev** [comment]
It's a good question which page should be the default. I would actually say the current way makes sense since Ferdium is useful to show notifications for incoming messages from different platforms, rather than using whole websites encapsulated inside it.

**Comment by mkozjak** [comment]
Moreover, I'd like Ferdium to just "zoom" into the messaging bit of LinkedIn. If you want full-fledged website, you can just use browser for that.

**Comment by vraravam** [comment]
@hirschferkel - are the above comments useful? Can we close this ticket please if you are satisfied?

**Comment by hirschferkel** [comment]
@vraravam yes you can close it, @Arthur-Huan was the best advice!
