### ISSUE TITLE
Use website's favicon instead of service icon?

### ISSUE THREAD

**Issue by RJVB** [ferdium/ferdium-app#1340]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22enhancement+%3Asparkles%3A%22) for a feature request that matches the one I want to file, without success.

### Problem Description

Service icons can be unreliable (see #1252) which of course should be fixed. In the meantime, a *reliable* option to use a site's favicon instead could be a perfect workaround.

Apparently Ferdium had a feature that put the favicon on the side bar which had a fix last year (#336).

### Proposed Solution

An option to display the site's favicon instead of the default or custom service icon.

### Alternatives Considered

NA

**Comment by trymeouteh** [comment]
Would be nice if there was a button on the service settings page to download the favicons from the website and choose one of the favicons to use as the service icon
