### ISSUE TITLE
Purple windows on Windows 10 Pro

### ISSUE THREAD

**Issue by icapa3** [ferdium/ferdium-app#1346]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.4.1-x64

### What Operating System are you using?

Windows

### Operating System Version

Windows 10 Pro - Windows Feature Experience Pack 1000.19041.1000.0

### What arch are you using?

x64

### Last Known Working Ferdium version

Never

### Expected Behavior

Work without problems

### Actual Behavior

Purple window when install Ferdium version o reinstallinb.

![Captura](https://github.com/ferdium/ferdium-app/assets/69592441/5379e963-fc59-4783-a64a-9b7ebb79787e)

### Steps to reproduce

Install version in my computer

### Screenshots

![Captura](https://github.com/ferdium/ferdium-app/assets/69592441/bed95d97-dfa7-413f-b939-b2334bd5cdeb)

**Comment by SpecialAro** [comment]
Hello @icapa3. Is this a fresh install or did you perform an update?

If it was an update which version were you on previously?

**Comment by icapa3** [comment]
It's for all versions I installed since version 6.2

**Comment by SpecialAro** [comment]
We fixed a vulnerability after 6.2 and some windows users faced this issue. The solution, unfortunately, was to do an uninstall and complete install and cleanup (delete) of the `%APPDATA%/Ferdium` folder. Bear in mind that if you are using an accountless option you will lose all you services (if you are using Ferdium Server or another server - which is the default - then this shouldn't be a problem)

**Comment by icapa3** [comment]
I uninstall complet, forlders removed and install again but the same problem. Purple window. Do you need to send anything?

**Comment by SpecialAro** [comment]
@icapa3 can you confirm the OS? The title says Windows 11 but the issue description says Windows 10.

**Comment by icapa3** [comment]
Sorry, it's Windows 10 Pro - 22H2 - 19045.3448 - Windows Feature Experience Pack 1000.19044.1000.0

**Comment by memeller** [comment]
@icapa3 please check your console log (ctrl + shift + i, switch to console tab) and see if there is an error that would include 'powershell is not recognized as an internal or external command'. For me there was and adding 'C:\Windows\System32\WindowsPowerShell\v1.0' to the PATH variable and restarting Ferdium after that fixed the problem. 
The problem is described [here](https://confluence.atlassian.com/bamkb/powershell-is-not-recognized-as-an-internal-or-external-command-1095246216.html) for example, along with detailed instructions on how to add the path variable.

**Comment by icapa3** [comment]
> @icapa3 please check your console log (ctrl + shift + i, switch to console tab) and see if there is an error that would include 'powershell is not recognized as an internal or external command'. For me there was and adding 'C:\Windows\System32\WindowsPowerShell\v1.0' to the PATH variable and restarting Ferdium after that fixed the problem. The problem is described [here](https://confluence.atlassian.com/bamkb/powershell-is-not-recognized-as-an-internal-or-external-command-1095246216.html) for example, along with detailed instructions on how to add the path variable.

**Thanks! Works for me!**
