### ISSUE TITLE
Support for new Slack UX/UI

### ISSUE THREAD

**Issue by ilopmar** [ferdium/ferdium-app#1371]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+%3Abookmark_tabs%3A%22+label%3A%22bug+%3Abeetle%3A%22+) for a bug report that matches the one I want to file, without success.

### Ferdium Version

6.4.1

### Recipe Name

Slack

### Recipe Version

1.5.0

### Steps to reproduce

1. Add one Slack channel that has already been migrated to the new Slack UX/UI. In my case this happened with Cloud Native Computing Foundation (cloud-native.slack.com)
2. There is no badge with the notifications
3. The slack icon is not shown in the sidebar

### Expected Behavior

- When there are unread messages the badge with the number of unread messages or the "blue dot" should be displayed as before.
- The slack icon should be displayed properly.

### Actual Behavior

- No unread messages badge
- No slack icon.

### Screenshots

You can see that there are two channels with unread messages but there is no notification. Also the channel icon is not displayed:
![image](https://github.com/ferdium/ferdium-app/assets/559192/a40edce1-b202-4d0a-8566-f57d4c060e30)

The channel with the "smile" icon is another Slack that has been migrated yet to the new UX/UI.

**Comment by Donaldini** [comment]
I was about to post the same thing concerning the icon-issue. Hadn't yet realized the notifications were an issue.

I'm running 6.5.0-nightly.6

**Comment by mcmxcdev** [comment]
I can confirm that the custom Slack icon is missing, but notifications (direct, indirect) show up correctly:

![Screenshot from 2023-09-23 09-11-31-obfuscated](https://github.com/ferdium/ferdium-app/assets/16797721/43466fa3-f12a-43d4-8354-7c9df07ef3af)

**Comment by mcmxcdev** [comment]
Support for new Slack UI was added in https://github.com/ferdium/ferdium-recipes/pull/425 and is part of https://github.com/ferdium/ferdium-app/releases/tag/v6.5.0-nightly.17
