### ISSUE TITLE
ChatGPT recipe has problems when logging in with Google

### ISSUE THREAD

**Issue by svatem1** [ferdium/ferdium-app#1378]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+%3Abookmark_tabs%3A%22+label%3A%22bug+%3Abeetle%3A%22+) for a bug report that matches the one I want to file, without success.

### Ferdium Version

6.4.1

### Recipe Name

ChatGPT

### Recipe Version

1.1.0

### Steps to reproduce

1. try to log in to ChatGPT Plus
2. select login via Google
3. fill in email address
4. press next
5. "This browser or app may not be secure. Try using a different browser. If you’re already using a supported browser, you can try again to sign in." will appear
6. if I add Gmail service, I can log in via the same dialog without any problem and as expected, if I later change serviceURL in package.json of Gmail service's directory to ChatGPT's, I get ChatGPT working
7. changing user agent string doesn't help, none that I've tried got me anywhere
8. I see there are issues in tracker and some MR already addressing this exact same problem, but in none of the comments there is described clear path how to get the result in some user friendly manner

### Expected Behavior

user should be able to log in via Google the same way user is able to log in to Gmail service

### Actual Behavior

user is not able to log in to ChatGPT Plus via Google and is presented with "This browser or app may not be secure. Try using a different browser. If you’re already using a supported browser, you can try again to sign in." message and no way to progress

**Comment by SpecialAro** [comment]
The latest nightly (not the current stable) has this issue fixed as stated in https://github.com/ferdium/ferdium-app/issues/1246. Please browse the issue board for open and closed issues before opening a new on.

Closing this issue as duplicate.

**Comment by svatem1** [comment]
> The latest nightly (not the current stable) has this issue fixed as stated in #1246. Please browse the issue board for open and closed issues before opening a new on.
> 
> Closing this issue as duplicate.

Thx for answer. I actually went over all issues regarding this problem including the one you referenced. I did read it. I was not facing "should I browse the issue board for open and closed issues before opening a new one?" but  rather "is this commit already included in my build and am I facing a regression? how do I find?" and concluded the best way to find out is to create new issue.

**Comment by SpecialAro** [comment]
This PR was merged on Sep 3, so the [6.5.0-nightly.5](https://github.com/ferdium/ferdium-app/releases/tag/v6.5.0-nightly.5) should be the version that has it (or the other latest nightly as well).

You should either wait for a stable release or `Include pre-releases` to update to the latest nightly
![image](https://github.com/ferdium/ferdium-app/assets/37463445/ff478493-8609-46f7-8613-d0cf34459f0d)
