### ISSUE TITLE
Zulip icons are not displayed

### ISSUE THREAD

**Issue by cmoulliard** [ferdium/ferdium-app#1381]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+%3Abookmark_tabs%3A%22+label%3A%22bug+%3Abeetle%3A%22+) for a bug report that matches the one I want to file, without success.

### Ferdium Version

6.4.1

### Recipe Name

Zulip

### Recipe Version

1.3.0

### Steps to reproduce

- Install ferdium 6.4.1 on macos
- Create a zulip service
- Look to the menu on the left

### Expected Behavior

Icons of the zulip servers should be displayed

### Actual Behavior

No icons

### Screenshots

![Screenshot 2023-09-28 at 18 07 49](https://github.com/ferdium/ferdium-app/assets/463790/a4ba3be4-8321-4025-9ed8-9c3528929ccd)

**Comment by SpecialAro** [comment]
Hello @cmoulliard,

![image](https://github.com/ferdium/ferdium-app/assets/37463445/f0020009-8b05-4d55-aa44-89ab3bc82c53)

I'm not facing this issue with the steps you provided.

By any chance, did you had custom icons on those services? We've updated (today) the server side to fix a issue with disappearing icons - just re-add them or delete and save (so it reverts to normal icon).

**Comment by cmoulliard** [comment]
I did what you suggested. Zulip icon(s) are back except that I dont see like before the quarkus or snowdrop zulip icons

![Screenshot 2023-09-28 at 18 33 50](https://github.com/ferdium/ferdium-app/assets/463790/e3bb1dfc-ded6-42fe-b4e0-401a36ba42f8)

**Comment by SpecialAro** [comment]
> did what you suggested. Zulip icon(s) are back

I'm glad that solved it!



> I dont see like before the quarkus or snowdrop zulip icons

I'm not sure what you mean by that, sorry. Is this issue resolved?

**Comment by cmoulliard** [comment]
Such a quarkus icon that I can see on quarkusio.zulipchat.com 
<img width="405" alt="Screenshot 2023-09-28 at 19 10 30" src="https://github.com/ferdium/ferdium-app/assets/463790/20f841fa-5fe0-48e2-8b9d-75503d4ab30a">

**Comment by SpecialAro** [comment]
> Such a quarkus icon that I can see on quarkusio.zulipchat.com <img alt="Screenshot 2023-09-28 at 19 10 30" width="405" src="https://user-images.githubusercontent.com/463790/271364178-20f841fa-5fe0-48e2-8b9d-75503d4ab30a.png">

I think that, for that, you need to use a custom icon for each service

**Comment by cmoulliard** [comment]
Ok. So the problem is then fixed.
