### ISSUE TITLE
Service Request: Obsidian.md

### ISSUE THREAD

**Issue by Supermarcel10** [ferdium/ferdium-app#1383]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+request+%3Asparkles%3A%22) for a recipe request that matches the one I want to file, without success.

### Name of the service

Obsidian.md

### URL of the service

https://obsidian.md

### Features you want implemented

TODO lists are already an accessible service through Ferdium.
Obsidian.md is an md editor featuring a network of markdown sheets, with TODO lists, different views and plugins. It's often useful for taking notes and research regarding a project.

Obsidian.md is based on JS, so it shouldn't be too hard to implement.

The Obsidian.md repo can he found [here](https://github.com/obsidianmd).
The Obsidian.md website can be found [here](https://obsidian.md).

**Comment by SpecialAro** [comment]
Hello @Supermarcel10 and thank you for logging this recipe request.

Does Obsidian.md have a web-app ? Otherwise, it won't be possible to integrate it in Ferdium as a recipe.

**Comment by Arthur-Huan** [comment]
I also use Obsidian. But there isn't a web app, so this is unfortunately not possible at the moment.

**Comment by SpecialAro** [comment]
Closing as per @Arthur-Huan comment. Thank you!
