### ISSUE TITLE
6.5.0 release - broken services

### ISSUE THREAD

**Issue by marrek13** [ferdium/ferdium-app#1387]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.5.0

### What Operating System are you using?

macOS

### Operating System Version

macOS Ventura 13.6

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Ferdium version

6.4.1

### Expected Behavior

After upgrade the app should still be working and load all the configured services

### Actual Behavior

All the services are gone and there are multiple errors happening in the developer tools (check the screenshot)

### Steps to reproduce

Upgrade 6.4.1 to 6.5.0.

### Debug link

https://debug.ferdium.org/4ce726cc-f27c-496b-b0af-e8ef9939c4af

### Screenshots

<img width="956" alt="Screenshot 2023-10-02 at 21 08 00" src="https://github.com/ferdium/ferdium-app/assets/3691208/b9a6f396-db57-4492-a627-86af7e0facbb">

**Comment by marrek13** [comment]
Downgrading to 6.4.1 fixed the issue.

**Comment by smithcoin** [comment]
Can confirm the same behavior on Mac M1. Downgrading fixed the issue.

**Comment by macCesar** [comment]
Where can we download the previous version ??

**Comment by Alphrag** [comment]
Sorry about that guys, the feedback I had on the nightly version was that focus mode was not working better, but nothing was broken. Seems like that was not the case. We are going to revert the problematic PR and push a new stable quickly!

**Comment by smithcoin** [comment]
https://github.com/ferdium/ferdium-app/releases/tag/v6.4.1

**Comment by bkimmett** [comment]
Looking in the app directory for Ferdium 6.4.1, maybe it's trying to read `app.asar` as a folder when it should be trying to read `app.asar.unpacked`?

**Comment by SpecialAro** [comment]
I'm publishing a stable patch for this issue right now (after merging this PR https://github.com/ferdium/ferdium-app/pull/1388).

**Comment by SpecialAro** [comment]
I'm linking this issue, who might be related https://github.com/ferdium/ferdium-app/issues/1360
