### ISSUE TITLE
Slack service doesn't load 

### ISSUE THREAD

**Issue by huuhp** [ferdium/ferdium-app#1406]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.5.2

### What Operating System are you using?

macOS

### Operating System Version

Sonoma 14.0

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

I newly installed the app and I selected Slack as a service. I expect to be able to log in Slack

### Actual Behavior

Slack doesn't load and just show a grey screen (screenshot). I tried to reload the service and restart the laptop but it doesn't work.

<img width="992" alt="image" src="https://github.com/ferdium/ferdium-app/assets/67207063/f40f7cd6-f03e-4b6c-b98f-fc0da87fda1d">

### Steps to reproduce

1. Select Slack as a service
2. Slack doesn't load

### Screenshots

<img width="992" alt="image" src="https://github.com/ferdium/ferdium-app/assets/67207063/5a24bc48-f9de-42b3-9c89-1a3293eb146d">

**Comment by SpecialAro** [comment]
Hi @huuhp !

have you placed the correct team in the following field?
![image](https://github.com/ferdium/ferdium-app/assets/37463445/a82db69d-c29c-4952-8739-bd83cec48e68)

**Comment by 20CCAA07** [comment]
Hi @SpecialAro,

not OP, but I have the same issue on Ubuntu 22.04.3 LTS after I have just installed Ferdium 6.5.2. Other services work well but Slack stays blank.

I can confirm that I have used the correct team in the field you mentioned above.

**Comment by 20CCAA07** [comment]
Hi @SpecialAro ,

Please disregard my last comment. I was just able to solve this issue (at least for my case).

This is how I got there:

I did a right-click on the blank page and selected "Open in Browser". Once the browser opened, I saw the problem. In Ferdium, I had entered the team URL with the leading https://. However, it looks like Ferdium adds https:// automatically which lead to "https://https://team-url.slack.com". And this of course led to nowhere.

Once I removed the "https://" from the team field, Slack loaded as it should.

// Edit: Corrected a few typos.

**Comment by SpecialAro** [comment]
@huuhp can you check the answer provided by @20CCAA07 and see if it fixes it for you?

**Comment by huuhp** [comment]
@SpecialAro @20CCAA07  thank you for the info. The issue is solved.
