### ISSUE TITLE
Bug: Links in Gmail Service Return Invalid URL

### ISSUE THREAD

**Issue by austin3410** [ferdium/ferdium-app#141]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.31

### What Operating System are you using?

Windows

### Operating System Version

Windows 10 and 11

### What arch are you using?

x64

### Expected Behavior

When I click on any link within any email within the Gmail service, a new browser window or tab should open to the page the link is addressed to.

### Actual Behavior

When I click on any link in any email within the Gmail service, it opens a new browser window or tab but returns an "invalid URL" Google Redirect notice. This is because the link gets altered to become invalid. For example:
If the original link in a email is "https://example.com/page".
At some point after clicking the link, Ferdium seems to alter the link to:
"http:/example.com/page"

Notice one of the /'s is missing in the altered link. This happens in any link I click on in any email while using the Gmail Service in Ferdium.

### Steps to reproduce

Click any link in any email while using the Gmail Service.

### Screenshots

![image](https://user-images.githubusercontent.com/32914667/167983608-379eb68d-5012-44a6-b17c-914eee291521.png)

### Additional information

This happens regardless of my default browser. I even emailed my self with a link to "https://ebay.com". That's is the attached picture.

Also, if I edit the full redirect URL and correct "https:/" to "https://", the page loads fine.

**Comment by vraravam** [comment]
This is not a problem with Ferdium unfortunately @austin3410 . Its not something that we can "fix".

**Comment by austin3410** [comment]
Oh, ok do you know the cause of the issue? Can I do anything on my end?

**Comment by vraravam** [comment]
> Oh, ok do you know the cause of the issue? Can I do anything on my end?

Unfortunately, no.

**Comment by vraravam** [comment]
Reopening since this was a regression from a different fix. Sorry for the regression.

**Comment by vraravam** [comment]
Building nightly `6.0.0-nightly.36` with this out-of-band fix since its quite important to fix the regression for our beta users.
