### ISSUE TITLE
FB Messenger failed document request

### ISSUE THREAD

**Issue by severinbratus** [ferdium/ferdium-app#1411]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+%3Abookmark_tabs%3A%22+label%3A%22bug+%3Abeetle%3A%22+) for a bug report that matches the one I want to file, without success.

### Ferdium Version

6.5.2

### Recipe Name

Messenger

### Recipe Version

1.8.0

### Last Known working version of the recipe

NA

### Steps to reproduce

1. Open Ferdium
2. Add a Messenger service, settings default
3. Observe the nothingness
4. Check the service devtools via `View`, `Ctrl+R` to reload

### Expected Behavior

Messenger should load, displaying a login screen.

### Actual Behavior

I see a blank white screen. The devtools report the request to `messenger.com` fails.

### Screenshots

![Screenshot from 2023-10-22 14-14-15](https://github.com/ferdium/ferdium-app/assets/69299116/d2204005-d26e-4b67-b060-8ddcf5a46846)

![Screenshot from 2023-10-22 14-13-17](https://github.com/ferdium/ferdium-app/assets/69299116/c4193163-890d-4d63-a7ac-19b4d2981506)

![Screenshot from 2023-10-22 14-13-27](https://github.com/ferdium/ferdium-app/assets/69299116/2c6169e4-fb1b-4d21-91d5-f15333c675bb)

### Additional Information

I am running Fedora Linux 38. I have installed Ferdium via the RPM off the website.

**Comment by SpecialAro** [comment]
I'm not able to reproduce this issue. Is it possible that your DNS/network is blocking messenger?

**Comment by severinbratus** [comment]
Hello. My bad, indeed you are right, I had a `0.0.0.0 messenger.com` rule in my `/etc/hosts` that I forgot about. Tnx
