### ISSUE TITLE
FB Messenger - All remote text is grey on white background

### ISSUE THREAD

**Issue by nexxai** [ferdium/ferdium-app#1416]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.5.2

### What Operating System are you using?

macOS

### Operating System Version

Sonoma 14.0

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Ferdium version

6.5.2

### Expected Behavior

Text to be readable

### Actual Behavior

Text is unreadable

### Steps to reproduce

Open Messenger

### Debug link

https://debug.ferdium.org/ecbbc03c-441b-496f-b7c6-8533f680e786

### Screenshots

<img width="376" alt="Screenshot 2023-10-24 at 5 29 07 PM" src="https://github.com/ferdium/ferdium-app/assets/4316564/61c4eeb0-674d-405f-a82f-1a412de258ab">

### Additional information

Everything was fine until (I think) about yesterday when all of a sudden the colors just decided to leave any remote text.  My own personal text shows up with the correct color, and this does not affect my local desktop instance of Messenger nor my phone.

**Comment by SpecialAro** [comment]
Closing this issue given yesterday was merged a fix on https://github.com/ferdium/ferdium-recipes/pull/448
