### ISSUE TITLE
Zoom resets after service change

### ISSUE THREAD

**Issue by iffikas** [ferdium/ferdium-app#1419]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.5.3-nightly.4

### What Operating System are you using?

Windows

### Operating System Version

Win10

### What arch are you using?

x64

### Expected Behavior

After changing between services the zoom state for service is saved

### Actual Behavior

After changing between services the zoom is reset

### Steps to reproduce

1. Open service 1
2. Change zoom for service 1
3. Change to service 2
4. Return to service 1

### Additional information

_Update (27.10.23):_
Build info
```
Version: 6.6.1-nightly.1
Server: Ferdium Server
Electron: 27.0.1
Chrome: 118.0.5993.89
Node.js: 18.17.1
Platform: Windows 10
Arch: x64
Build date: Fri Oct 27 2023 03:39:52 GMT+0300 (Eastern European Summer Time)
Git SHA: 65d24965
Git branch: nightly
```

**Comment by WillPresley** [comment]
This has been happening to me too on Win10/64 both 6.5.3 nightly 3 and nightly 4 (I think it was fine before that though). Was waiting to see if a quick fix came along or someone else made a bug report before I did. Definitely not a show-stopper, but pretty annoying when I had non-standard zoom levels for almost every service!

**Comment by mmoayyed** [comment]
Also seeing this with:

```
Version: 6.6.0
Server: Ferdium Server
Electron: 27.0.1
Chrome: 118.0.5993.89
Node.js: 18.17.1
Platform: macOS Unknown
Arch: arm64
Build date: Fri Oct 27 2023 04:32:01 GMT+0400 (Gulf Standard Time)
Git SHA: d157b865
Git branch: release
```

**Comment by sa1ntwolf** [comment]
Also experiencing the same issue above, just after the latest update.

**Comment by hasbifadilah** [comment]
me too

```
Version: 6.6.0
Server: Ferdium Server
Electron: 27.0.1
Chrome: 118.0.5993.89
Node.js: 18.17.1
Platform: macOS Unknown
Arch: arm64
Build date: Fri Oct 27 2023 07:32:01 
```

**Comment by sa1ntwolf** [comment]
Version: 6.6.0
Server: No Server
Electron: 27.0.1
Chrome: 118.0.5993.89
Node.js: 18.17.1
Platform: Windows 10
Arch: x64
Build date: Fri Oct 27 2023 08:32:03

**Comment by Shrekmachine** [comment]
same here, with nightly Build .1 no fix
Version: 6.6.1-nightly.1
Server: Ferdium Server
Electron: 27.0.1
Chrome: 118.0.5993.89
Node.js: 18.17.1
Platform: Windows 11
Arch: x64
Build date: Fri Oct 27 2023 02:39:52 GMT+0200 (Mitteleuropäische Sommerzeit)
Git SHA: 65d24965
Git branch: nightly

**Comment by mareknovotny** [comment]
+1  with difference
Server: No Server
Platform: Linux 6.5

> same here, with nightly Build .1 no fix 
> Version: 6.6.1-nightly.1 
> Server: Ferdium Server 
> Electron: 27.0.1 
> Chrome: 118.0.5993.89 
> Node.js: 18.17.1 
> Platform: Windows 11 
> Arch: x64 
> Build date: Fri Oct 27 2023 02:39:52 GMT+0200 (Mitteleuropäische Sommerzeit) 
> Git SHA: [65d2496](https://github.com/ferdium/ferdium-app/commit/65d2496546cd5f71aeee140dba1c11a907ccf1f7) 
> Git branch: nightly

Also together with https://github.com/ferdium/ferdium-app/issues/669 it seems that Ferdium is not usable for me. I need to use at least 2x zoom in for every service and switching regularly means it is a very regular action.
I am basically downgrading or stopping to use Ferdium if it is not fixed quickly :( 

Update: as pointed in https://github.com/ferdium/ferdium-app/issues/1419#issuecomment-1782517020 the latest stable version 6.6.0 is affected  too 😢

**Comment by ricain59** [comment]
me too:
Version: 6.6.0
Server: Ferdium Server
Electron: 27.0.1
Chrome: 118.0.5993.89
Node.js: 18.17.1
Platform: Linux 6.5
Arch: x64
Build date: Fri Oct 27 2023 01:30:26 GMT+0100 (Western European Summer Time)
Git SHA: d157b865
Git branch: release

**Comment by SpecialAro** [comment]
> This has been happening to me too on Win10/64 both 6.5.3 nightly 3 and nightly 4 (I think it was fine before that though). Was waiting to see if a quick fix came along or someone else made a bug report before I did. Definitely not a show-stopper, but pretty annoying when I had non-standard zoom levels for almost every service!

Hi! 

Can you confirm if 6.5.3-nightly.2 works fine? If so, the only possible change that introduced this issue was the update to the latest electron - we cannot control this (other than downgrading to an old electron version)

**Comment by Gaibhne** [comment]
Then I would put my vote in to downgrade electron and/or investigate what changed there and see if there is a new way to persist zoom levels. As someone with extremely poor eyesight (-10.0 plus torus distortion) the current Ferdium is literally unusable for me :( I'm going to see if I can downgrade somehow for the time being.

Version: 6.6.0
Server: No Server
Electron: 27.0.1
Chrome: 118.0.5993.89
Node.js: 18.17.1
Platform: Windows 10
Arch: x64
Build date: Fri Oct 27 2023 02:32:03 GMT+0200 (Central European Summer Time)
Git SHA: d157b865
Git branch: release

**Comment by rcmorano** [comment]
> > This has been happening to me too on Win10/64 both 6.5.3 nightly 3 and nightly 4 (I think it was fine before that though). Was waiting to see if a quick fix came along or someone else made a bug report before I did. Definitely not a show-stopper, but pretty annoying when I had non-standard zoom levels for almost every service!
> 
> Hi!
> 
> Can you confirm if 6.5.3-nightly.2 works fine? If so, the only possible change that introduced this issue was the update to the latest electron - we cannot control this (other than downgrading to an old electron version)

I can confirm 6.5.2 was working fine, I've just updated from it to 6.6.0 (then to the latest [0]) where this issue appeared.

[0]
```
Version: 6.6.1-nightly.1
Server: No Server
Electron: 27.0.1
Chrome: 118.0.5993.89
Node.js: 18.17.1
Platform: macOS Unknown
Arch: arm64
Build date: Fri Oct 27 2023 02:40:42 GMT+0200 (Central European Summer Time)
Git SHA: 65d24965
Git branch: nightly
```

**Comment by Gaibhne** [comment]
6.5.3-nightly.2 works fine for me

**Comment by iffikas** [comment]
I can confirm, works as expected on 6.5.3-nightly.2

**Comment by SpecialAro** [comment]
@Alphrag the electron upgrade caused this... Should we file an issue on their repo?

**Comment by SpecialAro** [comment]
After testing several versions of electron I can say, for sure, that `v26.1.0` is to blame (https://github.com/electron/electron/compare/v26.0.0...v26.1.0).

It seems like this is the faulty PR https://github.com/electron/electron/pull/39495 (but I haven't tested it because I'm not able to build electron from source).

**Comment by SpecialAro** [comment]
I just logged an issue on electron repo. Let's see what they can do https://github.com/electron/electron/issues/40354

**Comment by Alphrag** [comment]
@SpecialAro Well done on chasing the source of the problem! 

Downgrading electron would bring us all the way back to `v25.9.3` (since `v26` crashes on linux) which I think doesn't include all the vulnerability fixes, so I wouldn't be too keen on downgrading for all users.

**Comment by SpecialAro** [comment]
> @SpecialAro Well done on chasing the source of the problem!
> 
> Downgrading electron would bring us all the way back to `v25.9.3` (since `v26` crashes on linux) which I think doesn't include all the vulnerability fixes, so I wouldn't be too keen on downgrading for all users.

Thank you!

Unfortunately yes... We can't afford to downgrade. One of the things we can do is try to fork Electron and make changes to it in order to revert that commit until it is fixed. I've struggled with this though, given that it needs to be compiled in order to run (as far as my understanding goes).

**Comment by mstyle** [comment]
Same issue. The ability to zoom in was the reason I switched to Ferdium. It's been great until this happened. Hopefully it can be resolved soon.

**Comment by christofs** [comment]
Confirming the issue with Ferdium 6.6.0 on Ubuntu 22.04 LTS. This was fine until the last update.

**Comment by sa1ntwolf** [comment]
Just an update. I believe my issue has now been solved. Below are the Steps I took:
1. Downloaded and installed the older version of Ferdium (Ferdium-win-AutoSetup-6.5.3-nightly.4-x64.exe), but nothing changed (still had the same issue with the zoom resetting).
2. Restarted Win10.
3. Downloaded and installed the latest version and it seemed to have fixed the issue.

Only downside was I had to re-login to all the Accounts under all my services which took quite some time.
Good thing is the zooming issue is now gone. I've restarted a dozen times now and it seems to have fixed the issue.
Hope this helps. 
Cheers!

**Comment by SpecialAro** [comment]
Hello @sa1ntwolf. The solution you provided is to downgrade to a previous Ferdium version.

I'm advising all users against this option as the latest version has some very important security patches and also a great important change if you use the Ferdium Server.

Please hold on until Electron developers are able to pick up this issue, given this is out of our control!

Again, please, don't downgrade.

**Comment by sa1ntwolf** [comment]
Hi @SpecialAro,

Terribly sorry for the solution I posted. I just didn't have anything better to do during the weekend. :)
Just to note: I believe I'm not using the Ferdium Server, if that would help.

But you are correct. Downgrading is a terrible idea. I practically wasted 2+ hours just to set-up everything.
Will just wait for the Electron developers' update.

Cheers!

**Comment by elnoxgdl** [comment]
Hi All,

Just wanted to mention this happens on Mac too I downgraded my Ferdium version, until this issue is fixed. Thanks!

**Comment by SpecialAro** [comment]
No worries @sa1ntwolf 

@elnoxgdl as I stated previously, I really advise against downgrading, security wise

**Comment by felixmosh** [comment]
@SpecialAro unfortunately, with this bug, Fredium is not usable, It resets the zoom level on each service change, this is really annoying...

Let's vote this bug on Electron, so it will get attention 
 https://github.com/electron/electron/issues/40354

**Comment by deadmeu** [comment]
It might be worth mentioning that this bug can be reproduced simply by clicking the current service icon, without even needing to switch to a different one first.

**Comment by jgrigera** [comment]
As a workaround I went with adding:

```
HTML { 
zoom: 150%;
}
```

to the `user.css` of relevant services.

**Comment by marcosins** [comment]
I'm trying to debug this to post a reproduction example in the Electron issue. Here's my attempt:

I modified a snippet [^1] from SO [^2][^3] that `console.info` the `window.devicePixelRatio` on every zoom, then added this to the Ferdium Developer Tools and the Service Developer Tools:

```js
const zoomEvent = new Event('zoom')
let originalRatio = window.devicePixelRatio

function checkZooming() {
    console.info('ZOOM LEVEL: ', window.devicePixelRatio)
    if (originalRatio !== window.devicePixelRatio) {
        window.dispatchEvent(zoomEvent)
    }
}
window.addEventListener('resize', checkZooming)
window.addEventListener('zoom', ()=>{})
```

Every `CTRL` `+` `(+ or - or 0)` is logged to the service tools but nothing happens in the Ferdium tools. If you zoom in/out and then press the service icon, you also get a log with `window.devicePixelRatio = 1`.

So at some point clicking the service icon is triggering `webFrame.setZoomLevel(zoomLevel)` in [`zoom.ts`](https://github.com/ferdium/ferdium-app/blob/develop/src/webview/zoom.ts#L7-L35) and sending `window.devicePixelRatio` from the Ferdium window to the child service...or that's my guess.

[^1]: https://developer.chrome.com/docs/devtools/javascript/snippets/#create
[^2]: https://stackoverflow.com/questions/995914/catch-browsers-zoom-event-in-javascript
[^3]: https://gist.github.com/souporserious/b44ea5d04c38c2e7ff32cd1912a17cd0

**Comment by remmaum** [comment]
me too


```
Version: 6.6.1-nightly.7
Server: Ferdium Server
Electron: 27.0.1
Chrome: 118.0.5993.89
Node.js: 18.17.1
Platform: Windows 10
Arch: ia32
Build date: Tue Nov 07 2023 03:48:17 GMT+0300 (GMT+03:00)
Git SHA: 0c8e3b04
Git branch: nightly
```

**Comment by mareknovotny** [comment]
> As a workaround I went with adding:
> 
> ```
> HTML { 
> zoom: 150%;
> }
> ```
> 
> to the `user.css` of relevant services.

this doesn't work well with Slack new UI, it is basically due their weird layout. Also for Hangout or Google Chat there doesn't look the user.css actually works :( not sure why

**Comment by remmaum** [comment]
excellent, thx

> > As a workaround I went with adding:
> > ```
> > HTML { 
> > zoom: 150%;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to the `user.css` of relevant services.
> 
> this doesn't work well with Slack new UI, it is basically due their weird layout. Also for Hangout or Google Chat there doesn't look the user.css actually works :( not sure why

**Comment by RJVB** [comment]
> @SpecialAro unfortunately, with this bug, Fredium is not usable, It resets the zoom level on each service change, this is really annoying...
> 
> Let's vote this bug on Electron, so it will get attention [electron/electron#40354](https://github.com/electron/electron/issues/40354)

I don't know how one votes for (against?!) a bug but I did leave my grain of salt on that ticket which has a sadly low amount of reactions!

Isn't there a way for Ferdium to remember the zoom level and restore it whenever the service icon has been clicked?

FWIW, I'm seeing the zoom jump back to what I assume to be 100% after clicking another service's icon, just before the new service appears. I suppose no one cares about the zoomlevel of a service that's not in view, though ;)

**Comment by RJVB** [comment]
> As a workaround I went with adding:
> 
> ```
> HTML { 
> zoom: 150%;
> }
> ```
> 
> to the `user.css` of relevant services.

Is there a way to find out what zoomlevel you're at (I usually zoom out, not in so the above suggestion would be counterproductive for me ;) )

**Comment by marcosins** [comment]
> I don't know how one votes for (against?!) a bug but I did leave my grain of salt on that ticket which has a sadly low amount of reactions!

Please don't spam the Electron issue with _me too_ replies. They were very clear that to take some action we need to reproduce the issue with a minimal electron project.

I have been trying to do that but Ferdium is a complex piece of software so it's hard to isolate the problem to 1 React component alone. My suspicion is that this might be a `react-electron-web-view` thing but I'm not fluent in React development to make a proper minimal project reproducing the issue.

**Comment by RJVB** [comment]
Be that as it may, it really can't (shouldn't!) hurt to remind them from time to time that "we" are trying to come up with a demonstrator ... and that they could keep their eyes peeled.

I know nothing of this kind of development and last time I tried to build Ferdi (sic) the process failed for reasons beyond my grasp (that wasn't even just before making the switch either). So I can only give some, probably open-door, suggestions::
- It seems to me that the approach here would be to recreate a framework application that has 2 independent views just like Ferdium can have, with 2 hardcoded sites that clearly show the effect of the zoom being reset. From there, reimplement as much complexity/functionality as needed to trigger the issue. This *may* also lead to a possible work-around other than a custom zoom setting in the service preferences, or even expose a subtle bug in Ferdium.
- Do a bisect to find the Electron version or even commit that introduced the issue

BTW: I understand Franz is still being maintained; does it have the same problem?

How hard/impossible would it be to downgrade Electron to a version from just before the issue?

**Comment by SpecialAro** [comment]
> Be that as it may, it really can't (shouldn't!) hurt to remind them from time to time that "we" are trying to come up with a demonstrator ... and that they could keep their eyes peeled. I know nothing of this kind of development and last time I tried to build Ferdi (sic) the process failed for reasons beyond my grasp (that wasn't even just before making the switch either). So I can only give some, probably open-door, suggestions:: - It seems to me that the approach here would be to recreate a framework application that has 2 independent views just like Ferdium can have, with 2 hardcoded sites that clearly show the effect of the zoom being reset. From there, reimplement as much complexity/functionality as needed to trigger the issue. This *may* also lead to a possible work-around other than a custom zoom setting in the service preferences, or even expose a subtle bug in Ferdium. - Do a bisect to find the Electron version or even commit that introduced the issue BTW: I understand Franz is still being maintained; does it have the same problem? How hard/impossible would it be to downgrade Electron to a version from just before the issue?

I've already bisected the code to find which version introduced the issue (as per my comment on Electron repo).

Ever since, I was not able to make a reproducible case: all the tries I did with native electron (without the - maybe deprecated - `react-electron-web-view` that @marcosins stated) all worked fine when switching between webviews. So, it seems that it might be a problem with the `react-electron-web-view` wrapper and not Electron itself.

Three solutions could be implemented:
- Try to rebuild Electron from source (which is a pain given that we need to build the binaries for each platform and then use them in our CI) just to change the portion of the code that was changed
- Downgrade the Electron version - on which I've the opinion that this is not in the table given that this introduces great security vulnerabilities that weren't fixed back then (looking at the day 0 vulnerabilities the most).
- Take the time to code around the issue to programmatically store and set the zoom for each service (so that when a user clicks away, it changes back to the same zoom it was previously - this might be hard to implement given that clicking away might trigger the same function that calls setZoom())

If anyone could help with this issue (at least making a reproducible code in the electron issue) it would be really great!

**Comment by RJVB** [comment]
On Saturday November 11 2023 04:04:46 André Oliveira wrote:

> I've already bisected the code to find which version introduced the issue (as per my comment on Electron repo).

And this hasn't (yet) given any hints what change in Electron (if any) might cause the issue?

FWIW, when I said "subtle bug in Ferdium" I was thinking of one introduced by a subtle upstream API change that requires a change. The obvious change would be that a function Ferdium uses now takes a zoom argument that has a default setting at 100%. But I trust you already checked from something *that* obvious.

>- Take the time to code around the issue to programmatically store and set the zoom for each service (so that when a user clicks away, it changes back to the same zoom it was previously - this might be hard to implement given that clicking away might trigger the same function that calls setZoom())

I'd say we don't care what level the zoom is at after the user clicked AWAY from a service. It only has to be at the selected level when the service comes back into view - and I think we could all "live with it" if there's a visible reset to the level we configured. But that doesn't even have to be the case: the `user.css` trick above works without glitching. A per-service setting could write the corresponding code into `service.css` or `style.css`, or even a dedicated css file that gets read only when the user configured a custom zoom level.
IOW, the only things required would be 2 new controls and a more precise way to set (and check!) the zoom level.

I'd work on those things if I could because I think they're useful features even if the issue at hands gets fixed.

**Comment by slartibart70** [comment]
> As a workaround I went with adding:
> 
> ```
> HTML { 
> zoom: 150%;
> }
> ```
> 
> to the `user.css` of relevant services.

Do you know by chance which changes are necessary for msteams?
Here, the presence of user.css keeps the chat-view of teams from displaying its input field (rendering chats impossible). Some parts of teams are zoomed, others not.
Without user.css, all is fine - and zoomable via keyboard shortcuts without any visual glitches
(using 6.6.1 nightly7)

and, according to current tests, the zoom factor also does not work properly in ms-outlook, esp. for preview of attachments.
So long, i'm back to 6.5.3-nightly2, looking for fixing this zoom-bug by css is futile

**Comment by andre-m-faria** [comment]
> As a workaround I went with adding:
> 
> ```
> HTML { 
> zoom: 150%;
> }
> ```
> 
> to the `user.css` of relevant services.

Thanks for the workaround, it's working like a charm.

Version: 6.6.0
Electron: 27.0.1
Chrome: 118.0.5993.89
Node.js: 18.17.1
Platform: linux 6.2
Arch: x64
Ubuntu 22.04.3

Issue still happening, just for information.

**Comment by mstyle** [comment]
> As a workaround I went with adding:
> 
> ```
> HTML { 
> zoom: 150%;
> }
> ```
> 
> to the `user.css` of relevant services.

This works for me except in WhatsApp it breaks message reactions (when you click someone's message and pick an emoji from a list). Message reactions now appear partially off-screen if the clicked message is at the very bottom of the screen, and completely off-screen (not visible at all) if the clicked message is anywhere else.

![WhatsApp_reactions_broken](https://github.com/ferdium/ferdium-app/assets/4006580/02ef8a51-979f-4826-b2c4-d4ac81c8ae8d)

**Comment by RJVB** [comment]
On Friday December 01 2023 07:17:51 mstyle wrote:
>This works for me except in WhatsApp it breaks message reactions (when you click someone's message and pick an emoji from a list). Message reactions now appear partially off-screen if the clicked message is at the very bottom of the screen, and completely off-screen (not visible at all) if the clicked message is anywhere else.

What is your scale factor? Mine is set to 90% for whatsapp, and I'm just not getting the full plus-in-a-circle when I click on the smiley icon to the right of someone else's message (regardless of where it is vertically). I do get the entire selection pop-up when I go through the "React" action in the context menu that appears when you click the downward caret at the upper right of the message (under "Reply").

**Comment by mstyle** [comment]
> On Friday December 01 2023 07:17:51 mstyle wrote: This works for me except in WhatsApp it breaks message reactions (when you click someone's message and pick an emoji from a list). Message reactions now appear partially off-screen if the clicked message is at the very bottom of the screen, and completely off-screen (not visible at all) if the clicked message is anywhere else.
> What is your scale factor? Mine is set to 90% for whatsapp, and I'm just not getting the full plus-in-a-circle when I click on the smiley icon to the right of someone else's message (regardless of where it is vertically). I do get the entire selection pop-up when I go through the "React" action in the context menu that appears when you click the downward caret at the upper right of the message (under "Reply").

My scale factor is 150. Anything smaller is not comfortable for me to read. Before this problem began I always had my font at this size, and even bigger, and everything worked flawlessly, including the react menus.

Also, I just tried clicking the React option in the right-click menu (instead of the react icon) and it's the same - I can see the partial emoji pop-up when the message is at the bottom of the screen, and nothing if it's higher.

**Comment by RJVB** [comment]
FWIW, I can reproduce this in Google Chrome so it seems to be a WA issue!

**Comment by mstyle** [comment]
> FWIW, I can reproduce this in Google Chrome so it seems to be a WA issue!

I just tested it in Windows 10 Chrome, Firefox and Edge at web.whatsapp.com, in both regular and Incognito/InPrivate modes (6 tests total). In every single one reactions are working perfectly, even when zoomed in so much that I can only see one message per screen. Attaching one of the 6 screenshots below.

So, at least in my case, the issue is not with WhatsApp but with Ferdium.

![WhatsApp_web_reactions_working](https://github.com/ferdium/ferdium-app/assets/4006580/9c3d5602-8d6c-4e22-8ee8-bae5d8265bbd)

**Comment by WillPresley** [comment]
Looks like this has finally (hopefully) been fixed upstream in [#electron/electron/40650](https://github.com/electron/electron/pull/40650)! Once there is a Ferdium test build or Nightly, I'll give it a test.

**Comment by cristianmtr** [comment]
Do any of the new Nightly builds include this fix? I just downloaded 6.6.1 N14 and the issue persists.

**Comment by WillPresley** [comment]
@cristianmtr There hasn't been a new nightly build since that commit to Electron, so no.

**Comment by monkeylove** [comment]
> > As a workaround I went with adding:
> > ```
> > HTML { 
> > zoom: 150%;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to the `user.css` of relevant services.
> 



> 150

Thanks. In my case, though, it causes the slider in Twitter videos to act in a weird manner. I'll try it at 125%.

**Comment by mcmxcdev** [comment]
I tested the electron v28 upgrade locally, but I don't think it's ready yet to use.

Unsure if this is related to the way we use zoom or if the new major version still has bugs, but zooming doesn't work at all, and I see various errors in the dev tools when attempting to zoom. If someone has some free time to debug this, it would be highly appreciated.

**Comment by marcosins** [comment]
> I tested the electron v28 upgrade locally, but I don't think it's ready yet to use.

`29.0.0-alpha.3`[^1] has the fix for ferdium, you should test with that version

[^1]: Electron Releases: https://github.com/electron/electron/releases/tag/v29.0.0-alpha.3

**Comment by mcmxcdev** [comment]
That might be the case, but we won't be upgrading and releasing using an alpha version of electron and the stable release won't be out until February: https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline

**Comment by marcosins** [comment]
Totally understand. I'm not saying Ferdium should release using alpha software. I was trying to be specific about this issue.

I too replaced the electron version on the main `package.json` and then `pnpm debug`. I'm seeing lots of these:

```
Message REMOTE_RENDERER_CALLBACK sent by unexpected WebContents (undefined)
Message REMOTE_RENDERER_RELEASE_CALLBACK sent by unexpected WebContents (undefined)
Message REMOTE_RENDERER_CALLBACK sent by unexpected WebContents (undefined)
```

**Comment by SpecialAro** [comment]
@marcosins Thank you for pointing out the new Electron version that fixes this bug. I can confirm that (at least in dev mode) this issue is solved with that version of Electron.

![image](https://github.com/ferdium/ferdium-app/assets/37463445/41409105-75d9-4761-92df-2e53de4e5385)

**Comment by cristianmtr** [comment]
Is there a way to build that locally, or could you please release that build (as "experimental" etc.)?

**Comment by marcosins** [comment]
> Is there a way to build that locally, or could you please release that build (as "experimental" etc.)?

You can follow the instructions available in [CONTRIBUTING.md](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) to build a custom release of Ferdium.

**Comment by SpecialAro** [comment]
> Is there a way to build that locally, or could you please release that build (as "experimental" etc.)?

We could in theory do this, yes. But I can't assure that the app updates would work properly or even if it would break electron updater.

Nevertheless, it should be fairly "easy" to build this locally:
- Clone this repo using git (https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md#clone-repository-with-submodule)
- Install node version specified in https://github.com/ferdium/ferdium-app/blob/develop/package.json#L16
- Run the following script (https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md#run-the-script)
- Wait for builds to finish and run the app from the "out" folder that is created at the end

Take into consideration that doing this can log you out in services or mess up with your config files.

**Comment by bzsimon** [comment]
> @marcosins Thank you for pointing out the new Electron version that fixes this bug. I can confirm that (at least in dev mode) this issue is solved with that version of Electron.
> 
> ![image](https://private-user-images.githubusercontent.com/37463445/290234303-41409105-75d9-4761-92df-2e53de4e5385.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MzU1NjgsIm5iZiI6MTcwMjkzNTI2OCwicGF0aCI6Ii8zNzQ2MzQ0NS8yOTAyMzQzMDMtNDE0MDkxMDUtNzVkOS00NzYxLTkyZGYtMmU1M2RlNGU1Mzg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDIxMzQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwM2QzODQ0NzgxNDM2ZmVlZjYwNGRmN2QyZGRkYjE3NGY4YWU3NzM3MjIwMWQ2NjUxNzIyNDNmNDBkMGJhZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FTHkENYsOyGQap6rRdJ_mwEGLsg6b2P_Td7XlHMzNfs)

How can you install the alpha version of electron under windows ferdium? Thanks in advance

**Comment by max1c** [comment]
Upgraded to 6.7.0 and it's not fixed. Doesn't look like it's in the patch notes either :(

**Comment by bzsimon** [comment]
> Upgraded to 6.7.0 and it's not fixed. Doesn't look like it's in the patch notes either :(

If you read the answers above: mcmxcdev wrote "That might be the case, but we won't be upgrading and releasing using an alpha version of electron and the stable release won't be out until February: https://www.electronjs.org/docs/latest/tutorial/electron-timelines"

**Comment by max1c** [comment]
> > Upgraded to 6.7.0 and it's not fixed. Doesn't look like it's in the patch notes either :(
> 
> If you read the answers above: mcmxcdev wrote "That might be the case, but we won't be upgrading and releasing using an alpha version of electron and the stable release won't be out until February: https://www.electronjs.org/docs/latest/tutorial/electron-timelines"

Yea, thanks. Didn't realize Electron release was only in alpha. I do have to say this is a pretty big show stopper bug though. This making it into a release and not being fixed for close to 6 months with no workaround is pretty awful.

**Comment by bzsimon** [comment]
> > > Upgraded to 6.7.0 and it's not fixed. Doesn't look like it's in the patch notes either :(
> > 
> > 
> > If you read the answers above: mcmxcdev wrote "That might be the case, but we won't be upgrading and releasing using an alpha version of electron and the stable release won't be out until February: https://www.electronjs.org/docs/latest/tutorial/electron-timelines"
> 
> Yea, thanks. Didn't realize Electron release was only in alpha. I do have to say this is a pretty big show stopper bug though. This making it into a release and not being fixed for close to 6 months with no workaround is pretty awful.

Yes, I'm agree, but it is always a free opensource project, so when a bug depend on third "software" (if I've understood right) there is only to be patient ... I'm agree it a very heavy and long bug .... I'm trying to find a way to installa a compile version of ferdium with alpha electron that is without zoom bug ... for now I've found no guidelines ...

**Comment by RJVB** [comment]
The easy way is just to downgrade to the release just before the regression.

**Comment by mareknovotny** [comment]
> The easy way is just to downgrade to the release just before the regression.

it was noted that there were security issues fixed so downgrade is not recommended. I just started to use again Franz. P.S. I did tried to upgrade and compile with that alpha version, but i haven't been able to use it at all the built output. Maybe wrong compilation or whatever, but it didn't work at all. 
Did anyone tried to update and build it? The **patch** would be nice see and to link here for users able to try and verify it is really fixed there.

**Comment by RJVB** [comment]
>it was noted that there were security issues fixed so downgrade is not recommended.

Yeah, I'm sure you'd get pw0ned instantly, after all Ferdium is the ideal, recommended tool to do your banking/crypto business and visit shady websites...

**Comment by marcosins** [comment]
ℹ️ Please keep the conversation on-topic. Remember that every reply pings everyone.

**Comment by martin-braun** [comment]
I could absolutely accept this regression, if it was possible to enable split view only for certain services. I want to have two services side by side that don't have scaling issues for me, but it makes all other services unusable, because their UI is just too large that it forces me into mobile mode.

**Comment by SpecialAro** [comment]
> > The easy way is just to downgrade to the release just before the regression.
> 
> it was noted that there were security issues fixed so downgrade is not recommended. I just started to use again Franz. P.S. I did tried to upgrade and compile with that alpha version, but i haven't been able to use it at all the built output. Maybe wrong compilation or whatever, but it didn't work at all. Did anyone tried to update and build it? The **patch** would be nice see and to link here for users able to try and verify it is really fixed there.


If you checked my comment here: https://github.com/ferdium/ferdium-app/issues/1419#issuecomment-1854088439 you would see that I managed to build and test it to confirm it was fixed by the specified 29.0.0 alpha version of electron.
This will be fixed whenever electron 29 is released and once we pull that version to our code (in February hopefully)

I would advise you to not go back to Franz as its codebase is using electron 22.3.18 (https://github.com/meetfranz/franz/blob/86f7753a4fc0da89db25a281b6cd50ccb2c915e5/package.json#L130C26-L130C26) which is deprecated and therefore missing several important security and vulnerability fixes.

**Comment by johnsk18** [comment]
Experiencing the same issue as well.

Version: 6.7.0
Server: Ferdium Server
Electron: 27.1.3
Chrome: 118.0.5993.159
Node.js: 18.17.1
Platform: Windows 10
Arch: x64
Build date: Fri Dec 22 2023 14:27:46 GMT-0500 (Eastern Standard Time)
Git SHA: 2f449ce7
Git branch: release

**Comment by slartibart70** [comment]
i just built ferdium 6.7.1-nightly14 with electron 29.0.0-beta.5 in a container and replaced the files in /opt/Ferdium with the newly built version.
Zoom works as expected, no problems so far.

Just one thing: the container-build does not create the packages (like .rpm) as described [here](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md).
Did i miss something?

**Comment by Alphrag** [comment]
> Just one thing: the container-build does not create the packages (like .rpm). Did i miss something?

@slartibart70 good to see that you managed to build also on your side. If you build using `./scripts/build-unix.sh` as recommended, it does not actually build all of the assets, only the unpacked version corresponding to your OS and your architecture, so that it can be tested appropriately. If this works and you want to do all packaged builds, then you can run `pnpm build` which should then build all assets corresponding to your OS.

**Comment by SpecialAro** [comment]
Hello again!

Just to inform you that we merged a PR with the update to the Electron v29 beta which fixes this issue.

Please wait for a new nightly (probably released today/tomorrow) and update in order to see this fixed. You should enable pre-releases in the Ferdium Settings in order to update.

We will release a stable Ferdium update once Electron v29 is stable.

**Comment by vraravam** [comment]
New nightly released with the fix: https://github.com/ferdium/ferdium-app/releases/tag/v6.7.1-nightly.16

**Comment by iffikas** [comment]
Works as expected now.

> Version: 6.7.1-nightly.16
> Server: Ferdium Server
> Electron: 29.0.0-beta.8
> Chrome: 122.0.6261.18
> Node.js: 20.9.0
> Platform: Windows 10
> Arch: x64
> Build date: Mon Feb 12 2024 03:00:48 GMT+0200 (Eastern European Standard Time)
> Git SHA: dfe33dae
> Git branch: nightly

**Comment by Cknight70** [comment]
Hi, this is still not working for me on Arch Linux

Version: 6.7.1-nightly.19
Server: No Server
Electron: 27.3.1
Chrome: 118.0.5993.159
Node.js: 18.17.1
Platform: Linux 6.7
Arch: x64
Build date: Thu Feb 15 2024 17:44:26
Git SHA: 7b384208
Git branch: nightly

**EDIT: Updated to nightly 22, and the problem is fixed for me too. Sorry for the pings**

**Comment by marrws** [comment]
Upgrading to `6.7.1` fixed the issue, thank you
