### ISSUE TITLE
Credentials autocomplete

### ISSUE THREAD

**Issue by severinbratus** [ferdium/ferdium-app#1425]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22enhancement+%3Asparkles%3A%22) for a feature request that matches the one I want to file, without success.

### Problem Description

I am sure many are frustrated when seeing the log-in screen for a service in Ferdium. For instance, see #1301, #1409. In some services the login is likely to break inevitably due to interface changes.

### Proposed Solution

I believe it would be a good idea to have browser-like username-password-autocomplete to have easier back-up way to login when autologin fails. If this already a feature in Ferdium, let me know, since I have not been able to find it.

### Alternatives Considered

One alternative would to keep the recipes up to date at all times. This is of course would not hurt, but is probably more time-consuming for developers.

**Comment by SpecialAro** [comment]
Hello @severinbratus, thank you for logging this issue.


What are you proposing exactly?

Storing login information (email and password) like most browsers do to achieve an auto complete feature introduces additional security complexity.

As of now, Ferdium doesn't store any credentials or any other type of data from the user - which is, as far as I know, on purpose.

**Comment by slartibart70** [comment]
what about finally adding the extensions (chrome extensions) for ferdium?
Then we could have keepassxc extension which would offer sth. like credentials-autofill for your services(websites)

**Comment by severinbratus** [comment]
Closing as a duplicate of #135. I had missed this issue in my search, and I believe extension support would be the best solution to the problem.
