### ISSUE TITLE
Zoom settings on the page are not saved

### ISSUE THREAD

**Issue by max1c** [ferdium/ferdium-app#1428]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.6.0

### What Operating System are you using?

Windows

### Operating System Version

Windows 11 22621.2428

### What arch are you using?

x64

### Last Known Working Ferdium version

6.5.2

### Expected Behavior

When zooming in on a service the zoom settings are permanent unless changed.

### Actual Behavior

The zoom settings on the service are not being saved and reset each time you change the app or open settings.

### Steps to reproduce

1. Click View
2. Click Zoom In
3. Change to another service
4. Zoom resets

### Additional information

This is a regression as this was working as expected in all previous releases.

**Comment by max1c** [comment]
Found a previously opened issue for this: https://github.com/ferdium/ferdium-app/issues/1419

**Comment by sa1ntwolf** [comment]
Also experiencing the same issue above, just after the latest update.

**Comment by sa1ntwolf** [comment]
Version: 6.6.0
Server: No Server
Electron: 27.0.1
Chrome: 118.0.5993.89
Node.js: 18.17.1
Platform: Windows 10
Arch: x64
Build date: Fri Oct 27 2023 08:32:03

**Comment by SpecialAro** [comment]
Please don't comment on the duplicate issue but on the already open issue.

I'm closing the conversation to prevent comments here. Thank you!
