### ISSUE TITLE
Feature: List all configured Workspaces with keyboard shortcut on sidebar

### ISSUE THREAD

**Issue by Fabeuss** [ferdium/ferdium-app#143]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

To change workspace, you need 2 mouse clicks, it is not very quick and useful...

### Proposed Solution

It would be awesome to be able to switch workspaces directly, for example by creating a shortcut to access directly to the desired one, next to others icons on vertical bar

### Alternatives Considered

...

**Comment by vraravam** [comment]
<img width="241" alt="Screenshot 2022-05-14 at 5 04 56 AM" src="https://user-images.githubusercontent.com/69629/168421249-3d3bc440-b8ef-437c-bb40-55a88dd89da0.png">

@Fabeuss - this is already present. I have attached screenshots from my macos.

**Comment by Fabeuss** [comment]
@vraravam ok, I knew those shortcuts but what I was talking about was to add shortcut icons in the vertical bar for more ease access :

![2022-05-15_09-57](https://user-images.githubusercontent.com/40515597/168463128-d873a316-fbed-4de0-af95-93406d020d55.png)

**Comment by vraravam** [comment]
Did you mean like tooltips - similar to how they appear for the individual services from 1-9?

> To change workspace, you need 2 mouse clicks, it is not very quick and useful...

What I understood from the above is that you wanted a shortcut-based access to switch to different workspaces. And, that is already there. Could you please be more specific? maybe with screenshots of what you want actually?

**Comment by Fabeuss** [comment]
sorry for not being clear, in fact, I would just like to be able to select directly the workspace of my choice via the left column of icons :

![Sans titre](https://user-images.githubusercontent.com/40515597/168480225-2cf30da7-4c01-4a5e-971e-9c97fb4316df.png)

In fact, just like that, but on vertical bar :)

![2022-05-15_18-36](https://user-images.githubusercontent.com/40515597/168483709-8782cd63-563e-496c-abbe-9befe09e7769.png)
