### ISSUE TITLE
Update twitter logo in footer

### ISSUE THREAD

**Issue by adityadeshpande09** [ferdium/ferdium-app#1430]
### Your issue

The twitter logo in the footer needs to be updated to X.
![image](https://github.com/ferdium/ferdium-app/assets/98452243/03e37b3a-755b-4d12-a0c8-47f175ebb83d)

**Comment by adityadeshpande09** [comment]
I would like to work on this.

**Comment by SpecialAro** [comment]
Please follow the templates in order to correctly open issues.
