### ISSUE TITLE
[Recipe Request]: Threads

### ISSUE THREAD

**Issue by Dominiquini** [ferdium/ferdium-app#1435]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+request+%3Asparkles%3A%22) for a recipe request that matches the one I want to file, without success.

### Name of the service

Threads

### URL of the service

https://www.threads.net/

### Features you want implemented

Just want it to be integrated!

Thanks.

**Comment by mursonic** [comment]
+1

**Comment by isness** [comment]
I see it's mentioned in the release notes of 6.7.0, but Threads is still not available for addition as a service. Is it like a custom service? How do I add Threads as a service?

**Comment by mcmxcdev** [comment]
> I see it's mentioned in the release notes of 6.7.0, but Threads is still not available for addition as a service. Is it like a custom service? How do I add Threads as a service?

Oh my bad, just noticed that the PR was merged after the nightly that we used for releasing the stable version, so its not included. Our changelog is not fully automated, I removed it from being mentioned there again.

You can add a custom website for the time and wait until the next nightly/beta/stable release drops.
