### ISSUE TITLE
Error when connecting teams

### ISSUE THREAD

**Issue by rst-raphael** [ferdium/ferdium-app#1439]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.6.0

### What Operating System are you using?

Windows

### Operating System Version

windows 11

### What arch are you using?

x64

### Last Known Working Ferdium version

6.6.0

### Expected Behavior

After changing my password, I can't connect to MW Teams

### Actual Behavior

I can't connect to MW Teams

### Steps to reproduce

Add the service
add login and password
presents error: We found a problem. Try again

### Screenshots

![erro](https://github.com/ferdium/ferdium-app/assets/61321277/3afdce87-1a08-4332-ac70-e3da983db0fc)

**Comment by SpecialAro** [comment]
Hello! I'm not able to reproduce this issue with 6.6.1-nightly.7

Can you confirm which setting you have for WebRTC IP, as it might be related:
![image](https://github.com/ferdium/ferdium-app/assets/37463445/79078087-e4cb-4ae4-bb4a-94762b4aacde)

**Comment by vraravam** [comment]
Closing since there's no response from the OP
