### ISSUE TITLE
URL in whatsapp chat does not "auto-load" (preview) during or after sending message (When using W/A Beta)

### ISSUE THREAD

**Issue by stormy1777** [ferdium/ferdium-app#144]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.34

### What Operating System are you using?

Windows

### Operating System Version

Win10

### What arch are you using?

x64

### Expected Behavior

When placing any URL in whatsapp, to SEND to someone in a new chat, or followup/reply, the expected behavior is for the URL to "preload" and offer a "thumbnail" or "Preview" of that image/page, youtube video, so as to save trouble from clicking just to see what the url is about.

### Actual Behavior

Only the URL is sent, possibly with a 1 line title, no image or video preview is included at all.

### Steps to reproduce

I think this anomaly is limited to whatsapp BETA (as was discovered during work on):

"getferdi/ferdi] URL in whatsapp chat does not "auto-load" during or after sending message (Issue #2368)"

start a new CHAT and send any youtube video, before pressing SEND, typically the URL "expanded" in a preview/thumbnail..  even if it did that after pressing SEND That would be acceptable, however it does not do it at all.

**Comment by vraravam** [comment]
This is probably how WA beta works even in a normal browser. Have you verified this? Also, this behavior is not something that's on the client's side (like Ferdium), but rather in the embedded javascript within WA beta - so not in our control.

Also, please do not log bugs that are specific to services in this repo - as mentioned in the checklist for the issue template, there's a separate repo where you should be logging service-specific bugs.

**Comment by stormy1777** [comment]
Vijay, u r correct, further reading leads to this thread:
https://www.reddit.com/r/whatsapp/comments/omazw9/link_preview_not_working_on_whatsapp_web_latest/
currently many report same issue WA beta is just broken in that sense.
