### ISSUE TITLE
Multiple GMAIL service

### ISSUE THREAD

**Issue by Rush-er** [ferdium/ferdium-app#1444]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.6.0

### What Operating System are you using?

Windows

### Operating System Version

Windows 10, version 22H2

### What arch are you using?

x64

### Expected Behavior

If i set 2 istance for GMAIL and try to print a page the system redirect me to chrome/firefox with the print screen of the email.

If i do this on my 1st email the url should be https://mail.google.com/mail/u/0
if i do this on my 2nd email the url should be https://mail.google.com/mail/u/1

### Actual Behavior

The URL is always set to https://mail.google.com/mail/u/0 so if i open an email from account 2 it will pop up an error 
![image](https://github.com/ferdium/ferdium-app/assets/32925370/c1d61d12-2ecf-4561-9dc7-a7aa56de1d22)

### Steps to reproduce

1. Go to service and set up 2 gmail account
2. Try to print from both account

**Comment by Rush-er** [comment]
Also if there is any option to edit 
1. the url that pop-up so i can redirect to the correct mail number (0 or 1)
2. force gmail to check if here is another service started with the same url (site aware)

**Comment by SpecialAro** [comment]
You can add two Gmail recipes and use them separately

**Comment by Rush-er** [comment]
> You can add two Gmail recipes and use them separately

Hello, can you forward me to the right settings ?
i can't find this.

Thanks

**Comment by Rush-er** [comment]
If i got it correctly recipes are isolated, with this i can only edit the url for the second gmail but i still get redirect to https://mail.google.com/mail/u/0 from google side since there is only 1 account on that recipe

> You can add two Gmail recipes and use them separately

**Comment by vraravam** [comment]
you are correct @Rush-er - each service/recipe runs in isolation. So, in effect, each one is at the same "account 0" according to itself!
The site aware thing that you mentioned is not going to be implemented in Ferdium any time soon - since that's considered a security loop hole and can leak credentials across different accounts.
