### ISSUE TITLE
Slack workspace is opened in browser

### ISSUE THREAD

**Issue by fanatixan** [ferdium/ferdium-app#1454]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.6.0

### What Operating System are you using?

Windows

### Operating System Version

Windows 11 Pro 22H2 22621.2715

### What arch are you using?

x64

### Expected Behavior

Slack enterprise workspaces should be opened in Ferdium.

### Actual Behavior

They are opened in the browser.

### Steps to reproduce

1. Log in to a Slack enterprise team with multiple workspaces
2. Click `Launch in Slack` for a specific workspace

**Comment by mhajas** [comment]
I have the same issue with the following version:
```
Version: 6.6.0
Server: No Server
Electron: 27.0.3
Chrome: 118.0.5993.120
Node.js: 18.17.1
Platform: Linux 6.5
Arch: x64
Build date: Fri Oct 27 2023 02:30:26 GMT+0200 (Central European Summer Time)
Git SHA: d157b865
Git branch: release
```

**Comment by mothe-at** [comment]
I have the same issue here:

```
Version: 6.7.0
Server: No Server
Electron: 27.1.3
Chrome: 118.0.5993.159
Node.js: 18.17.1
Platform: macOS Unknown
Arch: x64
Build date: Fri Dec 22 2023 20:28:29 GMT+0100 (Central European Standard Time)
Git SHA: 2f449ce7
Git branch: release
```

**Comment by knumskull** [comment]
As a workaround, it's possible to use the destination workspace as service url. 
For example, if the workspace url is `workspace.slack.com` and offer two workspaces like `workspace-internal` and `workspace-external`, one could configure the service url directly using e.g. `workspace-internal.slack.com`

In that case the direct workspace is opened in Ferdium without a hassle.

**Comment by vraravam** [comment]
If you are referring to "Launch in Slack" in a browser window, that's not possible to open in Ferdium. 
As @knumskull suggested, you can configure/edit the slack service's url inside Ferdium to login directly in Ferdium.

**Comment by fanatixan** [comment]
> As a workaround, it's possible to use the destination workspace as service url. For example, if the workspace url is `workspace.slack.com` and offer two workspaces like `workspace-internal` and `workspace-external`, one could configure the service url directly using e.g. `workspace-internal.slack.com`
> 
> In that case the direct workspace is opened in Ferdium without a hassle.

I tried exactly this and it doesn't work. Note that the workspace URL is `company.enterprise.slack.com`:

![image](https://github.com/ferdium/ferdium-app/assets/7453887/5c005f0b-9204-4b63-8214-cfe6ba5403ab)

Then I get this page, so far so good:

![image](https://github.com/ferdium/ferdium-app/assets/7453887/4838b0e5-8c2f-415e-b7de-594fc6189d9f)

But when I click the button `Launch in Slack`, it opens in the browser. I guess it has something to do with having an additional subdomain in the workspace URL.

**Comment by knumskull** [comment]
@fanatixan click on each workspace you would like to connect (**not** Launch in Slack). 
![slack-workspaces](https://github.com/ferdium/ferdium-app/assets/2650167/627f1a1f-091b-446c-8030-ca9f6f604e98)

Click on the entire label, a pop-up is shown with information about the workspace link.

![slack-workspace-specific](https://github.com/ferdium/ferdium-app/assets/2650167/4eef5bde-04ac-4f3a-b25e-5650116b833f)

**Comment by fanatixan** [comment]
> @fanatixan click on each workspace you would like to connect (**not** Launch in Slack). ![slack-workspaces](https://private-user-images.githubusercontent.com/2650167/296978001-627f1a1f-091b-446c-8030-ca9f6f604e98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzOTM2NTIsIm5iZiI6MTcwNTM5MzM1MiwicGF0aCI6Ii8yNjUwMTY3LzI5Njk3ODAwMS02MjdmMWExZi0wOTFiLTQ0NmMtODAzMC1jYTlmNmY2MDRlOTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTZUMDgyMjMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzhjYzhjZGQ4YjVmYTM5MGY3YjUxMWI2OWI4NzBjY2Q3MWQwNWQ1ODkzOWNiZDliMDUxZTlkMTkwOTM1ZDdiZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4F_gNg8QH8mZqAh2wQoMwRMvWGMXoNyxz2xWFRjBuvk)
> 
> Click on the entire label, a pop-up is shown with information about the workspace link.
> 
> ![slack-workspace-specific](https://private-user-images.githubusercontent.com/2650167/296977342-4eef5bde-04ac-4f3a-b25e-5650116b833f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzOTM2NTIsIm5iZiI6MTcwNTM5MzM1MiwicGF0aCI6Ii8yNjUwMTY3LzI5Njk3NzM0Mi00ZWVmNWJkZS0wNGFjLTRmM2EtYjI1ZS01NjUwMTE2YjgzM2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTZUMDgyMjMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDFmMDRlYTVjMzA1Nzg0NThkYTY3MWVlNmM1YzhhZDRlMWQ2NzAzNTAyNzQ3ZGYxNDVkYmYyMTdmMDFjNWEwZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.FMjrMZkZEb6jqBX88wsAGRMrGtfJDSxYSQ8FP9U-sdA)

Wow, I feel stupid not realizing that. It works now. Thanks for the help @knumskull  and @vraravam
