### ISSUE TITLE
High RAM Usage on Windows

### ISSUE THREAD

**Issue by 8227846265** [ferdium/ferdium-app#1459]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.6.0

### What Operating System are you using?

Windows

### Operating System Version

Windows 11 23H2 (OS Build: 22631.2715)

### What arch are you using?

x64

### Expected Behavior

Low RAM usage

### Actual Behavior

High RAM usage

### Steps to reproduce

Install and run the following application on Ferdium:
- Google Messages
- WhatsApp
- Discord
- Zoho Mail

And the RAM usage with these apps is equivalent to Brave running 29 tabs.

### Debug link

https://debug.ferdium.org/162c710b-0ec2-494c-b6ca-ccb183ce6415

### Screenshots

![image](https://github.com/ferdium/ferdium-app/assets/66582769/7cca75b1-74cd-4d53-b67b-9b2915db0693)

### Additional information

Version: 6.6.0
Server: Ferdium Server
Electron: 27.0.1
Chrome: 118.0.5993.89
Node.js: 18.17.1
Platform: Windows 11
Arch: x64
Build date: Fri Oct 27 2023 08:32:03 GMT+0800
Git SHA: d157b865
Git branch: release

**Comment by vraravam** [comment]
Please try with the latest nightly 6.7.1-nightly.8 - we have upgraded to the latest released version of electron.
Unfortunately, the RAM usage depends on different characteristics - like the number of active services, the version of electron (which in turn brings in specific version of chrome), etc. As can be surmised, we are dependent on the upstream and the user for such things, and don't control anything independently on our side.
