### ISSUE TITLE
Wayland implemented in latest nightly only for Snap?

### ISSUE THREAD

**Issue by meiphoo7-Mae** [ferdium/ferdium-app#1462]
### Your issue

I saw that with pull request 1456 Wayland native support was implemented in the latest nightly.
Question: Is this only applicable to the Snap version?

If yes: you can ignore this question.

If no: it looks like there's something going wrong, because when Ferdium is started with certain switches in the launcher to invoke Wayland the titlebar looks like:
![Screenshot_20231201_071207](https://github.com/ferdium/ferdium-app/assets/95827976/6c080ec3-6d7e-42e9-8c49-c5a4ca1d1dfd)
The yellow icon with the white 'W' left shows it is running in Wayland mode.

However when Ferdium is started without switches in the launcher, the titlebar looks like:
![Screenshot_20231201_070813](https://github.com/ferdium/ferdium-app/assets/95827976/56e7d1b2-29ea-4357-9d91-f5f9462b61c9)
The gray-ish icon with the black 'X' left shows it is running in XWayland mode (technically X11).

Note: I assume it is supposed to show the moustache icon there but somehow that isn't working when Kubuntu is running in Wayland mode (which has something to do with Electron, if I recall correctly), when Kubuntu is running in X11 mode the moustache icon is shown.
Any way..., in this case it is a good test to detect if Wayland is used.

**Comment by mcmxcdev** [comment]
It was only implemented for Snap, see https://github.com/ferdium/ferdium-app/blob/develop/electron-builder.yml#L13C6-L13C6

These are the related PRs:
- https://github.com/ferdium/ferdium-app/pull/1455
- https://github.com/ferdium/ferdium-app/pull/1456

**Comment by meiphoo7-Mae** [comment]
Thank you. 
I'll close this issue.
