### ISSUE TITLE
Request For Click To Send ((or similar))

### ISSUE THREAD

**Issue by JennyTanSecretary** [ferdium/ferdium-app#1463]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22enhancement+%3Asparkles%3A%22) for a feature request that matches the one I want to file, without success.

### Problem Description

ClickToChat      https://play.google.com/store/apps/details?id=com.trianguloy.openInWhatsapp&pli=1  

We use it when we want to quickly contact a whats app user without actually going thru the process of adding to whats app. Very useful when one is simply saying HI or Thanks tosomeone you are unlikely to keep in contacts and also for things like respond to rental ads or buying online. As long as they have a WhatsApp number the App opens up WA and we can talk. After the conversation ends there is no contact stored inside WAPP .. so keeps my contact list "only for genuinly needed contacts" my contact jennytansecretary@outlook.com thanks Jenny 

### Proposed Solution

Can it be added or is alterantive available?

### Alternatives Considered

I have not seen alternative on Ferdium

### Additional Information

Thanks Jenny

**Comment by vraravam** [comment]
you can create a custom service with the above as the serviceUrl - and it might work (I haven't tried this).

That being said, Ferdium is only going to show/expose the web-based ui for different services - we don't create our own nor do we host any intermediate web pages. Closing this request.
