### ISSUE TITLE
Authorize Bitwarden to fill our account access

### ISSUE THREAD

**Issue by McFlyPartages** [ferdium/ferdium-app#1468]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22enhancement+%3Asparkles%3A%22) for a feature request that matches the one I want to file, without success.

### Problem Description

Hy,

Automatic account filling via Bitwarden

### Proposed Solution

I'd like to know if it's possible to give Bitwarden the ability to fill in our login details (in the application I'm talking about) because otherwise it requires some pretty repetitive copying and pasting (cf Home Assistant, etc).

### Alternatives Considered

empty

### Additional Information

I discovered Ferdium after the end of Hamsket and I find the service very nice.

Thanks and good job

**Comment by mydarkstar** [comment]
Hi @McFlyPartages, glad you enjoy Ferdium!

This is sadly not possible with Bitwarden and also entirely out of scope for us.

I recommend you to install Bitwarden's browser extension instead, and use it to fill-in your login details on websites:
https://bitwarden.com/download/#downloads-web-browser

For non-browser applications, you will sadly have to live with copy pasting the password.
Not even the official Bitwarden apps support this.

**Comment by zommuter** [comment]
Would be solved with #135
