### ISSUE TITLE
Pencil Pecipe

### ISSUE THREAD

**Issue by KAGEYAM4** [ferdium/ferdium-app#1470]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+request+%3Asparkles%3A%22) for a recipe request that matches the one I want to file, without success.

### Name of the service

Pencil

### URL of the service

http://pencil.evolus.vn/

### GitHub URL to a recipe that has already been created by someone else or you

https://github.com/evolus/pencil

### Features you want implemented

Complete Pencil support in ferdium.

**Comment by SpecialAro** [comment]
@KAGEYAM4 thank you for logging this service request but, unfortunately, Pencil doesn't have a web-app so it won't be possible to integrate it on Ferdium.
