### ISSUE TITLE
SOGo

### ISSUE THREAD

**Issue by packermann76** [ferdium/ferdium-app#1472]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+request+%3Asparkles%3A%22) for a recipe request that matches the one I want to file, without success.

### Name of the service

SOGo

### URL of the service

https://www.sogo.nu/

### Features you want implemented

SOGo is an open source GroupWare which provides also native ActiveSync support. It is as well shipped as the standard webmailer with mailcow (https://mailcow.email/de/).
Even though it can be used within Ferdium as a custom website, notifications and message-badge would be great to have.

**Comment by SpecialAro** [comment]
Hello @packermann76 and thank you for logging this recipe request.

The URL of the service should point to the webapp instance. As far as I understood, SOGO (probably) provides a webapp but it is only self-hosted. Is that the case? Can you point me to an example website that has the SOGO frontend for mail?

Thank you very much

**Comment by packermann76** [comment]
Hi @SpecialAro ,

you're correct, SOGo provides a webapp and can be self-hosted. On the SOGo project-page you can find an online-demo (https://www.sogo.nu/ , scroll down to find the link and demo-credentials).
Another possibility would be mailcow (https://mailcow.email/). They have as well an online-demo with Sogo deployed, alternatively mailcow can easily be deployed on a docker-host, it comes with easy to use deployment-scripts.
If none of these options work out for you, please ping me and I could setup you an account on my own instance.

**Comment by packermann76** [comment]
@SpecialAro huge thanks for providing this recipe that fast! Just included it in my installation and can confirm, it just works!

**Comment by SpecialAro** [comment]
You're welcome 😁

Let me know if there is something wrong!
