### ISSUE TITLE
Instagram Doesn't Show Unread Message Badge

### ISSUE THREAD

**Issue by Arthur-Huan** [ferdium/ferdium-app#1475]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+%3Abookmark_tabs%3A%22+label%3A%22bug+%3Abeetle%3A%22+) for a bug report that matches the one I want to file, without success.

### Ferdium Version

6.6.0

### Recipe Name

Instagram

### Recipe Version

2.5.2

### Last Known working version of the recipe

None

### Steps to reproduce

1. Open Instagram
2. (Use default settings, show unread message badges)
3. Receive a new DM

### Expected Behavior

There should be a badge (of the number of new messages) on the service icon within the app, as well as a red dot on the system tray icon.

### Actual Behavior

Nothing. Clicking in, you will on the website when you receive a new message, but the Ferdium app doesn't tell you.

**Comment by Mralexandresys** [comment]
hello @Arthur-Huan 

this was corrected in version 2.5.3 instagram and 1.1.2 for instagram-direct-messages. Do you have this version?

**Comment by Arthur-Huan** [comment]
@Mralexandresys I just forgot to pull. It works perfectly, thank you!
