### ISSUE TITLE
[Bug-Recipe] Element/Matrix

### ISSUE THREAD

**Issue by angeousta** [ferdium/ferdium-app#1479]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+%3Abookmark_tabs%3A%22+label%3A%22bug+%3Abeetle%3A%22+) for a bug report that matches the one I want to file, without success.

### Ferdium Version

6.6.0

### Recipe Name

Element/Matrix

### Recipe Version

1.4.0

### Steps to reproduce

Log into a service (matrix/element)

### Expected Behavior

It works

### Actual Behavior

"Session data missing"

Dati di sessione mancanti
Alcuni dati di sessione, incluse le chiavi dei messaggi cifrati, sono mancanti. Esci e riaccedi per risolvere, ripristinando le chiavi da un backup.

Probabilmente il tuo browser ha rimosso questi dati per mancanza di spazio su disco. Per aiutarci a prevenire questa cosa in futuro, inviaci i log.

### Screenshots

![immagine](https://github.com/ferdium/ferdium-app/assets/132761637/39a8d834-2efe-45c6-bc07-7a480e7fc1ff)

**Comment by Cknight70** [comment]
This happens to me too when the session data gets too large. This can also happen in the official desktop electron app for element, as well as browser, so it is not a Ferdium specific problem, though very annoying. 

Clearing your cache inside of element (element all settings> help and about> clear cache and reload at the bottom) once a month should prevent this, as well as having a backup session in your browser or official desktop app which you should open once a month to download data and keys to prevent any loss.

**Comment by Cknight70** [comment]
If you want this issue fixed I would look to https://github.com/element-hq/element-web

**Comment by vraravam** [comment]
thanks for the research @Cknight70 . Closing since this is not specific to Ferdium
