### ISSUE TITLE
Google Voice: no notification on text message

### ISSUE THREAD

**Issue by dchmelik** [ferdium/ferdium-app#1483]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+%3Abookmark_tabs%3A%22+label%3A%22bug+%3Abeetle%3A%22+) for a bug report that matches the one I want to file, without success.

### Ferdium Version

6.6

### Recipe Name

Google Voice

### Recipe Version

.6.1

### Steps to reproduce

1. Receive text message.

### Expected Behavior

Notify (in system tray).

### Actual Behavior

Even when notifications are left on, doesn't notify on receipt of text message.

**Comment by oc013** [comment]
This should be fixed in 0.6.2 https://github.com/ferdium/ferdium-recipes/pull/449 which was included in https://github.com/ferdium/ferdium-app/releases/tag/v6.6.1-nightly.7

**Comment by dchmelik** [comment]
Indeed it is.

**Comment by elderlabs** [comment]
I believe this issue has resurfaced in 7.2.2. I appear to be receiving notifications from other items, but not from Google Voice. Notifications are enabled, thus I am at a loss.

EDIT: rolled back to 7.1.2 and notifications are functional.
