### ISSUE TITLE
whatsapp changes language

### ISSUE THREAD

**Issue by iibrahimc** [ferdium/ferdium-app#1486]
### Your issue

Whatsapp changes language... When I refresh it, sometimes it gets better, sometimes it gets better after a few times. The language I use is Turkish.

**Comment by vraravam** [comment]
That doesn't seem to be an issue with Ferdium.

Also, please use the template to fill out all details while logging bugs - otherwise, its quite impossible for the maintainers and other contributors to guess your OS/arch, ferdium version, etc.
