### ISSUE TITLE
Gmail Unread Label Double Counting

### ISSUE THREAD

**Issue by jimmylad** [ferdium/ferdium-app#1496]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.7.0

### What Operating System are you using?

macOS

### Operating System Version

Ventura 13.5

### What arch are you using?

x64

### Expected Behavior

1 unread email shows 1 on the unread count

### Actual Behavior

The unread count is 2 for each unread email

### Steps to reproduce

Receive email

**Comment by jovanovski** [comment]
In my case, my private Gmail account is fine, but the Google Workplace Gmail account is counting double. Could be because of that type not being tested?

**Comment by jimmylad** [comment]
@jovanovski Yes I have 2 Workplace accounts so that makes sense

**Comment by enx1998** [comment]
Hi,
I have the same issue with a business Google Workplace Gmail account:
<img width="132" alt="image" src="https://github.com/ferdium/ferdium-app/assets/20546217/07e757ef-34c9-49ef-a33d-b7639ee6cd0c">

Thanks, ENx

**Comment by brc64** [comment]
I'm having the same issue with both a Google Workspace and a personal Gmail account. I first noticed it about a week ago. I've tried reloading as well as toggling unread message badges off and on, but it hasn't seemed to make a difference.

**Comment by jimmylad** [comment]
Yes the recipe code is wrong and needs updating.

**Comment by jimmylad** [comment]
I have managed to fix this by changing the gmail webview.js line 21 here

`const spaceAndChatBadges = document.querySelectorAll('span.XU.aH6');`

to 
`const spaceAndChatBadges = document.querySelectorAll('div.Xa.bSyoAf span.XU');`

This is just me hacking, could someone check it please?

**Comment by compi-tom** [comment]
![image](https://github.com/ferdium/ferdium-app/assets/98018447/1082cc6f-015d-4e26-af3f-a7555b2e7c81)

Your fix seems to be working. Thanks :+1: 

FYI : Ferdium 6.7.0, deb install on Ubuntu 22.04, using a Google Workspace account.

> I have managed to fix this by changing the gmail webview.js line 21 here
> 
> `const spaceAndChatBadges = document.querySelectorAll('span.XU.aH6');`
> 
> to `const spaceAndChatBadges = document.querySelectorAll('div.Xa.bSyoAf span.XU');`
> 
> This is just me hacking, could someone check it please?

**Comment by vraravam** [comment]
thanks @jimmylad  - i have raised a PR with your fix.

**Comment by marmotz** [comment]
In last nightly ([6.7.1-nightly.23), i've always this bug.

**Comment by lesourcil** [comment]
Me too
