### ISSUE TITLE
Window actions location wrong (hide, maximize, close)

### ISSUE THREAD

**Issue by 127001** [ferdium/ferdium-app#1508]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.7.0

### What Operating System are you using?

Ubuntu

### Operating System Version

Ubuntu 23.10

### What arch are you using?

x64

### Expected Behavior

The minimize, maximize and close icons in the top bar should be in the top right corner. 

Or, if relevant, follow the settings of the OS. In my case that is the default top right.

### Actual Behavior

The minimize, maximize and close icons in the top bar are in the top left corner.

### Steps to reproduce

1. Start Ferdium
2. Notice the icons.

### Screenshots

![image](https://github.com/ferdium/ferdium-app/assets/149222/00562502-b5bb-4366-a16f-9bb32c05b2b4)

### Additional information

This could be related to [#1456](https://github.com/ferdium/ferdium-app/pull/1456). Noticed in the screenshots of that PR that the icons switched from right to left.

**Comment by 127001** [comment]
Tried the suggestion from #1456 to switch back to XWayland and this puts the actions to the right again.

`snap set ferdium wayland-native=false`

**Comment by vraravam** [comment]
Thanks for the updaet @127001 . Closing the issue since it seems specific to your local setup ie wayland being turned on or off (though the mechanism to toggle from the command-line is useful for future reference). Thanks!
