### ISSUE TITLE
Messenger Dark Mode not applied properly to chat background

### ISSUE THREAD

**Issue by TaureHorn** [ferdium/ferdium-app#1519]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+%3Abookmark_tabs%3A%22+label%3A%22bug+%3Abeetle%3A%22+) for a bug report that matches the one I want to file, without success.

### Ferdium Version

6.7.0

### Recipe Name

Messenger

### Recipe Version

1.8.2

### Steps to reproduce

Enter a chat in Messenger with service dark mode enabled

### Expected Behavior

Chat background should be a dark colour in line with the rest of the ui panels

### Actual Behavior

Chat background is a solid white and doesn't change on toggling dark mode or service reload or Ferdium reload

### Screenshots

![ferdium](https://github.com/ferdium/ferdium-app/assets/6367950/ff742931-035c-466f-a5e9-17d5ad490de0)

### Additional Information
Fedora 39 KDE, Wayland
Installed through Flatpak

After trawling through messenger's annoyingly obfuscated classes I was able to find a variable to control the background 
` --mwp-message-row-background:`
I added that to the darkmode.css for messenger and now controls the chat background colour.
```
:root,
.__fb-light-mode {
    ...
    --mwp-message-row-background: #000000;
    ...
}
```

**Comment by nexxai** [comment]
Seeing the same thing here too.

**Comment by jovanovski** [comment]
> --mwp-message-row-background: #000000;

Nice find! I would swap this with `#1e1e1e`, if you're aiming for the previous color that was used before they updated it.

**Comment by gmnstr** [comment]
Having the same issue on Apple Silicon macOS Ventura 13.6.3.

**Comment by Julian88Tex** [comment]
Looks like someone already made the update here. Here are the steps I took to fix it on Mac:

1. Open Finder
2. Go to (CMD + SHIFT + G) by pasting this in `/Users/julianjoseph/Library/Application Support/Ferdium/recipes/messenger/`
3. Open `darkmode.css` in a text editor
4. Paste in code here: https://github.com/ducfilan/Dark-mode-Franz-Ferdi/blob/master/messenger/darkmode.css
5. Save
6. Refresh Messenger Service in Ferdi (CMD + R)

**Comment by SpecialAro** [comment]
This issue should be fixed in the latest nightly as per https://github.com/ferdium/ferdium-recipes/pull/494

Closing this issue. Thank you!
