### ISSUE TITLE
Ferdium Help menu has broken options  

### ISSUE THREAD

**Issue by stormy1777** [ferdium/ferdium-app#152]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.36

### What Operating System are you using?

Windows

### Operating System Version

Win10

### What arch are you using?

x64

### Expected Behavior

Proper URLs be opened for:

Help->Support 
Help->Terms of Service
Help->Privacy Statement

### Actual Behavior

Instead for Support, goes to: https://ferdium.org/contact (404, page not found)
other two attempt to find/upload/select a file??

### Steps to reproduce

Help->Support 
Help->Terms of Service
Help->Privacy Statement

**Comment by SpecialAro** [comment]
Hi @stormy1777 , thank you for raising this issue.

The only problem I find is in Help > Support given that https://ferdium.org/contact is not yet defined (https://github.com/ferdium/website should take care of that, maybe you can make an issue there?).

Both Terms and Privacy go to, as expected:
![image](https://user-images.githubusercontent.com/37463445/168492822-9227e4cb-761c-4467-94eb-7dbf55e0d884.png)
![image](https://user-images.githubusercontent.com/37463445/168492831-b3634a41-7353-42c6-a4e1-ee270fe3d9da.png)

Can you please confirm this again?

**Comment by stormy1777** [comment]
Opened: https://github.com/ferdium/website/issues/10

As for the terms and Privacy statement, that's not what I'm seeing.. Windows 10, latest nightly, it opens the Explorer "this PC" window almost as if it wants to UPLOAD a file... clicking any random text file, just OPENS it....  maybe they are missing somehow on my env/install ? (I did an installer msi installation, which ferdi was still installed, now since removed Ferdi).

**Comment by SpecialAro** [comment]
> Opened: [ferdium/website#10](https://github.com/ferdium/website/issues/10)

Thank you @stormy1777 !



> it opens the Explorer "this PC" window almost as if it wants to UPLOAD a file

Do you have a default browser set up on Windows? Maybe that's the fault. I've not experienced this on any OS so far (tested on Windows)

EDIT: macOS seems not to be able to open them as well. I'll try to look into it tomorrow! Thank you!

**Comment by stormy1777** [comment]
This is Win10, def browser is set to Firefox (older version, but still, there is a default listed), isn't there a more bullet proof way to open using the already used "chromium" browser that's at the heart of the Ferdium app? regardless of default browser setting or if it is "supported" or not...

**Comment by SpecialAro** [comment]
Tested again on Windows but now with the latest nightly. I'm seeing the same issue as you say @stormy1777 - The explorer opens.

**Comment by SpecialAro** [comment]
Managed to do some research and found out that this only happens if you are not connected to an API account.
This is given the fact that both Terms of Service and Privacy Statement are API dependent.
