### ISSUE TITLE
Cant sign into any google service

### ISSUE THREAD

**Issue by nickchomey** [ferdium/ferdium-app#1526]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.7.1-nightly.7

### What Operating System are you using?

Windows

### Operating System Version

Windows 11 22635.3061

### What arch are you using?

x64

### Last Known Working Ferdium version

I dont think Ferdium broke - Gmail changed

### Expected Behavior

Be able to sign into Gmail

### Actual Behavior

Cant sign in. 
```
Couldn’t sign you in
This browser or app may not be secure. [Learn more](https://support.google.com/accounts/answer/7675428?hl=en-US)
Try using a different browser. If you’re already using a supported browser, you can try again to sign in.
```

### Steps to reproduce

1. Add Gmail service
2. enter email address
3. Click next

### Debug link

https://debug.ferdium.org/84f8b9ee-423a-4bbc-8a2a-7b6815b807f1

### Screenshots

![image](https://github.com/ferdium/ferdium-app/assets/88559987/2eb3c224-6323-445f-8fe3-975771167430)

### Additional information

I have tried rolling back to v6.7.0 but that doesnt help. I think something changed with how gmail validates the browser. 
I also tried changing my user agent to match what is shown at `https://whatmyuseragent.com/`

Version: 6.7.1-nightly.7
Server: No Server
Electron: 28.1.3
Chrome: 120.0.6099.199
Node.js: 18.18.2
Platform: Windows 11
Arch: x64
Build date: Sat Jan 13 2024 18:54:01 GMT-0600 (Central Standard Time)
Git SHA: 0d657a10
Git branch: nightly

**Comment by vraravam** [comment]
please try other combinations for the user-agent. Google and Meta are known for such changes, which break the users of Ferdium and related alternatives. Unfortunately, we cannot do anything on our side.

**Comment by nickchomey** [comment]
Ok thanks. Any suggestions of a user agent that I can try, such as whatever one you're using?

**Comment by nickchomey** [comment]
Also, surely this isn't the problem - again I'm using the same user agent within Ferdium as I'm successfully using in my browser. There must be something unique to Ferdium that is causing this problem

**Comment by nickchomey** [comment]
I tried setting the user agent to https://accounts.google.com/, as per the solution in #1179

Likewise, using FerdiumApp - as per #1414 - works

It seems as if you can use anything except for an actual, legitimate user agent...

**Comment by opita04** [comment]
> I tried setting the user agent to https://accounts.google.com/, as per the solution in #1179
> 
> Likewise, using FerdiumApp - as per #1414 - works
> 
> It seems as if you can use anything except for an actual, legitimate user agent...

When trying this to log into X.com,and tried the account.google.com I get This browser is no longer supported.
Please switch to a supported browser to continue using x.com. You can see a list of supported browsers in our Help Center.

**Comment by vraravam** [comment]
> When trying this to log into X.com,and tried the account.google.com I get This browser is no longer supported. Please switch to a supported browser to continue using x.com. You can see a list of supported browsers in our Help Center.

That's the website (x.com) doing some inference based on the user agent being sent across with the request. You can change the user-agent in Ferdium either globally or per-service. Please try that feature out and report back as to what combination of user-agent strings worked for you. Usually, a plain vanilla Chrome or Firefox for Windows OS is the most supported on most sites that do this kind of strangling.
