### ISSUE TITLE
require is not defined when run source code

### ISSUE THREAD

**Issue by joeylin** [ferdium/ferdium-app#1529]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.7.1-nightly.7

### What Operating System are you using?

macOS

### Operating System Version

macos m2

### What arch are you using?

x64

### Expected Behavior

can show page ui

### Actual Behavior

have errors: 
![image](https://github.com/ferdium/ferdium-app/assets/2030833/c1c7b65c-ce3e-4f99-8e09-c419b6715bb6)
when run command: 
npm run dev

### Steps to reproduce

1. npm install
2. npm run dev

### Screenshots

![image](https://github.com/ferdium/ferdium-app/assets/2030833/86a163e7-954a-4daa-9c8d-8286d466f655)

**Comment by SpecialAro** [comment]
Hello, I see that you are trying to build using `npm` - we are currently using `pnpm` to handle packages.

Please follow https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md#setting-up-your-development-machine as it indicates the necessary steps to build from source.

Thank you!

**Comment by joeylin** [comment]
@SpecialAro thanks very much.

my machine is macos, I can not see any guide about mac os on the doc: https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md#setting-up-your-development-machine

does it mean development on macos is not supported ？

**Comment by joeylin** [comment]
I dont know why, but I can not run the code on my mac machine, there are many errors
![image](https://github.com/ferdium/ferdium-app/assets/2030833/5e9c30d3-ea98-42c7-aadd-524c082f4034)

**Comment by joeylin** [comment]
@SpecialAro cloud you pls reopen this issue ?

**Comment by SpecialAro** [comment]
@joeylin I closed this issue not to bloat the issue board with issues that are not related with bugs/features but are support requests.


I see that you already posted on Discord (that's the quickest way to get support) so let's chat there to fix this 😁

Nevertheless, macOS is a UNIX certified system, so you should build using the script `build-unix.sh`

Also, if you running the commands manually (without the script) then the sequence would be to first install the packages (`pnpm i`) and then to run `pnpm debug`. `pnpm start` is just used to run the app after building it (so you would need to build first), you shouldn't be needing to run this program while working on code.

For security reasons, it is highly recommend that you do not use `sudo` while running node applications. You are giving root access to the application, which is generally not needed.
