### ISSUE TITLE
Slack's latest version catches Ctrl+Tab action and opens a new window in browser

### ISSUE THREAD

**Issue by reggermont** [ferdium/ferdium-app#1543]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.7.0

### What Operating System are you using?

Other Linux and Windows 10

### Operating System Version

Linux arch 6.7.0-arch3-1 #1 SMP PREEMPT_DYNAMIC Sat, 13 Jan 2024 14:37:14 +0000 x86_64 GNU/Linux

### What arch are you using?

x64

### Last Known Working Ferdium version

None

### Expected Behavior

Ferdium doesn't send the "Ctrl+Tab" action to any workspace, keeping it for itself

### Actual Behavior

Slack's latest version catches Ctrl+Tab action and opens a new window in browser, not able to switch services anymore with the hotkey

### Steps to reproduce

1. Have multiple tabs with Slack in the middle
2. Do "Ctrl+Tab" multiples times
3. When Slack is focused and "Ctrl+Tab" is pressed, it opens the Slack workspace in the browser

**Comment by leoheck** [comment]
Nice, came here to report the same. Thanks dude.

**Comment by stedwick** [comment]
This is quite annoying. I don't believe Slack should hijack the control-tab hotkey; that's standard by the browser to switch tabs.

**Comment by stedwick** [comment]
sorry I actually thought I was reporting a slack bug =P

**Comment by leoheck** [comment]
It looks like it is fixed now.

**Comment by reggermont** [comment]
Fixed on my Linux, didn't try in my Windows but I will consider it as globally fixed. Will re-open if needed
