### ISSUE TITLE
Add Signal please

### ISSUE THREAD

**Issue by natedean85** [ferdium/ferdium-app#1552]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22enhancement+%3Asparkles%3A%22) for a feature request that matches the one I want to file, without success.

### Problem Description

I would love to be able to use my Signal account on this app. This app is awesome btw.

### Proposed Solution

https://www.signal.org/#signal is the site, 
![Screenshot from 2024-02-01 04-45-09](https://github.com/ferdium/ferdium-app/assets/157776882/da01af25-b774-445e-9785-82fe55aebaf2)
instructions to install on Linux from https://www.signal.org/download/

### Alternatives Considered

Just like having all my messegaing in one place, and this app is great for that. I use Signal because of the end-to-end encryption of the messaging.

**Comment by SpecialAro** [comment]
I'm sorry but signal doesn't provide a web app, which is a requirement for integrating it in Ferdium. Therefore I must close this issue
