### ISSUE TITLE
Proxmox not working

### ISSUE THREAD

**Issue by Cris70** [ferdium/ferdium-app#1569]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.7.0

### What Operating System are you using?

Other Linux

### Operating System Version

openSUSE Tumbleweed 20240209

### What arch are you using?

x64

### Last Known Working Ferdium version

n/a

### Expected Behavior

Ferdium should show the Proxmox web UI

### Actual Behavior

Ferdium shows a blank page or an eternal "Loading Proxmox" screen

### Steps to reproduce

1. add the proxmox web ui address as a new "Custom website"
2. click on the new service icon
3. Ferdium shows a blank page or an eternal "Loading Proxmox" screen

### Debug link

https://debug.ferdium.org/9e69e13a-df77-46d6-bb45-04d7053b498a

### Screenshots

![immagine](https://github.com/ferdium/ferdium-app/assets/5107224/fd7c34ab-6e3c-4372-bc5e-44b725576659)

### Additional information

The Proxmox web ui I want to add uses a self-signed certificate, so - in a normal browser - it is necessary to accept the risk to continue

**Comment by SpecialAro** [comment]
Hello @Cris70,

If you can, please update to the latest nightly (pre-releases) and go to Settings and Privacy (or security, I cannot check atm) tab and you will see a feature to add your own self-signed certs.

If you prefer to keep Ferdium at a stable version, just wait for the next stable release (probably next week) to have this feature.

Also, make sure you Edit that service and add the URL back (as it seems to not be present)


Let me know if that works out for you 😉

**Comment by Cris70** [comment]
@SpecialAro thank you!
I downloaded the latest nightly and followed your instructions.
It worked perfectly!!
