### ISSUE TITLE
Google Voice - No audio after call connects

### ISSUE THREAD

**Issue by chucksense** [ferdium/ferdium-app#1575]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+%3Abookmark_tabs%3A%22+label%3A%22bug+%3Abeetle%3A%22+) for a bug report that matches the one I want to file, without success.

### Ferdium Version

6.7.0

### Recipe Name

Google Voice

### Recipe Version

0.6.2

### Last Known working version of the recipe

Not since I switched from Franz, but not sure.

### Steps to reproduce

1. Make a call
2. Hear the call ringing
3. When the call is picked up, I can hear nothing and the other end cannot hear me

I've tried multiple numbers, cell phone, landline, etc, none are working.

### Expected Behavior

I can hear caller on other end and caller on other end can hear me.

### Actual Behavior

Neither party can hear the other.

### Additional Information

1. macOS 14.2.1
2. Ferdium has Microphone access enabled in Privacy & Security
3. Enable audio is enabled in the Service's settings
4. I've tried toggling Enable Media Play Indicator on and off and it doesn't work with either setting

**Comment by SpecialAro** [comment]
Hello @chucksense, please try the following:
https://github.com/ferdium/ferdium-app/issues/611

**Comment by chucksense** [comment]
Thank you @SpecialAro, I did not see that one in my searches.

Which is the least intrusive of the available options?  I tried this one:
![image](https://github.com/ferdium/ferdium-app/assets/199588/7866b8bd-1739-4c38-ae9e-45497288505b)

And it works now.  Is "public" IP in this case your VPN exit point and "local" IP your true IP? Or in the case of using a VPN is your "public" IP your actual non-VPN IP and "local" is your computer's IP on your local network?

I don't particularly care if Google Voice knows my true IP address when using a VPN, but there are some other services where I might not want that to be the case on a WebRTC connection.  Is there any consideration to making this a service-level config?

**Comment by SpecialAro** [comment]
Glad it worked out. I'm moving to close this issue if that is ok with you.

Please read the following:
https://help.herond.org/article/40-webrtc-ip-handling-policy

**Comment by ChaoticHolon** [comment]
I don't think this bug should have been closed (and should be re-opened), because while this workaround does work, because its a global setting it effectively exposes/leaks your IP globally in all Ferdium recipes/services. And we honestly need a per recipe solution that doesn't do this.
