### ISSUE TITLE
Bug: Slack opens thread images as url instead of preview

### ISSUE THREAD

**Issue by MagicLegend** [ferdium/ferdium-app#158]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.37

### What Operating System are you using?

Ubuntu

### Operating System Version

Linux <name> 5.13.0-41-generic ferdium/ferdium-app#46~20.04.1-Ubuntu SMP Wed Apr 20 13:16:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What arch are you using?

x64

### Expected Behavior

- Slack opens the thread, not the image url

### Actual Behavior

- The image gets opened, meaning you can't return to slack unless you reload the window

### Steps to reproduce

1. Open Slack
2. Click on an image to enlarge it

### Screenshots

Since this does work in Ferdi 5.8.0 I'm gonna assume something changed in Ferdium.

Ferdi 5.8.0:
![image](https://user-images.githubusercontent.com/3169104/168552973-49e363b3-5db2-41cc-948b-6c55a2c233f1.png)

Ferdium 6.0.0-nightly.37:
![image](https://user-images.githubusercontent.com/3169104/168553139-d7cfdfe5-619d-4d37-a67d-2aa13c151035.png)

### Additional information

This might be related to the redirect bugs specified in ferdium/ferdium-app#1007 .

_Edit:_

For images part of link previews it will actually go to that page instead of opening the preview.

**Comment by vraravam** [comment]
@MagicLegend - I have reverted the changes that I had done for ferdium/ferdium-app#1007 . Please test with the next nightly and check if this ticket can be closed.

**Comment by MagicLegend** [comment]
I can confirm that the revert of ferdium/ferdium-app#1007 fixes the issue. With Nightly 38 this issue is resolved.

**Comment by vraravam** [comment]
@all-contributors please add @MagicLegend  for bug
