### ISSUE TITLE
Reorder the services

### ISSUE THREAD

**Issue by pH142857** [ferdium/ferdium-app#1587]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.7.0

### What Operating System are you using?

Ubuntu

### Operating System Version

22.04

### What arch are you using?

x64

### Expected Behavior

In Settings > Services, I would expect to be able to change the order in which the services appear.

### Actual Behavior

Drag and drop does not work, and I see no other means to achieve this.

### Steps to reproduce

1. Go to settings
2. Click My Services
3. So no means of reordering the services

**Comment by SpecialAro** [comment]
Hi @pH142857, please drag and drop the services along the sidebar.

Closing this issue. Feel free to reply below if you can't manage to do it.

**Comment by slartibart70** [comment]
this does not seem to work properly in 6.7.1

drag and drop has reordered the services somewhat, but not to my taste :-)   
neither wayland nor x11 keeps the postion of the services i drag the icons to

Where can i find the config where the order is stored?

**Comment by slartibart70** [comment]
ahh... this does not work with workspaces !!!
only in 'all services'.... this should need a new bugticket, i think

see: #1611

**Comment by rauldipeas** [comment]
> ahh... this does not work with workspaces !!! only in 'all services'.... this should need a new bugticket, i think
> 
> see: #1611

I'm facing the same issue.

This works on some workspaces, maybe with a few apps (two or three).

**Comment by theAkito** [comment]
https://github.com/ferdium/ferdium-app/issues/146#issuecomment-2889022244

**Comment by Lewis8265** [comment]
I'm absolutely baffled why this isn't default behaviour. Very strange.
