### ISSUE TITLE
How to add Signal Messenger?

### ISSUE THREAD

**Issue by Cozynezz** [ferdium/ferdium-app#1591]
### Your issue

hey Guys,i  want to add the signal Messenger to ferdium.

At first, its not in the All services List, so i put the whole signal messenger folder in the dev folder, restart ferdium but nothing happens? what am I doing wrong?
![image](https://github.com/ferdium/ferdium-app/assets/147157684/ac714703-655f-4b49-a83f-127ea7e2c5a7)

**Comment by SpecialAro** [comment]
Please search the issue box before submitting new issues:
https://github.com/ferdium/ferdium-app/issues/1552

Closing as duplicate
