### ISSUE TITLE
When clicking it defaults to opening the webbrowser

### ISSUE THREAD

**Issue by pakyrs** [ferdium/ferdium-app#1596]
### Your issue

I am using a custom tab for N-Able Passportal, this silly website wants to open a new browser tab every time I click on something, since it seems Ferdium doesn't have tabs, it automatically forward the link to the webbrowser.

It's there a way to prevent this from happening? I can right click and select open within Ferdium but it's a lot of clicking to the already clickly stupid Passportal dashboard.

Any help appreciated.

P

**Comment by SpecialAro** [comment]
Hello @pakyrs,

You can right click on the service you want to prevent this from happening, click on `Edit` and then turn on the following option:
<img width="297" alt="image" src="https://github.com/ferdium/ferdium-app/assets/37463445/b63191af-c87a-46bd-8d17-8a9a860ba9b5">

This should work. If it doesn't, feel free to comment below. Thank you!

**Comment by pakyrs** [comment]
Thanks @SpecialAro you are a life saver! it was super simple, I somewhat overlooked it!
