### ISSUE TITLE
Microsoft Teams - V2 not working on Linux (Flatpak)

### ISSUE THREAD

**Issue by vampywiz17** [ferdium/ferdium-app#1597]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.7.0

### What Operating System are you using?

Other (specify below)

### Operating System Version

Zorin OS 17

### What arch are you using?

x64

### Last Known Working Ferdium version

-

### Expected Behavior

Start Teams with new UI

### Actual Behavior

Teams Start with classic UI, and no chance to change new one

### Steps to reproduce

1. Add Teams
2. Start it

### Debug link

https://debug.ferdium.org/0ca082da-12c3-499a-9b76-5333337ac649

### Screenshots

![image](https://github.com/ferdium/ferdium-app/assets/14281430/98629ee8-bd8b-46af-a38d-706ed0b04156)

### Additional information

In Windows version, the "change" option are seeable and working well.

**Comment by BioSs54** [comment]
Same problem here, im trying to create my own recipe but no success

**Comment by vampywiz17** [comment]
Now it workig, i get the option to switch V2 :)

**Comment by SpecialAro** [comment]
I can confirm that this is working properly on Ferdium. Please upgrade to the latest stable (sharescreen feature will only working on the next nightly though).
