### ISSUE TITLE
"New" Teams can't screenshare on Windows

### ISSUE THREAD

**Issue by Crashdummyy** [ferdium/ferdium-app#1598]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+%3Abookmark_tabs%3A%22+label%3A%22bug+%3Abeetle%3A%22+) for a bug report that matches the one I want to file, without success.

### Ferdium Version

6.7.1-nightly.24

### Recipe Name

Microsoft Teams

### Recipe Version

3.3.0

### Steps to reproduce

1. Add Microsoft Teams Service into Ferdium
2. Login
3. ( if not already ) enable the "new Teams experience"
4. Start a meeting
5. Try starting screenshare

### Expected Behavior

The Portal should open with the rtc dialog prompting for the window/display to capture.

### Actual Behavior

The Dialog does not appear and this gets logged into the console:

```
VM715:6 This document requires 'TrustedHTML' assignment.
(anonymous) @ VM715:6
await in (anonymous) (async)
window.navigator.mediaDevices.getDisplayMedia @ VM715:2
(anonymous) @ calling-pluginless-1aad1fad9b044fc9.js:1
Promise.then (async)
getStream @ calling-pluginless-1aad1fad9b044fc9.js:1
request @ calling-pluginless-1aad1fad9b044fc9.js:1
(anonymous) @ calling-pluginless-1aad1fad9b044fc9.js:1
Promise.then (async)
add @ calling-pluginless-1aad1fad9b044fc9.js:1
getStream @ calling-pluginless-1aad1fad9b044fc9.js:1
getOrCreateMediaStream @ calling-pluginless-1aad1fad9b044fc9.js:1
startStream @ calling-pluginless-1aad1fad9b044fc9.js:1
start @ calling-pluginless-1aad1fad9b044fc9.js:1
start @ calling-pluginless-1aad1fad9b044fc9.js:1
getMediaStream @ calling-pluginless-1aad1fad9b044fc9.js:1
getMediaStream @ calling-pluginless-1aad1fad9b044fc9.js:1
createDevicesHandle @ calling-pluginless-1aad1fad9b044fc9.js:1
getScreenHandle @ calling-pluginless-1aad1fad9b044fc9.js:1
startScreenSharing @ calling-pluginless-1aad1fad9b044fc9.js:1
executeInternal @ calling-pluginless-1aad1fad9b044fc9.js:1
checkPendingOperationAndExecute @ calling-pluginless-1aad1fad9b044fc9.js:1
execute @ calling-pluginless-1aad1fad9b044fc9.js:1
f @ calling-pluginless-1aad1fad9b044fc9.js:1
r.value @ calling-pluginless-1aad1fad9b044fc9.js:1
h @ 948843-0ee3c6ef3cc7c2bb.js:1
(anonymous) @ 948843-0ee3c6ef3cc7c2bb.js:1
(anonymous) @ v2/:1
d @ v2/:1
startScreenSharingOnCall @ 948843-0ee3c6ef3cc7c2bb.js:1
(anonymous) @ 855309-820851879f408fbf.js:1
Promise.then (async)
(anonymous) @ 855309-820851879f408fbf.js:1
startSharing @ 855309-820851879f408fbf.js:1
startSharing @ 855309-820851879f408fbf.js:1
(anonymous) @ 889975-3ac235ee37448f28.js:1
a @ v2/:1
Promise.then (async)
c @ v2/:1
(anonymous) @ v2/:1
d @ v2/:1
startSharing @ 889975-3ac235ee37448f28.js:1
Ie @ 512161-03fcfdccb1994194.js:1
he @ 512161-03fcfdccb1994194.js:1
(anonymous) @ 512161-03fcfdccb1994194.js:1
(anonymous) @ 512161-03fcfdccb1994194.js:1
(anonymous) @ 512161-03fcfdccb1994194.js:1
(anonymous) @ 512161-03fcfdccb1994194.js:1
fe @ 512161-03fcfdccb1994194.js:1
(anonymous) @ supermassive-incremental-link-c535598fa8225f98.js:1
Promise.then (async)
(anonymous) @ supermassive-incremental-link-c535598fa8225f98.js:1
(anonymous) @ async-entry-36674d553fd0a95b.js:30
e @ 624497-5c350f865d27eb99.js:1
t.subscribe @ 624497-5c350f865d27eb99.js:1
(anonymous) @ async-entry-36674d553fd0a95b.js:30
Promise.then (async)
(anonymous) @ async-entry-36674d553fd0a95b.js:30
e @ 624497-5c350f865d27eb99.js:1
t.subscribe @ 624497-5c350f865d27eb99.js:1
(anonymous) @ 461286-bff149ff789280e5.js:1
e @ 624497-5c350f865d27eb99.js:1
t.subscribe @ 624497-5c350f865d27eb99.js:1
complete @ 461286-bff149ff789280e5.js:1
t.start @ 461286-bff149ff789280e5.js:1
t @ 461286-bff149ff789280e5.js:1
e.getObservableFromLink @ 461286-bff149ff789280e5.js:1
(anonymous) @ 461286-bff149ff789280e5.js:1
(anonymous) @ 461286-bff149ff789280e5.js:1
(anonymous) @ v2/:1
(anonymous) @ v2/:1
(anonymous) @ v2/:1
d @ v2/:1
e.mutate @ 461286-bff149ff789280e5.js:1
e.mutate @ 461286-bff149ff789280e5.js:1
(anonymous) @ async-entry-36674d553fd0a95b.js:30
(anonymous) @ v2/:1
d @ v2/:1
mutate @ async-entry-36674d553fd0a95b.js:30
(anonymous) @ share-tray-337d0d03eaeeb157.js:1
(anonymous) @ v2/:1
d @ v2/:1
_startScreenshareFromCall @ share-tray-337d0d03eaeeb157.js:1
(anonymous) @ share-tray-337d0d03eaeeb157.js:1
(anonymous) @ v2/:1
d @ v2/:1
_onScreenSharingStarting @ share-tray-337d0d03eaeeb157.js:1
(anonymous) @ share-tray-337d0d03eaeeb157.js:1
(anonymous) @ v2/:1
d @ v2/:1
shouldCheckForOfficeWindowShareInterceptFlow @ share-tray-337d0d03eaeeb157.js:1
(anonymous) @ share-tray-337d0d03eaeeb157.js:1
(anonymous) @ v2/:1
d @ v2/:1
_onPreviewClicked @ share-tray-337d0d03eaeeb157.js:1
(anonymous) @ share-tray-337d0d03eaeeb157.js:1
(anonymous) @ 119579-568b6df4704e6f22.js:1
(anonymous) @ 119579-568b6df4704e6f22.js:1
Be @ 722183-a977a2d4c22ae7a6.js:1
Ke @ 722183-a977a2d4c22ae7a6.js:1
(anonymous) @ 722183-a977a2d4c22ae7a6.js:1
Pr @ 722183-a977a2d4c22ae7a6.js:1
Nr @ 722183-a977a2d4c22ae7a6.js:1
(anonymous) @ 722183-a977a2d4c22ae7a6.js:1
De @ 722183-a977a2d4c22ae7a6.js:1
(anonymous) @ 722183-a977a2d4c22ae7a6.js:1
Rr @ 722183-a977a2d4c22ae7a6.js:1
Jn @ 722183-a977a2d4c22ae7a6.js:1
Zn @ 722183-a977a2d4c22ae7a6.js:1
n.unstable_runWithPriority @ 722183-a977a2d4c22ae7a6.js:1
Hl @ 722183-a977a2d4c22ae7a6.js:1
Me @ 722183-a977a2d4c22ae7a6.js:1
Xn @ 722183-a977a2d4c22ae7a6.js:1

```

### Additional Information

~~My private PC with Linux on 6.7.6 + Wayland is not affected.~~
Affected on 6.8.2 Wayland/X11 as well

My company enforces the new teams tho where I am forced to use Windows.
It's Windows 10 22H2 as of now.
The screensharing worked using the "old" teams.

**Comment by geryduyck** [comment]
This is not a windows only issue! as I have the same problem on my MacBook Pro, MacOs 14.4
With the 'classic teams' no issue, with new teams I get an error message:
"Your video isn't working
We couldn't access your camera."

Camera and audio are working fine, so the error makes no sense at all...

**Comment by slartibart70** [comment]
same here, linux (fedora39) and wayland and teams/v2
pipewire-portal crashes, no screenshare (full screen, or indiv. windows) possible.
Same misleading error message as above , "Your video isn't working, We couldn't access your camera."

No problem with teams/v1 or with another browser (e.g. edge)

i also tried with 6.7.3/nightly.5 ... no change, still no screenshare possible

**Comment by HigHurtenflurst** [comment]
Same issue with 6.7.2, X11 and Teams v2 on Arch via the ferdium-bin package.

**Comment by Nerkho** [comment]
Yep having the same issue with Flatpak version on Fedora.

**Comment by bauxogeno** [comment]
same here with Linux Mint 20.2, ferdium 6.5.1

**Comment by Izak90** [comment]
same with ubuntu 22.04 ferdium 6.7.2

**Comment by carlcamilleri** [comment]
Same with Windows 11 Pro version 10.0.22621 Build 22621

**Comment by guilhermegps** [comment]
Same in Kubuntu 22.04

**Comment by nzeppos** [comment]
Not sure how these issue are prioritized, but I feel that this one should definitely get some attention. Teams v2 is gradually enforced by companies policies but without the ability to screenshare it is practically useless within Ferdium. Until yesterday I could at least revert to v1 but now it won't let me do that anymore.

**Comment by fernandobalieiro** [comment]
Same for me, company policy is being enforced for three weeks so far.

What I have been doing, as workaround, is to inspect the dialog below and remove its HTML block:
![image](https://github.com/ferdium/ferdium-app/assets/11398769/92845326-a041-4deb-b31c-2865d116d367)

**Comment by raqua** [comment]
+1

**Comment by bukajsytlos** [comment]
question is if this is issue with ferdium/electron or teams itself

**Comment by raqua** [comment]
@bukajsytlos When I open Teams in browser, it works fine for me. 

While doing that, I get asked by Teams to allow camera and microphone. I don't get that asked when I open Teams in Ferdium and I presume that might be the reason for this not working.

**Comment by vraravam** [comment]
Is it possible for someone to try to allow / approve the access to the camera even without ferdium prompting for it? Maybe that can provide a clue as to what's the root cause of the problem in ferdium/electron

**Comment by fastgunner** [comment]
Having the same issue on both Arch/x11 and MacOS.  I was not able to approve the camera access in ferdium, but I actually was able to reproduce the issue by denying the teams website access to my camera and microphone when prompted.  

The same behavior and error message occurred at that point.  If there is a way to approve it in Ferdium, please let me know the steps and I can try it to double confirm the issue.

**Comment by fernandobalieiro** [comment]
Hello @SpecialAro!
Thanks for the fix! I have been testing [6.7.4-nightly.2](https://github.com/ferdium/ferdium-app/releases/tag/v6.7.4-nightly.2) on Ubuntu 22.04 and the screen share now works.

Unfortunately, I have found two side-effects upon receiving a message:

1. The messages count doesn't appear anymore under the label of the service;
2. The system tray icon is not changing its color to red anymore:
![image](https://github.com/ferdium/ferdium-app/assets/11398769/2c4a72f4-57de-42d4-a26a-75c86b65a69e)

The desktop notifications seem to be working properly.

**Comment by SpecialAro** [comment]
Hello @fernandobalieiro,

Can you please log a new issue with those? I don't think they are related to the changes I made to the screen share feature.

If you can, please, tell us which services are not reporting (increasing the count).

Thank you so much!

PS: if you need further help (or if you can provide more information) ping me on Discord - I'm portuguese btw, if that helps 😁

**Comment by fernandobalieiro** [comment]
Hello @SpecialAro!

Thanks for answering :)
I have created the issue #1744.

OK, please, let me know if you need more information, so I can share with you.

Regards.
