### ISSUE TITLE
Superlist service addon would be nice

### ISSUE THREAD

**Issue by pecha2k2** [ferdium/ferdium-app#1601]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22enhancement+%3Asparkles%3A%22) for a feature request that matches the one I want to file, without success.

### Problem Description

Requesting this addon

### Proposed Solution

It's a web based addon so I think It would be easy to implement

### Alternatives Considered

No one at this moment

**Comment by SpecialAro** [comment]
Hello @pecha2k2, thank you for logging this service request.

To confirm, you are talking about this service: https://app.superlist.com/ am I right?

**Comment by pecha2k2** [comment]
Yes you are right and service would be welcomed
