### ISSUE TITLE
Ferdium 6.7.1 - Windows cannot access device path or file. Maybe you don't have rights to acces these item

### ISSUE THREAD

**Issue by mcrisostomo** [ferdium/ferdium-app#1609]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.7.1

### What Operating System are you using?

Windows

### Operating System Version

11

### What arch are you using?

x64

### Last Known Working Ferdium version

6.7.0

### Expected Behavior

Install and ferdium work as expected

### Actual Behavior

An alert windows opens tell that Windows cannot access installed files in my computer. I have noted that Ferdium.exe installed at C:\Program Files\Ferdium desn't have ferdium icon. Looks like it's a corrupted file.

### Steps to reproduce

- Install 6.7.1 version
- Try to open it

### Screenshots

![image](https://github.com/ferdium/ferdium-app/assets/7680268/20aae941-c8ff-4675-84a5-0176e061dd02)

**Comment by SpecialAro** [comment]
Hello @mcrisostomo, have you tried to download the file again?

**Comment by mcrisostomo** [comment]
Hi @SpecialAro. Yes and i have faced the same problem. I've decided to downgrade to v6.7.0 and it's working as well. But i can try again later

**Comment by mcrisostomo** [comment]
I'm closing this issue because i've tried to download it again and it worked without any problem. Thank you for the support
