### ISSUE TITLE
Ferdium not able to start on linux

### ISSUE THREAD

**Issue by I3lackEye** [ferdium/ferdium-app#1610]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.7.1-1

### What Operating System are you using?

Other Linux

### Operating System Version

Manjaro 6.6 KDE Plasma 5

### What arch are you using?

x64

### Expected Behavior

Ferdium app is supposed to start

### Actual Behavior

Ferdium app doesnt start

### Steps to reproduce

1. Either click Ferdium Icon in start menu or in write "ferdium" in CLI
2. App not starting

### Screenshots

![ferdium issue](https://github.com/ferdium/ferdium-app/assets/16986456/fc54c63b-ad64-4356-997b-610dc851bd7f)

**Comment by leadrien** [comment]
Same here on version 6.7.1. Also on Manjaro, Kernel 6.6.19 and Openbox

**Comment by SoyDiego** [comment]
Same problem in Manjaro after upgrade to last version:

```
OS: Manjaro Linux x86_64 
Host: GM6PX0X Standard 
Kernel: 6.6.19-1-MANJARO 
Uptime: 2 mins 
Packages: 1506 (pacman), 32 (flatpak), 13 (snap) 
Shell: zsh 5.9 
Resolution: 1920x1080, 1920x1080 
DE: Plasma 5.27.10 
WM: KWin 
WM Theme: Sweet-Dark 
Theme: [Plasma], Sweet-Dark-v40 [GTK2/3] 
Icons: Sweet-Rainbow [Plasma], Sweet-Rainbow [GTK2/3]
Terminal: kitty 
CPU: 13th Gen Intel i9-13900HX (32) @ 5.200GHz 
GPU: NVIDIA GeForce RTX 4060 Max-Q / Mobile 
GPU: Intel Raptor Lake-S UHD Graphics 
Memory: 3230MiB / 64039MiB 
```

**Comment by stanis64** [comment]
There is a problem in Manjaro  package electron29 from extra repository. According to this page: https://packages.manjaro.org/?query=electron29 is only in unstable branch.

Solution is to uninstall ferdium and electron29 package. After that install electron29-bin from AUR repository which works correctly. Now you can install ferdium again.

**Comment by mcmxcdev** [comment]
Seems to be Linux Manjaro-specific rather than an issue with Ferdium itself, closing.
