### ISSUE TITLE
Bug: Slack: Clicking on a @user link will crash the client with an invalid redirect

### ISSUE THREAD

**Issue by MagicLegend** [ferdium/ferdium-app#162]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.37

### What Operating System are you using?

Ubuntu

### Operating System Version

Linux <name> 5.13.0-41-generic ferdium/ferdium-app#46~20.04.1-Ubuntu SMP Wed Apr 20 13:16:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What arch are you using?

x64

### Expected Behavior

Getting shown the user profile

### Actual Behavior

The slack page reloads thinking it's doing a redirect and showing an error

### Steps to reproduce

1. Open Slack
2. Tag someone
3. Click on the blue `@asdf` tag

### Screenshots

![image](https://user-images.githubusercontent.com/3169104/168584164-cf7917a6-517f-42e3-93d8-545c357351f2.png)

### Additional information

As with ferdium/ferdium-app#158 , this works just fine in Ferdi 5.8.0.

The link HTML:

```html
<span dir="ltr" delay="150" data-sk="tooltip_parent">
    <a class="c-link c-member_slug c-member_slug--light c-member_slug--link " data-member-id="<MEMBER_ID>" data-member-label="@<NAME>" data-stringify-type="mention" data-stringify-id="<MEMBER_ID>" data-stringify-label="@<NAME>" tabindex="-1" aria-hidden="false" aria-haspopup="menu" aria-expanded="false" href="https://<TEAM>.slack.com/team/<MEMBER_ID>" rel="noopener noreferrer" data-remove-tab-index="true" data-tab-index-to-restore="0">@<NAME></a>
</span>
```

**Comment by vraravam** [comment]
@MagicLegend - this might also be fixed by my reverting of the change to the slack recipe. Please confirm and close with the next nightly.

**Comment by MagicLegend** [comment]
I can confirm that the revert of ferdium/ferdium-app#1007 fixes the issue. With Nightly 38 this issue is resolved.
