### ISSUE TITLE
WhatsApp service symetrical framing fit issue

### ISSUE THREAD

**Issue by ezekielar** [ferdium/ferdium-app#1664]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.7.2

### What Operating System are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

The inside frame should fit tightly.

### Actual Behavior

The inside frame has two unnecessary vertical bars annoying.

### Steps to reproduce

1. Select WhatsApp
2. See the issue mentioned

### Screenshots

![2 sided loss](https://github.com/ferdium/ferdium-app/assets/24434613/8f8320f3-3560-4716-a157-5d3fe2c256f4)

### Additional information

Version: 6.7.2
Server: No Server
Electron: 29.1.5
Chrome: 122.0.6261.130
Node.js: 20.9.0
Platform: Windows 10
Arch: x64
Build date: Sat Mar 23 2024 04:46:37 GMT+0300 (GMT+03:00)
Git SHA: ce7a8772
Git branch: release

**Comment by marcosins** [comment]
This is whatsapp itself not Ferdium.

Try disabling `max-width` using custom CSS:
- `.app-wrapper-web ._aigs`

Or use `CTRL` + `+` to Zoom In
