### ISSUE TITLE
Zoom Web Client

### ISSUE THREAD

**Issue by nicahokie** [ferdium/ferdium-app#1667]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+request+%3Asparkles%3A%22) for a recipe request that matches the one I want to file, without success.

### Name of the service

Zoom Web Client

### URL of the service

https://app.zoom.us/wc/home

### Features you want implemented

This is the web based client app (pwa?) of the zoom app for meeting hosts or guests.  It can leverage gpu acceleration reducing the strain on the cpu.  The current Zoom service is not as feature rich, it is just a meeting join page.

**Comment by vraravam** [comment]
Could you please use the recipe generator to generate the code and submit as a PR?
