### ISSUE TITLE
no longer can login to skype

### ISSUE THREAD

**Issue by dchmelik** [ferdium/ferdium-app#1668]
### Preflight Checklist
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+%3Abookmark_tabs%3A%22+label%3A%22bug+%3Abeetle%3A%22+) for a bug report that matches the one I want to file, without success.

### Ferdium Version
6.7.2

### Recipe Name
skype

### Recipe Version
3.6.2

### Last Known working version of the recipe
3.6.2

### Steps to reproduce
1. logout
2. try to login

### Expected Behavior
login

### Actual Behavior
opens separate web browser; can't login in ferdium itself

**Comment by SpecialAro** [comment]
@dchmelik can you please check which Ferdium version are you on, given that Ferdium v7.6.3 does not exist?

Also, I'm not able to reproduce this issue. Login in and out works just fine on my local. No separate web browser is open.

After logging out, click `CTRL/CMD+R` to reload the service and you will be presented with the login screen again.

**Comment by dchmelik** [comment]
Ferdium 6.7.2.  Maybe reloading works.

**Comment by SpecialAro** [comment]
Can you please confirm if reloading works?

**Comment by dchmelik** [comment]
yes
