### ISSUE TITLE
Bug:  Unable to save service (Nightly 38)

### ISSUE THREAD

**Issue by xalt7x** [ferdium/ferdium-app#167]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.38

### What Operating System are you using?

Ubuntu

### Operating System Version

22.04

### What arch are you using?

x64

### Last Known Working Ferdium version

6.0.0-nightly.37

### Expected Behavior

Service saves and adds

### Actual Behavior

After clicking "Save service" nothing happens (no output in terminal as well)

### Steps to reproduce

1. Delete config foolder (~/.config/ferdium)
2. Launch Nightly 38 (appimage)
3. "Use Ferdium without an Account"
4. Try to add/save any service
5. Repeat steps with Nightly 37 to make sure saving works there

**Comment by SpecialAro** [comment]
I have bisected and the responsible for this issue is bbde4a9d54d9c7dc03f34ca4113061a605dd5040. I'll raise a PR to revert it, thank you!

**Comment by vraravam** [comment]
Since this is an important functionality, I have kicked off a new nightly (out of band) to be able to get this working.

**Comment by vraravam** [comment]
@all-contributors please add @Alt37 for issue

**Comment by vraravam** [comment]
@all-contributors please add @Alt37 for bug
