### ISSUE TITLE
discord wont accept I'm a human

### ISSUE THREAD

**Issue by maxandersen** [ferdium/ferdium-app#1672]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.7.2

### What Operating System are you using?

macOS

### Operating System Version

14.4.1 (23E224) 

### What arch are you using?

x64

### Expected Behavior

discord should log in when filled in human check.

### Actual Behavior

when trying to login with discord (using qr code) i get asked if i'm a human twice and then it just return back to login screen. 
I respond correctly (I'm sure :) but it just stay logged out.

what is weird is that i do get notifications about new messages as if I am logged in...

### Steps to reproduce

1. add discord
2. provide login details/scan qr code
3. get 'are you human?` dialog and reply
4. #3 happens again
5. now you are back to login screen.

restarts does not change it.

### Debug link

https://debug.ferdium.org/privacy.html gives 404 so can't submit

### Screenshots

. 

### Additional information

.

**Comment by maxandersen** [comment]
hmm - same seem to happen on discord website login itself - thus probably not a ferdium only issue.

**Comment by SpecialAro** [comment]
This is not specific to Ferdium, as you stated. It is a problem related to Discord or the captcha service (which I think is Cloudflare)

Therefore, I'm closing this issue if that's ok.
