### ISSUE TITLE
No screen sharing with Teams New

### ISSUE THREAD

**Issue by danmer-dotcom** [ferdium/ferdium-app#1673]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

latest

### What Operating System are you using?

Ubuntu

### Operating System Version

ubuntu 22.04

### What arch are you using?

x64

### Last Known Working Ferdium version

latest

### Expected Behavior

I expect that when I press share screen it can do the sharing

### Actual Behavior

Good morning everyone. I've been using Teams with ferdium for a while now with no issues. My organization moved to Teams New. I can use chats and calls but with Teams New it is no longer possible to share the screen. When I try to share my screen I get the message that there is no webcam connected. I've never had this problem before.

### Steps to reproduce

1 press the share screen button

2 select screen, windows, or tab

3 sharing doesn't work and doesn't let me select which screen or tab

### Screenshots

![image](https://github.com/ferdium/ferdium-app/assets/61055706/e732af71-4096-4980-9579-a58b4b425cc6)

### Additional information

no additional info

**Comment by slartibart70** [comment]
see also  #1598

**Comment by nzeppos** [comment]
Same issue here with Ubuntu 20.04 and the new version of Teams.

I get the "camera" error shown in https://github.com/ferdium/ferdium-app/issues/1598#issuecomment-1993993902
