### ISSUE TITLE
Microsoft Teams has twice notifications with one message

### ISSUE THREAD

**Issue by awilliansd** [ferdium/ferdium-app#1675]
### Your issue

Version: 6.7.2
Server: Ferdium Server
Electron: 29.1.5
Chrome: 122.0.6261.130
Node.js: 20.9.0
Platform: Windows 11
Arch: x64
Git branch: release

I tried to look the code, but i didn't see any line that it has something about notifications.

**Comment by rmeissn** [comment]
This does not seem to be related to MS Teams only, as I can observe it with WhatsApp and RocketChat too.
I'm getting notifications in the Gnome notification bar as two entries for one message. It should be only one entry.
I don't know whether this is related to my recent update to Gnome 46 (from 44) or to a recent Ferdium update.

Version: 6.7.2
Server: No Server
Electron: 29.1.5
Chrome: 122.0.6261.130
Node.js: 20.9.0
Platform: Linux 6.8
Arch: x64
Build date: Wed Mar 27 2024 15:09:46 GMT+0100 (Mitteleuropäische Normalzeit)
Git SHA: ce7a8772
Git branch: release

**Comment by awilliansd** [comment]
I think that it is ferdium, because i use Windows SO

**Comment by tulexx** [comment]
I only have MS Teams service which generates notifications, so I don't know about others. But what I noticed is that not only they are double, but also require a mouse click to disappear.

I had to resort to creating a custom recipe from the official one and adding `onNotify` which sets `notification.options.requireInteraction` to false and compares title and body with a previous one. If they're the same, I return null.

Version: 6.7.3
Server: No Server
Electron: 30.0.1
Chrome: 124.0.6367.60
Node.js: 20.11.1
Platform: Linux 5.15
Arch: x64
Build date: Thu Apr 25 2024 03:13:04 GMT+0200 (Central European Summer Time)
Git SHA: d8f519a8
Git branch: release

**Comment by awilliansd** [comment]
Where could I change this value??

**Comment by ponces** [comment]
> I only have MS Teams service which generates notifications, so I don't know about others. But what I noticed is that not only they are double, but also require a mouse click to disappear.
> 
> I had to resort to creating a custom recipe from the official one and adding `onNotify` which sets `notification.options.requireInteraction` to false and compares title and body with a previous one. If they're the same, I return null.
> 
> Version: 6.7.3 Server: No Server Electron: 30.0.1 Chrome: 124.0.6367.60 Node.js: 20.11.1 Platform: Linux 5.15 Arch: x64 Build date: Thu Apr 25 2024 03:13:04 GMT+0200 (Central European Summer Time) Git SHA: [d8f519a](https://github.com/ferdium/ferdium-app/commit/d8f519a8eea28b88b727ddc6a2a42b6e3d784e02) Git branch: release

Could you please share it?

**Comment by tulexx** [comment]
Sure. This is the [webview.js](https://gist.github.com/tulexx/54df51101366b329cbdcc050f9a9037c). 

I used [this](https://github.com/ferdium/ferdium-recipes/blob/main/docs/updating.md) documentation to find the recipe folder, created a `dev` subfolder there and copied the whole msteams folder into it and changed the webview.js. After restarting Ferdium, this new service is available under Custom Services.

**Comment by awilliansd** [comment]
Thank you guy

**Comment by ponces** [comment]
Why is this closed? Was the main recipe changed?

**Comment by typoworx-de** [comment]
Also asking myself why this has been closed shouldn't there be a merge request to fix the source in the msteams addon?

**Comment by typoworx-de** [comment]
I've created MR for this using @tulexx patch, thanks for your work
https://github.com/ferdium/ferdium-recipes/pull/604
