### ISSUE TITLE
Include pre-releases not working corretly

### ISSUE THREAD

**Issue by max1c** [ferdium/ferdium-app#1705]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.7.3-nightly.12 (Supposed to be stable)

### What Operating System are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Last Known Working Ferdium version

N/A

### Expected Behavior

The software shouldn't be updating to the pre-release versions if the "Include pre-releases" if turned off. But it is:
![image](https://github.com/ferdium/ferdium-app/assets/11587156/e571040a-dc90-4b32-920f-b191cd941120)

### Actual Behavior

The software keeps updating to each pre-release version. Even though "Include pre-releases" is turned off:
![image](https://github.com/ferdium/ferdium-app/assets/11587156/e571040a-dc90-4b32-920f-b191cd941120)

### Steps to reproduce

Not sure. This might be happening because I installed a pre-release version previously but I think I was always using the stable version.

**Comment by SpecialAro** [comment]
Just to make sure, you were on nightly.9 with the pre-release button disable but you got the popup to update to nightly.12?

**Comment by max1c** [comment]
> Just to make sure, you were on nightly.9 with the pre-release button disable but you got the popup to update to nightly.12?

I don't know which version I was on originally. But I opened this issue since this has happened several times in a row now over the past week or so. I've gotten prompts to restart and update at least 2 or even 3 times now (which I did do it when it asked me to but I would prefer to be on a stable version) . The pre-release button has been off the whole time. I never turned it on.

**Comment by SpecialAro** [comment]
I've probably installed a nightly version and, ever since, no stable release has been made. Therefore, you got the popup to update on each nightly.

If you want to move to stable, uninstall the current Ferdium and install the latest stable (your settings should remain the same as long as you don't remove the %APPDATA%/Ferdium folder)

**Comment by max1c** [comment]
So if I just keep it this way until there's a stable release, will I be able to update to that with auto update and then not get anymore prompts to update to nightly?

**Comment by SpecialAro** [comment]
If you install a stable release, and disable pre-release button, yes, you won't be prompt to update to nightly versions, only stable versions.

**Comment by max1c** [comment]
Right. But assuming I stay on the current version, with the pre-release button disabled, will it give me the option to update to a future stable version? And then not give me prompts to update to a pre-release. Or is the only way for me to fix this is to manually install stable version?

**Comment by SpecialAro** [comment]
> Right. But assuming I stay on the current version, with the pre-release button disabled, will it give me the option to update to a future stable version? And then not give me prompts to update to a pre-release. Or is the only way for me to fix this is to manually install stable version?

In theory yes, you should be prompt to install the new stable and then you would stop having nightly releases. Though, it's safer to assume you're better off doing a manual install on the stable version if you don't want to be on the current nightlies.

**Comment by max1c** [comment]
Installed stable version and getting the same result:
![image](https://github.com/ferdium/ferdium-app/assets/11587156/cfc9500c-59b6-4b44-a8c2-fa43f64ab5a5)

**Comment by vraravam** [comment]
new stable version has been published - you can try the behavior and get back on what's happening. To be honest, I haven't tested this behavior till date.

**Comment by francwalter** [comment]
Disabling updates (with Enable updates disabled) works though.

**Comment by SpecialAro** [comment]
@max1c disabling updates will cause the app to get no updates at all. This is not advisable given that updates usually contains security fixes that are important.

**Comment by max1c** [comment]
Seems like after installing the latest stable update the issue has resolved itself.

**Comment by francwalter** [comment]
> Seems like after installing the latest stable update the issue has resolved itself.

So you installed the 6.7.3 stable, have the pre-releae switch off and you don't get pre release updates anymore? 
Did you install the 6.7.3 stable manually?

**Comment by SpecialAro** [comment]
If you are on a nightly you probably have to install the stable manually, yes.

**Comment by max1c** [comment]
> > Seems like after installing the latest stable update the issue has resolved itself.
> 
> So you installed the 6.7.3 stable, have the pre-releae switch off and you don't get pre release updates anymore? Did you install the 6.7.3 stable manually?

Pretty sure it was an auto update. Seems like the feature is just buggy.
