### ISSUE TITLE
Open links outside of service URL in browser setting

### ISSUE THREAD

**Issue by trymeouteh** [ferdium/ferdium-app#1707]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22enhancement+%3Asparkles%3A%22) for a feature request that matches the one I want to file, without success.

### Problem Description

When clicking on a link that takes you to a domain that is outside of the service URL, it will go to that URL inside of Ferdium.

### Proposed Solution

Please add a global setting were if you open a link that takes you outside the service domain, it will open this link in the browser. For example, if your service is https://account.proton.me/login, and if you click on a link that takes you outside of account.proton.me, it will open this link in the browser and not inside of Ferdium.

### Alternatives Considered

A setting for each service that does this.

**Comment by SpecialAro** [comment]
Hello again @trymeouteh (and thank you for raising all the issues so far). 😁

Have you checked the Trap links setting of each service (right click the service > Edit > Open links inside Ferdium)?

**Comment by trymeouteh** [comment]
Did not see this setting and it does seem to work
