### ISSUE TITLE
Ferdium 6.7.3 - No sound coming out in macOS 

### ISSUE THREAD

**Issue by InitPatch** [ferdium/ferdium-app#1727]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.7.3

### What Operating System are you using?

macOS

### Operating System Version

macOS Monterey 12.7.4

### What arch are you using?

x64

### Last Known Working Ferdium version

Can't recall the number; the one before this one (regular, not nighty/pre-release)

### Expected Behavior

When I play a sound or a video in Ferdium, no matter the service I'm using (WhatsApp/Slack/Twitter/etc... I should hear sounds.

### Actual Behavior

I don't hear any sound coming out from Ferdium
I do hear sounds when I use any other apps on my iMac

### Steps to reproduce

1. Open any service that can play sounds
2. Play the sound or video

### Debug link

https://debug.ferdium.org/53f97467-011f-446f-828c-4af28b289914

**Comment by SpecialAro** [comment]
Hi @InitPatch, can you make sure you didn't disable notifications/or sounds by accident?

**Comment by InitPatch** [comment]
Hi @SpecialAro 
I just did, and it's on, always has been actually
<img width="52" alt="image" src="https://github.com/ferdium/ferdium-app/assets/15719066/3c719aa3-d447-4ff9-ab3a-216ca9a01eec">

**Comment by SpecialAro** [comment]
And if you right click a specific service does it says enable sounds?

**Comment by InitPatch** [comment]
it says "disable audio", which means it's enabled:

<img width="220" alt="image" src="https://github.com/ferdium/ferdium-app/assets/15719066/2eab1074-6f24-4d6f-9520-d1146418dbbc">

**Comment by InitPatch** [comment]
Any other idea? 
Because I'm kinda blocked, as I work in the video game audio industry and need to send and receive a lot of audio and video files on Slack, Teams, Google Chat, etc...
For now, the only way to mitigate this is by downloading every file from all services I use, which is not practical and time-consuming. 
Yes, I can download the respective apps meanwhile, but it kinda kills the purpose of keeping running Ferdi 😅 
I appreciate all the help you can give me; or if I'm an isolated case, well; I'll have to wait until the next update and see if it magically fixes everything.
Cheers!

**Comment by SpecialAro** [comment]
Hello again @InitPatch!

I just tested this in my macOS Sonoma and it works just fine (as intended). Maybe something broke on your end?

If you ping me on discord I can try to help you out... but I'll probably need you to setup a dev environment so we can test things out and properly debug.

**Comment by InitPatch** [comment]
I'm on macOS Monterey.
I'll ping you on Discord.

**Comment by InitPatch** [comment]
Updating directly to the latest nightly build (6.7.4-nightly.3 ) appears to have resolved the issue.
