### ISSUE TITLE
Trying to update recipes removes all services

### ISSUE THREAD

**Issue by typoworx-de** [ferdium/ferdium-app#1728]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.7.3

### What Operating System are you using?

Ubuntu

### Operating System Version

Ubuntu 23.04

### What arch are you using?

x64

### Last Known Working Ferdium version

6.7.0

### Expected Behavior

I've had some issues with msteams service so I decided to update my ~/.config/Ferdium/recipes against fresh recipes from https://github.com/ferdium/ferdium-recipes.

Then I've tried to use either symlinks (and later cp -R) to link/copy recipes from ferdium-recipes/* to recipies/*.

After starting Ferdium again all services where gone!  Restoring backup from 'recipes~bak' to 'recipes' (after deleting the previous folder) brought back everyting.

### Actual Behavior

I would expect that account/service specific configurations are stored outside recipes. For some reason all services already configured disappeared from my Ferdium trying to update only the recipes folder.

### Steps to reproduce

```
cp -R recipes recipes~bak
git clone https://github.com/ferdium/ferdium-recipes.git

cd ferdium-recipe

# 1st try
ln -s ./recipes/* ../recipes/

# 2nd try
rm -rf recipes/
cp -R ./recipes/* ../recipes/
```

**Comment by SpecialAro** [comment]
Hello @typoworx-de,

This is not the proper way to update recipes. You should use the built-in feature for that.

You are modifying internal folders for Ferdium, which we only advise doing that if you really know what you are doing. Therefore, we are not "responsible" for providing support for this issue.

Nevertheless, I'm willing to try and help you. You probably messed up some permissions by making a symlink, and therefore Ferdium (i.e., Electron) can not properly see the recipes folder.

I'll advise you to delete the symlink and start fresh (or even trying to restore things by copy pasting your backup folder). If that doesn't work, delete the entire Ferdium folder to start fresh and from now on update using the built-in methods, please.

Thank you!


(closing this issue given it is out of scope - you can comment bellow nevertheless)
