### ISSUE TITLE
Second Outlook service asks to login every time

### ISSUE THREAD

**Issue by BearOutThere** [ferdium/ferdium-app#1735]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.7.0

### What Operating System are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

Every Outlook service should keep it's authenticated session on Ferdium restart.

### Actual Behavior

I have 2 Outlook services for different accounts.  One service maintains it's authenticated session between restarts and does not require a login.   The second service does not, and requires me to login every time i start Ferdium.   This is rather wasteful.  

### Steps to reproduce

1.  Setup the second MS Outlook service
2. Login into Outlook
3. Restart Ferdium
4.  The first Outlook service remains logged in
5.  The second Outlook service shows Outlook home page and requires a login.

**Comment by SpecialAro** [comment]
Hello @KirilOkun, please update to the latest stable and then see if this is still an issue. When opening a new issue you should always make sure you are on the latest stable or nightly.

I'm closing this issue, let me know if you want to open it back by installing the latest stable 😁
