### ISSUE TITLE
Nightly Ferdium wants my screen!!!

### ISSUE THREAD

**Issue by leoheck** [ferdium/ferdium-app#1738]
### Your issue

When I launch Ferdium it wants me to share the screen... 
Version `6.7.4.nightly.2`
I am running the AppImage version.

![image](https://github.com/ferdium/ferdium-app/assets/1277920/3eece584-e28d-4cd4-b7d3-81b1a3c35b2b)

**Comment by SpecialAro** [comment]
This has already been fixed (but we still didn't triggered a new nightly).

Keeping it open until we confirm this is fixed

**Comment by SpecialAro** [comment]
We just released a new nightly 😁 whenever you can, please test it out and let me know if it works!

**Comment by leoheck** [comment]
The update came now. This is fixed for me, thanks @SpecialAro 

```
Version: 6.7.4-nightly.3
Server: Ferdium Server
Electron: 30.0.2
Chrome: 124.0.6367.91
Node.js: 20.11.1
Platform: Linux 6.8
Arch: x64
Build date: Fri May 03 2024 21:46:39 GMT-0300 (Brasilia Standard Time)
Git SHA: 2489a396
Git branch: nightly
```
