### ISSUE TITLE
Teams V2 Messages Count not working and Ferdium System Tray not showing the red dot

### ISSUE THREAD

**Issue by fernandobalieiro** [ferdium/ferdium-app#1744]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.7.4-nightly.3

### What Operating System are you using?

Ubuntu

### Operating System Version

Ubuntu 22.04

### What arch are you using?

x64

### Last Known Working Ferdium version

6.7.3

### Expected Behavior

Messages count for Teams V2 should appear under the service label and Ferdium System Tray icon should show a red dot.

### Actual Behavior

**Teams V2** service does not show the message count under the service label:
![Screenshot from 2024-05-04 18-04-31](https://github.com/ferdium/ferdium-app/assets/11398769/e94a4466-72b9-41ea-a1d2-a41f3346412c)

And Ferdium icon does not show the red dot:
![Screenshot from 2024-05-03 15-04-11](https://github.com/ferdium/ferdium-app/assets/11398769/fc964763-b17d-46bf-8769-dbf25efe8808)

It works as expected after switching back to **Teams V1**:
![Screenshot from 2024-05-04 18-07-02_](https://github.com/ferdium/ferdium-app/assets/11398769/106ab93d-b9a8-40d2-afd5-ef51f827f464)

Ferdium icon also shows the red dot:
![image](https://github.com/ferdium/ferdium-app/assets/11398769/5b35eb1d-978c-4617-8c80-c3a943181353)

### Steps to reproduce

Crate a service using Teams V2, receive a message.

**Comment by fernandobalieiro** [comment]
Thanks again @SpecialAro!
I have tested using `6.7.4-nightly.5` and it's working properly :)
Do you guys have an ETA on when will have a stable version?
Best regards.

**Comment by SpecialAro** [comment]
You're welcome! Probably in one/two weeks 😁

**Comment by fernandobalieiro** [comment]
OK, thank you!

**Comment by pallebone** [comment]
Would it be possible to update the snap version on the snap store? I have the same issue but the latest stable on snap is 6.7.1

**Comment by bassmanitram** [comment]
Close to a year - it's NOT working in 7.1.0-nightly, nor, for me, has it EVER worked

**Comment by Ninu-Nightwatch** [comment]
It is not working for me. Is it working for you guys?

**Comment by Soetens** [comment]
> It is not working for me. Is it working for you guys?

Nope. Doesnt work.
