### ISSUE TITLE
RocketChat double notifications

### ISSUE THREAD

**Issue by jahtz** [ferdium/ferdium-app#1747]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.7.3

### What Operating System are you using?

Other Linux

### Operating System Version

Fedora 40 - 6.8.8-300.fc40.x86_64

### What arch are you using?

x64

### Expected Behavior

Notifications should be counted only once.

### Actual Behavior

Notifications are send twice.

### Steps to reproduce

1. Receive a message in RocketChat Channels or Chats.
2. Receive every desktop notification twice (Gnome notifications).

**Comment by mikymaione** [comment]
Same problem, with Whatsapp, Element, Telegram, Instagram. All notifications in Gnome 46 (Fedora 40) are duplicated.

**Comment by Thorarin** [comment]
I've also been experiencing double notifications for Microsoft Teams for the past few months or so.
Ferdium 6.7.3 on Windows 10.
