### ISSUE TITLE
annoyning message-box notifications by ferdium for ms-teams

### ISSUE THREAD

**Issue by typoworx-de** [ferdium/ferdium-app#1751]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.7.3

### What Operating System are you using?

Ubuntu

### Operating System Version

23.04

### What arch are you using?

x64

### Expected Behavior

I would expect push-notifications that automatically disappear after given time.  I already disabled notifications for ms-teams service in ferdium, but the annoying notifications still appear for every(!) message.

### Actual Behavior

Every message will show-up a message-confirm box like this!
![image](https://github.com/ferdium/ferdium-app/assets/1282298/6c2bfb48-f60a-426f-8ed5-2431266c546f)

### Steps to reproduce

I don't know if or how this is reproduceable. I've recently upgraded ferdium and ferdium-recieipts including ms-teams and then it was there.

### Screenshots

![image](https://github.com/ferdium/ferdium-app/assets/1282298/6c2bfb48-f60a-426f-8ed5-2431266c546f)

**Comment by r4dian** [comment]
I also have this on Windows, but in addition **every notification pops twice.**

**Comment by typoworx-de** [comment]
I already tried to patch the msteams recipe (https://github.com/ferdium/ferdium-recipes/tree/main/recipes/msteams), but so far with no long-term success. I've tried to override like this. But these annoying messages are still appearing. I did not find any code which looks like producing such confirm-dialogs yet. It only appears for msteams notifications, so I don't think it somehow relies to anything else in ferdium or other recipes.

Trying to disable notifications also is no solution yet to get rid off these annoying notifications, which do not automatically disappear and need user-interaction to get them away.

Tried to patch msteams recipce (tried multiple js-files) with no luck:
`window.conform = function() {}`

**Comment by typoworx-de** [comment]
Any news on this? I've even been trying to "patch" those annoying windows away, but so far without luck. I have a bunch of ferdium addons (Whatsapp, Slack, ....) but only Teams is giving me this absolutly annoying alerts trashing up my screen with this sucking alerts I always have to clean-up on my own.

Any help welcome :sos:

**Comment by r4dian** [comment]
Why is this closed? It still happens exactly as described in the original Issue. (I don't get the notifications twice anymore though)
