### ISSUE TITLE
MS Teams markdown - codeblock not working or working well

### ISSUE THREAD

**Issue by nerdCopter** [ferdium/ferdium-app#1771]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+%3Abookmark_tabs%3A%22+label%3A%22bug+%3Abeetle%3A%22+) for a bug report that matches the one I want to file, without success.

### Ferdium Version

6.7.4-nightyl

### Recipe Name

MS Teams

### Recipe Version

3.3.2

### Last Known working version of the recipe

unknown, but was.

### Steps to reproduce

any channel:
use 3 backticks

### Expected Behavior

it should render a codeblock to be filled in (highlighted in read):
![image](https://github.com/ferdium/ferdium-app/assets/56646290/462ee0c8-6c7c-47a8-b4fc-8b0564f1fe6a)

### Actual Behavior

it does not render (highlighted in red)
![image](https://github.com/ferdium/ferdium-app/assets/56646290/dcb67a0f-8f92-4635-9c7b-21809d94bb09)

### Additional Information

Also renders completely different from Firefox. Firefox renders as expected. Ferdium not so much.
MAYBE has to do with MS-Team classic versus new modes.
![image](https://github.com/ferdium/ferdium-app/assets/56646290/433daff9-66aa-4eae-bafc-25ad01ccdfef)

**Comment by nerdCopter** [comment]
maybe useful:

supported markdown:
https://support.microsoft.com/en-us/office/use-markdown-formatting-in-microsoft-teams-4d10bd65-55e2-4b2d-a1f3-2bebdcd2c772

cross-platform support:
https://learn.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-text-formats#formatting-text-content

**Comment by nerdCopter** [comment]
This is Google-Chrome, same ugly render, and same failure to render blockcode when commenting:
![image](https://github.com/ferdium/ferdium-app/assets/56646290/bfdeef25-a29a-4c2e-a48d-d4b3479b5a69)

Problem-source is Chrome/Chromium/NWjs or whatever wrapper Ferdium uses. :(

**Comment by vraravam** [comment]
Thanks for the update @nerdCopter - as per your investigation, this is a bug in the upstream, and cannot be fixed by the Ferdium team. Closing the ticket.
