### ISSUE TITLE
Windows 7

### ISSUE THREAD

**Issue by harryray33** [ferdium/ferdium-app#1773]
### Your issue

Does this work with Win 7?
Thanks

**Comment by SpecialAro** [comment]
Hello!

Windows 7 is a deprecated OS which now lacks security fixes so it's not recommend at all to be used in the modern world. Please consider updating your system as you might be exposed to vulnerabilities (extended support ended 4 years ago and the system was marked deprecated 10 years ago).

With that being said, we don't assure that Ferdium works on Windows 7. You can try it out but you will probably face errors or unstable behavior.

Also, in the future, small questions like this should preferably be asked in Discord, so as to keep the issue box clear for real app issues.

Thank you very much!

**Comment by vraravam** [comment]
I concur - if you just have a question (as opposed to a known bug), it can be better asked in discord.

**Comment by pepper3k** [comment]
> Hello!
> 
> Windows 7 is a deprecated OS which now lacks security fixes so it's not recommend at all to be used in the modern world. Please consider updating your system as you might be exposed to vulnerabilities (extended support ended 4 years ago and the system was marked deprecated 10 years ago).
> 
> With that being said, we don't assure that Ferdium works on Windows 7. You can try it out but you will probably face errors or unstable behavior.
> 
> Also, in the future, small questions like this should preferably be asked in Discord, so as to keep the issue box clear for real app issues.
> 
> Thank you very much!

actually, just to be precise, extended support ended on jan 1st 2023, but yeah i agree with you, if you want to use windows 7 you might as well keep using XP at this point...

**Comment by pepper3k** [comment]
this is the perfect opportunity to move to linux and gain your freedom
