### ISSUE TITLE
Status Page In Whatsapp Not Showing Completely

### ISSUE THREAD

**Issue by Shabeebcp** [ferdium/ferdium-app#1774]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.7.4

### What Operating System are you using?

Windows

### Operating System Version

W10

### What arch are you using?

x64

### Expected Behavior

Status Need to Show Full

### Actual Behavior

![image](https://github.com/ferdium/ferdium-app/assets/89440982/7a4169b4-56ec-4223-a84f-6806996ed236)

### Steps to reproduce

1.Route To Status Page

**Comment by eitchtee** [comment]
This is related to the service.css in your recipe folder, deleting the following line will fix the issue

```css
/* Hide install desktop application notice */
.xz9dl7a {
  display: none;
}

```

I don't know where the mentioned notice is located, but it doesn't seem to show for me (for now at least)
