### ISSUE TITLE
Problem with package validation not reporting the correct version number

### ISSUE THREAD

**Issue by Shampra** [ferdium/ferdium-app#1778]
### Your issue

Hi,

I try to update a recipe but each time I have an error in Ferdium Recipes build : 
```
Couldn't package "xxx": There were errors in the recipe's package.json: Found changes in 'recipes/xxx' without the corresponding version bump in 'recipes/xxx/package.json'
```

No matter which recipes....
- I change something in webview.js (update code... or for test : delete a comment, add an empty line,...)
- I update version in package.json (like   "version": "1.4.1" ->   "version": "1.4.2" )
- Building... error!

Error encountered on an update for Hangout chat (https://github.com/ferdium/ferdium-recipes/pull/549)
Tested in another random recipes (https://github.com/Shampra/ferdium-recipes/pull/3)

I can't figure it out.
Is it something I did wrong (thanks for the explanation)? Or a bug?
Thanks for your help!

**Comment by SpecialAro** [comment]
Please follow then contributing guidelines for ferdium-recipes

You should run `pnpm validate`

**Comment by Shampra** [comment]
Thanks but it's what I've done (with a Github action and after your message I also tried locally)

Always same result
![image](https://github.com/ferdium/ferdium-app/assets/16141040/b6c15429-024b-4bfd-aaf8-7ffb833014bd)

**Comment by Shampra** [comment]
And if I add log in scripts\package.json, change are correctly detected in webview and package json
![image](https://github.com/ferdium/ferdium-app/assets/16141040/c095a145-2e75-448f-8855-f9f1485af761)
But "No changes in recipes\hangoutschat\package.json detected", a problem with pkgJsonRelative?

edit : 
Item in result has **/** in their string path
pkgJsonRelative has **\\**
So `if (result.files.some(({ file }) => file === pkgJsonRelative))` is never true
If I change code to this to  : 
const normalizePath = p => p.replace(/\\/g, '/');
          const pkgJsonRelative = normalizePath(
            path.relative(repoRoot, packageJson),
          );
It's work.
But I'm not sure it's a global problem. Do you think it could be the subject of a PR?
