### ISSUE TITLE
Udemy - Some videos not play.

### ISSUE THREAD

**Issue by bicolorman** [ferdium/ferdium-app#1780]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+%3Abookmark_tabs%3A%22+label%3A%22bug+%3Abeetle%3A%22+) for a bug report that matches the one I want to file, without success.

### Ferdium Version

6.7.4

### Recipe Name

Udemy

### Recipe Version

1.2.1

### Steps to reproduce

I have a lot of courses in udemy.  In this course (az-900-azure-fundamental) the third video is not play.  The four is play.  In some courses only a few videos play.  I don't know what happend. If I open a browser external to ferdium like chrome, firefox, all works. 

### Expected Behavior

All videos I hope to play. 

### Actual Behavior

Some videos play.

### Screenshots

![image](https://github.com/ferdium/ferdium-app/assets/20631807/edf2896d-bdcb-427b-a07e-0f1c56f45d8b)

**Comment by Arthur-Huan** [comment]
Is this perhaps the same as #1818, which is fundamentally about the DRM issue raised in #720? If it is could you close this previous issue?

**Comment by SpecialAro** [comment]
Closing as per @Arthur-Huan comment. It is indeed due to DRM issue.
