### ISSUE TITLE
Discord channels style is not good. Channels looks disabled. 

### ISSUE THREAD

**Issue by leoheck** [ferdium/ferdium-app#1784]
### Your issue

Using Discord, the channels are faint. This looks like they are not enabled to be used.
Can we have a better style on this thing? 

![image](https://github.com/ferdium/ferdium-app/assets/1277920/d90105f2-7e73-4724-8c0b-77ff2fb9b019)

See the apps tab, which has a better style that allows us to see the existing services and also differentiate from the selected one.
![image](https://github.com/ferdium/ferdium-app/assets/1277920/170a073b-11d2-4509-a0c9-c48d10389b71)

```
Version: 6.7.5-nightly.2
Server: Ferdium Server
Electron: 30.0.6
Chrome: 124.0.6367.207
Node.js: 20.11.1
Platform: Linux 6.8
Arch: x64
Build date: Sun May 19 2024 21:49:16 GMT-0300 (Brasilia Standard Time)
Git SHA: 3ea062e3
Git branch: nightly
```

**Comment by SpecialAro** [comment]
Please disable the dark theme that is being injected to the service (right click the service and disable dark mode). Make sure you restart Ferdium/the service

**Comment by leoheck** [comment]
hm, thanks, that was good.. it worked without restarting the Ferdium. Thanks.
