### ISSUE TITLE
Bug: “Ferdium” is damaged and can’t be opened. You should move it to the Bin.

### ISSUE THREAD

**Issue by fbartels** [ferdium/ferdium-app#180]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.39

### What Operating System are you using?

macOS

### Operating System Version

macOS Monterey 12.3.1 (21E258)

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Ferdium version

first version tried so far

### Expected Behavior

Ferdium starts up

### Actual Behavior

Only a popup opens saying that the Ferdium app is damaged and cannot be opened:

![image](https://user-images.githubusercontent.com/1257835/169271592-80395192-0a3f-4cce-b17a-fce25fd35de2.png)

### Steps to reproduce

Have macos and run the following commands (as instructed on the website):

- brew tap ferdium/ferdium
- brew install ferdium-nightly

Same behaviour when trying `brew install ferdium`

**Comment by kishaningithub** [comment]
This is not a bug though the reason and fix is documented/linked here.

https://github.com/ferdium/ferdium-app#unsigned-nightlies-on-macos

Let know if this works for you

**Comment by fbartels** [comment]
Hi @kishaningithub,

ah I seemed to have missed that bit. After executing the command I was able to start Ferdium.
