### ISSUE TITLE
device-dependent shown/enabled services (?)

### ISSUE THREAD

**Issue by bryanpedini** [ferdium/ferdium-app#1815]
Hello, newcomer here 👋🏻
(sorry if this has been asked already but either github didn't find the relevant issue, or I'm an idiot at searching)

I would like to know if there is already the possibility to enable/disable (or even show/hide) services based on the device used.
For example, I would like to have my personal Whatsapp web on all my devices, desktop, personal laptop, and work laptop, however the Whatsapp web and the Google messages of the shared number we use at work to communicate with customers I would like to be enabled and possibly shown only on my work laptop, and disabled or even hidden on my personal machines.

I know I can just _not log in_ since states are on-device and not shared, however it would be nice to toggle a button in the service settings and make it "only on this device".

Don't know if relevant: I'm on a self-hosted ferdium server.
If the issue is more appropriate to be a feature request because the functionality does not exist yet, but other people too would like to have it, please let me know, and I'll close this "question if exists" and open a FR for it to be implemented.

Thanks in advace.

**Comment by SpecialAro** [comment]
Hello @bryanpedini and thank you for logging this issue!

We don't support that feature in fact. And probably for your use case it would be better to have two different accounts (one for work and another for personal). Or even just setup a local account (without needing to sync).

**Comment by bryanpedini** [comment]
> Or even just setup a local account (without needing to sync).

Well the idea was to be able to sync everything **but** something specific, like, I want services X, Y, and Z to be always with me sort of speak, like whatsapp web of my cellphone, or openai chatgpt, or linkedin, but for example not the company emails, stuff like that...

Anyway, I'll close this one, if anybody is interested they can open a FR or code the feature themselves and open a PR.
Thanks at least for have taken the time to answer my question 💪🏻😄
