### ISSUE TITLE
Master lock password

### ISSUE THREAD

**Issue by joaonunatings** [ferdium/ferdium-app#1843]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22enhancement+%3Asparkles%3A%22) for a feature request that matches the one I want to file, without success.

### Problem Description

As most services don't have a lock feature (password require to activate/show service) there should be a master lock feature to Ferdium.

This is a feature based on what Hamsket/Rambox had.

### Proposed Solution

Settings should have an option 'Lock Ferdium with password' on/off button.
When enabled, there should be an input box for the user to insert the password.
Each time Ferdium startups, it asks for the master password. There can also be an hotkey or settings in the top bar for locking Ferdium.

### Alternatives Considered

For now, I just close the window, making it go to tray. But this solution is not as near as what I described.

**Comment by vraravam** [comment]
This feature already exists.
Launching screen when a password is set: <img width="366" alt="Screenshot 2024-07-08 at 7 42 35 AM" src="https://github.com/ferdium/ferdium-app/assets/69629/edda234f-dc50-4799-9df7-b5985f564fa0">

Preferences section, go to `Privacy` tab and scroll down: 
<img width="597" alt="Screenshot 2024-07-08 at 7 43 22 AM" src="https://github.com/ferdium/ferdium-app/assets/69629/3797c14e-5332-4d28-9322-3ae368b0e1e7">

The sidebar also shows a lock icon to lock Ferdium. And there's a shortcut key `Cmd+Shift+L` (mac) and `Ctrl+Shit+L` (windows and linux)

**Comment by joaonunatings** [comment]
I misesd that setting completely, thank you!

**Comment by FatherGroup** [comment]
I installed the app on my mac and was setting it up, when I was in the security options and enabled password protection, the power went out and came back immediately. I turned on the mac, opened the app and it asks me for a password, but I never managed to enter any password. I deleted the app, put it back in and it still asks for a password. I would like you to help me remove this restriction, so I can configure it again, thank you.

![Capture_Jul-23-2024_10 53 37](https://github.com/user-attachments/assets/41ccd328-8c8b-48cb-8963-bdd53ebcea28)

**Comment by vraravam** [comment]
you can edit this file `~/Library/Application Support/Ferdium/config/settings.json` and remove the whole line that says `lockedPassword`. Do this when Ferdium is not running. Then start Ferdium - and it should be good.

**Comment by FatherGroup** [comment]
> you can edit this file `~/Library/Application Support/Ferdium/config/settings.json` and remove the whole line that says `lockedPassword`. Do this when Ferdium is not running. Then start Ferdium - and it should be good.

Great, it worked, thanks for your help.
