### ISSUE TITLE
Setup i18n with Crowdin

### ISSUE THREAD

**Issue by nathanaelhoun** [ferdium/ferdium-app#185]
- [x] Create a Crowdin project : https://crowdin.com/project/ferdium-app
- [x] Setup the Crowdin → GitHub integration to submit daily PRs 
- [x] Fix the internationalization setup

The setup is a bit strange for i18n at the moment:
- The code languages listed in `src/i18n/locales` are not consistent: some are two characters locales code like `fr.json`, other are regionalized locale codes like `zh-HANT.json` or `en-US.json`
- The languages listed here in `src/i18n/languages.ts` (availables to the users) doesn't correspond to the languages listed in Crowdin, nor to the files present in the `src/i18n/locales/` folder. For instance:
    - `zh-HANT` is meant to be Chinese Traditional according to [some sources](https://www.alchemysoftware.com/livedocs/ezscript/Topics/Catalyst/Language.htm), but it's mapped to Chinese Simplified on Crowdin.
    - ~~"Nederlands" is marked in the UI, but it is "Dutch" on Crowdin.~~ expected as we write the native language names in the UI
    - Vietnamese is translated to 90% but is not available to the users. (fixed by #562)
    
We have decided to not hold the 6.0.0 release for this, as the current translations are working. But this will be fixed before allowing translations again through Crowdin.

If you see some strings that need to be fixed before 6.0.0, please report them below this issue.

**Comment by comradekingu** [comment]
Some locales actually use country-specific codes.
However, your locale problem will not improve with Crowdin.
It creates non-workable alias locales, invalidating even good efforts.

Crowdin itself is a disservice to translators, as it is not possible to see more languages and draw from them, things get held up in voting, and large arrays of strings can't be browsed at once.
This makes for incomplete and inconsistent translations, at best reaching coverage by way of multiple translators having less oversight.

The "privacy" policy, has (among other things)
>behaviourally targeted advertising cookies - These cookies are used to deliver adverts more relevant to you and your interests. They are also used to limit the number of times you see an advertisement as well as help measure the effectiveness of the advertising campaigns. They are usually placed by advertising networks with the website operator’s permission. They remember that you have visited a website and this information is shared with other organisations such as advertisers. Quite often targeting or advertising cookies will be linked to site functionality provided by the other organisation.

**Comment by pepper3k** [comment]
@comradekingu  Sounds to me like a good time to ditch this platform

**Comment by comradekingu** [comment]
@eitanprezes Weblate is as viable as its differentiation from other platforms.
Happy to help set up shop and help out on https://weblate.bubu1.eu/ or https://hosted.weblate.org/hosting/ if you drop the CoC in name and content (in favour of something like https://github.com/WeblateOrg/weblate/blob/main/CONTACT.md ).
As you can see I am an outside Weblate contributor and user.

Edit: Outside of https://docs.weblate.org/en/latest/formats.html?highlight=supported%20formats#translation-types-capabilities
the setup needs to be pointed to the stringbase files in what isn't the most polished workflow.
Don't know if they are shared between Win and macOS or not.
