### ISSUE TITLE
Custom service shows blank page

### ISSUE THREAD

**Issue by Cris70** [ferdium/ferdium-app#1850]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.7.6-nightly.3

### What Operating System are you using?

Other Linux

### Operating System Version

openSUSE Tumbleweed 20240712

### What arch are you using?

x64

### Last Known Working Ferdium version

n/a

### Expected Behavior

Ferdium should correctly show the web page.

### Actual Behavior

Ferdium shows a blank page.

### Steps to reproduce

The issue is triggered accessing a web page for which I do not want to disclose the IP.

### Debug link

https://debug.ferdium.org/0edf652f-c39c-4978-a8c1-6e73aa8338f0

### Screenshots

![immagine](https://github.com/user-attachments/assets/cae173dc-7042-42d3-86fe-0475b309c8b4)

### Additional information

I am trying to access the web page of one of my Proxmox servers.
I have three of them. Two are on the same version of Proxmox, while one is on a previous version.
All three use self-signed certificates.
One of the two Proxmox servers which are on the same version, only show a blank page in Ferdium (no problem in Firefox or Falkon).
Looking in the developer console I see this error: `Error invoking remote method 'GUEST_VIEW_MANAGER_CALL'`.
I found this error in a closed Ferdium bug (#1227), but it should now be corrected. Also, all Proxmox servers have self-signed certificates, but only one shows the blank page.
I have tried several times to clear the cache; I even deleted and re-created the service, with no success.

**Comment by SpecialAro** [comment]
Hello @Cris70 👋 

Thank you for logging this issue!

Did you add both self-signed certificates to Ferdium? One per each proxmox server you are accessing?

Can you check if you haven't miswritten https (it should have the s) on the services?

**Comment by Cris70** [comment]
Thank you @SpecialAro for your reply!
These services have been set up so many months ago that I do not remember much of what I did.
How do I add self-signed certificates to Ferdium? I thought it would simply ask me to accept an insecure certificate.
Regarding your second question: all three services have https in their URL.

**Comment by SpecialAro** [comment]
Ok, just to check, have you enabled this setting and added the self-signed certificates inside the folder? Follow the instructions in that screen:

![299351409-bd5b1ac6-8df5-4a67-833c-4f4df359c22c.png](https://github.com/user-attachments/assets/a1796b9b-eaf8-4d0d-9e5d-476cd48e20c3)

**Comment by Cris70** [comment]
Thank yoy @SpecialAro !!!
I had completely forgot of this procedure.
The certificate was already there, but in the meantime it had been probably updated, as the new certificate is different.
After replacing the certificate with the new one and refreshing the service, everything is OK!!
