### ISSUE TITLE
Add confirmation on the Delete service action in the service settings form

### ISSUE THREAD

**Issue by MurzNN** [ferdium/ferdium-app#1852]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22enhancement+%3Asparkles%3A%22) for a feature request that matches the one I want to file, without success.

### Problem Description

I accidentally deleted my active service via the "Delete service" red button already several times. Just by miss-clicking, because in some other apps, the "Save" button is located on the right side, whereas Ferdium has the "Delete" button. The red button color doesn't help enough :)

And the service is deleted instantly after clicking this button, without any confirmation!

### Proposed Solution

Please add a confirmation window when deleting a service, to prevent accidentally deleting services.

### Alternatives Considered

Include a captcha in the confirmation window? :joy: 
Maybe improve the protection from deleting by typing the service name, but I think just a confirmation popup window should be enough.

**Comment by vraravam** [comment]
If you are right clicking into the context menu of the sidebar on the left, there's a confirmation that pops up. Is this what you are asking for? Or are you referring to a different delete button?

**Comment by MurzNN** [comment]
I'm about this Delete button:
![image](https://github.com/user-attachments/assets/5ef240a5-23fa-4cd2-a2ed-668710d4d620)

**Comment by vraravam** [comment]
@MurzNN - i have raised a PR (#1853) for this. you can see the screenshot in that PR. It will be available in the next nightly.
