### ISSUE TITLE
How to permanently get rid of Slack bottom banner nudge prompt "Stop juggling tabs, download the Slack app"

### ISSUE THREAD

**Issue by logan-life** [ferdium/ferdium-app#1860]
### Your issue

I am using Ferdium mostly to handle my Slack workspaces. 

When using it, I often get the nudge prompt shown in the screenshot. It reads:

"Stop juggling tabs, download the Slack app. Get Slack for macOS. (Already have the app? Open Slack."

After clicking to dismiss the prompt, the prompt comes back regularly. It's quite annoying to always have the nudge prompt there. Does anyone know why it keeps coming back and/or how to permanently remove it?

<img width="1380" alt="image" src="https://github.com/user-attachments/assets/80a72396-c554-42ef-8b1e-4977c4d05c92">

**Comment by logan-life** [comment]
It seems like specifying a user agent string in Ferdium settings to convince slack that i'm actually using the native app has solved it. I'm using

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Slack/4.39.90 Chrome/91.0.4472.124 Electron/13.1.9 Safari/537.36`

**Comment by logan-life** [comment]
closing

**Comment by ajkavanagh** [comment]
I had change the version bit for Chrome to be `127.0.6533.72` so that it then didn't put up a banner about upgrading my OS.  Now, if only I could get rid of the "Add colleagues" bold/bright/white heading ...

**Comment by rgurley** [comment]
Not a Ferdium user, but I solved this for myself with a Slack.desktop entry in .local/share/applications/Slack.desktop and the Exec is like

chromium --app=slack_url --new-window --user-agent="Slack/24.10.20.0"

Now I have a slack "app" which doesn't bug me about installing the app. Thanks to logan-life for the user-agent tip.
