### ISSUE TITLE
Ferdium-win-Portable Update button.

### ISSUE THREAD

**Issue by HermanRas** [ferdium/ferdium-app#1870]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.7.6, 6.7.5, 6.7.4

### What Operating System are you using?

Windows

### Operating System Version

Windows 11, Version 23h2 (OS Build 22631.3737)

### What arch are you using?

x64

### Last Known Working Ferdium version

NONE

### Expected Behavior

Them the update prompt indicates a new version is available, and you click the restart & install update button the latest portable exe should be downloaded for use by the user as a minimum, even better would be if it updated to the latest version, but being portable I assume there is limitation in replacing running exe's .

![image](https://github.com/user-attachments/assets/589f7c77-bd04-415e-8e5c-21d7aa52ac95)

### Actual Behavior

Currently clicking the restart & install update button does nothing.

### Steps to reproduce

1. download and open any Ferdium-win-Portable-6.7.X version of the app.
2. wait a second for it to detect a new version, the prompt will appear at the bottom of the app.
3. click the button [restart & install update button] on the update prompt on the bottom of the app.

### Additional information

If this is a known limit of portable electron apps I am happy to have the issue closed, I can create a feature request to add a download link option to the Help > About Menu , linked to latest releases git page.

**Comment by HermanRas** [comment]
I am starting to look at the update not working on portable, and really hope its not a limitation.
I am testing with :
 - Version: 6.7.5
 - Server: No Server
 - Electron: 31.1.0
 - Chrome: 126.0.6478.114
 - Node.js: 20.14.0
 - Platform: Windows 11
 - Arch: x64
 - Build date: Sat Jun 29 2024 03:44:01 GMT+0200 (South Africa Standard Time)
 - Git SHA: 5514cab9
 - Git branch: release

Below debug output from the App shows no visible errors:
### Debug Info Clean Install - before update clicked
 - https://debug.ferdium.org/fe95b180-4086-4dba-ac92-3e73cc00e4ee
### Debug Info Clean Install - after update clicked
 - https://debug.ferdium.org/fe95b180-4086-4dba-ac92-3e73cc00e4ee

**Comment by HermanRas** [comment]
So I still don't know why but I do know its an intended behavior to ignore the updates for the portable version by design:

https://github.com/ferdium/ferdium-app/blob/develop/src/components/AppUpdateInfoBar.tsx
```JS
    <InfoBar
      type="primary"
      ctaLabel={intl.formatMessage(messages.buttonInstallUpdate)}
      onClick={event => {
        // eslint-disable-next-line @typescript-eslint/no-unused-expressions
        !isWinPortable && onInstallUpdate(event);
      }}
      onHide={onHide}
    >
```
![image](https://github.com/user-attachments/assets/c478305d-113e-46d1-911f-2428028a0ed1)

Next Action remove the "not portable" filter and see what dies..

**Comment by SpecialAro** [comment]
Hello @HermanRas

Automatic updates on Ferdium Portable are not supported. You should manually download the new version and run it over the old version.

In the future, we will change that same line of code to send the user to the download page to download it manually.

**Comment by HermanRas** [comment]
Thank you !

**Comment by HermanRas** [comment]
App working as designed, The update function will in future be updated to redirect portable version of the app to the latest Git Repo page, for easy download.
