### ISSUE TITLE
Windows Defender Win32/Cinjo.O!cl

### ISSUE THREAD

**Issue by max1c** [ferdium/ferdium-app#1872]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.7.6

### What Operating System are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Ferdium version

6.7.5

### Expected Behavior

Not be blocked by Windows Defender.

### Actual Behavior

Seeing this issue today in the morning. Trying to do a fresh install gets instantly blocked as well.
![image](https://github.com/user-attachments/assets/b90fde35-5012-41a5-9848-b95981632bf3)

### Steps to reproduce

1. Install Ferdium
2. Get Defender pop-up

**Comment by Arthur-Huan** [comment]
I believe I've seen this before, if it's the same issue it's down to something with the Electron builder. electron-userland/electron-builder#5759 might be relevant.

**Comment by max1c** [comment]
> I believe I've seen this before, if it's the same issue it's down to something with the Electron builder. [electron-userland/electron-builder#5759](https://github.com/electron-userland/electron-builder/issues/5759) might be relevant.

I saw these issues with Electron too when I was looking into it. It was pretty random. I used Ferdium on 3 different machines and it only happened on one of them. Downgrading solved the problem.

**Comment by SpecialAro** [comment]
This looks like a false positive. Nevertheless, I post here the VirusTotal report of `ferdium.exe`:
https://www.virustotal.com/gui/file/81f0930ad505c7e893087274f49430178a1027dd40bcbf8a04d8dba6535b8dae?nocache=1

As you can see, 0 of 74 tests came back positive.
