### ISSUE TITLE
Release a .src.rpm version

### ISSUE THREAD

**Issue by xgrind** [ferdium/ferdium-app#1878]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22enhancement+%3Asparkles%3A%22) for a feature request that matches the one I want to file, without success.

### Problem Description

It is not possible to install the .rpm version on Mageia Linux, as the libXtst library has a different name.

### Proposed Solution

Release a .src.rpm version

### Alternatives Considered

Compile for Mageia 9 or release a .src.rpm version, so any rpm distribution can create its package.

### Additional Information

![Captura de tela_2024-08-18_13-11-10](https://github.com/user-attachments/assets/561fca2b-87b4-4f95-81b4-628e0c4fa87f)

**Comment by Alphrag** [comment]
Hi @xgrind, we do not create the targets ourselves: everything is done directly by `electron-builder` and unfortunately they do not have `src.rpm` in [their list of possible targets](https://www.electron.build/linux#target). You could either request that directly from them, or if you find a way to create it on the fly, there could be an action ran to make it available.

**Comment by xgrind** [comment]
Got it. It was just a suggestion, but I'm using the Appimage version and it's working fine.
Thanks for responding.
I'm closing this bug.
