### ISSUE TITLE
Murena mail Can't connect to host error

### ISSUE THREAD

**Issue by Lauloque** [ferdium/ferdium-app#1885]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.7.6

### What Operating System are you using?

Windows

### Operating System Version

Win 11 Pro 23H2

### What arch are you using?

x64

### Last Known Working Ferdium version

unknown, whatever was the stable reasle back in early 2024

### Expected Behavior

I used to be able to add Murena mail to my Ferdium services: https://murena.io/apps/snappymail/

I have it in my services, I just had to login once in a while and that was it.

### Actual Behavior

I had a hiatus using it, I haven't logged in to Murena since about february 2024. But now it seems to give an error when trying to log in:

```
Server unreachable
Server Message: Can't connect to host "ssl://mail.ecloud.global:993"
```

I can login normally on any other browser I have.

### Steps to reproduce

1. have an account on murena
2. add `https://murena.io/apps/snappymail/` to services
3. login

### Debug link

https://debug.ferdium.org/9ed24580-d8b7-442c-88a3-45a0a04cc819

### Screenshots

![image](https://github.com/user-attachments/assets/04eeb769-e585-4835-90b2-467f1e0a1af4)

![image](https://github.com/user-attachments/assets/f8f9b74a-ae92-4d56-ba7c-df356e8780bf)

**Comment by digitalkram** [comment]
This is not an issue with Ferdium but with the Murena service. I just checked with the infra team on their end. The issues should be gone by now. Try again to verify.

**Comment by Lauloque** [comment]
indeed it works now. thanks!
