### ISSUE TITLE
Feature: media control

### ISSUE THREAD

**Issue by paulclaude** [ferdium/ferdium-app#189]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I would like to suggest some unusual but useful feature (absent in other all-in-one messengers)

### Proposed Solution

1. allow automatic media download to pc (images, video) in services
2. allow backup to pc of any service history

### Alternatives Considered

no alternatives

**Comment by cino** [comment]
@paulclaude Thank you for taking the time to create this feature request, however we have decided to not implement this feature as we decided this to be out-of-scope of the Ferdium application.
