### ISSUE TITLE
Outlook login only opens web browser

### ISSUE THREAD

**Issue by dchmelik** [ferdium/ferdium-app#1898]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.7.6

### What Operating System are you using?

Other Linux

### Operating System Version

Devuan GNU/Linux 5

### What arch are you using?

Other (specify in Additional information section)

### Expected Behavior

Login to Outlook.

### Actual Behavior

Opens web browser.

### Steps to reproduce

1. Start Ferdium (with Outlook added).
2. Use any the three logins for Outlook.

### Additional information

n86 (a.k.a. x86, n86_64, x86_64)

**Comment by flying-sheep** [comment]
Workaround: https://github.com/ferdium/ferdium-app/issues/1782#issuecomment-2178482693

**Comment by dchmelik** [comment]
Duplicate of https://github.com/ferdium/ferdium-recipes/issues/8, https://github.com/ferdium/ferdium-recipes/issues/56, https://github.com/ferdium/ferdium-app/issues/564, https://github.com/ferdium/ferdium-app/issues/995, https://github.com/ferdium/ferdium-app/issues/1301.  Worked in past but I had to do it again; thanks.
