### ISSUE TITLE
freetube

### ISSUE THREAD

**Issue by tomaszduda23** [ferdium/ferdium-app#1907]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+request+%3Asparkles%3A%22) for a recipe request that matches the one I want to file, without success.

### Name of the service

freetube

### Features you want implemented

https://github.com/FreeTubeApp/FreeTube or https://github.com/MarmadileManteater/FreeTubeAndroid. The second one is fork of first which support PWA.

**Comment by SpecialAro** [comment]
Hello,

Given that FreeTube is not a web app but rather an executable, there is no way to implement it in Ferdium, sorry.

Closing this issue.

**Comment by tomaszduda23** [comment]
@SpecialAro the fork which I mentioned is PWA which is web base.
