### ISSUE TITLE
Add Signal Messenger

### ISSUE THREAD

**Issue by Vaishnav-Sabari-Girish** [ferdium/ferdium-app#1908]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+request+%3Asparkles%3A%22) for a recipe request that matches the one I want to file, without success.

### Name of the service

Signal

### URL of the service

https://signal.org/

### GitHub URL to a recipe that has already been created by someone else or you

NA

### Features you want implemented

Hi. First of all thank you for this app. I really love the features. If possible could you please add Signal messenger to your app list. Thank you

**Comment by SpecialAro** [comment]
Hello,

Please search the issue box before opening a new ticket.

There is already a closed issue regarding the addition of Signal to Ferdium.

Closing this ticket.

**Comment by MarcHagen** [comment]
Dupe of ticket: #1552
