### ISSUE TITLE
After starting the project, in which file can you modify the name displayed on the taskbar for this software?

### ISSUE THREAD

**Issue by skyceo121** [ferdium/ferdium-app#1921]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+request+%3Asparkles%3A%22) for a recipe request that matches the one I want to file, without success.

### Name of the service

After starting the project, in which file can you modify the name displayed on the taskbar for this software?

### GitHub URL to a recipe that has already been created by someone else or you

After starting the project, in which file can you modify the name displayed on the taskbar for this software?

### Features you want implemented

After starting the project, in which file can you modify the name displayed on the taskbar for this software?

**Comment by SpecialAro** [comment]
Hello, please refer to the Electron docs to solve that question.

https://www.electronjs.org/docs/latest/api/app#appgetname
> app.getName()
> Returns string - The current application's name, which is the name in the application's package.json file.
> 
> Usually the name field of package.json is a short lowercase name, according to the npm modules spec. You should usually also specify a productName field, which is your application's full capitalized name, and which will be preferred over name by Electron.

https://www.electronjs.org/docs/latest/api/app#appsetnamename

> app.setName(name)
> name string
> Overrides the current application's name.
> 
> Note: This function overrides the name used internally by Electron; it does not affect the name that the OS uses.
