### ISSUE TITLE
Everyday ferdium is coming down

### ISSUE THREAD

**Issue by awilliansd** [ferdium/ferdium-app#1941]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.7.7

### What Operating System are you using?

Windows

### Operating System Version

Version: 6.7.7 Server: Ferdium Server Electron: 32.1.2 Chrome: 128.0.6613.162 Node.js: 20.17.0 Platform: Windows 11 Arch: x64 Build date: Sun Sep 22 2024 01:16:21 GMT-0300 (Horário Padrão de Brasília) Git SHA: a98731a3 Git branch: release

### What arch are you using?

x64

### Last Known Working Ferdium version

6.7.7

### Expected Behavior

Works well

### Actual Behavior

The last days, I've been noticing, my ferdium is coming down. There is no specific time.

![image](https://github.com/user-attachments/assets/4a98c982-c12e-4537-a4cd-ec25f2d666bd)

### Steps to reproduce

Look the picture

**Comment by PublicBenemy** [comment]
Just stumbled upon https://github.com/ferdium/ferdium-app/issues/1926#issuecomment-2425236423 which confirms the current and past issues.

**Comment by awilliansd** [comment]
@PublicBenemy thanks

**Comment by rojosinalma** [comment]
Same here. Even though the status page says its up, it's really not.

**Comment by halphas91** [comment]
Same here !

**Comment by psabaris** [comment]
Same here  de api server , not response
"500 Internal Server Error
openresty"

**Comment by mauro-miatello** [comment]
today https://api.ferdium.org returns 500 Internal Server Error

**Comment by kamilkrzeminski** [comment]
IMO a server going down is not as big a problem as wiping all your accounts instead of using a recent local copy, rendering the application unusable.

**Comment by KazOverOnGitHub** [comment]
Same here :(

**Comment by jvleminc** [comment]
Yeap, currently several services are shown as down here: https://ferdium.github.io/ferdium-status/

**Comment by awilliansd** [comment]
It works well now

**Comment by rojosinalma** [comment]
> It works well now

No it doesn't. It's still very much down. Please don't close issues until it's completely resolved.

**Comment by awilliansd** [comment]
When I closed, API worked well, but now, service is down again
