### ISSUE TITLE
Bug: Discord immediately opens image on click on Linux

### ISSUE THREAD

**Issue by Cknight70** [ferdium/ferdium-app#195]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

v6.0.0-beta.1

### What Operating System are you using?

Other Linux

### Operating System Version

Linux 5.17.9-arch1-1 KDE X11

### What arch are you using?

x64

### Last Known Working Ferdium version

last version of ferdi did not have this issue for me

### Expected Behavior

When clicking an image in Discord normally, a pop up with the image appears within the page with the option to open in browser.

### Actual Behavior

When I click on an image in Ferdium Discord, the image immediately opens in browser. I will never see the Discord image viewer.
The image viewer looks like this 
![image](https://user-images.githubusercontent.com/28763729/170894019-30119a83-52e0-4c71-8c70-3daa42199faf.png)

### Steps to reproduce

Click on any image on Discord within the ferdium app, the image will immediately open in browser instead.

**Comment by vraravam** [comment]
Yes, looks like we are overriding the default behavior from the webpage on click handlers.

@SpecialAro - if you think that's valid, please put back the `if (url.includes('views/imgpsh_fullsize_anim'))` code and try?
