### ISSUE TITLE
Certificate problems on Meta sites?

### ISSUE THREAD

**Issue by RJVB** [ferdium/ferdium-app#1951]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.7.3

### What Operating System are you using?

Other Linux

### Operating System Version

Kubuntu 14.04 with self-updated main libraries

### What arch are you using?

x64

### Expected Behavior

No certificate error or warning messages

### Actual Behavior

Plenty of terminal messages like

```
[31890:1029/142408.475209:ERROR:ssl_client_socket_impl.cc(970)] handshake failed; returned -1, SSL error code 1, net_error -202
[31777:1029/142410.557753:ERROR:cert_verify_proc_builtin.cc(874)] CertVerifyProcBuiltin for gateway.instagram.com failed:
----- Certificate i=1 (O=Meta Platforms Inc.,L=Menlo Park,ST=California,C=US,CN=Facebook Rootcanal Prod Intermediate (e=3) CA 2023-10) -----
ERROR: No matching issuer found


[31890:1029/142410.558914:ERROR:ssl_client_socket_impl.cc(970)] handshake failed; returned -1, SSL error code 1, net_error -202
[31777:1029/142413.558406:ERROR:cert_verify_proc_builtin.cc(874)] CertVerifyProcBuiltin for gateway.instagram.com failed:
----- Certificate i=1 (O=Meta Platforms Inc.,L=Menlo Park,ST=California,C=US,CN=Facebook Rootcanal Prod Intermediate (e=3) CA 2023-10) -----
ERROR: No matching issuer found


[31890:1029/142413.574918:ERROR:ssl_client_socket_impl.cc(970)] handshake failed; returned -1, SSL error code 1, net_error -202
[31890:1029/142417.682677:ERROR:ssl_client_socket_impl.cc(970)] handshake failed; returned -1, SSL error code 1, net_error -202
```

### Steps to reproduce

1. Add Whatsapp and/or Instagram services
2. switch to either with Ferdium launched from a terminal

### Debug link

https://debug.ferdium.org/e5e3842b-6a5c-4b30-b3e1-6e6dbebb64f9

### Additional information

This started somewhere between 14:00 and 14:30 CET. For now it doesn't appear to break any functionality and I'm hoping it's a transient thing.

Is there a system store of known issuers that may need updating, and if so, which one and how?

**Comment by vraravam** [comment]
Please upgrade to the latest version of Ferdium before raising bugs. Its not possible for the volunteers to go back to a previous version to reproduce bugs, etc

**Comment by RJVB** [comment]
Does Ferdium come with its own root certificate store? If not this can hardly be linked to a specific recent version. And if it can we won't know that until there's confirmation that this issue affects only users running older versions. 

Until someone puts Ferdium in flatpak I can't run the latest version, annoyingly, I can only try to upgrade the resources subdir and snapshot_blob.bin to run against the Electron skeleton that still accepts my libc .

But if there's a more appropriate place to raise this kind of question I'll be happy to move it there.

**Comment by RJVB** [comment]
As I hoped it seems to have been a transient issue.

But did anyone else notice it??

**Comment by vraravam** [comment]
> Does Ferdium come with its own root certificate store? If not this can hardly be linked to a specific recent version. And if it can we won't know that until there's confirmation that this issue affects only users running older versions. 

No, we do not ship any kind of certificates in Ferdium.

> Until someone puts Ferdium in flatpak I can't run the latest version, annoyingly, I can only try to upgrade the resources subdir and snapshot_blob.bin to run against the Electron skeleton that still accepts my libc .

I thought flatpak was already supported as one of the installation formats. If not, maybe one of the linux contributors can help set that up.

**Comment by RJVB** [comment]
On Wednesday October 30 2024 02:27:03 Vijay Aravamudhan wrote:

>No, we do not ship any kind of certificates in Ferdium.

Thought so because I couldn't find any trace of it. As far as I understand these things that means that either something is missing from the local store of (root) certificates (I do keep mine up to date, and checked it when the issue started), or there's an upstream issue somewhere. Looks like it was the latter and I guess I should say "sorry for the noise".

>I thought flatpak was already supported as one of the installation formats. If not, maybe one of the linux contributors can help set that up.

It's not in flathub in any case, according to `flatpak search`.
