### ISSUE TITLE
Add Signal 

### ISSUE THREAD

**Issue by DelobelleEmilie** [ferdium/ferdium-app#1957]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22enhancement+%3Asparkles%3A%22) for a feature request that matches the one I want to file, without success.

### Problem Description

Hello I don't see the social network signal.

### Proposed Solution

Hello, would it be possible to add the social network signal please.

### Alternatives Considered

If this is not possible I have no alternative to propose.

**Comment by Akasiek** [comment]
Not possible for Ferdium because Signal does not have a web app.

**Comment by Akasiek** [comment]
https://www.reddit.com/r/signal/comments/v19o4y/can_we_have_signal_web/

**Comment by Richardvi** [comment]
Yes, I would really like a Signal service in Ferdium as well!

And I think a web app is available now? https://signal.org/download/windows/

**Comment by calamarain** [comment]
> And I think a web app is available now? https://signal.org/download/windows/

That's not a web app, but an application you download and run on your computer (on Windows, in this case).

**Comment by myzinsky** [comment]
any updates on this?

**Comment by calamarain** [comment]
> any updates on this?

As long as you cannot use Signal from a web browser, it’s impossible for Ferdium to support Signal.
