### ISSUE TITLE
Bug: Pasting an image from clipboard does not appear to work on Discord Linux

### ISSUE THREAD

**Issue by Cknight70** [ferdium/ferdium-app#196]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

v6.0.0-beta.1

### What Operating System are you using?

Other Linux

### Operating System Version

Linux 5.17.9-arch1-1 KDE X11

### What arch are you using?

x64

### Last Known Working Ferdium version

I did not have this issue with the last version of ferdi

### Expected Behavior

Pasting images from clipboard to the discord text box will normally show a preview of the image you can then post to chat.

### Actual Behavior

Pasting an image has no apparent result for discord in the ferdium app

### Steps to reproduce

1. open the image ``https://pbs.twimg.com/media/FT6qhhJakAAqSV4?format=jpg&name=orig`` in browser, 
2. right click and select copy image
3. ctrl v or right click and paste the image into the discord chat box
4. No apparent result

### Additional information

Possibly related to https://github.com/ferdium/ferdium-app/issues/193

**Comment by vraravam** [comment]
I am unable to reproduce this on macox x64 running Ferdium 6.0.0-beta.1

Is there any other clipboard manager in use? can someone verify this on linux?

**Comment by Cknight70** [comment]
If related I am using https://userbase.kde.org/Klipper with KDE.

Also as discussed on Discord, I was able to successfully paste the image when I take the url, put it in the Ferdium navigation bar (I have that in "always visible mode"), right clicked, "Copy image", and then came back using the back button in the navbar, pasted the clipboard contents there.

**Comment by MimaHakurei** [comment]
I'm using stock GNOME on latest Arch x86_64.
I also experience the bug on Discord sessions.

Element sessions don't appear to be affected (although it used to affect Element in the past)

**Comment by SpecialAro** [comment]
I am not able to reproduce this on Ferdium 6.0.0-nightly.49 on Windows 11 x64.

Maybe it's an issue with the native clipboard manager on Linux?

**Comment by MimaHakurei** [comment]
Maybe, but I don't know why it would only affect Discord and only in Ferdium...

**Comment by palepinkdot** [comment]
@vraravam Confirmed on Arch using xfce on Ferdium 6.0.0-beta.1.

**Comment by Janrupf** [comment]
Interesting, I'm also experiencing this bug - _also_ running Arch. So far I have only seen people using Arch Linux having this problem.

For the sake of completeness, my system information:
```
OS: Arch Linux x86_64 
Kernel: 5.18.12-zen1-1-zen 
Resolution: 1920x1080, 1920x1080 
WM: i3 
X.Org version: 21.1.4
```

And the package information:
```
Name            : ferdium-bin
Version         : 6.0.0.nightly.101-1
```

Copy and paste is working in all other services, only Discord is affected.

**Comment by mcmxcdev** [comment]
Cannot reproduce this on Ubuntu 23.04 with 6.5.0-nightly.17:

[Screencast from 2023-10-01 13-50-32.webm](https://github.com/ferdium/ferdium-app/assets/16797721/4b91f588-cfd7-4d15-9b72-16802703ff78)

**Comment by Cknight70** [comment]
I have not had this issue on arch Linux for quite some time either since I re installed my system. 🤷
I will close the bug, if anyone is still having the issue they can provide more up to date information.
