### ISSUE TITLE
Feature: Google Keep as Todos

### ISSUE THREAD

**Issue by yarons** [ferdium/ferdium-app#197]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Although the Todos currently supports Google Tasks I'm sometimes using Google Keep although it's not the best approach for managing task, is it possible to add that as well?

### Proposed Solution

Adding Google Keep as a Todos option.

### Alternatives Considered

Google Tasks, Microsoft ToDo, I don't like any of these.

**Comment by SpecialAro** [comment]
Hello @yarons , thank you for raising this ticket.

Although this can be considered, you can currently select "Other Service" in the Todo Server dropdown under Settings and paste the "Custom Todo Server" URL for the application you need (I imagine that, in this case, it should be: https://keep.google.com/).

![image](https://user-images.githubusercontent.com/37463445/171208617-29233d4c-6f0d-4a0b-8ca3-89563b170530.png)
