### ISSUE TITLE
No AUR package found for electron33

### ISSUE THREAD

**Issue by skf-funzt** [ferdium/ferdium-app#1988]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

none - wanted to onboard

### What Operating System are you using?

Other (specify below)

### Operating System Version

Manjaro

### What arch are you using?

x64

### Expected Behavior

Installing Ferium on Arch Linux using

```
yay -S ferdium-bin
# or, to compile yourself
yay -S ferdium
```

should install the application.

### Actual Behavior

```
$ yay -Sy ferdium-bin
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 multilib is up to date
 -> No AUR package found for electron33
 -> could not find all required packages: electron33

$ yay -Sy ferdium
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 multilib is up to date
 -> No AUR package found for electron33
 -> could not find all required packages: electron33
```

Missing package `electron33``

### Steps to reproduce

1. Install ferdium[-bin] on arch

**Comment by Alphrag** [comment]
I think this problem is specific to Manjaro which has not yet put `electron33` into [stable distribution](https://manjaristas.org/branch_compare?q=electron33) whereas it is available as an [AUR package](https://archlinux.org/packages/extra/x86_64/electron33/). Please see also the comments in #1610.

**Comment by skf-funzt** [comment]
Thanks @Alphrag for pointing that out.
I'll close the ticket.
