### ISSUE TITLE
Bug: Context & Application menus become hard to read on hover

### ISSUE THREAD

**Issue by keunes** [ferdium/ferdium-app#199]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.49

### What Operating System are you using?

Ubuntu

### Operating System Version

Ubuntu 18.04.6 LTS

### What arch are you using?

x64

### Expected Behavior

Always display menus with legible text/font.

### Actual Behavior

Application and context menus open legible, but when hovering become hard to read (extra bold, but in an ugly way).

### Steps to reproduce

1. Open the application menu
2. Hover mouse over the menu
3. See bug

### Screenshots

On open:
![Screenshot from 2022-05-31 07-48-00](https://user-images.githubusercontent.com/11229646/171104735-0a5346c1-2c18-43f8-a273-02095b4c457c.png)

On hover:
![Screenshot from 2022-05-31 07-49-18](https://user-images.githubusercontent.com/11229646/171104768-cb921106-412e-462d-8637-2ffded454c89.png)

**Comment by cino** [comment]
@keunes Can you confirm if this is still an issue on the latest version? I'm not able to replicate this issue on a VM with Ubuntu 22.04

**Comment by keunes** [comment]
Hi @cino,

Yep, I unfortunately can still confirm. I should note that I installed Ferdium as Snap - is that the case for you, too? I'm starting to think it's related to #200.

```
Version: 6.0.0-nightly.102
Server: No Server
Electron: 19.0.8
Chrome: 102.0.5005.148
Node.js: 16.14.2
Platform: Linux 4.15
Arch: x64
Build date: Sun Jul 17 2022 04:45:52 GMT+0200 (Central European Summer Time)
Git SHA: b85efe34
Git branch: nightly
```

**Comment by cino** [comment]
@keunes That is not the case for me unfortunately as I don't think that's possible for ARM at the moment (only seeing the AMD). However, I don't think that should be the deciding difference.

Do you have any custom theming on your Linux environment?

**Comment by keunes** [comment]
> Do you have any custom theming on your Linux environment?

Nope.
Maybe the fact that I'm running 18.04.6 LTS rather than 22.04 makes a difference. And as noted in #200 my session uses GNOME Shell 3.28.4 // xorg (22.04 uses Wayland by default).

**Comment by mcmxcdev** [comment]
I assume this was either an Electron bug or something related to xorg. 

@keunes Do you still encounter these rendering issues?

**Comment by keunes** [comment]
Hi @mcmxcdev,

Yes - none of the elements (Ferdium, gnome) updated on my system since, so the situation is still as it was.

According to the debug window I'm now on Electron 25.3.2 and with xorg.

**Comment by mcmxcdev** [comment]
Okay, I would make the same decision as with the about window: 

Ubuntu v18 is pretty old according to https://endoflife.date/ubuntu and not officially supported anymore except for ESM, so we should treat it the same way. Closing.
