### ISSUE TITLE
Bug: About & file selection windows doesn't have a background

### ISSUE THREAD

**Issue by keunes** [ferdium/ferdium-app#200]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.49

### What Operating System are you using?

Ubuntu

### Operating System Version

18.04.6 LTS

### What arch are you using?

x64

### Expected Behavior

About & file selection windows have a background.

### Actual Behavior

About & file selection windows have no background - is text on a transparent area.

### Steps to reproduce

1. Open About window.
2. See error.

### Screenshots

![Ferdium About backround](https://user-images.githubusercontent.com/11229646/171105329-8865bb62-a818-48a8-b10d-d2c33a2a0e2d.png)

![Ferdium transparency issue](https://user-images.githubusercontent.com/11229646/171113208-84c81fa3-a159-4a4b-bbae-503be36d4617.png)

**Comment by NathanaelGandhi** [comment]
@keunes I couldn't replicate this issue on an ubuntu 18.04 vm with nightly 49. Can you please install the latest nightly and confirm if the issue still exists?

**Comment by keunes** [comment]
Hi @NathanaelGandhi,
Sorry for replying only now. I just checked with nightly 86 and I still have the issue:
![image](https://user-images.githubusercontent.com/11229646/177057135-7b252af9-c69c-45ca-b9c8-e42907604595.png)

I should note that I've been upgrading this machine at least once.
GNOME Shell 3.28.4 // using xorg

**Comment by cino** [comment]
@keunes Is this still an active issue? (Kinda hoping it's randomly fixed, otherwise going to setup a ubuntu vm)

**Comment by mcmxcdev** [comment]
The "About" window looks fine on my end:
![image](https://github.com/ferdium/ferdium-app/assets/16797721/219bd120-fb09-4a64-8f07-1703f58ec6af)

Same for the file dialog picker, so I would close this. 

@keunes Let us know in case this is still a problem.

**Comment by keunes** [comment]
Hi @mcmxcdev
This still is an issue on my system. But given that, as noted above, I'm on an incredibly old system (and don't currently use Ferdium because it's too heavy) it's fine for me to leave it unresolved.

**Comment by mcmxcdev** [comment]
Yeah, v18 is pretty old according to https://endoflife.date/ubuntu and not officially supported anymore except for ESM, so we should treat it the same way.
