### ISSUE TITLE
How do I change the maximize minimization in the top right corner and close the button icon

### ISSUE THREAD

**Issue by Jumao-OC** [ferdium/ferdium-app#2008]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22enhancement+%3Asparkles%3A%22) for a feature request that matches the one I want to file, without success.

### Problem Description

How do I change the maximize minimization in the top right corner and close the button icon

### Proposed Solution

How do I change the maximize minimization in the top right corner and close the button icon

### Alternatives Considered

How do I change the maximize minimization in the top right corner and close the button icon

### Additional Information

How do I change the maximize minimization in the top right corner and close the button icon

**Comment by SpecialAro** [comment]
The only way to change the maximize and close buttons of the ribbon is to code it by referring to the electron documentation.

As this is out of scope of this project I'm closing the issue.

**Comment by Jumao-OC** [comment]
He used <titleBar>the component, which seems to support menu templates, is it possible to pass the menu template to implement it

**Comment by Jumao-OC** [comment]
> The only way to change the maximize and close buttons of the ribbon is to code it by referring to the electron documentation.
> 
> As this is out of scope of this project I'm closing the issue.

He used <titleBar>the component, which seems to support menu templates, is it possible to pass the menu template to implement it

**Comment by Jumao-OC** [comment]
> The only way to change the maximize and close buttons of the ribbon is to code it by referring to the electron documentation.
> 
> As this is out of scope of this project I'm closing the issue.

<TitleBar>

**Comment by Jumao-OC** [comment]
> The only way to change the maximize and close buttons of the ribbon is to code it by referring to the electron documentation.
> 
> As this is out of scope of this project I'm closing the issue.

titleBar Component
