### ISSUE TITLE
Feature: Add audio-record plug [Snap]

### ISSUE THREAD

**Issue by NathanaelGandhi** [ferdium/ferdium-app#214]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

The audio-record interface should be implemented to allow the system audio service, such as PulseAudio, to enable microphone/audio recording hardware access (in Snap). 
Ref: https://snapcraft.io/docs/audio-record-interface

This is preferred to implementing PulseAudio directly as that was depreciated in snapd 2.41.
Ref: https://snapcraft.io/docs/pulseaudio-interface

Note: The audio-playback interface is auto-connected.

### Proposed Solution

Add audio-record to [/electron-builder.yml](https://github.com/ferdium/ferdium-app/blob/356c87fb2e87c73161b7e41f21facc068e8dad88/electron-builder.yml) snap plugs.

### Alternatives Considered

Manually connecting ferdium:pulseaudio - depreciated.

### Additional Information

audio-record (and camera) do not auto-connect, requiring manual connection once ferdium is installed from snap. This should be addressed by requesting auto-connection from snapcraft reviewers. This should be tracked as a separate issue. The ferdium website should also be updated with the corrected snap connect command until auto-connection has been granted.
Ref: https://snapcraft.io/docs/process-for-aliases-auto-connections-and-tracks

**Comment by vraravam** [comment]
@NathanaelGandhi - now that #215 has been merged (and it should appear in the next nightly in a few mins) - please verify and close this ticket?

**Comment by NathanaelGandhi** [comment]
Works as expected. 

Plug shows up under snap connections
![image](https://user-images.githubusercontent.com/36506137/173058131-ef61ba2d-08bb-4d07-b874-a64a718ac1aa.png)

Once the plug is activated using ```snap connect ferdium:audio-record``` microphone access works as expected (tested using whereby service).

https://github.com/ferdium/website/pull/21 can move forward
