### ISSUE TITLE
Bug: No user prompt for snap interfaces that require manual connection

### ISSUE THREAD

**Issue by NathanaelGandhi** [ferdium/ferdium-app#216]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly-alphrag.52

### What Operating System are you using?

Other Linux

### Operating System Version

Arch Linux x86_64 5.17.9-arch1-1 

### What arch are you using?

x64

### Last Known Working Ferdium version

none

### Expected Behavior

Snap plugs (camera & audio-record) should auto-connect to improve the user experience. When integrating services that use webcam or voice services, these can not be enabled until the user manually runs interface connect for Snap versions of ferdium.

### Actual Behavior

Snap plugs (camera & audio-record) require manual connection using ```snap connect ferdium:camera
snap connect ferdium:audio-record```
EDIT ADD: removeable-media interface added in #227 

### Steps to reproduce

1. Install ferdium snap (edge or beta)
2. run ```snap connections --all | grep ferdium```
3. Slots for camera & audio-record show ```-```

### Additional information

The problem was initially outlined in "Additional Information" #214.

This should be addressed by requesting auto-connection from snapcraft reviewers.
Ref: https://snapcraft.io/docs/process-for-aliases-auto-connections-and-tracks

Options:
- ~~Requester creates a forum post in the store-requests category and makes case for change. https://forum.snapcraft.io/c/store-requests~~
- ~~If auto-connection is not granted, ~~we can have the snap check if the interface is connected via snapctl is-connected <iface> and instruct the user to use the snap connect CLI command or connect via the snap-store/gnome-software GUI.

Once a solution is achieved, the connect commands should be removed from the website download instructions (for snap) https://github.com/ferdium/website/blob/b8db9ae4ac73e6e94b12a50976f3fe3380c7ecf6/pages/download.tsx#L55

**Comment by 3v1n0** [comment]
Given than ferdium can contain ANY web application IMHO it's definitely safer to leave this manual.

**Comment by NathanaelGandhi** [comment]
So the option to "have the snap check if the interface is connected via snapctl is-connected and instruct the user to use the snap connect CLI command" is probably our best bet then, balances between security and useability. 

The reason I see this as a potential problem is that going to a software download page (even snap) isn't standard, just issuing snap install from CLI and expecting the program to work unless prompted otherwise i'm assuming is common practice.

**Comment by SpecialAro** [comment]
@NathanaelGandhi , are you using 6.0.0-nightly-alphrag.52 ? You should be using the official version 😄

**Comment by NathanaelGandhi** [comment]
@SpecialAro haha yeah, I'm not on that anymore. Bounced around a few different versions, now on the 6.0.0-nightly.92 snap

**Comment by cino** [comment]
@NathanaelGandhi Is this issue ready to be closed or is there still work to be done? :)
