### ISSUE TITLE
Bug: Can't open links on todoist as Ferdium Todos

### ISSUE THREAD

**Issue by rishubil** [ferdium/ferdium-app#222]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly-54

### What Operating System are you using?

macOS

### Operating System Version

macOS Monterey 12.4

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Todoist can enter a url in title or description of task, and it should be open when it clicked.

### Actual Behavior

It does nothing when I click the link on task, neither left and right mouse button.
but it works if I click it with left mouse button with pressing command key.

### Steps to reproduce

1. Enable Ferdium Todos
2. Set Todo Server to Todoist
3. Open Ferdium Todos
4. Login Todoist
5. Create new task with url(ex https://www.google.com/) on title or description
6. Click the link

**Comment by SlanDF** [comment]
This issue also applies to ticktick

**Comment by SpecialAro** [comment]
This should apply to all Todos services. Needs fix.

**Comment by bjoern-zapadlo-ef** [comment]
Are there any plans when this will be fixed?

**Comment by cino** [comment]
@bjoern-zapadlo-ef Yes, looking at this atm.

**Comment by maxandersen** [comment]
anything one can do to help here? makes todoist rather harder to use in ferdium :/

**Comment by maxandersen** [comment]
found https://github.com/ferdium/ferdium-recipes/issues/192 and same fix works - don't use todoist as ferdium's todo app.

now i can use links again...but have no todo app in ferdium..
