### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by thwaller** [ferdium/ferdium-app#225]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-beta.1

### What Operating System are you using?

Other Linux

### Operating System Version

Fedora 36

### What arch are you using?

x64

### Expected Behavior

Dark mode to work as it does on other services.

### Actual Behavior

Dark mode does not properly apply itself. IT is dark only in some areas, mainly dialer buttons.

### Steps to reproduce

1. Set the service to enable dark mode
2. Toggle dark mode in the UI
3. View the Voice service

### Additional information

installed via Flatpak.

**Comment by vraravam** [comment]
@thwaller - thanks for trying out Ferdium, but:
1. Please specify which service is causing the issue
2. Please log all service-specific issues in the https://github.com/ferdium/ferdium-recipes/issues board

**Comment by thwaller** [comment]
It appears it did not add a title, interesting. Sorry about that. The service is Google Voice.
