### ISSUE TITLE
Bug: Ferdium only shows blank window

### ISSUE THREAD

**Issue by lukasmichel** [ferdium/ferdium-app#230]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0.nightly.56.r5506.cf182890-1 (AUR ferdi-git package)

### What Operating System are you using?

Other Linux

### Operating System Version

Archlinux

### What arch are you using?

x64

### Expected Behavior

When starting ferdium, the window should show my services and I should be able to interact with them.

### Actual Behavior

After starting (and opening) ferdium, the window remains blank (see screenshot below).
I get the following log output:

### Steps to reproduce

Launch ferdium

### Debug link

Not Possible. The help menu has no entries (show `(empty)`

### Screenshots

Screenshot of the ferdium window, just to make sure we talk about the same thing when I say it remains blank
![Screenshot_20220611_132620](https://user-images.githubusercontent.com/20126509/173185898-4618f7ea-f18c-4e4e-9331-ee214bb1316c.png)

### Additional information

```bash
$ ferdium --enable-logging             
[37145:0611/132530.385413:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
[37177:0611/132530.411115:WARNING:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
[37145:0611/132530.644542:INFO:CONSOLE(111)] "%cDownload the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
You might need to use a local HTTP server (instead of file://): https://reactjs.org/link/react-devtools-faq font-weight:bold", source: /opt/ferdium-git/resources/app.asar/node_modules/@sentry/utils/dist/instrument.js (111)
[37145:0611/132531.169996:INFO:CONSOLE(943)] "Uncaught Error: Cannot find module 'react-virtualized'
Require stack:
- /opt/ferdium-git/resources/app.asar/node_modules/electron-react-titlebar/dist/renderer.js
- /opt/ferdium-git/resources/app.asar/components/layout/AppLayout.js
- /opt/ferdium-git/resources/app.asar/containers/layout/AppLayoutContainer.js
- /opt/ferdium-git/resources/app.asar/routes.js
- /opt/ferdium-git/resources/app.asar/index.html", source: node:internal/modules/cjs/loader (943)
[37145:0611/132532.337313:INFO:CONSOLE(111)] "Could not connect to Sentry main process. Did you call init in the Electron main process?", source: /opt/ferdium-git/resources/app.asar/node_modules/@sentry/utils/dist/instrument.js (111)
```

**Comment by lukasmichel** [comment]
I have just checked my package cache, and I found a version that still worked: `6.0.0.nightly.55.r5502.6cbb438a-1`

**Comment by NathanaelGandhi** [comment]
@lukasmichel are you using the ferdi or ferdium aur package?

Ferdium https://aur.archlinux.org/packages/ferdium-git

**Comment by NathanaelGandhi** [comment]
The recommended install methods from the aur on the [ferdium website](https://ferdium.org/download) are

```
yay -S ferdium-bin
// or, to compile yourself
yay -S ferdium
```

**Comment by lukasmichel** [comment]
I am using the ferdium-git package. Sorry, I mistyped it in my original post.

**Comment by NathanaelGandhi** [comment]
@lukasmichel im unfortunately away from my computer for the weekend, does 6.0.0.nightly.57.r5510.20beb97e-1 fix your issue?

**Comment by lukasmichel** [comment]
no, unfortunately not. I am currently trying to find the responsible commit, but given my very limited experience with npm, this might take a while

**Comment by NathanaelGandhi** [comment]
Do you experience this issue with another package type of the same version? Flatpak/snap?

**Comment by nathanaelhoun** [comment]
#235 signals the same problem on Manjaro and W11.

**Comment by patrickclark9** [comment]
> Do you experience this issue with another package type of the same version? Flatpak/snap?

I have the same issue, with all packages on Arch (ferdium-git, ferdium, and ferdium-bin), flatpak works correctly, no blank screen, for me at least. Haven't tried the snap version

**Comment by vraravam** [comment]
Building the same code from source on local, passes though:
<img width="284" alt="Screenshot 2022-06-12 at 5 54 33 PM" src="https://user-images.githubusercontent.com/69629/173233030-43db3db3-e512-4ac0-a8b9-7ab902b88478.png">

**Comment by nathanaelhoun** [comment]
On my archlinux machine, with a clean build (`CLEAN=true ./scripts/build-unix.sh`) on `tag:6.0.0-nightly.57`, the problem is still present.

**Comment by vraravam** [comment]
Downloaded the built binaries from GH, `nightly 56` works, while `nightly 57` doesn't - tested on my mac.

**Comment by lukasmichel** [comment]
I also tested the GH binaries by editing the PKGBUILD of [ferdium-bin](https://aur.archlinux.org/packages/ferdium-bin) AUR package accordingly. nightly.56 works fine, nightly.57 doesn't and logs an error about missing dependency `react-virtualized`.

**Comment by pepper3k** [comment]
I can confirm the same bug with Win7x64 nightly-57.
Installing nightly-56 solves the problem.

**Comment by Jvlsc** [comment]
@vraravam you removed the sentry integration in the client, could be an issue in the server side with sentry?

**Comment by lukasmichel** [comment]
> @vraravam you removed the sentry integration in the client, could be an issue in the server side with sentry?

That's rather unlikely, I experienced the problem with the blank window before the removal of sentry. I actually only reported the sentry usage because I realized sentry being active when I tried to debug this issue.

**Comment by jan-moeller** [comment]
Confirming this for Ubuntu 22.04 with the snap package 6.0.0-nightly.57.

Edit: 6.0.0-nightly.56 still works.

**Comment by Shadester** [comment]
This is the error I see on my mac with build 57.
Uncaught Error: Cannot find module 'react-virtualized'
```
Require stack:
- /Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/electron-react-titlebar/dist/renderer.js
- /Applications/Ferdium.app/Contents/Resources/app.asar/components/layout/AppLayout.js
- /Applications/Ferdium.app/Contents/Resources/app.asar/containers/layout/AppLayoutContainer.js
- /Applications/Ferdium.app/Contents/Resources/app.asar/routes.js
- /Applications/Ferdium.app/Contents/Resources/app.asar/index.html
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at i._resolveFilename (node:electron/js2c/renderer_init:33:1095)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at i._load (node:electron/js2c/renderer_init:33:356)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at menu-list-item.tsx:4:108
    at Object.<anonymous> (/Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/electron-react-titlebar/dist/renderer.js:1:8591)
    at Object.<anonymous> (/Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/electron-react-titlebar/dist/renderer.js:3:3)```

node:internal/modules/cjs/loader:943

**Comment by kris7t** [comment]
~For me, even https://github.com/ferdium/ferdium-app/commit/858d9b524cfdfcacc01f8b5d45884d28001cba7d seems to be broken right now (tried `CI=true npm run build --x64 --linux --dir`). Most notably, the `build/node_modules` directory does not contain any `react-virtualized`, so no wonder it doesn't get packaged into `app.asar`.~

~On the other hand, I managed to compile and run https://github.com/ferdium/ferdium-app/commit/6cbb438a0cb76dfa6e6363b31673a42b7abdb574, so the bug might be somewhere in between.~

Scratch that, now I can't even build https://github.com/ferdium/ferdium-app/commit/6cbb438a0cb76dfa6e6363b31673a42b7abdb574. Maybe its some weirdness with the toolchain? I'm deleting `node_modules` are reinstalling (dev) dependencies to see if that makes a difference.

---

My build is still broken even after reinstalling the toolchain. Investigating the build that I have installed now to see if there's a difference.

**Comment by vraravam** [comment]
> Most notably, the `build/node_modules` directory does not contain any `react-virtualized`, so no wonder it doesn't get packaged into `app.asar`.

This hasn't changed in the recent past - and `electron-react-titlebar` is still being referenced in the main `dependencies` not `devDependencies`.

That being said, i also noticed this module missing in `./node_modules`

**Comment by kris7t** [comment]
`electron-react-titlebar` in `dependencies` seems correct, since we're apparently using it:

```
$ rg electron-react-titlebar
package.json
74:    "electron-react-titlebar": "^1.1.0",

package-lock.json
39:        "electron-react-titlebar": "^1.1.0",
11695:    "node_modules/electron-react-titlebar": {
11697:      "resolved": "https://registry.npmjs.org/electron-react-titlebar/-/electron-react-titlebar-1.1.0.tgz",
40059:    "electron-react-titlebar": {
40061:      "resolved": "https://registry.npmjs.org/electron-react-titlebar/-/electron-react-titlebar-1.1.0.tgz",

src/index.ts
496:  require('electron-react-titlebar/main').initialize();

src/styles/main.scss
1:@import './node_modules/electron-react-titlebar/assets/style';

src/components/layout/AppLayout.js
5:import { TitleBar } from 'electron-react-titlebar/renderer';

src/components/auth/AuthLayout.js
4:import { TitleBar } from 'electron-react-titlebar/renderer';
```

But the question is why aren't we pulling in its transitive dependencies properly?

**Comment by kris7t** [comment]
Apparently, the build that I have working correctly installed indeed has an `app.asar/node_modules/react-virtualized`.

It also has `electron-react-titlebar@1.1.0`, which pulls in `react-virtualized@^9.22.3` as a `dependency`.

In contrast, our `electron-react-titlebar@^1.1.0` dependency pulls in `electron-react-titlebar@1.2.0` (released 2 days ago) despite `@1.1.0` being specified in `package-lock.json`. Apparently, `electron-builder` ignores `package-lock.json` when reinstalling our dependencies to `build/node_modules`.

It seems `electron-react-titlebar@1.2.0` has moved from `react-virtualized` to `react-window: https://github.com/KochiyaOcean/electron-react-titlebar/commit/c01ae646bcdc81fe7df64da15a96a072140c8263#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L64-R65

I guess the problem is caused by using a different version of `electron-react-titlebar` during development vs production. I'll try to bump it to `1.2.0` in the (top-level) `package.json` to see whether it helps.

**Comment by vraravam** [comment]
@kris7t : I just raised https://github.com/ferdium/ferdium-app/pull/236 with an explicit dependency on `react-virtualized`. Is that not needed any more?

On a side note - this is exactly the reason I dislike using the open-ended dependency specification! If the fix is going to take a long time, we should just lock the dependencies and move ahead. wdyt?

**Comment by kris7t** [comment]
We shouldn't need #236 -- it doesn't fix the problem at all, only hides it.

`package-lock.json` should already lock the dependencies, so we should be instead thinking about how to make sure `electron-builder` uses that properly.

But this problem is much mysterious: it looks like `electron-react-titlebar@1.2.0` has the `@1.1.0` bundles in its `dist` directory! The files in `src` are correct an reference `electron-window`, but the bundles are just outdate. I suspect this is a packaging error in `electron-react-titlebar` and I'll raise an issue there.

In the meantime, we should lock `electron-react-titlebar@1.1.0` with two TODOs:
* Bump to 1.2.0 when the packaging error is fixed.
* Try to make `electron-builder` respect `package-lock.json`

**Comment by vraravam** [comment]
i can change the PR's branch to doas per your suggestion.

**Comment by kris7t** [comment]
Cool, thanks! This patch seems to be working for me:

```diff
diff --git a/package.json b/package.json
index 0c931c20..492ed74a 100644
--- a/package.json
+++ b/package.json
@@ -70,7 +70,7 @@
     "debug": "4.3.4",
     "electron-dl": "^3.3.1",
     "electron-find": "^1.0.7",
-    "electron-react-titlebar": "^1.1.0",
+    "electron-react-titlebar": "1.1.0",
     "electron-updater": "^4.6.5",
     "electron-window-state": "^5.0.3",
     "fast-folder-size": "^1.6.1",
```

**Comment by vraravam** [comment]
If it works for you - please approve the PR?

**Comment by kris7t** [comment]
I opened an issue for the dependency packaging: https://github.com/KochiyaOcean/electron-react-titlebar/issues/27

**Comment by lukasmichel** [comment]
#236  works for me, too.
