### ISSUE TITLE
Feature: Github discussions

### ISSUE THREAD

**Issue by HenrijsS** [ferdium/ferdium-app#231]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Seeing the absolute sh*tshow that was going on with Ferdi, it would be a great idea to move all talks about Ferdium here in the repo. (Maybe, in case something goes south again).

### Proposed Solution

Enbale the Github Discussion tab so people can communicate with each other, help answer questions or suggest ideas without cluttering up the Issue tracker.

### Alternatives Considered

Welp. Discord's always a thing, but it's too bloated.

**Comment by vraravam** [comment]
Looks like `Discussions` have been turned on. Closing this ticket.

**Comment by HenrijsS** [comment]
![image](https://user-images.githubusercontent.com/49265222/173549303-69cc6eac-2a5f-4334-8eb8-56ad29c83c1c.png)

@vraravam Still doesn't show for me. Is it only closed to participants?

**Comment by vraravam** [comment]
hmm - not sure if that's the case. Could you please ask in the Discord room? Someone else is managing these settings in GH.

**Comment by SpecialAro** [comment]
![image](https://user-images.githubusercontent.com/37463445/173579163-d3972805-7f80-45f9-8d1e-0d9db2b915d2.png)

Enabled 😄

**Comment by HenrijsS** [comment]
@SpecialAro And can't create a new discussion :D

**Comment by SpecialAro** [comment]
Oh god XD

@dqos can you take a look pls?

**Comment by dqos** [comment]
@HenrijsS this should be working now: https://github.com/ferdium/ferdium-app/discussions
