### ISSUE TITLE
Feature: Custom Search Engine

### ISSUE THREAD

**Issue by pepper3k** [ferdium/ferdium-app#240]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Search engines gather a lot of personally identifiable information and also contain website trackers that track web usage across many sites. For this reason it is desirable to be able to configure a search engine that respects privacy like startpage.com and many others.

For the many people who are concerned with protecting their privacy, the search functionality is unusable.

### Proposed Solution

1. Include the ability to add custom search engine URL. (Like in chrome)
2. Set startpage.com as the default search engine to respect privacy by default.

### Alternatives Considered

I see no other solution.

### Additional Information

Also, seeing as how neither google or duckduckgo support this project in any way, it seems unnecessary to set them as default.

**Comment by vraravam** [comment]
I like the idea of adding startpage as another search engine.

I also dont use Chrome a lot, but for curiosity I went and saw the UI that they have:
<img width="677" alt="Screenshot 2022-06-13 at 7 07 51 AM" src="https://user-images.githubusercontent.com/69629/173264484-fc1690d3-d509-46a8-9ca9-7f0761ddad55.png">
Getting something similar in Ferdium, where the url is editable, is quite cumbersome.

As a simpler approach, I would suggest that we have a hard-coded list in a drop down, where each has a hardcoded url. In addition to this, we can have an `Other` entry, which when chosen can expose a textbox where the user can type in their choice. (The textbox can remain shown, but non-editable for the default search engines that are hardcoded OOTB). That way, the preference can always be from what's in the textbox. This is how the `Other` option in the Ferdium ToDos dropdown in the Settings screen works.

**Comment by pepper3k** [comment]
you're right, hardcoding is much simpler, i think we should leave a customizable field for after a stable release

**Comment by vraravam** [comment]
I will pick this up this weekend or earlier if I get time.

**Comment by vraravam** [comment]
This has now been merged for the hardcoded `startpage.com`. I will close this issue now, we can resurrect later (post a stable release)

**Comment by o0-o** [comment]
This was closed but only half implemented.

Can I request to have this reopened to address:

> 1. Include the ability to add custom search engine URL. (Like in chrome)

Or would it be preferable to open a new issue?

The ability to use [SearXNG](https://github.com/searxng/searxng) is important to the pro-privacy/self-host community and inherently requires a custom search engine URL.
