### ISSUE TITLE
Bug: Figma "Loading Figma"

### ISSUE THREAD

**Issue by macuser79** [ferdium/ferdium-app#244]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.58

### What Operating System are you using?

macOS

### Operating System Version

Mojave

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Ferdium version

6.0.0-nightly.58

### Expected Behavior

After logging into Figma I expected not to have the page loading

### Actual Behavior

After logging into Figma, the page being loaded remains with the message "Loading Figma" in the center

### Steps to reproduce

1. Open Ferdium
2. Add Figma service
3. Login su Figma Service
4. Loading View

### Screenshots

<img width="700" alt="Screenshot 2022-06-13 at 14 13 41" src="https://user-images.githubusercontent.com/4025071/173351364-c21ebf3f-5322-4788-a2bd-b50178655b85.png">

### Additional information

Mac OS X M1

**Comment by SpecialAro** [comment]
Hello @macuser79 , thank you for logging this issue. Can you please try to reload all services/reload Ferdium/restart Ferdium and see if the same happens? Thank you.

**Comment by macuser79** [comment]
Hello,
restarting the Ferdium app, the problem seems to have been solved.
I apologize for not trying this earlier

**Comment by mydarkstar** [comment]
Duplicate of #157
