### ISSUE TITLE
Bug: Ferdium doesn't load services any more

### ISSUE THREAD

**Issue by alecive** [ferdium/ferdium-app#249]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly-59

### What Operating System are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

Ferdium loads services at startup

### Actual Behavior

At startup, Ferdium doesn't load services. It is stuck in "Couldn't load services and user information":

![image](https://user-images.githubusercontent.com/4378663/173574334-99568330-fec8-4c07-8443-62ec18e4eddc.png)

If I press on "Get started", it doesn't find services:

![image](https://user-images.githubusercontent.com/4378663/173574478-4bab2585-3ff7-4104-bcff-d0c2c7473435.png)

I was originally on beta-1, now I upgraded to nightly-59 and nothing has changed. I suspect the services server is down?

### Steps to reproduce

1. Open Ferdium

**Comment by SpecialAro** [comment]
Hello @alecive . Some users are reporting this issue as well. This is caused by the Ferdi API Server and not by any Ferdium Services. Can you please check if you're currently logged in with a Ferdi account/using Ferdi Server?

**Comment by alecive** [comment]
I suspect so. However, how can I check? My account page doesn't load any more either.

**Comment by diego-treitos** [comment]
I am using Ferdi (looking into a switch to Ferdium) and it is happening to me too.

I do **not** have an account in Ferdi (all should be local), however, for some reason, Ferdi/Ferdium makes a couple of requests to `api.getferdi.com`:

* `https://api.getferdi.com/v1/me`
* `https://api.getferdi.com/v1/me/services`

I don't understand why this is done even when there is no remote account and all services are defined locally but I think that Ferdium should get rid of these requests in case accounts are local or at least allow the use of the app if the API server is down...

**Comment by OskarEichler** [comment]
Same issue here - how can we transition away from Ferdi server?

**Comment by SpecialAro** [comment]
> I am using Ferdi (looking into a switch to Ferdium) and it is happening to me too.
> 
> I do **not** have an account in Ferdi (all should be local), however, for some reason, Ferdi/Ferdium makes a couple of requests to `api.getferdi.com`:
> 
> * `https://api.getferdi.com/v1/me`
> * `https://api.getferdi.com/v1/me/services`
> 
> I don't understand why this is done even when there is no remote account and all services are defined locally but I think that Ferdium should get rid of these requests in case accounts are local or at least allow the use of the app if the API server is down...

If you're getting calls to api.getferdi.com then **you're** connected to the Ferdi Server.

Many users are reporting this, specially the ones that used any script to migrate from Ferdi to Ferdium.

If you want to switch to an **offline account**, just go to Settings > Logout/Exit Session > Use Ferdium without an account.

If you want to switch to Ferdium server you:
* Go to to Settings > Logout/Exit Session > Change Server > "Ferdium (Default)" > Submit > Create a free account
* (optional - might not be working given that Ferdi API is offline) Export your settings from the Ferdi API (by going to https://api.getferdi.com/, login and export) and import your account on Ferdium Server (https://api.ferdium.org/) by login and go to import. Then, restart Ferdium.

**Comment by Drek282** [comment]
Ferdi is down.  The Ferdi API is down.  The Ferdi domain is inaccessible.  So anything that relies on any of that right now will not work.  There could be all kinds of reasons for this, so it's pointless to speculate.  Hopefully the outage  won't last long.

**Comment by Drek282** [comment]
But yes, it's a little stupid that a local account still requires access to the Ferdi API.  That kinda spoils the whole point of choosing the local account option...

**Comment by SpecialAro** [comment]
> But yes, it's a little stupid that a local account still requires access to the Ferdi API. That kinda spoils the whole point of choosing the local account option...

Again, a local account doesn't require access to any API. People are just using the Server option without knowing...

**Comment by alecive** [comment]
I've moved to Ferdium's server. Everything seems to be working fine. Closing as this fixes the issue (and I'm happy to move away from Ferdi's server anyways). Thanks for the help!

On a separate note, @SpecialAro I think it would be great to still be able to use servers, but also caching the list of services locally so that when the internet goes down one may be able to access e.g. Gmail offline and stuff like that.

**Comment by Drek282** [comment]
> > But yes, it's a little stupid that a local account still requires access to the Ferdi API. That kinda spoils the whole point of choosing the local account option...
> 
> Again, a local account doesn't require access to any API. People are just using the Server option without knowing...

Apologies, I missed that in the responses.

**Comment by SpecialAro** [comment]
> On a separate note, @SpecialAro I think it would be great to still be able to use servers, but also caching the list of services locally so that when the internet goes down one may be able to access e.g. Gmail offline and stuff like that.

There is an existing ticket for this https://github.com/ferdium/ferdium-app/issues/83
