### ISSUE TITLE
Bug: can not install ferdium on Apple M1

### ISSUE THREAD

**Issue by benja83** [ferdium/ferdium-app#252]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.60

### What Operating System are you using?

macOS

### Operating System Version

mac os Monterey 12.4

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Run the brew commands from https://ferdium.org/download and start using the applicationh

### Actual Behavior

Using the brew formula or downloading the file from github I have been enable to install it

### Steps to reproduce

brew tap ferdium/ferdium
brew install ferdium-nightly

### Screenshots

<img width="253" alt="image" src="https://user-images.githubusercontent.com/7469433/173628305-d8f1f49f-4b58-4066-b15a-f4d8d8683e3d.png">
.

**Comment by vraravam** [comment]
please RTFM: 
<img width="884" alt="Screenshot 2022-06-14 at 10 00 23 PM" src="https://user-images.githubusercontent.com/69629/173629164-fe61122e-8dad-4776-a9c1-35b38cf2ead8.png">
