### ISSUE TITLE
Feature: Auto download icon for "Custom website" service

### ISSUE THREAD

**Issue by MurzNN** [ferdium/ferdium-app#257]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

When I'm adding a "Custom website" service, I always have the same "Globe" icon. 

### Proposed Solution

But most of websites have their own icons (at least a little favicon, but very often they provide also high resolution icons). So will be good of Ferdium will try to detect an icon, auto download it and attach to the service, if it was not already uploaded manually by user.

Additionally, will be good to allow paste url of icon, additionally to current ability to upload the icon from local filesystem, because most of favicons are available via url, so we'll can get rid of the "File » Save as + Upload to Ferdium" ritual :)

### Alternatives Considered

Nope

**Comment by trymeouteh** [comment]
Would be nice if there was a button on the service settings page to download the favicons from the website and choose one of the favicons to use as the service icon
