### ISSUE TITLE
Github sponsors

### ISSUE THREAD

**Issue by Zethson** [ferdium/ferdium-app#262]
### Your issue

Hey,

I was a happy contributor to the development of Ferdi until "the incident". I'd be happy to throw a bunch of $ at you again if you enable Github sponsors (or another service).

Cheers

**Comment by dqos** [comment]
Thanks, we are still working hard on Ferdium itself, but this has been added to the TODO list.

Reference:
https://opencollective.com/
https://github.com/sponsors

**Comment by SpecialAro** [comment]
Duplicate of https://github.com/ferdium/ferdium-app/issues/114
