### ISSUE TITLE
Bug: Scoop install fails as per website instructions

### ISSUE THREAD

**Issue by DanBuchan** [ferdium/ferdium-app#271]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.60

### What Operating System are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

`scoop install ferdium-nightly` installs the nightly build

### Actual Behavior

`scoop install ferdium-nightly` returns the following error

```
Couldn't find manifest for 'ferdium-nightly' from 'main' bucket.
```

### Steps to reproduce

1. Open Powershell in windows 10
2. Ensure scoop is installed
3. run `scoop install ferdium-nightly`

**Comment by Lod3** [comment]
Same problem here

**Comment by kungshinhean** [comment]
same here too

**Comment by vraravam** [comment]
I have updated the website with new instructions. Could @DanBuchan  / @Lod3 / @kungshinhean please verify that the commands actually work? I am not on windows, and only followed the instructions from the scoop website.

**Comment by vraravam** [comment]
Closing this - as the latest instructions in the website have been confirmed to work.
