### ISSUE TITLE
Bug: Custom website icons not displaying

### ISSUE THREAD

**Issue by mp-strachan** [ferdium/ferdium-app#275]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.63

### What Operating System are you using?

Ubuntu

### Operating System Version

Ubuntu 22.04

### What arch are you using?

x64

### Expected Behavior

Custom icon shown in sidebar and settings screen

### Actual Behavior

No icon shown. Dev tools shows a `net::ERR_FILE_NOT_FOUND` error for the custom icon asset, with the URL:
file:///opt/Ferdium/resources/app.asar/ferdium.mydomain.com/v1/icon/e11f37fc-58a6-425e-a1a7-d82e8afd2a8603ad6000-cbc6-4371-b9ae-4901a0b32aad.png

I can confirm that the URL can be reached at the ferdium server domain.

### Steps to reproduce

1. Goto settings
2. Create new custom website service
3. Upload a custom icon PNG (512x512px)
4. Save service
5. Icon doesn't load
6. Dev tools shows resource not found error

### Screenshots

![image](https://user-images.githubusercontent.com/26296076/173974148-247f435c-78de-44b6-a0b2-83975f2dbcee.png)
![image](https://user-images.githubusercontent.com/26296076/173974209-370fad6d-7860-4bb9-bd82-1f5fe0910d37.png)
![image](https://user-images.githubusercontent.com/26296076/173974400-398e840a-6e53-4ec7-a49c-8ccd902ed5fa.png)
![image](https://user-images.githubusercontent.com/26296076/173974703-995934b8-5d46-4265-adc6-35b5eca15139.png)
![image](https://user-images.githubusercontent.com/26296076/173974895-04cf8f6c-81e9-47a9-bbfc-52fc4bd57622.png)

### Additional information

Running latest version of ferdium-server on docker with client connected to server

**Comment by k1ba-meow** [comment]
I have the same issue with a service imported from a Ferdi export (without a custom icon, just the regular icon), causing that service to not have an icon for a couple of seconds until the favicon of the web page is loaded
Affected service: RocketChat (self-hosted instance)
Ferdium version: 6.0.0-nightly.71
Running without server login, i.e. with a local ferdium server
Platform: Arch Linux, Kernel 5.18 on x64
Installed from AUR

**Comment by mp-strachan** [comment]
Can confirm issue is also present on Windows 11, running nightly 73, connected to ferdium-server pinned to latest.

**Comment by mp-strachan** [comment]
Looking through the dev tools, it appears the custom server URL scheme isn't being applied to the custom website icon's img element...

![image](https://user-images.githubusercontent.com/26296076/175181830-c56764e5-cd65-423e-9ac8-d9cbd4532755.png)

Manually adding `HTTPS://` to the img src fixes the image:

![image](https://user-images.githubusercontent.com/26296076/175181984-d0784761-d90a-4f74-b7e2-c10a1feb32ff.png)
![image](https://user-images.githubusercontent.com/26296076/175182011-5cf678fe-e7d6-4660-a055-3f7a97d530b7.png)

**Comment by SpecialAro** [comment]
> Looking through the dev tools, it appears the custom server URL scheme isn't being applied to the custom website icon's img element...
> 
> ![image](https://user-images.githubusercontent.com/26296076/175181830-c56764e5-cd65-423e-9ac8-d9cbd4532755.png)
> 
> Manually adding `HTTPS://` to the img src fixes the image:
> 
> ![image](https://user-images.githubusercontent.com/26296076/175181984-d0784761-d90a-4f74-b7e2-c10a1feb32ff.png) ![image](https://user-images.githubusercontent.com/26296076/175182011-5cf678fe-e7d6-4660-a055-3f7a97d530b7.png)

So, I imagine you're on a Custom Server instead of Ferdium Server, right?
When you added the custom server you also added the "https://" prefix or is it missing ?

**Comment by mp-strachan** [comment]
![image](https://user-images.githubusercontent.com/26296076/175458797-6c50fef8-fb7c-4c68-8609-b81c11d0477f.png)
Yes, custom server.
Yep - I have included the prefix when I added the custom server.

**Comment by mp-strachan** [comment]
So your comment had me thinking....

I checked my docker-compose config for the ferdium server:
![image](https://user-images.githubusercontent.com/26296076/175459711-7f9a261d-10f6-4d97-aa9d-69a812888920.png)
And adding the HTTPS:// prefix:
![image](https://user-images.githubusercontent.com/26296076/175459771-be7980e3-6202-481b-965f-ee795728cc44.png)

This seems to have fixed the issue. I had to re-add the custom icon, but as soon as that was done, the sidebar loads the new icon no problems.

**Comment by mp-strachan** [comment]
So your comment had me thinking....

I checked my docker-compose config for the ferdium server:
![image](https://user-images.githubusercontent.com/26296076/175460121-341019ee-92ad-4bfe-b901-41d68167caf0.png)
And adding the HTTPS:// prefix on the APP_URL variable:
![image](https://user-images.githubusercontent.com/26296076/175460145-13b9dc58-9b07-44e7-8806-5cc276dc8946.png)

This seems to have fixed the issue. I had to re-add the custom icon, but as soon as that was done, the sidebar loads the new icon no problems.
![image](https://user-images.githubusercontent.com/26296076/175460174-82dd5efc-7bfd-4b01-9335-f083fd90c327.png)

**Comment by SpecialAro** [comment]
OK, awesome! This was something on your server set up end. I'm closing this issue now.

If you need it, we can reopen it after 😄
