### ISSUE TITLE
Bug: “Ferdium” is damaged and can’t be opened. You should move it to the Trash.

### ISSUE THREAD

**Issue by lewiss444** [ferdium/ferdium-app#276]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

latest

### What Operating System are you using?

macOS

### Operating System Version

Big Sur 11.5.2

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Install Ferdium

### Actual Behavior

Installed trough homebrew and got this error message: “Ferdium” is damaged and can’t be opened. You should move it to the Trash.

### Steps to reproduce

in terminal used :
brew tap ferdium/ferdium
brew install ferdium-nightly

than open the app trough launcher

### Screenshots

![Screen Shot 2022-06-16 at 12 07 54 PM](https://user-images.githubusercontent.com/23320207/173995587-3aca913f-6f04-45ac-9f67-f31ca14126be.png)

**Comment by switowski** [comment]
I just came here looking for a fix to the same problem as you posted and it seems that it's a [problem](https://github.com/ferdium/ferdium-app/issues/180) with unsigned nightly releases that can be [easily fixed](https://github.com/ferdium/ferdium-app#unsigned-nightlies-on-macos). It worked for me, so I hope it helps you too.

**Comment by lewiss444** [comment]
> I just came here looking for a fix to the same problem as you posted and it seems that it's a [problem](https://github.com/ferdium/ferdium-app/issues/180) with unsigned nightly releases that can be [easily fixed](https://github.com/ferdium/ferdium-app#unsigned-nightlies-on-macos). It worked for me, so I hope it helps you too.

Awesome, works now. Thanks

**Comment by SpecialAro** [comment]
Hello @lewiss444 ! Welcome to Ferdium.

You can solve this by looking at the website faq (https://ferdium/faq) and at the readme on the GH page.

![Screenshot_20220616-121445_GitHub](https://user-images.githubusercontent.com/37463445/174058638-08563bd5-2044-4991-b993-4a0ec05d1ec1.jpg)
![Screenshot_20220616-121310_Brave](https://user-images.githubusercontent.com/37463445/174058651-3565bb77-41b4-4f8f-aab2-8b678e3fc766.jpg)


Next time, please, read the closed tickets and also the faq sections before logging an issue.
