### ISSUE TITLE
Bug: ferdium.exe flagged as malicious by  Gridinsoft  Trojan.Heur!.02046823

### ISSUE THREAD

**Issue by dkhokhlov** [ferdium/ferdium-app#278]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.63

### What Operating System are you using?

Windows

### Operating System Version

Windows 7

### What arch are you using?

x64

### Expected Behavior

After installation from MSI the ferdium.exe shall not be flagged as malicious by Virustotal

### Actual Behavior

After installation from MSI the ferdium.exe flagged as malicious by Virustotal:

Gridinsoft  Trojan.Heur!.02046823
https://www.virustotal.com/gui/file/692c2cd1776aea7456629d8b5b72b2d444c95ac6d577b07c9b9eae129f25c70e/detection

### Steps to reproduce

1. install using MSI
2. check insgtalled exe using virustotal

**Comment by yarons** [comment]
Can you specify the exact download location for reference?

**Comment by SpecialAro** [comment]
Also, some Antivirus mark installers which are not code signed (again, we are still looking into this... as of the start of this week, is on our top priority!)... may be the issue.

But, as @yarons pointed out, make sure to always download through the official links we provide (here, on GH or through the website https://ferdium.org/)

**Comment by dkhokhlov** [comment]
Steps:
1) download from https://github.com/ferdium/ferdium-app/releases/download/v6.0.0-nightly.63/Ferdium-6.0.0-nightly.63.msi
2) right click install
3) upload C:\Users\<User>\AppData\Local\Programs\ferdium\ferdium.exe to Virustotal
4) detection result: https://www.virustotal.com/gui/file/692c2cd1776aea7456629d8b5b72b2d444c95ac6d577b07c9b9eae129f25c70e/detection

**Comment by SpecialAro** [comment]
> Steps:
> 1) download from https://github.com/ferdium/ferdium-app/releases/download/v6.0.0-nightly.63/Ferdium-6.0.0-nightly.63.msi
> 2) right click install
> 3) upload C:\Users\<User>\AppData\Local\Programs\ferdium\ferdium.exe to Virustotal
> 4) detection result: https://www.virustotal.com/gui/file/692c2cd1776aea7456629d8b5b72b2d444c95ac6d577b07c9b9eae129f25c70e/detection
> 

Thank you for your details on this.

Again, this maybe due to the fact the Ferdium-App is not code signed yet. Can ai ask you to, please, test it with the same installer for the latest Ferdi and paste here the detection result as well?

I've monitored the changes on the codebase so far, ever since we changed from Ferdi to Ferdium and nothing suspicious popped up. So, if Ferdi doesn't have that trojan detection I can only assume it's the code signing part.

Once we code sign I'll ask you to test this again if you can 😁

**Comment by dkhokhlov** [comment]
Extract files from latest  MSI:

> msiexec /a Ferdium-6.0.0-nightly.63.msi /qb TARGETDIR=c:\temp\test

Hash of ferdium.exe:

MD5 ca5cf7eaa09955c6836e5a5448c1220a
SHA-1 f0d2074ff309b3bde9583be030af49f222c1ae99
SHA-256 692c2cd1776aea7456629d8b5b72b2d444c95ac6d577b07c9b9eae129f25c70e
Vhash 0180f6656d156515501614z1f2zff8z143za7z3001f334zb9e 

Can you publish the hash you get for ferdium.exe from 6.0.0-nightly.63? Try Virustotal.
