### ISSUE TITLE
npm warnings on deprecated packages

### ISSUE THREAD

**Issue by hadesxp** [ferdium/ferdium-app#279]
### Your issue

Hello,
using Manjaro Linux and the AUR repository to build ferdium, I got a few warnings which could be fixed moving to newer package dependencies - maybe it is allready in the backlog:

npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated set-value@1.0.0: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).

**Comment by SpecialAro** [comment]
Hello @hadesxp ! Thank you for noticing this 😄 

In fact, this is known to be an "issue" as we are trying to update dependencies. We should look at those when we get the chance!

**Comment by mcmxcdev** [comment]
I silenced these warnings in https://github.com/ferdium/ferdium-app/pull/1282 so you shouldn't see any of these anymore.

Upgrading the dependencies which use these deprecated dependencies is an ongoing task.
