### ISSUE TITLE
Bug: Ferdi Login needed when using Ferdium-6.0.0-nightly.63.msi

### ISSUE THREAD

**Issue by Michael-Schaer** [ferdium/ferdium-app#280]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

Ferdium-6.0.0-nightly.63.msi

### What Operating System are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

I can use Ferdinum without any Login and without error messages

### Actual Behavior

After the installation, Ferdinum tryies to find my Ferdi-Account and Fails with an Error Message.

This does not happen with the exe-file (Ferdium-6.0.0-nightly.63.exe). I want to use the msi-Version though, because the exe version seems to only execute ferdi, instead of installing it on my system. 

### Steps to reproduce

Go to GitHub Releases
Download Ferdium-6.0.0-nightly.63.msi
Install
The Application opens
-> Searching and failing to load Ferdi login

### Screenshots

![Ferdinum](https://user-images.githubusercontent.com/1799621/174062094-64d8d534-f85f-4573-9dfe-79fff81a38c2.png)

**Comment by SpecialAro** [comment]
Hello @Michael-Schaer , thank you for logging this issue. Welcome to Ferdium!

> -> Searching and failing to load Ferdi login

Are you trying to connect to Ferdi Server instead of Ferdium Server? Did you try to use our migration scripts (maybe that's the issue).

**Comment by SpecialAro** [comment]
Also, give a shot to [Ferdium-Setup-6.0.0-nightly.63.exe](https://github.com/ferdium/ferdium-app/releases/download/v6.0.0-nightly.63/Ferdium-Setup-6.0.0-nightly.63.exe) (.exe version installer). It's the one I use 😄

**Comment by Michael-Schaer** [comment]
> Hello @Michael-Schaer , thank you for logging this issue. Welcome to Ferdium!
> 
> > -> Searching and failing to load Ferdi login
> 
> Are you trying to connect to Ferdi Server instead of Ferdium Server? Did you try to use our migration scripts (maybe that's the issue).

Ahh! That was it! I was able to delete the folder in AppData and reinstall it, then it worked as expected!

> Also, give a shot to [Ferdium-Setup-6.0.0-nightly.63.exe](https://github.com/ferdium/ferdium-app/releases/download/v6.0.0-nightly.63/Ferdium-Setup-6.0.0-nightly.63.exe) (.exe version installer). It's the one I use 😄

Thanks for the tip!

**Comment by SpecialAro** [comment]
Awesome! Closing the issue 😁
