### ISSUE TITLE
Bug: Todo settings

### ISSUE THREAD

**Issue by Dominiquini** [ferdium/ferdium-app#281]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.63

### What Operating System are you using?

Windows

### Operating System Version

Windows 10 Version 21H2 (OS Build 19044.1766)

### What arch are you using?

x64

### Expected Behavior

In the settings, I shoulf be able to enable / disable the "TODOs" features

### Actual Behavior

The settings for enabling / disabling the 'TODOs' and selecting the server disappear!

### Steps to reproduce

1) Open and login the default 'TODO' server
2) Open settings and change the next server
3) Login with this another server
4) Change to the next server
5) Repeat until I selected "Google Keep"
6) After I login if "Google Keep" the settings disappear
7) Restating the app don't work...

### Screenshots

![Ferdium_fX8qiTKQzE](https://user-images.githubusercontent.com/1180808/174140110-f21606c9-38b4-425c-9a4a-30aa506a242a.png)

### Additional information

I was testing multiple 'TODOs' options, but when I finally selected 'Google Keep', the settings to enable / disable and the settings for selecting the server disappear!

**Comment by SpecialAro** [comment]
Hello @Dominiquini , thank you for raising this issue.

This is peculiar... I'm unable to reproduce this issue. This shouldn't be happening at all, maybe this is a faulty installation of Ferdium. Which installer/executable did you run?

**Comment by Dominiquini** [comment]
> Hello @Dominiquini , thank you for raising this issue.
> 
> This is peculiar... I'm unable to reproduce this issue. This shouldn't be happening at all, maybe this is a faulty installation of Ferdium. Which installer/executable did you run?

I used for last the [Ferdium-Setup-6.0.0-nightly.63.exe](https://github.com/ferdium/ferdium-app/releases/download/v6.0.0-nightly.63/Ferdium-Setup-6.0.0-nightly.63.exe)

But the problem start with the first version that I installed, that was [Ferdium-Setup-6.0.0-nightly.60.exe ](https://github.com/ferdium/ferdium-app/releases/download/v6.0.0-nightly.60/Ferdium-Setup-6.0.0-nightly.60.exe)

* Explaining better:
The problem started on the 60 version (my first version usning this app). Updating to the 63 remains the same!

Thanks

**Comment by vraravam** [comment]
I'm also not able to reproduce this with the latest code from source running on macos 12.4
<img width="1481" alt="Screenshot 2022-06-17 at 7 53 03 AM" src="https://user-images.githubusercontent.com/69629/174212339-2685e503-f08c-47b1-bfd7-185b2eb44a74.png">

**Comment by Dominiquini** [comment]
Before selecting Google Keep, I tested (selected, close the settings, open TODO panel, logged in the service, etc) multiple other services... After selecting Google Keep and logging on it, the bug appears!

Thanks for the reply!

**Comment by WouterJansen** [comment]
I experience the same on Windows 10, using 6.0.0 nightly 69.

I enabled todos and selected google keep. Now the settings have disappeared.

**Comment by SpecialAro** [comment]
Can someone who is experiencing this provide the debug link so I can check the console log? Or just paste the log in here?

**Comment by Dominiquini** [comment]
My Published Debug Information: https://debug.ferdium.org/d14f9057-ea12-4e4d-8e05-4d36e6b14e29

Debug Information: https://mypastetext.com/whpj8pfxjt

Thanks

**Comment by SpecialAro** [comment]
For the first time ever, and for some unknown reason, I'm experiencing this on Dev Mode!
![image](https://user-images.githubusercontent.com/37463445/177139261-ae9265d1-706f-4cef-99ae-f0ef0b53bfc5.png)

As you can see, no button to "Enable Ferdium Todos" appears.
![image](https://user-images.githubusercontent.com/37463445/177139357-5ac480fa-0260-441e-bd35-4371cd4d97d2.png)

**Comment by SpecialAro** [comment]
Found the culprit! I have "Todoist" set as my ToDo service and also Have it added on the sidebar as a recipe (as you can see). When this happens, it hides the button... I'm removing that check from the code (as I don't think it makes any sense).

**Comment by vraravam** [comment]
@SpecialAro - i think that was a "feature" - please check with the wider userbase in discord before removing.
For eg, as a user, if i have a TODO service configured, AND if i open that same service in the main service-area, then the TODO panel is redundant - and that was a "feature" that was implemented based on user-asks.

Maybe the better option would be to have a floating bar on top (which can be closed) which informs the user why this TODO panel is "missing"

**Comment by SpecialAro** [comment]
> @SpecialAro - i think that was a "feature" - please check with the wider userbase in discord before removing. 

Will do, thank you @vraravam!

> For eg, as a user, if i have a TODO service configured, AND if i open that same service in the main service-area, then the TODO panel is redundant - and that was a "feature" that was implemented based on user-asks.

This is true, but it still applies - if you have the TODO menu enabled and opened, and if you go to the TODO service, it automatically closes the TODO menu (because of the redundancy).

I don't think we should remove the option entirely on the settings because if the user wants to switch the TODO service (and still keep it as a common service) he would need to delete the service first and then go to settings, change it, and add the deleted service back again.

E.g. If a user sets up Google Keep as the TODO service and adds it as service, the option to change the TODO service disappears from the settings UI. If the user want's to change the TODO to Todoist and still keep Google Keep as a service, he would need to: delete Google Keep, change the TODO to Todoist, add Google Keep back again. And I think this is unintended.
