### ISSUE TITLE
Bug: Ferdium servers down?

### ISSUE THREAD

**Issue by eXistenZNL** [ferdium/ferdium-app#286]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.60, 6.0.0-nightly.65

### What Operating System are you using?

Ubuntu

### Operating System Version

21.04

### What arch are you using?

x64

### Last Known Working Ferdium version

6.0.0-nightly.60

### Expected Behavior

I can use Ferdium by starting it up and seeing the tabs of my services on the left side of the screen.

### Actual Behavior

The Ferdium servers seem to be down. I switched from Ferdi to Ferdium earlier this week and had high hopes of being able to use Ferdium from now on, but it seems that the Ferdium servers are down too as of this morning.

I looked for a status dashboard like status.ferdium.com but that does not seem to exist (yet?).
Then I looked on Twitter and Discord, but I found no signs of connection issues anywhere.

### Steps to reproduce

1. Start Ferdium
2. See the red bar saying "Could not load services and user information [Try again]"

**Comment by dqos** [comment]
Are you able to visit this site? https://api.ferdium.org/

Ferdium uses that to fetch account services. Try to visit/login there.

**Comment by vraravam** [comment]
Yes - the api server seems to be up. I dont see this issue. Maybe its localized to your location?

**Comment by SpecialAro** [comment]
From time to time I experience this but I hit the try button or just wait a bit and it fixes itself. I thought/think that this was/is related with my DNS issue (been talking to @dqos about it, maybe it's location connection problems).

**Comment by isikerkan** [comment]
When I use the Ferdium Setup to install it on the OS I get the same error, that I can't connect to the Ferdium API. When I set a Ping over the CMD it works fine.

When I use the Portable Exe Ferdium works fine and no Errors appear. It somehow has Problems with the native OS Setup. Here is a Debug of the Ferdium Setup Installation: 

`{"host":{"platform":"win32","release":"10.0.22000","screens":[{"id":2528732444,"bounds":{"x":-3840,"y":-313,"width":3840,"height":2160},"workArea":{"x":-3840,"y":-313,"width":3840,"height":2112},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:SRGB, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":3840,"height":2160},"displayFrequency":60,"workAreaSize":{"width":3840,"height":2112},"scaleFactor":1,"rotation":0,"internal":false,"touchSupport":"unknown"},{"id":2779098405,"bounds":{"x":0,"y":0,"width":2560,"height":1440},"workArea":{"x":0,"y":0,"width":2560,"height":1392},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:SRGB, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":2560,"height":1440},"displayFrequency":165,"workAreaSize":{"width":2560,"height":1392},"scaleFactor":1,"rotation":0,"internal":false,"touchSupport":"unknown"}]},"ferdium":{"version":"6.0.0-nightly.69","electron":"19.0.4","installedRecipes":[{"id":"android-messages","version":"2.2.4"},{"id":"franz-custom-website","version":"1.1.0"},{"id":"instagram","version":"2.0.0"},{"id":"msteams","version":"1.3.2"},{"id":"outlook","version":"1.1.0"},{"id":"slack","version":"1.3.0"},{"id":"steamchat","version":"1.3.0"},{"id":"whatsapp","version":"3.3.7"},{"id":"wpmuhub","version":"1.0.0"}],"devRecipes":[{"id":"wpmuhub","version":"1.0.0"}],"services":[],"messages":[{"type":"error","info":["error","[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[bound ]'",{}]},{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.service` of type `Object` supplied to `AppLayoutContainer`, expected instance of `_class`.","\n    at AppLayoutContainer (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\containers\\layout\\AppLayoutContainer.js:1:1742)\n    at C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\mobx-react\\dist\\mobxreact.cjs.development.js:513:34\n    at <anonymous> (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at <anonymous> (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at Routes (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\routes.js:1:2444)\n    at C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\mobx-react\\dist\\mobxreact.cjs.development.js:513:34\n    at IntlProvider (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\react-intl\\src\\components\\provider.js:83:47)\n    at I18N (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\I18n.js:1:470)\n    at C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\mobx-react\\dist\\mobxreact.cjs.development.js:513:34\n    at Provider (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\mobx-react\\dist\\mobxreact.cjs.development.js:482:24)"]},{"type":"error","info":["error","Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.%s","\n    at AppLayoutContainer (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\containers\\layout\\AppLayoutContainer.js:1:1742)\n    at C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\mobx-react\\dist\\mobxreact.cjs.development.js:513:34\n    at <anonymous> (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at <anonymous> (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at Routes (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\routes.js:1:2444)\n    at C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\mobx-react\\dist\\mobxreact.cjs.development.js:513:34\n    at IntlProvider (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\react-intl\\src\\components\\provider.js:83:47)\n    at I18N (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\I18n.js:1:470)\n    at C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\mobx-react\\dist\\mobxreact.cjs.development.js:513:34\n    at Provider (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\mobx-react\\dist\\mobxreact.cjs.development.js:482:24)"]},{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.app` of type `Object` supplied to `AuthLayoutContainer`, expected instance of `_class`.","\n    at AuthLayoutContainer (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\containers\\auth\\AuthLayoutContainer.js:1:1143)\n    at C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\mobx-react\\dist\\mobxreact.cjs.development.js:513:34\n    at <anonymous> (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at <anonymous> (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at Routes (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\routes.js:1:2444)\n    at C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\mobx-react\\dist\\mobxreact.cjs.development.js:513:34\n    at IntlProvider (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\react-intl\\src\\components\\provider.js:83:47)\n    at I18N (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\I18n.js:1:470)\n    at C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\mobx-react\\dist\\mobxreact.cjs.development.js:513:34\n    at Provider (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\mobx-react\\dist\\mobxreact.cjs.development.js:482:24)"]},{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.service` of type `Object` supplied to `PublishDebugLogModal`, expected instance of `_class`.","\n    at PublishDebugLogModal (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\features\\publishDebugInfo\\Component.js:1:2558)\n    at C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\mobx-react\\dist\\mobxreact.cjs.development.js:513:34\n    at C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\react-jss\\dist\\react-jss.cjs.js:407:25\n    at injectIntl(WithStyles(inject-with-stores-actions(PublishDebugLogModal)))\n    at AuthLayout (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\components\\auth\\AuthLayout.js:1:1111)\n    at injectIntl(AuthLayout)\n    at ThemeProvider (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\theming\\dist\\theming.cjs.js:78:37)\n    at AuthLayoutContainer (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\containers\\auth\\AuthLayoutContainer.js:1:1143)\n    at C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\mobx-react\\dist\\mobxreact.cjs.development.js:513:34\n    at <anonymous> (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at <anonymous> (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at Routes (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\routes.js:1:2444)\n    at C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\mobx-react\\dist\\mobxreact.cjs.development.js:513:34\n    at IntlProvider (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\react-intl\\src\\components\\provider.js:83:47)\n    at I18N (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\I18n.js:1:470)\n    at C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\mobx-react\\dist\\mobxreact.cjs.development.js:513:34\n    at Provider (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\mobx-react\\dist\\mobxreact.cjs.development.js:482:24)"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"default"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.user` of type `Object` supplied to `LoginScreen`, expected instance of `_class`.","\n    at LoginScreen (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\containers\\auth\\LoginScreen.js:1:657)\n    at C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\mobx-react\\dist\\mobxreact.cjs.development.js:513:34\n    at div\n    at div\n    at AuthLayout (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\components\\auth\\AuthLayout.js:1:1111)\n    at injectIntl(AuthLayout)\n    at ThemeProvider (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\theming\\dist\\theming.cjs.js:78:37)\n    at AuthLayoutContainer (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\containers\\auth\\AuthLayoutContainer.js:1:1143)\n    at C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\mobx-react\\dist\\mobxreact.cjs.development.js:513:34\n    at <anonymous> (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at <anonymous> (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at Routes (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\routes.js:1:2444)\n    at C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\mobx-react\\dist\\mobxreact.cjs.development.js:513:34\n    at IntlProvider (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\react-intl\\src\\components\\provider.js:83:47)\n    at I18N (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\I18n.js:1:470)\n    at C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\mobx-react\\dist\\mobxreact.cjs.development.js:513:34\n    at Provider (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\mobx-react\\dist\\mobxreact.cjs.development.js:482:24)"]},{"type":"error","info":["error","Updater error:",{}]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"health"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"login"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.user` of type `Object` supplied to `SignupScreen`, expected instance of `_class`.","\n    at SignupScreen (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\containers\\auth\\SignupScreen.js:1:736)\n    at C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\mobx-react\\dist\\mobxreact.cjs.development.js:513:34\n    at div\n    at div\n    at AuthLayout (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\components\\auth\\AuthLayout.js:1:1111)\n    at injectIntl(AuthLayout)\n    at ThemeProvider (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\theming\\dist\\theming.cjs.js:78:37)\n    at AuthLayoutContainer (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\containers\\auth\\AuthLayoutContainer.js:1:1143)\n    at C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\mobx-react\\dist\\mobxreact.cjs.development.js:513:34\n    at <anonymous> (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at <anonymous> (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at Routes (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\routes.js:1:2444)\n    at C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\mobx-react\\dist\\mobxreact.cjs.development.js:513:34\n    at IntlProvider (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\react-intl\\src\\components\\provider.js:83:47)\n    at I18N (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\I18n.js:1:470)\n    at C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\mobx-react\\dist\\mobxreact.cjs.development.js:513:34\n    at Provider (C:\\Users\\isik4\\AppData\\Local\\Programs\\ferdium\\resources\\app.asar\\node_modules\\mobx-react\\dist\\mobxreact.cjs.development.js:482:24)"]}],"workspaces":[],"windowSettings":{"width":1429,"height":1004,"x":0,"y":0,"displayBounds":{"x":0,"y":0,"width":2560,"height":1440},"isMaximized":false,"isFullScreen":false},"settings":{"autoLaunchOnStart":false,"autoLaunchInBackground":false,"runInBackground":true,"reloadAfterResume":true,"enableSystemTray":true,"startMinimized":false,"confirmOnQuit":false,"minimizeToSystemTray":true,"closeToSystemTray":false,"privateNotifications":false,"clipboardNotifications":true,"notifyTaskBarOnMessage":false,"showDisabledServices":true,"showServiceName":false,"showMessageBadgeWhenMuted":true,"showDragArea":false,"enableSpellchecking":true,"spellcheckerLanguage":"de-de","darkMode":false,"splitMode":false,"splitColumns":3,"fallbackLocale":"en-US","beta":false,"isAppMuted":false,"enableGPUAcceleration":true,"enableGlobalHideShortcut":false,"server":"https://api.getferdi.com","predefinedTodoServer":"https://todo.microsoft.com/?app#","autohideMenuBar":false,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernateOnStartup":true,"hibernationStrategy":300,"wakeUpStrategy":"300","wakeUpHibernationStrategy":"0","wakeUpHibernationSplay":true,"inactivityLock":0,"automaticUpdates":true,"universalDarkMode":true,"userAgentPref":"","adaptableDarkMode":true,"accentColor":"#7367f0","progressbarAccentColor":"#7367F0","serviceRibbonWidth":"55","sidebarServicesLocation":0,"iconSize":"20","navigationBarBehaviour":"never","searchEngine":"duckDuckGo","useVerticalStyle":false,"hideRecipesButton":false,"useGrayscaleServices":false,"grayscaleServicesDim":50,"hideWorkspacesButton":false,"hideNotificationsButton":false,"hideSettingsButton":false,"alwaysShowWorkspaces":false,"liftSingleInstanceLock":false,"enableLongPressServiceHint":false,"proxyFeatureEnabled":false,"onlyShowFavoritesInUnreadCount":false,"locale":"de","showServiceNavigationBar":false,"sentry":false,"nightly":false,"serviceLimit":5,"hibernate":true,"todoServer":"isUsingCustomTodoService","customTodoServer":""},"features":{}}}`

**Comment by SpecialAro** [comment]
Are you using the msi or the exe installer? If you're using the msi one, please uninstall and try with the exe option and get back to us, please.

**Comment by isikerkan** [comment]
I tried both and had the same Problem. I removed Ferdium and manually deleted the Appdata Folders:

AppData\Local\ferdium-updater
AppData\Roaming\Ferdium

After that I reinstalled with the Setup.exe once more and the Connection worked flawless

**Comment by SpecialAro** [comment]
Awesome that you manage to solve it. It might have been a faulty installation. Closing the issue 😄
