### ISSUE TITLE
Bug: Settings are not permanent

### ISSUE THREAD

**Issue by mfortini** [ferdium/ferdium-app#30]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Steps to reproduce

* Installed ferdium with deb (former ferdi user).
* Moved config with export/import tools. All well
* Logged in to whatsapp.
* Quit ferdium
* Open ferdium
* Whatsapp asks again to register
Same with telegram, btw.

**Comment by mfortini** [comment]
(and BTW, thank you immensely for reviving ferdi)

**Comment by SpecialAro** [comment]
Hello @mfortini ! Thank you for registering this issue 😁

Me and other user have experience the same, but a fix is now in progess and merged. Should be available in the next nightly.

See https://github.com/ferdium/ferdium-app/pull/23

**Comment by vraravam** [comment]
@mfortini - I just released the latest nightly: https://github.com/ferdium/ferdium-app/releases/tag/v6.0.0-nightly.9 which has the fix for #17 which is the same as your issue. Please try it out and close the ticket.

**Comment by mfortini** [comment]
Thank you, I confirm nightly 9+ works.
