### ISSUE TITLE
Bug: Reload after system resume not working

### ISSUE THREAD

**Issue by krisrok** [ferdium/ferdium-app#305]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly-58 and -69 tested

### What Operating System are you using?

Windows

### Operating System Version

10.0.19041 Build 19041

### What arch are you using?

x64

### Expected Behavior

Ferdium should be just usable after system resume, e.g. after hibernation or longer standby times.

If this is not easily possible, at least the settings option "Reload after system resume" should trigger in these cases and issue a full app reload.

### Actual Behavior

After hibernation or longer standby times all Ferdium tabs are unloaded. I have to reload all (ctrl+shift+r) to continue.

### Steps to reproduce

1. Put your computer to sleep
2. Wait a while
    - I don't know how long exactly, but I've tested a bit:
    - Unfortunatley, a short sleep time is ok apparently (I immediately woke up my computer after putting it to sleep)
    - Also, a short hibernation time is also ok (I just used `shutdown /h /f` and immediately woke the computer up again)
    - So there has to be some kind of unkown timeout duration...?
4. Wake your computer
5. Find Ferdium unusable :(

### Additional information

**Comment by vraravam** [comment]
**As a workaround**, a hard-refresh `Cmd+Shift+R` on macos, would get Ferdium running again.

**Comment by krisrok** [comment]
I've update the versions I tested.

**Comment by krisrok** [comment]
Thanks @SpecialAro! I've just installed nightly.72 and will keep an eye on it.

**Comment by vraravam** [comment]
the in-app upgrades for mac are now running, if you are on mac and on nightly 72, please upgrade and callout the experience?

**Comment by krisrok** [comment]
I'm on Windows -- I'll be happy to test when the cert for windows is in place :)

**Comment by krisrok** [comment]
From what I can tell so far it looks like Reload after resume works as intended now, great!

**Comment by joshua-martius** [comment]
Doesnt work for me on newest Manjaro KDE. Anyone else with this problem? 

In addition it would be nice to have a "reload all services" button. Not only to temporarily fix this problem, but in general.
