### ISSUE TITLE
Feature: Working Devcontainer to improve contributions

### ISSUE THREAD

**Issue by cino** [ferdium/ferdium-app#323]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

As I tried to work with this repository I noticed that the DevContainer is not ready to be used. And would suggest providing a working DevContainer in the repository to improve the developer experience for potential new contributors to the project.

### Proposed Solution

Working DevContainer.

### Alternatives Considered

No alternatives.

### Additional Information

Willing to work on this myself, just wanted to create the issue as well.

**Comment by vraravam** [comment]
Sorry, im not sure why this is necessary? (Unless of course one doesn't want to install the system dependencies on the host machine). But, even then, it'll only be useful to build and package. Running a gui application inside a docker container has too many issues to be worthwhile imo.

**Comment by cino** [comment]
@vraravam Initially my idea was not to have any development-related software on my laptop and run everything from containers. However, after looking into this and running the electron app, I've concluded it's not worth the time.

As the DevContainer doesn't actually work would you agree if I submitted a PR to remove it completely? This would save people time trying to run it in the first place.

**Comment by vraravam** [comment]
yes pls - that would be good. Thanks!

**Comment by cino** [comment]
Closing this in favor of #328
