### ISSUE TITLE
Bug: Infinite loading on gmail

### ISSUE THREAD

**Issue by jnvillar** [ferdium/ferdium-app#325]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.71

### What Operating System are you using?

macOS

### Operating System Version

macOs Monterey 12.2

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

I have 2 gmail services added. Each one uses a different email account. Both services used to work just fine

### Actual Behavior

One of the two services is freezed and shows an infinite loading pop up. If I press `shift+cmd+r` and force a reload, the one service I am focussed starts to work fine and the other one is freezed with a loading pop up

### Steps to reproduce

- Add 2 gmail services
- One of them should have the bug

### Screenshots

<img width="383" alt="Screen Shot 2022-06-21 at 09 49 14" src="https://user-images.githubusercontent.com/7551569/174803081-61a77106-afcc-464c-ae8c-40b9195209ec.png">

<img width="63" alt="Screen Shot 2022-06-21 at 09 49 33" src="https://user-images.githubusercontent.com/7551569/174803131-5d0097b3-279a-4e30-974d-cddbb4d397b1.png">

### Additional information

I used 2 gmail services for a looooong time, this bug was introduced recently

**Comment by vraravam** [comment]
please upgrade to the latest nightly - this has been replaced with a progressbar on top, as well as the same can be turned on/off from the settings screen.

**Comment by jnvillar** [comment]
I am using the latest nightly! (6.0.0-nightly.71)

<img width="631" alt="Screen Shot 2022-06-21 at 11 49 04" src="https://user-images.githubusercontent.com/7551569/174829481-f1fc76c1-edec-4467-b5c3-1e091e860ae3.png">

@vraravam

**Comment by SpecialAro** [comment]
Please, reload Ferdium (CMD + SHIFT + R) or restart it (make sure it is closed). It will most likely fix this

**Comment by jnvillar** [comment]
I have tried doing `CMD + SHIFT + R` several times already and it only fixed one of the two services. 

I tried again though and now both services are working fine 🎉 

Did something change?

**Comment by SpecialAro** [comment]
> I have tried doing `CMD + SHIFT + R` several times already and it only fixed one of the two services. 
> 
> I tried again though and now both services are working fine 🎉 
> 
> Did something change?

No change whatsoever... Some users experience this on the first runs , and also there is a similar issue if you have multiple recipes (like, 15+)
