### ISSUE TITLE
Feature: Use native filepicker on linux.

### ISSUE THREAD

**Issue by Regular-Baf** [ferdium/ferdium-app#33]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

It can be quite jarring for a less experienced user to see a menu you may be less familiar with. But, it's also just a bit ugly, and doesn't integrate with the system.

### Proposed Solution

Ferdium could supply the correct file picker when using KDE, Gnome, and others.

### Alternatives Considered

n/a

**Comment by vraravam** [comment]
Looks like this was merged for electron 14 itself: https://github.com/electron/electron/pull/19159 - could you please raise a bug in electron if its not working for your OS flavor?

**Comment by kris7t** [comment]
You might be affected by https://github.com/electron/electron/issues/31258

**Comment by MurzNN** [comment]
For me this already works well on Ubuntu with `snap` package:
![image](https://user-images.githubusercontent.com/336662/169254960-757cbd93-3b2c-42b2-b8b9-3fd9747fd97f.png)

And for native Linux packages maybe it needs the manual creation of symlink (and restarting Ferdium):
```
sudo ln -s /usr/lib/x86_64-linux-gnu/libgtk-3.so.0 /usr/lib/x86_64-linux-gnu/libgtk-3.so
```
