### ISSUE TITLE
Bug: Javascript changing favicon overrides custom service icon

### ISSUE THREAD

**Issue by k1ba-meow** [ferdium/ferdium-app#336]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.71

### What Operating System are you using?

Other Linux

### Operating System Version

Linux 5.18.5-arch1-1

### What arch are you using?

x64

### Expected Behavior

When setting a custom icon for a service, that icon should always be displayed for that service.

### Actual Behavior

The custom icon is displayed while the service loads, but after the service is loaded and changes the favicon via JS, that favicon replaces the custom icon.

### Steps to reproduce

1. Add a service that uses JS to set the favicon, e.g. RocketChat or Slack
2. Set a custom icon for that service
3. Reload Ferdium
4. After the service loads, the icon in the sidebar changes

### Additional information

This is explicitly not a duplicate of #275 because it likely has a different cause: Rather than not being loaded in the first place, the icon is overridden by the website's favicon

**Comment by cino** [comment]
Confirmed this is a bug, I'm looking into creating a PR for this in the next ~30 min.

**Comment by vraravam** [comment]
@L12C - @cino 's changes are merged in. Please download the next nightly (74) and verify and close this ticket.

**Comment by k1ba-meow** [comment]
Sorry for the delay, it works now. Thanks!
