### ISSUE TITLE
Bug: can't open mac arm version of ferdium

### ISSUE THREAD

**Issue by josefhelie** [ferdium/ferdium-app#34]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Steps to reproduce

Sorry my system is in French so I don't know the exact error label, but roughly I can't launch the arm version or Ferdium. The system displays a popup telling me that the app is damaged and cannot be opened. Intel version works after I authorized it in the security panel.

Thanks for your efforts guys!

**Comment by vraravam** [comment]
I m able to run the arm version. Please check if you can run this command from the `Terminal` window:
```bash
sudo xattr -rd com.apple.quarantine /Applications/Ferdium.app
```

All this does is remove the quarantine bit from that app's metadata in your macos.

Once this is done, you should be able to open Ferdium via Spotlight or double-clicking from the `/Applications` folder in Finder

Please also post a screenshot or other information of the specific version of Ferdium that you are trying to launch

**Comment by vraravam** [comment]
Closing the issue since its fixed by https://github.com/ferdium/ferdium-app/issues/34#issuecomment-1107655575

**Comment by josefhelie** [comment]
Okay thanks. Quick question, how can you imagine a random user to run a command line to make an app run? How did that happen?

**Comment by vraravam** [comment]
@josefhelie - the very first nightly had this in the release notes - that we do not have signed builds yet.

Searching the internet for "macos unsigned app" would have taken the user to the same command-line invocation. The intention that we had was to provide a quick mechanism for users to get off of the drama-train that's happening with Ferdi and the hosted servers.

Based on the release notes, the releases themselves being **nightly**, I dont think that's an unfair ask. Either ways, I do apologize for any inconvenience.

**Comment by b-n** [comment]
I'm not sure if this is the same issue, however here is a (non terminal) way to get around the lack of signed license on at least intel macs:

- Install the application (by dragging to Applications etc)
- On the First opening, right click the Ferdium, and click Open
- You will be prompted to "Open" or "Close" instead of just "Close"

^-- You only need to do this after each install (until the license is sorted).
