### ISSUE TITLE
Bug: Ribbon menu doesn't looks right in terms of design

### ISSUE THREAD

**Issue by AhmadrezaAlipouryaan** [ferdium/ferdium-app#343]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.74

### What Operating System are you using?

Windows

### Operating System Version

Windows 11 version 22000.776

### What arch are you using?

x64

### Expected Behavior

 It should be square but it's looks like something like square with rounded layer on top of it

### Actual Behavior

not a big issue

### Steps to reproduce

open the ribbon bar

### Screenshots

![image](https://user-images.githubusercontent.com/86818979/175292025-d590b6fc-6ff3-4043-a802-c059a7fbc0a2.png)

**Comment by vraravam** [comment]
@AhmadrezaAlipouryaan - could you please highlight/put an arrow around which part of that image feels wrong? we do not have any decoration like that in ferdium's codebase

**Comment by SpecialAro** [comment]
@vraravam he's referring to this part, which is misplaced (had been trying to make it look good for a while now)
![image](https://user-images.githubusercontent.com/37463445/175526859-ef74c7a3-fd12-41e0-a25d-2167e25a0dc4.png)
