### ISSUE TITLE
Bug: Unable to reorder apps when "Display service name.." is enabled

### ISSUE THREAD

**Issue by coderclan-bi** [ferdium/ferdium-app#346]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.73

### What Operating System are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

When "Display service name under the icon" (Settings > Appearance) is enabled, apps cannot be dragged and dropped into a new position.

### Actual Behavior

When "Display service..." is disabled, this functionality works as expected.

### Steps to reproduce

1. Settings > Appearance
2. Enable "Display service name under the icon"
3. Try to drag and drop services to re-order

### Additional information

https://issuehunt.io/r/getferdi/ferdi/issues/2191
This is original getferdi issue link

**Comment by vraravam** [comment]
This is because of these lines: https://github.com/ferdium/ferdium-app/blob/develop/src/components/services/tabs/TabItem.js#L369-L376

When the `showServiceNameSetting` is off/false, then there's only a single `img` tag in the DOM. When the setting is toggled, the `img` is nested within a `div` tag - which then breaks the drag-n-drop functionality. I have tested that this change breaks DnD, but I dont know how to fix it.

**Comment by cino** [comment]
@vraravam I tried to fix this last night but my lack of CSS skills made me quit, however, the solution would be to remove the div and change the CSS styling accordingly so the img&span are displayed correctly (they are already in a parent-div which can be utilized for arranging the divs on top of each other).

This would solve the draggable part, I just couldn't get it to align nicely so if anyone with proper CSS skills could do that :)

**Comment by vraravam** [comment]
Thanks @cino - yes, that's what I have done in #347

**Comment by pepper3k** [comment]
LOL I discovered this months ago and thought it was a feature by design!
