### ISSUE TITLE
Feature: Support Flatpak release officially

### ISSUE THREAD

**Issue by spazziale** [ferdium/ferdium-app#352]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I see that on flathub there is a version with some bugs ( Ex. dark mode doesn't work ). It feel like it's an unofficial port. Also on the website there isn't any mention to a flatpak version. I would like to see an official flatpak version. (Sorry for my bad english)

### Proposed Solution

Like the snap version, I would be great to publish a flatpak version on flathub repo.

### Alternatives Considered

If flatpak will not be supported, please add a COPR fedora repo.

**Comment by vraravam** [comment]
We would welcome code contributions from linux users to be able to do this @marc0x1

**Comment by ItzYanick** [comment]
i seems like Ferdium on Flathub is indeed active. It's just that it sticks with the beta versions instead of the nightly ones. This seems to lead to the missing features.

**Comment by lhw** [comment]
Hello everyone.
Yes, the flathub repository for ferdium is active but flathub does not have the required resources to have us build the nightly builds daily. So for now the master branch, what you see on flathub, features the beta builds and flathub-beta has the occasional nightly builds.

The latest beta 2 is already available via flathub and should fix most the issues present in beta 1.

**Comment by SpecialAro** [comment]
@lhw thank you for clarifying everything! Also, thank you so much for your hard work on that ☺️

I think we should close this issue now, as this is not an issue after all.

**Comment by NathanaelGandhi** [comment]
I see this issue implicitly highlighting the fact that the flatpak isnt mentioned in our documentation/website get instructions. Maybe it should be added there with a little description of the current beta only releases.

**Comment by nathanaelhoun** [comment]
Closing this as [FlatHub has the latest stable version of Ferdium](https://flathub.org/apps/details/org.ferdium.Ferdium) and flatpak is mentionned on the https://ferdium.org/download page.
