### ISSUE TITLE
Bug: Update from within the app does not work

### ISSUE THREAD

**Issue by doctopus** [ferdium/ferdium-app#363]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0 nightly 71

### What Operating System are you using?

macOS

### Operating System Version

Monterey 12.4

### What arch are you using?

x64

### Last Known Working Ferdium version

Unknown

### Expected Behavior

Under settings > Updates. With updates enabled, check for updates throws error both when the include pre-release is toggled on and off. It shows in red, "An error occurred, check the console for more details."

### Actual Behavior

Should normally fetch for update and update the app.

### Steps to reproduce

Settings > 
Updates > 
Check for Updates

**Comment by SpecialAro** [comment]
Hello @doctopus, thank you for raising this issue.

The in-app updates only started to work after Code Signing the app, which happened in the version `6.0.0-nightly.72` for macOS (and not on the 71) and for Windows in `6.0.0-nightly.76`.

This means that the in-app updates will only work for macOS for the nightly 72 onwards and for the Windows on the 76 onwards.

So, please, in your case, upgrade manually to the latest version or to version 72 and then check the in-app update feature.

**Comment by doctopus** [comment]
@SpecialAro Yes, Thank you. Updating it solved the in app update problem. Thank you. This thread may be closed.

**Comment by pwlnk** [comment]
Hi @SpecialAro, I'm using `6.0.0-nightly.99` version and the problem persist. The macOS version is _macOS Monterey 12.4_.
I tried to clean cache and Ferdium profile directory - didn't help.

![Screenshot 2022-07-13 at 13 41 43](https://user-images.githubusercontent.com/7137780/178725641-0cbb6df3-6bb4-49ae-8621-1ec96127039e.png)

**Comment by SpecialAro** [comment]
> Hi @SpecialAro, I'm using `6.0.0-nightly.99` version and the problem persist. The macOS version is _macOS Monterey 12.4_. I tried to clean cache and Ferdium profile directory - didn't help.

@pwlnk have you tried to check the "Pre-releases" toggle above the "Check for updates" button? We're currently on nightlies, with no stable release, so you need to toggle that.

**Comment by pwlnk** [comment]
After check on "Pre-releases" the message disappeared indeed. Thank you! :)
