### ISSUE TITLE
Bug: Empty value in Accent Color input Crash the App in any reload

### ISSUE THREAD

**Issue by achavazza** [ferdium/ferdium-app#368]
### Avoid duplicates

- [x] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.77

### What Operating System are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Ferdium version

6.0.0-nightly.77

### Expected Behavior

I was trying to reset the default Ferdium color, expecting some fallback or default value

### Actual Behavior

The app went in a crash loop, with no message other than a "reload" button.

### Steps to reproduce

1. Go to Setting / Appearance
2. Emtpy both values in Accent Color Settings
3. Apply Color
4. Reload

Now the app will crash everytime

**Comment by SpecialAro** [comment]
I'm not able to reproduce this on Windows 11.

**Comment by SpecialAro** [comment]
I finally was able to reproduce this issue and now my Ferdium is broken :c
