### ISSUE TITLE
Bug: can't move window in mac

### ISSUE THREAD

**Issue by helloabella** [ferdium/ferdium-app#370]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-beta.2

### What Operating System are you using?

macOS

### Operating System Version

macOS Monterey 12.4

### What arch are you using?

x64

### Last Known Working Ferdium version

6.0.0-nightly.69

### Expected Behavior

Able to drag app window around with the top section of the app

### Actual Behavior

Was able to drag window for a brief second before Skype fully loaded, but does not work on Whatsapp or Slack.

### Steps to reproduce

1. Open App
2. Attempt to drag window around

### Debug link

https://debug.ferdium.org/0b690e10-b6ad-4650-8181-5f250501d1e8

**Comment by cino** [comment]
@helloabella I'm closing this issue as the problem has been resolved in #372 and released in the  v6.0.0-nightly.79 release. If you have any other issues feel free to open an issue again.
