### ISSUE TITLE
Feature: Indication Icon which service is playing sound

### ISSUE THREAD

**Issue by Latschenharry** [ferdium/ferdium-app#371]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

If one service is playing sound/music there is no way of seeing which it is.

### Proposed Solution

A small speaker icon next to the service icon that plays the sound.
![icone-de-haut-parleur-jaune](https://user-images.githubusercontent.com/12736979/175811032-ca589ef2-1e88-4dc1-9437-636358f65b27.png)

### Alternatives Considered

A button to jump to the active service

**Comment by santhosh-chinnasamy** [comment]
@vraravam / @SpecialAro this can be closed.

**Comment by SpecialAro** [comment]
Yes @santhosh-chinnasamy 😊 thank you very much for your contribution!
