### ISSUE TITLE
Bug: Discord service displays mobile version

### ISSUE THREAD

**Issue by WillyReyno** [ferdium/ferdium-app#379]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.74

### What Operating System are you using?

macOS

### Operating System Version

macOS Monterey 12.4

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Ferdium version

none

### Expected Behavior

Discord service should be displayed on its desktop version 

### Actual Behavior

When opening Discord on Ferdium the mobile version is displayed

### Steps to reproduce

1. Install Ferdium
2. Add Discord service
3. Log into Discord

### Debug link

https://debug.ferdium.org/08ce4f50-74df-46b7-b696-207c4d0672ac

### Screenshots

![Capture d’écran 2022-06-27 à 12 46 12](https://user-images.githubusercontent.com/5576482/175926127-3fb50cc0-b87c-4b12-8a2e-ccb54df2e39f.png)
![Capture d’écran 2022-06-27 à 12 47 03](https://user-images.githubusercontent.com/5576482/175926131-b9a4660a-313f-4dcd-b731-bb39dc72ad23.png)

**Comment by vraravam** [comment]
Please see the last FAQ here: https://ferdium.org/faq
