### ISSUE TITLE
Feature: Add new hosted server: api.ferdium.org

### ISSUE THREAD

**Issue by vraravam** [ferdium/ferdium-app#38]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Currently, since we forked from ferdi, the code only supports 4 "servers" for non-accountless usage:
1. Franz hosted
2. Ferdi hosted
3. Ferdi self-hosted
4. Local

Since we would like our users to not have to deal with the ongoing drama about the hosted server being taken down, we need to give a solution for the same.

### Proposed Solution

The proposal is to add another server (Ferdium hosted) into the above chain. The user is then free to choose whichever server they want to use - assuming that they do not want the accountless option.

### Alternatives Considered

Pre-existing servers - but, the user is at the mercy of whoever controls that server's up/down status.

**Comment by SpecialAro** [comment]
Hey @vraravam ! Do you mean this?
![image](https://user-images.githubusercontent.com/37463445/165289536-e60d083d-1e78-46f2-bb2b-40d733956daa.png)

I can push a PR with those changes if that is what you mean by this enhancement. If not, then I apologize for my misinterpretation of the enhancement

**Comment by vraravam** [comment]
Yes - this is one of the changes. If you also search for usages of `LIVE_FERDIUM_API` and `LIVE_FRANZ_API` - and follow the logic threads wherever they are being used - that should be what this ticket is for.

Also, as a part of the rebranding, we seem to have changed the `ferdi` server, and its not present now. We should probably resurrect that as part of this ticket.

**Comment by vraravam** [comment]
@SpecialAro - can this feature request be closed based on the PR that you raised?

**Comment by SpecialAro** [comment]
Yes, please. That PR solves this issue. Thank you very much for raising it 😁
