### ISSUE TITLE
Bug: Ferdi logo displayed in internal import export webserver pages

### ISSUE THREAD

**Issue by BrianGilbert** [ferdium/ferdium-app#39]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.10

### What Operating System are you using?

macOS

### Operating System Version

12.3.1 (21E258)

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

See ferdium branding

### Actual Behavior

seeing ferdi logo

### Steps to reproduce

1. Access Help menu and select Import/Export Configuration Data

### Screenshots

![ferdium-internal-server 2022-04-25 08-27-54](https://user-images.githubusercontent.com/114017/164999521-cf647552-78a5-4639-8bfe-0fe3076e85c0.png)

**Comment by vraravam** [comment]
Whoever works on this ticket, [this file](https://github.com/ferdium/ferdium-app/blob/develop/src/internal-server/public/images/logo.png) needs to be updated to the new logo for Ferdium.

**Comment by mydarkstar** [comment]
Should be fixed with the next nightly release (12). Thank you for the report!

**Comment by vraravam** [comment]
@BrianGilbert - can you please verify and close this ticket?

**Comment by BrianGilbert** [comment]
@vraravam confirmed
![ferdium-internal-server 2022-04-30 11-37-41](https://user-images.githubusercontent.com/114017/166085601-df7daa6d-094d-4bd2-ac86-f2fe2dfb6970.png)

**Comment by mycanaletto** [comment]
Same problem in custom web site, the imported logo does not appear in the sidebar, regardless of its size ....
![image](https://user-images.githubusercontent.com/45459269/167154886-ee766ea1-c243-4555-b2ca-814ac03d4a92.png)

**Comment by vraravam** [comment]
@mycanaletto - that is a different problem - please raise a different bug ticket for this

**Comment by mycanaletto** [comment]
> @mycanaletto - that is a different problem - please raise a different bug ticket for this

OK, sorry, I have deleted
