### ISSUE TITLE
Bug: Auto-Update Installer reporting ferdium still running

### ISSUE THREAD

**Issue by Shrekmachine** [ferdium/ferdium-app#398]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0.-nightly.80

### What Operating System are you using?

Windows

### Operating System Version

Win11 64b

### What arch are you using?

x64

### Last Known Working Ferdium version

6.0.0-nightly.78?

### Expected Behavior

Updating to newest version after pressing update button

### Actual Behavior

Update from within App not working. Installer reporting ferdium still running while it is not showing in the Win Task Manager

### Steps to reproduce

Click on Restart & install update in big blue banner at bottom

### Screenshots

![image](https://user-images.githubusercontent.com/8019511/176510344-6aabf170-1623-4354-8980-4a302d5edadf.png)
![image](https://user-images.githubusercontent.com/8019511/176510452-bbf4925b-bcd9-49e4-90b0-b4aee0639ee5.png)

**Comment by SpecialAro** [comment]
Hello @Shrekmachine , can you please check if the tray icon is still there? Also, can you post some more screenshots of the Windows Manager?

Thank you.

Also, next time, make sure you write the correct title on the issue, please.

**Comment by Shrekmachine** [comment]
Hi, tray icon gone. Only ferdium related in Task Manager is the installer
![image](https://user-images.githubusercontent.com/8019511/176515181-1a0129e2-78ce-49a0-bc6e-714b77fc3b3e.png)
![image](https://user-images.githubusercontent.com/8019511/176515508-ff33d719-3bb0-48c1-ac8e-3d035a189cf8.png)

**Comment by Shrekmachine** [comment]
After cancel there comes a 2nd popup
![image](https://user-images.githubusercontent.com/8019511/176515771-8bcb8856-53aa-4f12-95a3-48205abd0ff3.png)
Basically saying that "the old applications data could not be deinstalled. Please try to rerun the installer"

**Comment by SpecialAro** [comment]
Maybe this is a faulty installation on your side.

#### Connected to Ferdium Server (which will keep data) or don't mind loosing data
**Are you connected to Ferdium Server?** If so, please try to uninstall Ferdium (make sure `%APPDATA%/Roaming/Ferdium` is also deleted) and try to install Ferdium nightly.79 and try to update it again.

**If you're not connected to Ferdium Server** and don't mind loosing data, do the same as above.

### OR

#### You want to keep your data
Try to manually download the latest nightly manually (https://github.com/ferdium/ferdium-app/releases/tag/v6.0.0-nightly.81) and install it over the current version you have.

**Comment by Shrekmachine** [comment]
Thanks for the recommendation.
manual download and overwriting in folder worked, but did not change behaviour.
I'll try complete uninstall as I reinstalled using Ferdium server couple of days ago.

**Comment by SpecialAro** [comment]
> I'll try complete uninstall as I reinstalled using Ferdium server couple of days ago.

Please do... and make sure to delete this path `%APPDATA%/Roaming/Ferdium`

**Comment by Alphrag** [comment]
I have noticed that clicking the "try again" 2-3 times made it work usually.

@SpecialAro It looks like there is a time race going on here. On Mac we need to make sure that the app stays running for long enough for the updates to trigger while it appears that for Windows we need to close it as early as possible when the update is meant to happen. We will need to have another look at that code and possibly make it conditional on the os.

**Comment by SpecialAro** [comment]
> I have noticed that clicking the "try again" 2-3 times made it work usually.
> 
> @SpecialAro It looks like there is a time race going on here. On Mac we need to make sure that the app stays running for long enough for the updates to trigger while it appears that for Windows we need to close it as early as possible when the update is meant to happen. We will need to have another look at that code and possibly make it conditional on the os.

Yes, maybe we need to implement that ... Different times for different OSes (goddammit) xD

**Comment by Shrekmachine** [comment]
I noticed that Franz and Ferdi folders were still present. Ferdi was even installed.
I deleted all now by windows feature and then removing all fragments.
Interestingly it showed Ferdium installed twice. Once as regular install and once as nightly.
Reinstall worked incl. reconnectign to Ferdium server.
Seems some settings like chat and icon size are locally stored. Had to reconnect all devices.
Update check currently failing

**Comment by SpecialAro** [comment]
> Update check currently failing

This is due to another issue (draft releases on GH). But should be working properly now

**Comment by Shrekmachine** [comment]
![image](https://user-images.githubusercontent.com/8019511/176658155-eeb0a9ba-32c0-46ee-9608-edd35d638e2b.png)
Let me know in case I can support with a log

**Comment by SpecialAro** [comment]
> Let me know in case I can support with a log

If you can provide a log it would be good. But it's most likely the problem with draft releases (there is no .82 version available yet)

**Comment by Shrekmachine** [comment]
ok, I'll monitor it, raise a new issue if needed, once new releases are available.
thanks for your support.

**Comment by Shrekmachine** [comment]
Update is working now. No blocked update routine, no error message in setup / updates.
I can't confirm if it is solved by reinstallation as such or because of the version that was installed with it (.81), but it works :)
Thanks again

**Comment by SpecialAro** [comment]
Awesome 😁 glad you managed to solve it.

I'm closing this issue now. If there is a need of reopening it in the future, please comment on it 👍
