### ISSUE TITLE
Bug: Gmail redirects to HTML version while using business email

### ISSUE THREAD

**Issue by TheRealGramdalf** [ferdium/ferdium-app#399]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0b2

### What Operating System are you using?

Other Linux

### Operating System Version

Fedora 36

### What arch are you using?

x64

### Expected Behavior

Gmail will load in full version

### Actual Behavior

Gmail gives a banner message
![image](https://user-images.githubusercontent.com/79593869/176562613-ead1eb97-0379-4603-a461-1d74eced680a.png)
and loads the HTML version

### Steps to reproduce

1. Add a gmail account using a business address (signin through the google portal, but with your own end, i.e. email@mywebsite.com)
2. Switch workspaces to a workspace without the gmail account
3. Switch back
4. HTML version is loaded

**Comment by TheRealGramdalf** [comment]
Forgot to add this in additional information:

Setting a different useragent didn't work (tested multiple, including chrome on a chromebook from whatmyuseragent.com)
Gmail loads perfectly fine normally, it is only with the custom @mywebsite that it breaks down.

**Comment by SpecialAro** [comment]
For me, using a custom @Mywebsite works:
![image](https://user-images.githubusercontent.com/37463445/176633227-b7ff6bec-a9f3-4676-92ca-c7f80f7431cb.png)

**Comment by vraravam** [comment]
My company also uses gmail with a custom domain - and I dont see any issues.

**Comment by cino** [comment]
Closing the issue due to no response since Jul 3.
