### ISSUE TITLE
Bug: Slack screen remains blank/white after logging in via SSO

### ISSUE THREAD

**Issue by ndemie** [ferdium/ferdium-app#410]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

v6.0.0-nightly.84

### What Operating System are you using?

macOS

### Operating System Version

macOS 12.4 (21F79)

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Slack logs in and shows the dashboard

### Actual Behavior

After logging in to Slack the screen remains white/blank. 

### Steps to reproduce

1. Add Slack service with domain that requires SSO
2. Login via SSO
3. Screen becomes white/blank

### Screenshots

<img width="1501" alt="Screenshot 2022-07-01 at 15 25 50" src="https://user-images.githubusercontent.com/5329710/176903668-24c6b7a3-01cf-4003-bcdc-26f3b42c5db1.png">

### Additional information

Doing a reload or removing the service and readding it results in the same behaviour

**Comment by ndemie** [comment]
I also tried using the "Custom Website" service and the same behaviour happens there. Looking at the URL the callback from Google back to Slack doesn't work; it stays on the blank/white page where it is supposed to happen

**Comment by ndemie** [comment]
Overwriting the User Agent with the latest Chrome User Agent `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36` fixes this issue

**Comment by vraravam** [comment]
Closing the issue - since that's the intended use of the user-agent being controlled by the user as needed.
