### ISSUE TITLE
Bug: Autostart enabled in Portable Windows starts temporary binary.

### ISSUE THREAD

**Issue by n00b42** [ferdium/ferdium-app#415]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.74

### What Operating System are you using?

Windows

### Operating System Version

Ferdium-6.0.0-nightly.74.exe

### What arch are you using?

x64

### Expected Behavior

Enabling Autostart in the Portable version should configure to start the portable binary as the temporary binary does not know about the portable FerdiumAppData folder.

### Actual Behavior

Autostart starts the temporary binary, creating a new profile instead of using the FerdiumAppData folder.

### Steps to reproduce

- Start portable
- Configure stuff
- Configure Autostart
- Reboot
- Ferdium launches with empty/new profile

**Comment by n00b42** [comment]
Reported that in Discord as well, but figured it might be better documented here.
Furthermore, it makes it easiert to add and follow information about it.

**Comment by n00b42** [comment]
Some hints (without knowing the inner workings so far)

[AppStore.ts](https://github.com/ferdium/ferdium-app/blob/develop/src/stores/AppStore.ts)
```
const executablePath = isMac ? remoteProcess.execPath : process.execPath;
const autoLauncher = new AutoLaunch({
  name: 'Ferdium',
  path: executablePath,
});
```

Probably, `process.execPath` points to the temporary binary.
Checking and using `process.env.PORTABLE_EXECUTABLE_DIR` might help?
(Reference: https://github.com/electron-userland/electron-builder/issues/3186)

**Comment by Alphrag** [comment]
Yes that is a very good point, I think we need to make a few tests regarding the value of `PORTABLE_EXECUTABLE_DIR` in order to change the executable path so that both a menu shortcut and autostart would work. We will have a look at that.

**Comment by n00b42** [comment]
Sorry, I meant to reference `PORTABLE_EXECUTABLE_FILE`, as we need the filename as well...
