### ISSUE TITLE
FAQ Windows msi installer "additional options"

### ISSUE THREAD

**Issue by n00b42** [ferdium/ferdium-app#424]
### Your issue

The FAQ states: `The msi installer: [...] this installer allows for a few additional options when installing the app compared to the automatic installer`.

Which "additional options", if I remember correctly, it does not ask for any option, and just automatically installs.

**Comment by SpecialAro** [comment]
> ### Your issue
> The FAQ states: `The msi installer: [...] this installer allows for a few additional options when installing the app compared to the automatic installer`.
> 
> Which "additional options", if I remember correctly, it does not ask for any option, and just automatically installs.

Have you downloaded the `.msi` file? The `.exe` installer installs without prompting any options, but the `.msi` one should prompt the user.

**Comment by Alphrag** [comment]
Hmm you seem to be right that it installs without prompt. I'm sure the `.msi` was asking for install location at some point 😕 
I'll have a look at this and otherwise, we will simply delete that information on the FAQ ^^

**Comment by SpecialAro** [comment]
> I'm sure the `.msi` was asking for install location at some point 😕

Just tested myself and it didn't asked, in fact... But it should. Does it have to do/Can it be related with any updates on the `electron-builder`?

**Comment by vraravam** [comment]
`msi` installer has been removed in #459

**Comment by Alphrag** [comment]
The FAQ on the website has also been updated to reflect the change: (cf https://github.com/ferdium/ferdium-website/pull/28).
