### ISSUE TITLE
Bug: Can't login to slack if two factor auth is active

### ISSUE THREAD

**Issue by vmgustavo** [ferdium/ferdium-app#427]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-beta.2

### What Operating System are you using?

Ubuntu

### Operating System Version

Ubuntu 20.04.4 LTS

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

The page to input the code for the two factor authentication should appear

### Actual Behavior

The page freezes nothing shows up to input the code and it goes back to the starting page to log into Slack

### Steps to reproduce

1. Add Slack as a service
2. Login through Google Sign In
3. Try to log in
4. Wait for code
5. It goes back to login page

### Debug link

https://debug.ferdium.org/bc427dc5-7748-4b56-ae76-505b004dc980

**Comment by SpecialAro** [comment]
Hello @vmgustavo . This is a duplicate issue of https://github.com/ferdium/ferdium-app/issues/256.
