### ISSUE TITLE
Bug: Links to Discord messages are opened in browser outside the Ferdium client

### ISSUE THREAD

**Issue by tarragonfly** [ferdium/ferdium-app#431]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.89

### What Operating System are you using?

Windows

### Operating System Version

Windows 11 Home 21H2

### What arch are you using?

x64

### Last Known Working Ferdium version

None?

### Expected Behavior

When using Discord's "Copy Message Link" function and clicking the link it generates, I'd expect Ferdium client to center on the linked message when that link is clicked.

### Actual Behavior

Clicking a Discord link generated by "Copy Message Link" function opens the linked message in browser outside the Ferdium client.

### Steps to reproduce

1. Use "Copy Message Link" to copy a Discord message
2. Paste that link and post it as a new message in a Discord channel
3. Click the link

### Debug link

This does not seem to work on my portable version of Ferdium with no account.

**Comment by vraravam** [comment]
This already controllable by the user using this preference:
<img width="625" alt="Screenshot 2022-07-06 at 6 21 58 AM" src="https://user-images.githubusercontent.com/69629/177440249-8085a443-fc7f-4281-8814-95269c086d40.png">


Right click on the service in the sidebar, and click `Edit`, which will open the service-specific settings. In there, you will find the above option. Remember to reload the service after this change.

**Comment by tarragonfly** [comment]
It's not the same thing though since I expect only Discord message URLs to be contained within Ferdium so it would be consistent with the native Discord client or Discord opened in a browser. This is also how it worked in Ferdi, Rambox and others.

The option highlighted above opens all URLs including ones to external websites right inside Ferdium, which I don't want to happen.

**Comment by SpecialAro** [comment]
> The option highlighted above opens all URLs including ones to external websites right inside Ferdium, which I don't want to happen.

@vraravam I think this is a feature request instead of a bug.

Also, most certainly that Ferdi did not have this implementation @tarragonfly , given that this is a hard fork of it.

**Comment by vraravam** [comment]
I agree @SpecialAro - looks like a new enhancement to differentiate between the service-level URLs (and open them within the same service) whereas for URLs that are not from that same service to be opened in an external browser.

@tarragonfly - please create a new enhancement card describing exactly what you want implemented.
