### ISSUE TITLE
Feature: Folder

### ISSUE THREAD

**Issue by alphamalli** [ferdium/ferdium-app#442]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Hello Jerami,

Can you add folder feature like discord server folder system or android or iphone folder system...

So we can stack application I mean webs into folders which is really would helpful to someone who does multitask And they can organize their workstation :)

          Have a nice day Jerami

                                                                             ~neo wixx~ 

### Proposed Solution

![Screenshot_20220707-130825_Discord](https://user-images.githubusercontent.com/89414195/177769269-f0bfc674-d6e5-4df5-8e87-cb3bbad98030.jpg)
#194

**Comment by cino** [comment]
If this is something we are going to implement we would need to think about how we change the cmd/ctrl+<number> shortcuts as this will impact that.

**Comment by alphamalli** [comment]
> 

Well Jerami,

I'm pretty new to ferdium but this concept is pretty cool, I just felt that folders would make it more enjoyable. I personally use 3 discords in ferdium so you know why I am saying, it's useful for every ferdium fellas

But I have never tried that cmd/Ctrl+ shortcut thing...

**Comment by cino** [comment]
I suggest you have a look at the feature we call Workspaces, this actually resolves the need of having folders like this as this is most likely not going to be implemented. 

I'm closing this issue for now, If you would lke to discuss this further you can reach us at [Discord](https://discord.gg/jVv4Qns8pP)
