### ISSUE TITLE
Feature: Contain Discord specific URLs to Ferdium client

### ISSUE THREAD

**Issue by tarragonfly** [ferdium/ferdium-app#446]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Discord has a built in function to link to specific messages via the "Copy Message Link" option. Clicking that link in the native Discord client centers on the linked message, it does not open the URL externally. Same with a browser tab where Discord is opened - clicking the message link centers on the message, it does not open a new browser tab.

Currently, in Ferdium client clicking Discord message link opens that message externally in the browser, which is not consistent with how native Discord and browser Discord work. 

Note that only Discord message URLs are contained within Discord, it still opens any external links in the browser as usual. 

The "Open URLs within Ferdium" option is also not the solution since it opens all URLs in Ferdium when I only expect the Discord message links to be contained within Ferdium.

### Proposed Solution

Contain Discord message ID URLs to the Ferdium client so it's consistent with native client and browser versions of Discord.

### Alternatives Considered

I don't have any alternatives in mind. It could maybe be made optional, but it'd make more sense to have Discord behaviour be consistent no matter where it's open.

**Comment by SpecialAro** [comment]
Thank you @tarragonfly for logging this issue.
This should be fixed in the next nightly. You can comment below to reopen the issue if it persists. Thank you!
