### ISSUE TITLE
Bug: out of the box - No UI element that allows me to go back to select server/use offline account

### ISSUE THREAD

**Issue by ayim** [ferdium/ferdium-app#449]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-beta.2

### What Operating System are you using?

Windows

### Operating System Version

Windows 10 OS Build 19044.1806

### What arch are you using?

x64

### Expected Behavior

![image](https://user-images.githubusercontent.com/10951869/178080779-c07e6234-88bd-4535-be8d-758fdfb4a9f9.png)

Upon seeing this screen, I should have the ability to go back and select use offline account/Franz server.
![image](https://user-images.githubusercontent.com/10951869/178080851-c3c295e9-efae-4e28-8838-9443fd631509.png)

### Actual Behavior

I am stuck on this screen.

### Steps to reproduce

1. Launch Ferdium
2. Go to "Sign-in"

### Screenshots

![image](https://user-images.githubusercontent.com/10951869/178080779-c07e6234-88bd-4535-be8d-758fdfb4a9f9.png)

**Comment by SpecialAro** [comment]
Hello! Thank you for logging this issue.

You can go back if you press the big ferdium logo.
