### ISSUE TITLE
Bug: After auto-updating APP screen stays blank

### ISSUE THREAD

**Issue by SpecialAro** [ferdium/ferdium-app#460]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.93

### What Operating System are you using?

Windows

### Operating System Version

11

### What arch are you using?

x64

### Last Known Working Ferdium version

6.0.0-nightly.91

### Expected Behavior

After an automatic in-app update the app starts itself and I can see my services.

### Actual Behavior

After an automatic in-app update the app starts itself but only a blank screen appears

### Steps to reproduce

1. Update through the in-app update feature
2. Let the update finish and the app start itself (automaticly) after
3. See the blank screen

### Screenshots

![image](https://user-images.githubusercontent.com/37463445/178160726-430cf4c8-733d-4a9e-b34b-be41afa8c0e1.png)

### Additional information

This seems to be related with this PR https://github.com/ferdium/ferdium-app/pull/406 and this one  https://github.com/ferdium/ferdium-app/pull/444 (@cino), as I was not experiencing this before - altough I haven't tested it enough to comprove it.

Other changes on .92 (that seem to be unrelated to this):
* Upgrade 'macos-notification-state' to '2.0.1' by @vraravam in https://github.com/ferdium/ferdium-app/pull/440

Errors on console:
![image](https://user-images.githubusercontent.com/37463445/178161044-40baa909-5b91-4505-98fd-a6a369fc6eb2.png)
![image](https://user-images.githubusercontent.com/37463445/178161051-62668604-d707-4062-a050-e99cb099874c.png)
![image](https://user-images.githubusercontent.com/37463445/178161059-68980e17-28ab-47fe-a95b-9902a46da9ee.png)

**Comment by SpecialAro** [comment]
Seems like #463 didn't fix this issue.

**Comment by M0UL** [comment]
for me the last update made it worse.  with the previous build  restarting the would make it load again. this no longer works. 

edit: downgrading the app. made it load again.

**Comment by SpecialAro** [comment]
> for me the last update made it worse. with the previous build restarting the would make it load again. this no longer works.

Yes, I'm fixing it now... seems like an issue with a dependency.

**Comment by M0UL** [comment]
version .96  works after a manual restart

**Comment by pepper3k** [comment]
I can confirm this bug as well:
Win7x64

I had to roll back.

**Comment by csolisr** [comment]
Currently having a similar problem on Windows, not sure if it's related to patch #464 . Starting the app from command line outputs the following error:

```
SyntaxError: C:\Users\user\AppData\Roaming\Ferdium\config\proxy.json: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at readFileSync (C:\Users\user\AppData\Local\Programs\ferdium\resources\app.asar\node_modules\fs-extra\node_modules\jsonfile\index.js:52:17)
    at Settings._hydrate (C:\Users\user\AppData\Local\Programs\ferdium\resources\app.asar\electron\Settings.js:1:799)
    at new Settings (C:\Users\user\AppData\Local\Programs\ferdium\resources\app.asar\electron\Settings.js:1:485)
    at Object.<anonymous> (C:\Users\user\AppData\Local\Programs\ferdium\resources\app.asar\index.js:1:2172)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
```

**Comment by SpecialAro** [comment]
> Currently having a similar problem on Windows, not sure if it's related to patch #464 . Starting the app from command line outputs the following error:
> 
> ```
> SyntaxError: C:\Users\user\AppData\Roaming\Ferdium\config\proxy.json: Unexpected token  in JSON at position 0
>     at JSON.parse (<anonymous>)
>     at readFileSync (C:\Users\user\AppData\Local\Programs\ferdium\resources\app.asar\node_modules\fs-extra\node_modules\jsonfile\index.js:52:17)
>     at Settings._hydrate (C:\Users\user\AppData\Local\Programs\ferdium\resources\app.asar\electron\Settings.js:1:799)
>     at new Settings (C:\Users\user\AppData\Local\Programs\ferdium\resources\app.asar\electron\Settings.js:1:485)
>     at Object.<anonymous> (C:\Users\user\AppData\Local\Programs\ferdium\resources\app.asar\index.js:1:2172)
>     at Module._compile (node:internal/modules/cjs/loader:1118:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
>     at Module.load (node:internal/modules/cjs/loader:988:32)
>     at Module._load (node:internal/modules/cjs/loader:829:12)
>     at c._load (node:electron/js2c/asar_bundle:5:13343)
> ```


On which version are you on?

**Comment by csolisr** [comment]
> On which version are you on?

Nightly as usual. I also manually uninstalled and reinstalled Nightly v96.

**Comment by SpecialAro** [comment]
Please update to the latest beta (.3)
Nevertheless a full close and manual star of the app should work fine.

Please report back after installing the beta.3

**Comment by csolisr** [comment]
Good news, installing the beta solved my issue.

**Comment by pepper3k** [comment]
I can confirm that installing nightly 98 solved this issue for me.
