### ISSUE TITLE
Bug: The offer to perform an update while using an appimage does not work as expected.

### ISSUE THREAD

**Issue by meiphoo7-Mae** [ferdium/ferdium-app#461]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.93

### What Operating System are you using?

Ubuntu

### Operating System Version

Ubuntu 22.04

### What arch are you using?

x64

### Last Known Working Ferdium version

It has never worked.

### Expected Behavior

When running the appimage, it should tell there's an update and invite the user to download it, but not actually offer to perform the update. Or perhaps even better: download the appimage and tell the user to use that appimage.

### Actual Behavior

When running the appimage, it offers to perform the update. This is not going to work out well because an appimage cannot be updated (that's why it is called an image of course...). What it in fact does is perform an update of the currently unpacked running version of Ferdium. This is unfortunate because that unpacked version resides in a subfolder of the /tmp folder which is erased at every reboot (at least on Ubuntu, I believe even in all modern Linux versions).
So an update is indeed performed but it only survives until the next reboot. Even worse: if Ferdium is terminated the whole subfolder where it is installed is deleted including the 'update'.

Related:
Also disable the option to start Ferdium at boot when using an appimage, because it installs a startup-script like:
```
[Desktop Entry]
Type=Application
Version=1.0
Name=ferdium
Comment=ferdiumstartup script
Exec=/tmp/.mount_FerdiuXXXXXX/ferdium
StartupNotify=false
Terminal=false
```
where XXXXXX is a sequence of 6 random characters. The "Exec" line refers to the temporarily existing subfolder of /tmp I mentioned above.
The only viable option here is replace the "Exec" line with the path to the actual appimage in order to unpack and run the appimage at every boot.
I've used that modification for over a year now and it works every time.

### Steps to reproduce

Just run the appimage on Linux, look in the /tmp directory in which folder it has been unpacked and look at the startup script (on Ubuntu it is in ~/.config/autostart). To make it even clearer: terminate Ferdium and run the appimage again. You'll see the folder where it is unpacked is different each time.

**Comment by Alphrag** [comment]
Heya, thanks for the details. I have personally been using the appimage and its auto-update feature since we started Ferdium and have made it work (under ubuntu 20.04). What the auto-updater does is that it downloads the new appimage next the to previous one, and then when it closes and reopen, it deletes the previous appimage and runs the new one. From my understanding of the structure of an appimage, these are meant to be run as standalone executable instead of the unpacked folder it puts into /tmp to help it run. 

I also have a `ferdium.desktop` stored at `.local/share/applications/` which does perfectly the job for everything (using indeed the path of the appimage itself which means that between nightlies we need to rename it), and I have never seen the script you mention. If you know where it is generated I can take a look closely and see if there is anything we can change in the build settings relatively to this (I know that one is automatically created for a `.deb` install).

I would be interested to know where your appimage is located and where does it put the `.desktop` file (none was automatically set on my computer which is why I manually had to create one).

**Comment by meiphoo7-Mae** [comment]
Well, that's interesting. We have the same OS and different observations. So let's elaborate on that.
I routinely store any downloads (including appimages) in: ~/Downloads.
I'm pretty sure the updater does not download the appimage automatically because after my experiment I downloaded the latest appimage manually and there was no message about a file being overwritten. What I did see is that in the /tmp folder there was initially 1 folder with a random name and after the update there were 2 of them. After exiting Ferdium both were gone so one of those contained the "old" version and the other one the "updated" version.

The appimage does not automatically install a .desktop file. To get the .desktop file you'll need to start Ferdium first and then when you activate the first switch in the general settings of Ferdium (the one about starting Ferdium during boot) the file is created. The .desktop file is included in the appimage itself and is copied with some modifications to the location I mentioned.
It is possible yours ends up in a different location because I use Kubuntu (Ubuntu with KDE desktop).

**Comment by meiphoo7-Mae** [comment]
I've made a little progress. The updater does download the appimage but stores it in the folder ~/.cache/ferdium-updater/pending. So it's is not in ~/Downloads from where I run the manually downloaded appimages.
Also after performing the update, the appimage is deleted and can only retained by manually copying it to another location before performing the update.

Edit: after some close inspection:
Wait a minute..., I need to do more research. It seems that the updater DID replace the old AppImage now. But I don't know for sure as I cannot remember right now if I renamed it manually.

**Comment by Alphrag** [comment]
> Edit: after some close inspection: Wait a minute..., I need to do more research. It seems that the updater DID replace the old AppImage now. But I don't know for sure as I cannot remember right now if I renamed it manually.

Aha ok, interesting.

I have checked on my side and when the app updates, there is nothing in /tmp that changes, and it downloads it where I have stored it (which is a special location where I have privileges on my work computer at `/usr/local/localapps`, so far from Downloads or usual locations).
I am using Gnome so the handling of appimages might be different that KDE (who knows ^^), but I can try to see if something different happens with xfce later today if you want.

**Comment by meiphoo7-Mae** [comment]
I did more testing and the situation is as follows:
The appimage still resides in ~/Downloads. I renamed it to Ferdium, as I'm not particularly interested in the original name because I can always find that from within Ferdium itself and it is useful for my custom startup script because I can use the short customized name.

I did not do any manual action and just tried the updater and therefore this time I can confirm that updater replaced the old appimage with the new appimage and it even retained the custom name that I mentioned above so my custom startup script is still valid.

I believe something has changed in the nightly.94 to nightly.96 versions that made it work.
So I guess this part of the issue is solved. Then we still have the issue of the startup script. I already revealed I use a custom version and you said you use a custom version too. So I think we can reach the conclusion that this 'works for us'. I don't see a reason to pursue this any longer and actually I didn't check what happens in the recent version because I'm happy with my custom script.
Then we have the subject of the two temporary folders. I've made a screenshot and in the red box are the two temporary folders. After the next reboot there's only one left so I think this is also not an urgent problem.

![Screenshot_20220713_020841](https://user-images.githubusercontent.com/95827976/178624942-425c12bc-ea3c-4d56-9353-54dc337403d5.png)

**Comment by Alphrag** [comment]
> I did more testing and the situation is as follows: The appimage still resides in ~/Downloads. I renamed it to Ferdium, as I'm not particularly interested in the original name because I can always find that from within Ferdium itself and it is useful for my custom startup script because I can use the short customized name.
> I did not do any manual action and just tried the updater and therefore this time I can confirm that updater replaced the old appimage with the new appimage and it even retained the custom name that I mentioned above so my custom startup script is still valid.

Holy Grail, the change of name works! :astonished: I think when we started and I tried to modify the name it didn't like it, so I kept modifying my `ferdium.desktop` to reflect the name change after each update. That will make my life so much easier now! :laughing: 

> I believe something has changed in the nightly.94 to nightly.96 versions that made it work. So I guess this part of the issue is solved. 

Hmm, nothing explicit from our side that I can recall tbh... but as long as it does the job, that's the most important :+1: 

> Then we still have the issue of the startup script. I already revealed I use a custom version and you said you use a custom version too. So I think we can reach the conclusion that this 'works for us'. I don't see a reason to pursue this any longer and actually I didn't check what happens in the recent version because I'm happy with my custom script. Then we have the subject of the two temporary folders. I've made a screenshot and in the red box are the two temporary folders. After the next reboot there's only one left so I think this is also not an urgent problem.

Ok, I have found these temp folder. This corresponds to the run of the appimage. If you close the app, the folder will be deleted, as it is only there during execution (temporary unpacking), so no problem on this side.
Now there is inside this temporary folder a `ferdium.desktop` that we could maybe use. [I have to check but I think it corresponds to a similar one created for `.deb` package :thinking: ] I think in the short term we can keep it as manual (I'll add something in the documentation for that then) but I'll have a think about putting a toggle in the setting that would create a file in the appropriate location, and that would modify it upon update if that setting is turned on (in case a user wants it in a different place or with different parameters).

**Comment by Alphrag** [comment]
I will mark this as closed for now, but feel free to reopen if needs be :slightly_smiling_face:

**Comment by meiphoo7-Mae** [comment]
I like the idea about the toggle to create (or not create) the .desktop file.

Thanks for your assistance and feedback in this issue. Closing this issue is fine.
