### ISSUE TITLE
Typo on flathub issue link

### ISSUE THREAD

**Issue by Breno-Spangler** [ferdium/ferdium-app#467]
### Your issue

The issues button on the ferdium-app page on flathub links to "https://github.org.ferdium/ferdium-app/issues".
My guess is that it should be "https://github.org/ferdium/ferdium-app/issues"

**Comment by lhw** [comment]
Oh yeah. That's from an accidental regex replace a while back. I thought I got all of them. Will fix it with the next release

**Comment by lhw** [comment]
Fixed with the beta 3 build. Should be up in a few hours.

**Comment by SpecialAro** [comment]
![image](https://user-images.githubusercontent.com/37463445/179268355-e083295f-3da5-4f51-967a-34386aed7fae.png)

Now it says this.

**Comment by lhw** [comment]
https://github.com/flathub/org.ferdium.Ferdium/commit/51dde7dc8d58ea895a21942eb8db5043a7d6c48e yea. wups
