### ISSUE TITLE
Bug: Videos send in Slack have no sound [snap only]

### ISSUE THREAD

**Issue by mitelg** [ferdium/ferdium-app#471]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-beta.3

### What Operating System are you using?

Ubuntu

### Operating System Version

Ubuntu 22.04

### What arch are you using?

x64

### Expected Behavior

- get a video via Slack message
- play it
- here sound

### Actual Behavior

- get a video via Slack message
- play it
- there is no sound

### Steps to reproduce

- get a video via Slack message
- play it
- there is no sound

### Additional information

I installed ferdium via snap `snap install --beta ferdium`. At first I did not do the extra config step to connect with `audio-record`, I tried that afterwards, but without any change. 
I also tried `snap connect ferdium:pulseaudio`

**Comment by SlanDF** [comment]
Seems to be a Linux only issue (personally can't reproduce) but tested on macOS and W10 and both work just fine

**Comment by mitelg** [comment]
I just tried the installation via deb file and this works for me. so I guess there is a problem with the snap installation. 

Is there a way to migrate from snap to deb installation?

**Comment by mitelg** [comment]
turns out, I had disabled the sound for this service :man_facepalming: 

sorry for the noise! 
Keep on going your great work :heart:
