### ISSUE TITLE
Bug: Discord: "Open URLs within Ferdium" behaves incorrectly

### ISSUE THREAD

**Issue by ylluminate** [ferdium/ferdium-app#474]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.98

### What Operating System are you using?

macOS

### Operating System Version

12.4

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

When clicking an internal Discord link (eg: https://discord.com/channels/592103645835821068/592106336838352923/995865013057245205), it should not reload the Discord Ferdium tab, but rather instantly jump to the conversation to which the URL leads.

This worked in the past, but now seems to be broken. This causes very difficult behavior when moving between conversations that other users link to.

### Actual Behavior

Currently when you click an internal Discord link within the Ferdium tab/service, it reloads Discord and then jumps to the location in question. 

### Steps to reproduce

1. Modify service settings and turn on "Open URLs within Ferdium"
2. Find a chat URL (example provided above)
3. Click it
4. Notice how it reloads the entire service/tab.

If you disable "Open URLs within Ferdium" it now simply does not go anywhere or goes to the default browser for the OS.

**Comment by SpecialAro** [comment]
This should be fixed in the next nightly 😁 thank you for opening this issue!
