### ISSUE TITLE
Bug: Clicking on Links in Ferdium but nothing happens

### ISSUE THREAD

**Issue by gelsas** [ferdium/ferdium-app#489]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.101

### What Operating System are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

When clicking on a link it should either open in Ferdium or in Browser

### Actual Behavior

Nothing happens at all when clicking on links.

Even when right clicking and clicking on "Open in Browser" nothing happens.

### Steps to reproduce

1. Click on any link in Ferdium in your services.
2. I am currently only using Ferdium for Discord, Slack, Skype, Gmail on all of those clicking links does nothing for me.

**Comment by SpecialAro** [comment]
Hello @gelsas, thank you for logging this bug.

Would you be able to provide some console log about this?

Probably you need to open the recipes console log (View > Toggle recipe console log)

**Comment by gelsas** [comment]
It was probably a windows 11 issue. Wasn't working in other apps too.
After the latest windows 11 update it works again.

**Comment by vraravam** [comment]
Thanks for the update @gelsas . Closing the ticket for now.
