### ISSUE TITLE
[Feature] Shortcuts missing

### ISSUE THREAD

**Issue by leoheck** [ferdium/ferdium-app#50]
### Your issue

First of all, thank you for the huge effort to make this project happen after Ferdi has ended operations.

Shortcuts to change the selected service was a good feature in Ferdi that Ferdium is missing.

These are the main shortcuts that I would love to see in Ferdium land.
- `Ctrl+Tab` to move forward to the next service
- `Ctrl+Shift+Tab`to move backwards

**Comment by SpecialAro** [comment]
Hi @leoheck ! What nightly version are you currently running (Help Menu > About Ferdium > Version: ... ) ?

Also, in what platform are you using Ferdium?
Asking this because I'm currently on Windows and those shortcuts work just fine.

Thank you 😄

**Comment by leoheck** [comment]
Hey @SpecialAro sorry for the missing info. I am using the latest nightly.

But here is the full version
![image](https://user-images.githubusercontent.com/1277920/165345977-28bc45f2-4d45-4201-9f86-4788d3bc3b3f.png)

I am running Ubuntu 2022.04

**Comment by vraravam** [comment]
nice to interact with you once again @leoheck !
I am on the latest nightlies on both macx86 and mac arm - and the shortcuts (along with `Cmd+S` for the `QuickSwitch`) also work seamlessly for me.
btw, Discord traps the `Cmd+S` as do some other services, and this is a known limitation which we can't fix per se. I will create a new feature enhancement card to have custom keyboard shortcuts - which was on the Ferdi tracker, but is lost for now

**Comment by vraravam** [comment]
As intimated, I have created a new (more generic) feature request: https://github.com/ferdium/ferdium-app/issues/53

imo, this one can be RCA'ed like a bug and closed - since the current codebase **should** work

**Comment by leoheck** [comment]
Thanks, @vraravam, it is nice to see you here too.

Right now I just have Whatsapp and Google Chat configured.

**Comment by leoheck** [comment]
After restarting the computer shortcuts were working. So I am closing this issue for now. If I have any related issue tomorrow I will open this again.
