### ISSUE TITLE
Bug: Skype file download is opening up on the browser which causes HTTP ERROR 401

### ISSUE THREAD

**Issue by momodev19** [ferdium/ferdium-app#501]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.90

### What Operating System are you using?

Ubuntu

### Operating System Version

Ubuntu 18.04.6 LTS

### What arch are you using?

x64

### Expected Behavior

It should open file explorer to navigate where you want to download that file

### Actual Behavior

It opens up the browser which causes ERROR 401 and not be able to download the file

### Steps to reproduce

1. Send a file through skype
2. click download

### Debug link

https://debug.ferdium.org/fbdd1e73-2423-4822-a9f0-1ad9800ba3f5

### Screenshots

![image](https://user-images.githubusercontent.com/78622526/180089991-d1904100-eb6a-4d36-a0e7-c51cfc77932c.png)
![image](https://user-images.githubusercontent.com/78622526/180090025-7bd84625-8898-4ded-a69f-1a2f9be7d1c3.png)

### Additional information

It is working if you enable to open link within Ferdium but it will also open other urls within Ferdium which is not ideal.

**Comment by SpecialAro** [comment]
Hello @momodev19 . For the time being, please, use this workaround:

- Right click on the service and edit the service.
- toggle this toggle on:
![image](https://user-images.githubusercontent.com/37463445/184101089-4b3bfb9a-3505-4dcf-9f41-913efe6ed0eb.png)
-  Right click on the service and Reload.

**Comment by cino** [comment]
Closing this issue due to no respone since August 11, if this is still an issue feel free to re-open.

**Comment by kanunnikau** [comment]
Hello. I am experiencing the same issue (Linux OpenSuse Tumbleweed).
Workaround from [this comment](https://github.com/ferdium/ferdium-app/issues/501#issuecomment-1211732734) works, but then I cannot just click on normal links. The rest of "not download" links have to be opened by middle-clicking on them.

**Comment by LiBOSS-CZ** [comment]
Same for me with latest version 6.2.7 nad Windows 11 Pro
