### ISSUE TITLE
Bug: Cannot start a teams call / receive calls since today

### ISSUE THREAD

**Issue by FWidm** [ferdium/ferdium-app#503]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

Version: 6.0.0-nightly.103

### What Operating System are you using?

Ubuntu

### Operating System Version

Linux 5.15.0-10041-tuxedo #44~20.04.1tux2 SMP x86_64 x86_64 x86_64 GNU/Linux

### What arch are you using?

x64

### Last Known Working Ferdium version

Version: 6.0.0-nightly.103

### Expected Behavior

I should be able to call people on teams and receive calls from people.

### Actual Behavior

Since today i can neither call people nor receive calls from people on ferdium, the received calls fail directly as missed calls and when you call you see the following:

Version: 6.0.0-nightly.103
Server: No Server
Electron: 19.0.8
Chrome: 102.0.5005.148
Node.js: 16.14.2
Platform: Linux 5.15
Arch: x64
Build date: Tue Jul 19 2022 18:44:02 GMT+0200 (Central European Summer Time)
Git SHA: b21671e3
Git branch: nightly

### Steps to reproduce

Calling
1. log into teams
2. press the call button on a person
3. teams says the browser is incompatible

Receiving calls
1. get someone to call you
2. the call goes directly to voice mail

### Screenshots

![image](https://user-images.githubusercontent.com/3480240/180132073-7e3c8e28-a99b-495c-95b4-2678f3b95db1.png)

**Comment by vraravam** [comment]
I was able to edit the user-agent for this MS Teams service and set this value: `Mozilla/5.0 (Windows NT 10.0; rv:104.0) Gecko/20100101 Firefox/104.0`. Looks like microsoft is also going the same route as google in disallowing certain browsers from accessing their servers. Closing this since its not controllable by us, and all we can do is use the workaround

**Comment by FWidm** [comment]
Thank you the user agent fixed it for me for now
