### ISSUE TITLE
Feature: add "translate" option for selected text

### ISSUE THREAD

**Issue by fgordon-maker** [ferdium/ferdium-app#504]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Add option to translate selected text in any service.

### Proposed Solution

It would be a very nice feature to be able to select some text on a page on any service and then right-click and be able to see an automatic translation in a popup. Pretty much like the Google Translate Chrome extension works.

Optionally, if the text exceeds a certain length, a link to Google Translate could be provided and the selected text passed as a parameter to that page.

![image](https://user-images.githubusercontent.com/60240124/180208089-e25707a6-74da-493d-ab51-f6b7af03f016.png)

### Alternatives Considered

An alternative solution is to install the Google Translate service and to copy-paste the text. This works but it requires much more effort.

**Comment by vraravam** [comment]
We currently use crowdin for translating content. Please sign up for ﻿﻿https://crowdin.com/project/ferdium-app to contribute

**Comment by fgordon-maker** [comment]
> We currently use crowdin for translating content. Please sign up for ﻿﻿https://crowdin.com/project/ferdium-app to contribute

I'm not talking about Ferdium's UI. I was referring to the text provided by the services, e.g. emails text or twitter posts in foreign languages.

**Comment by vraravam** [comment]
If you are asking for the extensions - that is a long ways off. We just released v6.0.0 - and have some other major items to complete before we can support extensions. If someone is willing to take this up, we will be very appreciative of the contributions though

**Comment by fgordon-maker** [comment]
I wasn't making any assumptions of how the feature would be implemented. Of course, supporting extensions is one way, arguably a harder one.

**Comment by SpecialAro** [comment]
Maybe this https://www.npmjs.com/package/translate-google or https://www.npmjs.com/package/google-translate-api can be used to achieve this. I can try to implement such think when I get the time, but no promises 😄

**Comment by SpecialAro** [comment]
10 minutes in and I could implement something like this:

![image](https://user-images.githubusercontent.com/37463445/183246135-8022701a-df67-4fd4-bb4f-f462e456f836.png)

Now we have to find a way of proper introduce the text to the user.

**Comment by yogasw** [comment]
nice features, i like 😁

**Comment by MurzNN** [comment]
It's a nice feature, but much more convenient to have a system-wide tool that translates any text in any applications. I use https://crow-translate.github.io/ that works well in Ferdium, Firefox and any other app!
