### ISSUE TITLE
Bug:  Auto update broken on mac?

### ISSUE THREAD

**Issue by jnvillar** [ferdium/ferdium-app#51]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.10

### What Operating System are you using?

macOS

### Operating System Version

macOs Monterey 12.2

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Clicking on the pop up that appears when there is a new version closes the app and installs the new version of ferdium

### Actual Behavior

Clicking on the update pop up does nothing

### Steps to reproduce

Install 6.0.0-nightly.10 wait for the pop up to appear and click on "install". Make sure to have updates enabled in settings and pre-releases on 

### Screenshots

<img width="639" alt="Screen Shot 2022-04-26 at 11 32 04" src="https://user-images.githubusercontent.com/7551569/165324000-c8c51df9-f5b5-47f0-85a9-cdb6726e7d72.png">

**Comment by vraravam** [comment]
@jnvillar - thanks for logging this ticket. This is a known issue as also communicated in the [first nightly release notes](https://github.com/ferdium/ferdium-app/releases/tag/v6.0.0-nightly.7)
