### ISSUE TITLE
Bug: Don't have the icon on flatpak

### ISSUE THREAD

**Issue by jessybreyne** [ferdium/ferdium-app#510]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-beta.3

### What Operating System are you using?

Other Linux

### Operating System Version

Arch Linux

### What arch are you using?

x64

### Expected Behavior

I want the icon on the task bar

### Actual Behavior

I have the big icon flatpak in my OS search list but I don't have a small icon on my task bar.
I have other flatpak apps and they have the icon. (Like discord)

### Steps to reproduce

Install a linux  like arch linux with XFCE. (maybe with others linux too)
Install the ferdium flatpak app.
See the icons after opening the app

### Screenshots

![Capture d’écran_2022-07-24_12-09-18](https://user-images.githubusercontent.com/34346742/180642264-abad24aa-d749-4fc9-a5fc-0ea5fc354c30.png)

**Comment by Keksgesicht** [comment]
I had something similar. This should have been resolved with the newest update to Ferdium 6.1.0. Probably due to an update to Electron 20. For me the correct icon is now used inside the panel.

Setup:
KDE Plasma (Wayland)
installed via flatpak (flathub)

**Comment by mcmxcdev** [comment]
Hey @jessybreyne, I have just installed the flatpak version of Ferdium to debug this, but I do see an icon as expected. Do you still encounter this?

**Comment by jessybreyne** [comment]
Hey, I don't see the bug anymore. But I also changed my desktop environment (I'm on GNOME). In my case it may be closed. Thanks
