### ISSUE TITLE
Feature: Publish snap package

### ISSUE THREAD

**Issue by 3v1n0** [ferdium/ferdium-app#52]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I was depending on ferdi snap: https://snapcraft.io/ferdi

Could you please publish a snap for ferdium too?

### Proposed Solution

Publish a snap package to snapcraft.io

### Alternatives Considered

.

**Comment by vraravam** [comment]
Thanks for logging the ticket @3v1n0 
The snap package creation/publish have been turned off while we can get a contributor to set it up and apply the secrets into the GH Actions CI pipeline. Would you be willing to contribute in this aspect?

Also, can I request that we please limit logging tickets to a single repo? The core team here will not be able to track tickets in other forked repositories.

**Comment by NathanaelGandhi** [comment]
I would be interested in contributing to this, however, I do not have any prior experience setting up such things. 

I'll look into using https://github.com/snapcore/action-build and https://github.com/snapcore/action-publish and see if I can get something set up in a personal repo to learn.

@vraravam Do you know if the action should be added to Builds or to its own workflow? Publishing to the store will need a secret for store login, does this secret exist or does this also need to be explored?

**Comment by vraravam** [comment]
@NathanaelGandhi - the code was working in Ferdi. Its just been commented out in https://github.com/ferdium/ferdium-app/commit/8330a9299776359001d5e700113b7935e6057df1 and https://github.com/ferdium/ferdium-app/commit/34a2a84c9f217d9aa40b3d74dc0429dad49a4696

>  Do you know if the action should be added to Builds or to its own workflow?

The way `electron-builder` works is not to create a new build pipeline, you just add the respective lines in `electron-builder.yml` and it'll do the job.

>  Publishing to the store will need a secret for store login, does this secret exist or does this also need to be explored?

and yes, you will need to create the snapstore login, generate an API token/password, and set it up in the GH Actions as a secret

**Comment by 3v1n0** [comment]
Yeah, so you should just use `snapcraft` to create register the application name, and get the login data to do the publishing.

It's quite easy, you can do it easily from an ubuntu docker instance too.

See https://snapcraft.io/docs/registering-your-app-name

**Comment by MurzNN** [comment]
Also want to notice that Ferdi's snap package misses access to camera plug, so all apps have no access to webcam. I can't find something like `snapcraft.yaml` file in the repo to figure out the source of missing webcam plug problem.

So, can you please check and fix this in Ferdium's snap package?

**Comment by NathanaelGandhi** [comment]
@MurzNN I think you should log this as a separate issue in [issue tracker](https://github.com/ferdium/ferdium-app/issues) after following [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md). 

I've had a quick look and don't really know how to fix it, maybe it's something to do with interfaces? Hopefully opening it up as an issue will allow someone to pick it up.

**Comment by vraravam** [comment]
Closing this ticket, since we are releasing [nightly-18](https://github.com/ferdium/ferdium-app/releases/tag/v6.0.0-nightly.18) which has snap packages that are published.

**Comment by MurzNN** [comment]
Great, will recheck and post a separate issue, but I still don't see the snap package in the release https://github.com/ferdium/ferdium-app/releases/tag/v6.0.0-nightly.18 and in latest https://github.com/ferdium/ferdium-app/releases/tag/v6.0.0-nightly.20 too...

**Comment by MurzNN** [comment]
Have found it in official catalog: https://snapcraft.io/ferdium - but the camera access is still missing, will post a separate issue.

**Comment by 3v1n0** [comment]
@MurzNN it's only available in the edge channel right now, so I suppose you should switch to that. And camera profile should be enabled manually, but will require developers to include it in the manifest.

**Comment by vraravam** [comment]
#88 should have fixed the manifest @3v1n0 - it will be in the next nightly

**Comment by MurzNN** [comment]
Yeah, camera connections appears and works well, thanks!
```
$ snap connections ferdium | grep camera
camera                    ferdium:camera           :camera                          manual
```
Want to notice, that It isn't connected by default so must be connected manually (and pulseaudio to make microphone works - too), via commands:
```
$ snap connect ferdium:camera
$ snap connect ferdium:pulseaudio
```
I've made a PR with explaining how to do this for Snapcraft users: https://github.com/ferdium/ferdium-app/pull/98
