### ISSUE TITLE
Feature: User-overridable keyboard shortcuts

### ISSUE THREAD

**Issue by vraravam** [ferdium/ferdium-app#53]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

As different services "grab" keyboard shortcuts, it gets a but painful to have to remember which shortcuts work in which service. For eg, Discord grabs the `Cmd + S` (QuickSwitch) and so within Discord, QuickSwitch doesn't work.

### Proposed Solution

It would be a good idea to allow Ferdium's users to be able to override their own shortcuts.

### Alternatives Considered

none

**Comment by Alistair1231** [comment]
Yes, this! I used to always use Ctrl(+Shift)+Tab to switch between WhatsApp chats. And using Ctrl+# to switch services is sufficient for me. I would love to be able to unbind hotkeys.

**Comment by jnvillar** [comment]
this feature would be awesome! there are some slack shortcuts that do not work because of this

**Comment by Shwaolin** [comment]
also voting for this. i have a system wide shortcurt (ctrl+alt+s) for pasting a symbol which will constantly trigger split mode with it in ferdium

**Comment by nickchomey** [comment]
I'd love this too. I much prefer Ctrl+Pg Up/Pg Down for changing tabs, like chrome, edge etc... I find Ctrl+Tab to be awkward

**Comment by pkvdesigns** [comment]
+1 the Ferdium shortkeys for switching services takes over the shortkeys for Teams to switch between tabs.
Also the CMD+N key adds a Ferdium service which I near to never need, and blocks the Teams shortcut for a new chat, which I use all the time.

**Comment by radekwlsk** [comment]
Would be nice to hear something from the team on that one.

**Comment by plundration** [comment]
I +1 this. Would love to be able to remap at least the tab switching to `Alt + i/k`.

**Comment by insidewhy** [comment]
I've opened a PR with this functionality now, currently limited to activating next/previous service. Please see https://github.com/ferdium/ferdium-app/pull/1920

**Comment by insidewhy** [comment]
@plundration @nickchomey You can rebind these with the latest code, I'm not sure when it will be released.

@Alistair1231 you can unbind these keys with the latest code, in advanced settings just delete the text from the associated shortcut inputs.

@pkvdesigns I didn't add support for rebinding the "new service" binding in that PR, but to do so would be easy by following the code in the PR linked to this ticket. See https://github.com/ferdium/ferdium-app/commit/167a6a009a4acc16515c97425a7ef9bf4b28722e new bindings can be added by editing 4 of the 7 files that were changed in this PR.

**Comment by nickchomey** [comment]
@insidewhy Thanks! How can i use an arrow key as the shortcut? It seems like we have to manually type the key name rather than just press the combination to register it

Edit: Nevermind, you can just type Left/Right/Up/Down

**Comment by insidewhy** [comment]
> @insidewhy Thanks! How can i use an arrow key as the shortcut? It seems like we have to manually type the key name rather than just press the combination to register it
> 
> Edit: Nevermind, you can just type Left/Right/Up/Down

Yeah I wanted to make it grab the shortcut like that in a future update, but I'm not sure if I'll be working on ferdium again. Recently I switched from ferdium to Firefox with the web containers extension and side tabs enabled. I wanted to use the stylus extension to override CSS styles within WhatsApp and Telegram. But perhaps I'll come back and try to add extension support to ferdium since the UI/UX is nicer than Firefox in other ways.
