### ISSUE TITLE
switch `ferdium-bin` in AUR off nightly builds

### ISSUE THREAD

**Issue by m1karii** [ferdium/ferdium-app#531]
### Your issue

now that 6.0.0 has been released I think `ferdium-bin` in AUR can switch from nightly builds into stable builds / releases

**Comment by nathanaelhoun** [comment]
I think that @cedricroijakkers is still the maintainer for `ferdium-*` packages in the AUR

**Comment by cedricroijakkers** [comment]
I just checked, and both `ferdium` and `ferdium-bin` are tracking the latest production release.

**Comment by nathanaelhoun** [comment]
Thanks for checking Cedric!
