### ISSUE TITLE
Differences from Ferdi?

### ISSUE THREAD

**Issue by notpushkin** [ferdium/ferdium-app#537]
### Your issue

Just found out about Ferdium. At first I thought Ferdi is discontinued and this is just a community supported fork, but I see there are [recent commits](https://github.com/getferdi/ferdi) so now I'm confused. Is there any backstory to this fork?

**Comment by SpecialAro** [comment]
Hello @notpushkin , welcome to Ferdium 👋 

Please read the following:
 - https://github.com/ferdium
 - https://github.com/ferdium/ferdium-app/blob/develop/CHANGELOG.md
 
Summing up, Ferdium should have more stability and security than Ferdi (given that we updated dependencies), with some new Features also.

> Ferdi recent commits are mainly automated to update some dependencies and the submodules, so nothing too much of a development there... 
>
> Ferdi is a hard-fork of Franz, and Ferdium is a hard-fork of Ferdi. We started the Ferdium project after the major issues that Ferdi experienced from the project owner (which was one person). Former Ferdi contributors got offended and disrespected. The Ferdi social accounts, GitHub organization and domains where also taken down multiple times by the owner.
>
> On the 11th of June 2022 the owner of the Ferdi project announced on Twitter: "There will be no further updates to Ferdi. Thanks to everyone for the wild ride!".

If you have any more questions, please, feel free to join us on discord (https://discord.gg/jVv4Qns8pP) or to comment bellow so I can re-open this issue.

**Comment by notpushkin** [comment]
Gotcha. Thanks for the clarification!

Perhaps add this to the [FAQ](https://ferdium.org/faq)?
