### ISSUE TITLE
Feature: Native notifications on Plasma and Gnome

### ISSUE THREAD

**Issue by theunclemez** [ferdium/ferdium-app#555]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

When using ferdium on Plasma by KDE under Linux 
the notifications are the ones from Plasma, not bad but we can't do a lot with those.

### Proposed Solution

With custom notifications system overtaking the Gnome/Plasma and even windows and allowing us to reply to certain messages like directly from the notification itself (like we do with telegram i.e) for stuffs like tweet etc. things could be much fun

### Alternatives Considered

nothing else for now

### Additional Information

I run ferdium on

Operating System: openSUSE Tumbleweed
CPE OS Name: cpe:/o:opensuse:tumbleweed:20220820
Kernel: Linux 5.19.2-1-default
Architecture: x86-64
Hardware Vendor: Acer
Hardware Model: Aspire V5-122P
Firmware Version: V2.10

**Comment by TiZ-HugLife** [comment]
I'm *strongly* against the use of custom notification popups on Linux. They break cohesion more than Electron apps already inherently do, they act unpredictably between different DEs and window managers, and will probably get worse when you add X11 vs Wayland. When Teams's standalone app had a custom notification popup, it was the worst part of the app. If this is to be added, please keep it optional.

Alternatively, [Plasma's notifications should support quick reply already.](https://phabricator.kde.org/D25851) It's on Ferdium to try and integrate it, as long as Electron does not inhibit them from so doing.

**Comment by mcmxcdev** [comment]
As already described by @HugLifeTiZ, that would become messy quickly.

We are a small team of maintainers, so building and maintaining a custom notification system would be a huge overhead that we would like to avoid.
