### ISSUE TITLE
Google Chat launches browser and do not download/access the content.

### ISSUE THREAD

**Issue by leoheck** [ferdium/ferdium-app#568]
Hi folks, I am having this issue with Google Chat that can't download content. 

On Google Chat, when clicking on a link (to download pictures or any other thing), Ferdium launches Google-Chrome and the operation results in:

![image](https://user-images.githubusercontent.com/1277920/186191108-30432dbc-f07f-4115-849a-6189a4b6d478.png)

Is there any way that we could improve this behavior? I would prefer to skip opening in chrome and just download the content.

This particular case is happening when I click on a picture, then the picture expands, and in the top right, I click on this "Download" icon
![image](https://user-images.githubusercontent.com/1277920/186191859-4eacf918-d448-42f2-9180-88c5384c7a60.png)

Ferdi I am using, but it works like that for a long time.

```Version: 6.0.1-nightly.18
Server: No Server
Electron: 20.0.3
Chrome: 104.0.5112.81
Node.js: 16.15.0
Platform: Linux 5.15
Arch: x64
Build date: Fri Aug 19 2022 23:41:38 GMT-0300 (Brasilia Standard Time)
Git SHA: 145a8fce
Git branch: nightly
```

**Comment by vraravam** [comment]
@leoheck - could you please try with the latest Ferdium version? Also, as you know, we are not part of Ferdi. Please confirm that you are using ferdium (and not ferdi) - so that we can take a look at what the problem might be.

**Comment by leoheck** [comment]
Sure, give me some minutes.

**Comment by leoheck** [comment]
It still launches the default browser (which is Google Chrome) and shows the same `403. That’s an error.`

I have 2 Google Chrome users logged on Ferdium.
I have 4 or more Google Users logged on Google-Chrome, it may be using the wrong user to finish the request there too.
However, it would awesome if Ferdium could download the file directly, instead.

Is there any info or file that I can get to help understanding the issue?

Using now.
```
Version: 6.2.1-nightly.7
Server: No Server
Electron: 21.0.1
Chrome: 106.0.5249.61
Node.js: 16.16.0
Platform: Linux 5.15
Arch: x64
Build date: Fri Sep 30 2022 00:32:10 GMT-0300 (Brasilia Standard Time)
Git SHA: 81cc1752
Git branch: nightly
```

**Comment by vraravam** [comment]
Unfortunately, the `trapLinks` code that we have implemented will not suffice for the above "link". Its actually, not a link that google has implemented - instead its a `div` element with a clickHandler - which we cannot code for.
<img width="325" alt="Screenshot 2022-10-04 at 10 31 58 PM" src="https://user-images.githubusercontent.com/69629/193881792-d594b715-0607-4ccf-aeec-3bd958c802a9.png">

**Comment by leoheck** [comment]
Is it possible to replace the link with an alternative URL to open that chat message in the browser?
So the user could click the donwload, to be redirected to the thread in a browser and then he could download from there?

what I do, is to login in to the browser manually, then find the conversation, then find the thread, then find the file and then download the link. Kind of hard specially when you have to be quick on an important meeting.

**Comment by vraravam** [comment]
Sorry - we try to not change DOM elements within the page itself.
