### ISSUE TITLE
Bug: Ferdium is not creating system notifications on Arch Linux

### ISSUE THREAD

**Issue by JBlocklove** [ferdium/ferdium-app#569]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0

### What Operating System are you using?

Other Linux

### Operating System Version

Arch Linux 5.19.2-arch1-1

### What arch are you using?

x64

### Expected Behavior

When getting a notification through a service (e.g. Discord), the notification should be pushed as a system notification (in this case through something like `libnotify`).

### Actual Behavior

When getting a notification through a service, no system notification is given.

### Steps to reproduce

1. Install Ferdium through the AUR
2. Set up Discord as a service and log in
3. Ensure that the Discord service has notifications and audio enabled
4. Receive a message in Discord which should ordinarily create a notification

### Additional information

My notification server is `dunst`, though I don't believe that should have any impact on this issue, as it seems Ferdium is not interacting with `libnotify` which would be used to send notifications to `dunst`

**Comment by JBlocklove** [comment]
Slight update: I added a Slack account and it seems like those notifications are working just fine. This may be a bug specific to only certain services and how they handle notifications.

**Comment by jorisvandijk** [comment]
I have this problem on Arch as well, but only with Discord. Things like WhatsApp and Teams notify just fine. Might only be an issue with Discord. Also, when Ferdium was Ferdi, notifications did work with Discord, so something did change. Another thing, when I have earphones in and nothing is playing, I do notice that there's an audible hum in the earphones when I should get a Discord notification.

**Comment by JBlocklove** [comment]
Just found a toggle for notifications that I had missed earlier that fixes the issue. In the Discord settings there's a toggle for "Enable Desktop Notifications" that seems to default to off. Changing that to on seems to have fixed my issue. Sorry for missing that.
