### ISSUE TITLE
Bug: Whatsapp-Chats extremly slow

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [ferdium/ferdium-app#581]
### Avoid duplicates

- [x] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.1.0

### What Operating System are you using?

Windows

### Operating System Version

Windows 10 22H2, 19045.1889

### What arch are you using?

x64

### Last Known Working Ferdium version

6.1.0

### Expected Behavior

To not slow down to a crawl.

### Actual Behavior

In Whatsapp, when you have a chat with stickers (not emoji!) and a chat without stickers:

- Switching between these chats slows down the software, i.e. it takes 2-3 seconds to switch to chat with stickers, and back to normal chats with just text and emojis.
- In chats with stickers, in my case, whenever I try to type ?, ! or (), the software takes about 4-5 seconds to actually type it it.
- If I copy/paste ?, !, (, ) it works normal

### Steps to reproduce

See "Actual Behavior"

### Debug link

https://debug.ferdium.org/0c33e1df-80f1-4160-9f36-2cad855f167b

**Comment by SpecialAro** [comment]
Hello @Unrepentant-Atheist 👋 thank you for logging this issue.

Does this issue also happens with WhatsApp Web?

**Comment by Unrepentant-Atheist** [comment]
Didn't think to test. Did a quick test: Nope, everything as fast as it should be, no delays whatsoever. Tested on Firefox, Edge and Chrome.

**Comment by jdegger** [comment]
I'm also seeing the same delays. These delays somewhere started of the weekend. 

No clue Whats 'Appening (pun intended) but it's barely usable right now.

**Comment by derjohn** [comment]
Same here. I type some words and after a delay of some seconds (!) my words appear.

**Comment by jdegger** [comment]
To add: I'm on Mac, so it's not a windows-only problem.

When I copy/paste stuff into whatsapp it takes around 10 seconds and it appear likes this:

When I copy:
```
1
2
3
4
```

And paste it twice it appears as:
```
1
1
2
2
3
3
4
4
```
(I paste twice because I'm impatient..)

**Comment by xmsanchez** [comment]
Seems to be something related to whatsapp itself. I detected the same behaviour with the old Ferdi + I there's an opened issue in Vivaldi forums with this problem when using it's built-in panel for whatsapp.

**Comment by derjohn** [comment]
> Seems to be something related to whatsapp itself. I detected the same behaviour with the old Ferdi + I there's an opened issue in Vivaldi forums with this problem when using it's built-in panel for whatsapp.

For me it began with 6.0.0 release. I'm not sure though, if the issue occurred directly after the upgrade to 6.......

**Comment by warrendt** [comment]
Same issues with WhatsApp. Super slow when switching to it.

**Comment by warrendt** [comment]
> Same issues with WhatsApp. Super slow when switching to it.

Emptying my Ferdium cache folder and updating to latest nightly has helped, not sure if others have the same

**Comment by Unrepentant-Atheist** [comment]
Issue still persists.

**Comment by derjohn** [comment]
> Issue still persists.

Yes it does. I'm still asking myself if the issue hits all WA Users oder only some of us.

**Comment by Unrepentant-Atheist** [comment]
Well, this issues doesn't exit if I use https://web.whatsapp.com/ , it's just Ferdi or Vivaldi Whatapp built-in panel (which is basically the same like Ferdi)

**Comment by Unrepentant-Atheist** [comment]
Deleting C:\Users\[USER]\AppData\Roaming\Ferdium seems to have solved this problem, didn't before.

**Comment by haras-unicorn** [comment]
For me it doesn't even have to have stickers - everything is just so slow to the point where i just disable it in Ferdi and use my phone

**Comment by SpecialAro** [comment]
> For me it doesn't even have to have stickers - everything is just so slow to the point where i just disable it in Ferdi and use my phone

If you're using Ferdi, then you should not be in this GH. This is for Ferdium only, please bear that in mind.

Nevertheless, we added a bit of code to solve the slow down issues with whatsapp some time ago. I use it daily without any issue whatsoever. Can you please check your Service Version (right-click on whatsapp icon on Ferdium > Edit > Scroll to the bottom) ?

The version you should be using: 3.4.6

Also, as @warrendt pointed out, please clean the Ferdium cache frequently.

**Comment by gbonanome** [comment]
Hi @SpecialAro,
I'm on a MacBook Pro (14", 2021) with MacOS 12.6 and Ferdium 6.1.0 and just checked that the Whatsapp recipe is on the version 3.4.5. I've just removed and added again the service but still on 3.4.5.

BTW I don't have the exact problem mentioned in this thread, but I was wandering between issues related to Whatsapp since I also have some issues 😅 (today I get [this one](https://github.com/ferdium/ferdium-recipes/pull/138) about a warning message)

**Comment by SpecialAro** [comment]
@gbonanome hello,

The nightly version has that last issue resolve, so be sure to check it out. 😁

**Comment by vraravam** [comment]
Closing as per the last comment
