### ISSUE TITLE
WhatsApp not working anymore

### ISSUE THREAD

**Issue by jra66** [ferdium/ferdium-app#584]
### Your issue

I have a weird problem with Ferdium. I started using Ferdium Portable x64 6.0.0 just for using WhatsApp on my Desktop (Win 7) because the native app requires Win 8 or above. Everything worked fine.

After Ferdium noticed me about new version 6.1.0 I clicked on update, but this took me from portable to installed version, which I uninstalled afterwards and downloaded new portable 6.1.0.

Now WhatsApp isn't working anymore. The screen is stuck as mentioned in #553 ("end-to-end encrypted") and won't proceed any further.

I tried a lot of things: cleaning cache, killing WhatsApp with Ferdium's process manager, starting from scratch, i.e. deleting FerdiumAppData directory before, doing all the same with portable 6.0.0 which was working flawlessly before, deleting the connection in WhatsApp on my phone, rebooting Windows, ...

Nothing of the above helped. In my Firefox WhatsApp web works fine. It seems to me, that either the temporary "real" installation of Ferdium or even Ferdium Portable leaves something on my PC which prevents even formerly working portable version from running again.

I hope that you can help me because WhatsApp on desktop is real work saver!

**Comment by SpecialAro** [comment]
Hey @jra66 , thank you for logging this issue!

Have you tried deleting the entire folder on %appData%/Roaming/Local/Ferdium and then a fresh install of the app? Also, please try to prefer the usage of the installer over the Portable version, as we have experienced some inconsistencies with that version.

**Comment by harryfear** [comment]
Same issue on macOS.

I reset Service Local Storage and re-authorised the session on my phone and now okay.

**Comment by jra66** [comment]
Thanks a lot for your reply. Deleting the mentioned directory under appData did not solve the problem with the portable version. As suggested I tried a fresh install with Ferdium-win-AutoSetup-6.1.0-x64.exe. This works very well!

Seems to be a problem with the portable version only, but I still don't understand why portable 6.0.0 doesn't work any more, too.

I now switch to the installed version. Could you please tell me where the installer and the app itself store persistent data? I found AppData\Roaming\Ferdium, AppData\Local\Programs\ferdium and AppData\Local\ferdium-updater. Are there any other places or perhaps registry entries?

**Comment by krestel** [comment]
Just confirming the same issues with me with the most recent portable version...both the 64 and normal portable. And once I installed the installed version WhatsApp work correctly.

**Comment by Floffyko** [comment]
Try portable version, Ferdium Portable 6.1.1 nightly 6, it has not this bug anymore.

**Comment by harryfear** [comment]
For me, portable, not portable is irrelevant. WA just got somehow corrupted and had to be data-reset then it was fine.

**Comment by Floffyko** [comment]
I just found out that v. Portable 6.1.1 nightly 6 (for me portable is important) have no more this bug. You have v 6.1.0.

**Comment by krestel** [comment]
I feel so stupid for asking this, but where are the nightly app builds located for the portable version? (Is there a scoop bucket for it?) I can run scoop for the normal install and all...but I'm too much of a newb to find the portable version nightly build. Help much appreciated in advance.

**Comment by Floffyko** [comment]
https://github.com/ferdium/ferdium-app/releases

**Comment by cino** [comment]
Based on @Floffyko's response on Sep 3 I'm closing this issue as resolved, if this is not the case please re-open.
