### ISSUE TITLE
Feature: add ability to add Grammarly and enable it globally for every service

### ISSUE THREAD

**Issue by stefanobartoletti** [ferdium/ferdium-app#589]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I think that it would be great to have a global spell-checking service added to Ferdium, that once enabled will be active in all configured services/containers.

Maybe some other spell-checking services could be considered, but Grammarly is currently one of the most popular choices, so it could be a nice place to start.

### Proposed Solution

Add Grammarly integration in Ferdium

### Alternatives Considered

Currently, Ferdium has a basic spell checking service, it is viable but it doesn't cover all features of an advanced one like Grammarly

**Comment by MurzNN** [comment]
It's related to the https://github.com/ferdium/ferdium-app/issues/135 issue that will fix this via more general way.

**Comment by stefanobartoletti** [comment]
Thank you! Yes by adding the ability to add extensions this will be solved.

I think that you can close this issue if you want then :)
