### ISSUE TITLE
Bug: Screen sharing doesn't work (Linux, Gnome, X11)

### ISSUE THREAD

**Issue by cedricroijakkers** [ferdium/ferdium-app#59]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.15

### What Operating System are you using?

Other Linux

### Operating System Version

Linux 5.17.5-arch1-1, Gnome 42.1, X11

### What arch are you using?

x64

### Last Known Working Ferdium version

n/a

### Expected Behavior

When clicking on the share screen button in an application (tried in MS Teams and Jitsi), the share screen popup shows and I can select a screen to share, and then the sharing starts.

### Actual Behavior

Nothing happens, clicking the share button yields an error in the developer console for the service.

### Steps to reproduce

For MS Teams:

1. Join a call or meeting
2. Click the screen share button
3. Select a screen to share in the popunder
4. Nothing happens

For Jitsi:
1. Join any room on https://meet.jit.si
2. Click the screen share button
3. Nothing happens

### Additional information

Using Ferdi 5.8.1 on the exact same computer with the exact same version of Linux, Gnome, and X11 works fine.

No logging in the console output when running Ferdium from the command line.

No logging in the Developer Tools for Ferdium itself.

Error in the MS Teams Developer Tools: https://pastebin.com/ea1Yw17d

Error in the Jitsi Developer Tools: https://pastebin.com/MQU22Vag

Possibly related to: https://github.com/ferdium/ferdium-app/issues/32 but this is X11, not Wayland.

**Comment by vraravam** [comment]
Looks like this was broken from the upgrade from electron 16 -> 18
https://www.electronjs.org/blog/electron-17-0#breaking-changes
