### ISSUE TITLE
Bug: Service is always loading

### ISSUE THREAD

**Issue by SoyDiego** [ferdium/ferdium-app#590]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.1.0

### What Operating System are you using?

Other Linux

### Operating System Version

5.15.60-1-MANJARO #1 SMP PREEMPT Thu Aug 11 13:14:05 UTC 2022 x86_64 GNU/Linux

### What arch are you using?

x64

### Expected Behavior

Create service NOTION and use it.

### Actual Behavior

I have created service NOTION but I can't use, always is LOADING.

### Steps to reproduce

1) Create a service Notion
2) Go to service Notion.
3) You will see loading message but never finish and the page is like frozen.

### Debug link

I tried and clicked the button but doesn't works either.

### Screenshots

![image](https://user-images.githubusercontent.com/19764334/187497536-dac20f21-e3d2-4dcd-b531-a98a6a1da4b8.png)

### Additional information

Version: 6.1.0
Server: Ferdium Server
Electron: 20.1.0
Chrome: 104.0.5112.102
Node.js: 16.15.0
Platform: Linux 5.15
Arch: x64
Build date: Sat Aug 27 2022 01:37:57 GMT+0200 (Central European Summer Time)
Git SHA: 117ea8b2
Git branch: release

**Comment by 8227846265** [comment]
This actually happens as well for Windows version, but mine happens on:
A. Google Messages
B. WhatsApp

**Comment by MarcBalaban** [comment]
Can confirm this happens with WhatsApp:

**Version: 6.1.0
Server: Franz Server
Electron: 20.1.0
Chrome: 104.0.5112.102
Node.js: 16.15.0
Platform: macOS Monterey
Arch: x64
Build date: Fri Aug 26 2022 16:42:11 GMT-0700 (Pacific Daylight Time)
Git SHA: 117ea8b2
Git branch: release**

**Comment by jkischel** [comment]
Reliably reproducible on nearly every service:
1. use a Ferdium version, be logged in to a service
2. click on the update banner at the bottom to install the newer version

-> bang. after updating, every service (facebook, discord, whatsapp, ... you name it) is already loaded, but will still keep the "[servicename] is loading" overlay.  The only way to get rid off this is to re-load the page (e.g. by pressing F5 or CTRL+R or click the reload button in the navigation bar). It looks like that a callback doesn't work properly.

**Comment by zgrummedical** [comment]
This happens on all my APPS when I first open it.. windows 10 - latest Ferdium version

**Comment by 8227846265** [comment]
This bug is still appearing as of:

Version: 6.2.3
Server: Ferdium Server
Electron: 21.3.3
Chrome: 106.0.5249.199
Node.js: 16.16.0
Platform: Windows 11
Arch: x64
Git SHA: 550a0d5e
Git branch: release

**Comment by tripplehelix** [comment]
I'm getting this bug in the Home Assisstant service. Using V6.7.7-nightly.7
