### ISSUE TITLE
Bug: Dark Mode - When start doesn't remember last config

### ISSUE THREAD

**Issue by SoyDiego** [ferdium/ferdium-app#591]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.1.0

### What Operating System are you using?

Windows

### Operating System Version

Edition	Windows 10 Enterprise Version	21H2 Installed on	‎07/‎03/‎2022 OS build	19044.1889 Experience	Windows Feature Experience Pack 120.2212.4180.0

### What arch are you using?

x64

### Expected Behavior

Open Ferdium and remember my dark mode settings in the services.

### Actual Behavior

When I start, always is in light mode, but in the left-bar said "Disable Dark mode". Is enabled but not works.
To solve this always i need to press "Disabled dark mode" (nothing happen obviusly because start in light mode". The menu of the bar change to "Enable Dark Mode". I press, and I have dark mode.

### Steps to reproduce

1. Configure Whatsapp in Dark Mode.
2. Close Ferdium
3. Open Ferdium again
4. You will see Ferdium Whatsapp in Light Mode but the service say "Disable Dark Mode"

### Debug link

https://debug.ferdium.org/3cb43c40-dd4c-41fc-8f8c-8a5079fc8e6e

### Screenshots

![image](https://user-images.githubusercontent.com/19764334/187607138-140bea7d-6a2c-47bd-8c8c-b178c23ffc9b.png)

### Additional information

Version: 6.1.0
Server: Ferdium Server
Electron: 20.1.0
Chrome: 104.0.5112.102
Node.js: 16.15.0
Platform: Windows 10
Arch: x64
Build date: Sat Aug 27 2022 01:40:44 GMT+0200 (Central European Summer Time)
Git SHA: 117ea8b2
Git branch: release

**Comment by meiphoo7-Mae** [comment]
Looks a lot like #535 and #490.  :grinning:

**Comment by SoyDiego** [comment]
> Looks a lot like #535 and #490. grinning

Oh maybe yes, I searched but I didn't read that post. Sorry.
Likewise, in neither of the two posts, was there a solution :(

**Comment by cino** [comment]
@SoyDiego Is this still an issue?

**Comment by SoyDiego** [comment]
> @SoyDiego Is this still an issue?

Yes @cino, all days I have the same problem. I start ferdium and always start in Light Mode and I need to change it :(

**Comment by SoyDiego** [comment]
Not solution yet? I continue with the same problem =(
