### ISSUE TITLE
Bug: Alt+Shift to change language doesn't work

### ISSUE THREAD

**Issue by eyallior** [ferdium/ferdium-app#594]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.1.0

### What Operating System are you using?

Ubuntu

### Operating System Version

Pop!_OS 22.04

### What arch are you using?

x64

### Expected Behavior

The alt moves the focus to the top menu. Should happen when pressing alt+shift to change input language when typing. Happens in franz too. but the bozos don't want to get bug reports they rather not know.

### Actual Behavior

Focus goes to top menu

### Steps to reproduce

any text field, even login form to a service (in all services) - press alt+shift

**Comment by MurzNN** [comment]
It's an Electron issue, more information is here: https://github.com/electron/electron/issues/28088

**Comment by teras** [comment]
Hello, isn't this issue fixed in Electron's version [13.1.0](https://www.electronjs.org/releases/stable?page=1#13.1.0)?
