### ISSUE TITLE
Bug: WebRTC leaks real IP when using a VPN

### ISSUE THREAD

**Issue by TheFrenchGhosty** [ferdium/ferdium-app#598]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.1.0

### What Operating System are you using?

Other Linux

### Operating System Version

N/A

### What arch are you using?

x64

### Expected Behavior

Ferdium doesn't leak anything.

### Actual Behavior

Ferdium leaks the real IP address of the user through WebRTC

### Steps to reproduce

- Connect to a VPN
- Start Ferdium
- Open https://ipleak.net/ (or any other test website) in Ferdium
- Notice that it leaks your real IP

### Additional information

This make Ferdium unusable to anyone who want to hide their IP.

Some information about how to disable it: https://www.ivpn.net/knowledgebase/general/my-ip-is-being-leaked-by-webrtc-how-do-i-disable-it/

(PS: It was also a problem in Ferdi, and it was ignored, hopefully you don't ignore it too)

**Comment by MadelineProtoFan** [comment]
Very important thing!
Please fix it

**Comment by SpecialAro** [comment]
Hey!

Found this issue interesting so I started to invest some time into it. I think I solved the issue using this: https://www.electronjs.org/pt/docs/latest/api/web-contents#contentssetwebrtciphandlingpolicypolicy

Before the fix:
![image](https://user-images.githubusercontent.com/37463445/188933155-ce8e70e3-f7fd-45b4-810f-6065092d63f8.png)


After the fix:
![image](https://user-images.githubusercontent.com/37463445/188932608-6da9e429-f0bc-4837-93ac-f4be74fa810d.png)

Is this the intended behaviour @TheFrenchGhosty ?

Also, should we give the user some ability to chose on of the available options for the whole app? Or should we force a specific behaviour?
The options:
![image](https://user-images.githubusercontent.com/37463445/188933501-57a4a0fe-4962-4f29-b47a-680a008cbec7.png)

**Comment by TheFrenchGhosty** [comment]
@SpecialAro Yes, this is exactly the intended behavior.

It should default to hide the IP and *maybe* ask users on services susceptible to need the real IP (otherwise, just having the option to not leak the IP globally is at least a first).

**Comment by SpecialAro** [comment]
> @SpecialAro Yes, this is exactly the intended behavior.
> 
> It should default to hide the IP and _maybe_ ask users on services susceptible to need the real IP (otherwise, just having the option to not leak the IP globally is at least a first).

Awesome!

I'll make a general UI setting in the Privacy panel to account for this. I'll make the default go to `disable_non_proxied_udp` and if the user wants another option he can change globally.

Making this Service dependent can be more difficult (at least it will take some more time to do it), so for now lets just have this as global setting.

I don't know when I can implement this change completely (next week I'll be out in a conference, so will be short on time) - but I promise you it will be implemented for sure 😄 

Hope you are enjoying Ferdium so far!

**Comment by TheFrenchGhosty** [comment]
@SpecialAro Amazing! Thanks a lot!

(PS: something you might want to implement is also a switch to completely disable WebRTC)

**Comment by SpecialAro** [comment]
> @SpecialAro Amazing! Thanks a lot!
> 
> (PS: something you might want to implement is also a switch to completely disable WebRTC)

You're welcome!

I've implemented this:
![image](https://user-images.githubusercontent.com/37463445/188951586-e9fcc0f7-a94f-4925-8aac-76dfc7e54903.png)
![image](https://user-images.githubusercontent.com/37463445/188951721-6816647a-123a-4bfe-b335-2b89cd12d71a.png)


I'm raising a PR now :D
