### ISSUE TITLE
Bug: Discord Call RTC connecting

### ISSUE THREAD

**Issue by MartinRJDagleish** [ferdium/ferdium-app#611]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.1.1-nightly.10

### What Operating System are you using?

Ubuntu

### Operating System Version

Ubuntu 22.04 LTS

### What arch are you using?

x64

### Expected Behavior

I wanted to use Ferdium for a Discord call, but although my sound seems to work the call never connects. 

### Actual Behavior

I am stuck at RTC connecting and I cannot hear the other person.

### Steps to reproduce

1. Go to Discord
2. Call a friend / join a server voice chat 
3. RTC connecting 

### Debug link

https://debug.ferdium.org/af669fe2-2706-4c80-af9a-67dad22af547

### Screenshots

![Screenshot from 2022-09-11 22-12-21](https://user-images.githubusercontent.com/52655835/189547076-218d1346-311a-476f-bed5-9403ad98b003.png)

**Comment by Axel29** [comment]
Same issue here, I've had this bug for a week now.

**Comment by Yuki2DX** [comment]
Same bug here. Discord App works fine, but the Ferdium recipe isn't working now :\

**Comment by SpecialAro** [comment]
Hello 😁 thank you for logging this issue.

Are you by any chance using the latest nightly and not the stable version?

If so (using the nightly), then it is probably due to the new feature for WebRTC IP handling. This was introduced in a nightly version, with the default option to hide the public and private IP and interfaces for WebRTC.

This behavior can be changed in the Privacy section of the Settings menu. Please, if you can, try all options and see what works. Notice that if you change the option you need to perform a full restart of Ferdium (close Ferdium, make sure it is not running and open again).

Disclaimer: be aware that changing that setting can expose your public/private IPs and interfaces to the WebRTC... So make sure you know what you are doing (you can read more about that if you search WebRTC IP leaks).

Let me know the results please 😁

Edit: I can see that you're using the nightly.10 so it is probably due to the new feature. Please try the above steps.

Also, are you building nightly.10 locally? Because it is not published on our repo.

**Comment by MartinRJDagleish** [comment]
Hey @SpecialAro,

Thank you. Yes I was using the nightly.10 and your proposed fix did work :) Thank you. 

I have switched distros to Manjaro now and I am using the "normal" versions, so this should not be a problem any longer.

**Comment by SpecialAro** [comment]
Btw @MartinRJDagleish, which option work out for you?

@vraravam should we change the default value of the WebRTC IP handle to the "default" option (leaking both private and public IP and interfaces)?

When I implemented this, I focused on getting a setting where the user is protected by default (i.e. disabling IP leaks regardless) - but this can also introduce some issues on recipes that depend on WebRTC as seen here.

Maybe we should implement this recipe wise instead (tho I'm not sure it is possible) and change the defaults for some recipes.

**Comment by DeN-AlB** [comment]
> Btw @MartinRJDagleish, which option work out for you?

For me, all other 3 settings in v6.2.0 work to be able to join a voice chat in Discord. Only the default setting (Do not expose public or local IPs) is not working. So I choose the 3rd setting (Expose user public or local IPs - only use default route used by http).

**Comment by PhlegmaTREEc** [comment]
I just found this and made my discord work again. What is the least bad option to choose? The one that @DeN-AlB did or the second one?

**Comment by DeN-AlB** [comment]
> What is the least bad option to choose?

I'm interested in that, too.

**Comment by fgurdradee** [comment]
> > Btw @MartinRJDagleish, which option work out for you?
> 
> For me, all other 3 settings in v6.2.0 work to be able to join a voice chat in Discord. Only the default setting (Do not expose public or local IPs) is not working. So I choose the 3rd setting (Expose user public or local IPs - only use default route used by http).

I can confirm that the first 3 options all work. Tested on Linux Mint with deb file and flatpak installation, and Windows. Running 6.2 stable. 

![2022-09-30_16-23-56](https://user-images.githubusercontent.com/92288970/193226609-0a9e94d9-4634-482d-b3d1-07b5e464d007.png)

**Comment by wennbley** [comment]
I am now getting this issue on 2 of my Macs. I have the latest public build Version: 6.2.0

Changing to any of the WebRTC IP Handling Policy does not work for me!

**Comment by fnagel** [comment]
Tried all three options (on Windows 10) but I was not able to make Discord work. Using Ferdium 6.2.6 nightly 8.

**Comment by trendespresso** [comment]
> > Btw @MartinRJDagleish, which option work out for you?
> 
> For me, all other 3 settings in v6.2.0 work to be able to join a voice chat in Discord. Only the default setting (Do not expose public or local IPs) is not working. So I choose the 3rd setting (Expose user public or local IPs - only use default route used by http).

Same! Perhaps if a user adds the Discord app then Ferdium can notify the user about the issue and suggest changing the setting to one less strict?

**Comment by dargmuesli** [comment]
@SpecialAro do you have a recommendation for the question
> What is the least bad option to choose?

:pray: thank you. If it's not easy to explain, a link to some specification to read ourselves would surely help as well :heart:

**Comment by SpecialAro** [comment]
Hi @dargmuesli 

I think you have to try and error from the best case (not exposing anything) to the worst case (exposing everything).

Take a look at this issue (the one that triggered the implementation of the WebRTC) https://github.com/ferdium/ferdium-app/issues/598

**Comment by ChaoticHolon** [comment]
I don't think this bug should have been closed (and should be re-opened), because while this workaround does work, because its a global setting, it effectively exposes/leaks your IP globally in all Ferdium recipes/services. And we honestly need a per recipe solution that doesn't do this.

**Comment by Mohamedkrms** [comment]
same problem for me , the temporary solution is restart my pc again and again it work but i m working for this to fixed it  in the future but if any one have solution for linux user please reply me as soon as possible
