### ISSUE TITLE
Feature: Start "non-contact" chats on WhatsApp

### ISSUE THREAD

**Issue by frankhommers** [ferdium/ferdium-app#616]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Just an idea, I don't know if it will fit here.

But it would be really great if we could add a button to the whatsapp interface somewhere, that allows you to input a number.

After inputting the number, if we set the location to `https://web.whatsapp.com/send?phone=31612345678&text&type=phone_number&app_absent=1` 

If you replace `31612345678` with the phone number, you are starting a direct chat to a phone number that is not necessarily in your contacts. 

Currently I do this by pasting the URL in the service address bar.  I use it at lot for companies that have a business whatsapp and I don't have as a contact.

### Proposed Solution

See the problem description. (It's actually not a problem).

### Alternatives Considered

I don't think there are alternatives.

**Comment by vraravam** [comment]
This is not something we can control. We would not want to inject code into the webpage.

**Comment by andresimi** [comment]
Hello. However, this option is already available on whatsapp web:
![image](https://user-images.githubusercontent.com/7464255/217310897-b12d84c6-f727-4652-b873-ed18a848fb7f.png)


Why ferdium doesn't have these features?
![image](https://user-images.githubusercontent.com/7464255/217310730-202f5f0e-e17a-4caa-bc12-a8e618ea02c1.png)

Best!

**Comment by SpecialAro** [comment]
@andresimi maybe you are talking about WhatsApp Desktop and not WhatsApp Web. If that's the case, as @vraravam stated, we will not want to inject code into the webpage.

This is my WhatsApp web:
![image](https://user-images.githubusercontent.com/37463445/217314966-8c824bad-7791-441f-b486-f179407bb22e.png)

**Comment by andresimi** [comment]
Hi @SpecialAro , actually it is watsapp web. I don't know what is the engine Ferdium uses, but this options are enabled when I enter in https://web.whatsapp.com/ in Google Chrome.
I am using Fedora 37 as OS by the way.

**Comment by SpecialAro** [comment]
Well, that's pretty strange! Maybe you got a version update first than I?

Nevertheless I tested it on Brave browser, tomorrow I can test it out on Chrome but I don't think I'll see any changes. We use a WebView of WhatsApp web, so what you get is (should be at least) exactly the same as in opening on a browser. Just to confirm, no browser extensions whatsoever are causing that behavior?

(Don't get me wrong, i really think it is a cool feature, and if WhatsApp has rolled out that their web version we should be able to get that exact same behaviour... Are you available to help out in debugging stuff if I'm not able to get those features myself using chrome? Maybe we can try to figure out why we are having such differences)

**Comment by vraravam** [comment]
There could be 2 reasons that I can think of:
1. WA is doing a rolling release of such a feature. @andresimi was one of the group that got this feature, while others are not so lucky. I have verified in my WA - both in Chrome, Firefox and Ferdium - and I don't see this feature.
2. WA could be selectively allowing specific browsers to access such a feature. To verify that this is the case, @andresimi can try to login into WA web on different browsers and check. If this is the case, then I would suggest to take their Chrome user agent and put it into Ferdium - at least specifically in the WA service settings if not the global one.

**Comment by andresimi** [comment]
Hi @vraravam and @SpecialAro, I forgot to provide an important information: I am using whatsapp Business in my iphone! It's free. It has special features indeed. However, this features are not presented when I acess  https://web.whatsapp.com/ on Firefox for example.
My user agent on chrome is: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

Best!

**Comment by vraravam** [comment]
thanks for confirming @andresimi - as you also attested, if the web version of WA does not show this in a regular browser, then Ferdium cannot also show this.

**Comment by andresimi** [comment]
Ok. But Chrome is not considered a regular browser? An if I use an user agent of chrome shouldn't it be the same as on chrome web aplication?

**Comment by vraravam** [comment]
`However, this features are not presented when I acess https://web.whatsapp.com/ on Firefox for example.` - this is what you had posted, yes? And if Chrome also has the same behavior (irrespective of the user agent), then its the default behavior, yes?

**Comment by vraravam** [comment]
you cannot compare Chrome on your mobile browser vs Firefox on a desktop/laptop, for eg. (if that's what you were doing earlier - its not clear on the comment above)

**Comment by andresimi** [comment]
I think there is some confusion here. The only thing I use on my mobile device is the Whatsapp Business App (https://apps.apple.com/br/app/whatsapp-business/id1386412985). I said that i can add a non-contact chat when I acess whatsapp web via chrome web browser on my desktop (fedora 37) but not when I access whatsapweb on firefox on the same desktop.

**Comment by vraravam** [comment]
thanks for that clarification. In that case, it clearly points to WA doing something smart based on the user-agent. With this knowledge, at this stage, I would suggest that you use the Chrome user agent, and put it into Ferdium for the WA service in the service's settings, and see what happens

**Comment by andresimi** [comment]
Yeah, I copyed the output from https://whatmyuseragent.com/ to the user agent on Ferdium and restarted it. However, nothing changed. It didn't enabled the feature.

**Comment by carra1975** [comment]
Hello how are you, glad to be here and I was looking for a solution to this problem you speak of.

What @andresimi comments is an extension called blueticks (blueticks.co) that is in chrome.

I use it in my chrome and edge browser, but in ferdium I don't know how it could be installed if of course it can.

This type of extensions would be of great help if it could be installed in ferdium to be able to vitaminize whatsapp businesses.

Greetings from Spain.
