### ISSUE TITLE
Bug: Password can be bypassed

### ISSUE THREAD

**Issue by eyallior** [ferdium/ferdium-app#618]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

5.8.1

### What Operating System are you using?

Windows

### Operating System Version

Windows 10 Pro

### What arch are you using?

x64

### Expected Behavior

Password should secure access to my accounts - meaning there should be no way to get to my accounts, inc stealing cookies or whathaveyou. This is very disappointing, being just a pretended password mechanism to make people believe they have privacy while they totally don't.

### Actual Behavior

config file can be edited and password removed, then access is possible to my accounts.

### Steps to reproduce

1. Lock Ferdi with password
2. Shut Ferdi down
3. Change setting.config - lockingFeatureEnabled to false
4. Start Ferdi

**Comment by SpecialAro** [comment]
Hello @eyallior , thank you for logging this issue.


We don't have any 5.8.1 version of Ferdium, you are probably referring to Ferdi.

Can you please check if the same happens with the most recent version of Ferdium and then we, if we does, we can take measures?

Thank you

**Comment by SpecialAro** [comment]
Tried to reproduce this locally and it didn't work.

Nevertheless, the setting that actually creates this issue is: `locked: false` and not `lockingFeatureEnabled: false`.

Quoting @vraravam from discord:

> Yes - this backdoor is known. @kris7t also posted an extensive message on this topic. Essentially, if a hacker has physical access to your laptop, they can do much more harm than getting into Ferdium using this backdoor
on the positive note, if someone has forgotten their password for Ferdium, this is the way to get unlocked 🙂

**Comment by kris7t** [comment]
Additionally, the cookies on disk are not encrypted, and Electron has no reliably way of encrypting them, so even if the password lock couldn't be disabled from the config file, an attacker could just access the raw cookies on the disk.

I've submitted a feature request to Electron to enable user data encryption with a configurable key (which would be needed for this feature to wok properly), but unfortunately, the request was closed with no substantial response.
