### ISSUE TITLE
Workspace Icons Padding issue

### ISSUE THREAD

**Issue by Virgus** [ferdium/ferdium-app#619]
### Your issue

Hello I just migrated from Ferdi and choosed to install the latest version 6.1.0
I just tried changing the GUI appearance: set normal width sidebar and enabled "Display service name under the icon".
The icons padding doesn't take into account the text labels so the lower icons overlap the text label.

I don't know if this issue has been already addressed in the latest nightly builds but I haven't find anything here on Github so I'm writing this comment just in case. Attached a snapshot of what I see on my W7U OS.

Thanks for this great work !

Regards,
V.

![Screenshot 20220915_225615](https://user-images.githubusercontent.com/6388217/190508819-fc41a18c-ece1-4cc1-8333-42996c9a0c81.png)

**Comment by neel1996** [comment]
Hi @vraravam,

If this issue is up for grabs, I can work on this.

The `.tab-item` is the selector being used for the tab items, which has a `min-height` attribute. The min-height value is currently '50px' which is not sufficient for the tab items with label when the viewport height shrinks.

**Comment by vraravam** [comment]
please go ahead @neel1996 - thanks for signing up for this.
