### ISSUE TITLE
Bug: with service "custom website" links get opened in default browser rather than Ferdium

### ISSUE THREAD

**Issue by spi43984** [ferdium/ferdium-app#626]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.1.1-nightly.11

### What Operating System are you using?

Ubuntu

### Operating System Version

20.04

### What arch are you using?

x64

### Expected Behavior

With a custom website service there is a setting "open URLs in Ferdium". When clicking a link on the custom website I'd expect the new website or pdf or whatever to be opened within Ferdium.

### Actual Behavior

The link gets opened in the system default browser instead. That doesn't work though if the website expects authentication.

### Steps to reproduce

1. create custom website service
2. click any link
3. link gets opened in system default browser and not within Ferdium

**Comment by spi43984** [comment]
Forgot debug link. If needed will submit later.

**Comment by SpecialAro** [comment]
As per implementation, this is "working as expected" since we didn't code that part in that recipe. Tho, we can (should) try to implement a global catch all for every recipe (if the setting is active in the recipe).

**Comment by spi43984** [comment]
> As per implementation, this is "working as expected" since we didn't code that part in that recipe. Tho, we can (should) try to implement a global catch all for every recipe (if the setting is active in the recipe).

How can that be achieved? If you ping me in that direction I can try to fix it. Can't use some of my web services as they need authentication and every link opens default browser with not authenticated session.

**Comment by spi43984** [comment]
Am looking into the zoom and steamchat recipes to see how they solve that.

If a website links to a pdf file for instance - will it ever be possible to open that pdf within Ferdium or is this something that need to be opened and rendered by the default browser?

Currently if I click a link (that is linked to a pdf) in Ferdium that link is opened in the default browser - which actually doesn't open the pdf as I am not authenticated in the default browser.

If I right click the link and choose "Open Link in Ferdium" I can download the pdf to a custom folder - not too bad.

If I right click the link and choose "Open in Browser" the link gets opened in the browser, I need to authenticate and the service default start page is loaded - too complicated.

BTW - should I move that issue to ferdium-recipes?

**Comment by xalt7x** [comment]
@SpecialAro 
> As per implementation, this is "working as expected" since we didn't code that part in that recipe. 

I wonder where does "Open URLs within Ferdium"  actually work. All services I've tested  ("Google/Hangouts Chat", "Facebook Messenger", "Zulip") which always opened external links with a system browser still did it regardless of the setting.

Apart from 
> right click the link and choose "Open Link in Ferdium"

There's another workaround: left click with pressed Shift. It opens a new Ferdium window where you can view external page or download file.

I would love to see "Open Link in Ferdium" as a default behaviour for a simple left click.

P.S. Found answer [in this comment](https://github.com/ferdium/ferdium-app/issues/87#issuecomment-1162907493):
> [As per the implementation](https://github.com/ferdium/ferdium-recipes/pull/30/files), this is only implemented for Discord, Skype, Steamchat and zoom. If needed for other services, please raise specific requests in the ferdium-recipes repo.

Well, in this case it's confusing to see such options for other services...

**Comment by spi43984** [comment]
I opened an [issue](https://github.com/ferdium/ferdium-recipes/issues/185) with ferdium-recipes...

**Comment by vraravam** [comment]
Closing since the associated issue https://github.com/ferdium/ferdium-recipes/issues/185 has been fixed in the latest nightly.
