### ISSUE TITLE
Feature: Load multiple instances of the same service e.g. Gmail

### ISSUE THREAD

**Issue by tappoz** [ferdium/ferdium-app#629]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I would like to load multiple recipes/services of the same type e.g. a private Gmail account and a work-related Gmail account.

### Proposed Solution

I would like to be able to decouple services, by loading multiple instances of the same service.

### Alternatives Considered

I tried to load a service in separate workspaces, but what I end up is the same service e.g. the same Gmail account being shared across different workspaces.

**Comment by SpecialAro** [comment]
Hello @tappoz 👋 this feature already exists. You just need to add a new service that is exactly the same as the one you want to duplicate (you can even change the name of the service)

**Comment by SpecialAro** [comment]
Closing as this is already an existing feature.

If you need assistance, feel free to message (ping) me on Ferdium Discord: https://discord.gg/jVv4Qns8pP
