### ISSUE TITLE
Feature: Allow navigating back and forward in web app with command + [ / ]

### ISSUE THREAD

**Issue by calvinwyoung** [ferdium/ferdium-app#649]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I frequently use the command + bracket hotkeys to navigate back and forward in certain apps (e.g., gmail). Right now these hotkeys get swallowed by Ferdium, but I'd love to forward them to the web app

This is sort of a natural extension of #45 which was fixed a few months back.

### Proposed Solution

Forward `command + [` and `command + ]` to web app instead of Ferdium UI

### Alternatives Considered

Can currently use mouse to navigate backwards and forwards, but would love to use keyboard shortcuts

**Comment by vraravam** [comment]
If you meant go forward/backward in navigation history, this is already present:
<img width="295" alt="Screenshot 2022-10-03 at 7 27 37 AM" src="https://user-images.githubusercontent.com/69629/193488670-c1cbfe17-6fa4-4185-88b4-08c7bc01a978.png">

Please close the ticket if this is the case.

**Comment by calvinwyoung** [comment]
@vraravam Thanks for the quick response. You're absolutely correct that resolves my issue — I'm not sure how I missed that previously. I'll go ahead and close this ticket!
