### ISSUE TITLE
Bug: New media indicator doesn't hide when a service hibernates/disabled

### ISSUE THREAD

**Issue by Jvlsc** [ferdium/ferdium-app#656]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.1-nightly.9

### What Operating System are you using?

Windows

### Operating System Version

Windows10

### What arch are you using?

x64

### Last Known Working Ferdium version

This feature was added in the latest version.

### Expected Behavior

When a service hibernates (auto or manual), media indicator should be hidden.

### Actual Behavior

Media indicator remains when a service is hibernated.

### Steps to reproduce

1. Play any media in a sevice.
2. Hibernate/Disable the service (manual or automatic).

### Screenshots

![Screenshot from 2022-10-05 11-19-45](https://user-images.githubusercontent.com/36289254/194027135-13a91892-22c8-4a9b-a6f1-c10c28750a6d.png) ![Screenshot from 2022-10-05 11-20-12](https://user-images.githubusercontent.com/36289254/194027136-07f8459f-47b6-4846-abbf-e9983a7e39e6.png)

### Additional information

I think it would be interesting to link it with other issue I created in the past: #445.

The perfect behavior would be prevent any service auto-hibernates while media is playing. But if user manually hibernates/disables a service, the media indicator icon should be hidden.

I hope it helps.

Kind regards.

**Comment by santhosh-chinnasamy** [comment]
@Dvlnst Thanks for reporting the bug.
