### ISSUE TITLE
Feature: 

### ISSUE THREAD

**Issue by J-Kappes** [ferdium/ferdium-app#668]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

The text when using Zulip through Ferdium is pretty tiny. Too small to read comfortably.
Here's a screenshot with the Ferdium tool bar for scale.
![image](https://user-images.githubusercontent.com/87168492/195150814-1935a7d0-0859-4dbc-92ee-0058ee86153a.png)

### Proposed Solution

Content zoom feature as in a web browser like Firefox. My preferred input method is Ctrl+Scroll.

### Alternatives Considered

I hoped Zulip would have text size options, but it doesn't.

**Comment by SpecialAro** [comment]
Hello @J-Kappes

That feature already exists inside the "View" menu on the top bar of Ferdium. Please, look at the screenshot bellow:
![image](https://user-images.githubusercontent.com/37463445/195154188-a626e428-6154-4bd6-96a2-30f4926c2f72.png)

Also, next time, please make sure you introduce a title that best describes the issue/feature, and do not leave it blank as this one is.

Thank you!

I'm closing this as completed.
