### ISSUE TITLE
Feature: Title-Less "Custom Website" Recipe

### ISSUE THREAD

**Issue by Gaibhne** [ferdium/ferdium-app#677]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Title says it all. I have multiple websites I use via the 'Custom Website' template, but none of them profit from having a title bar any more than, say, IRCCloud, Instagram, Gmail or any of the other premade services that hide the title bar.

### Proposed Solution

I would also like to hide the title bar in my custom services, and it seems like a quick solution for that would be a new "Custom Website w/o Titlebar" template.

### Alternatives Considered

Weeping, I guess ? I don't know what an alternative solution would be other than having premade services for every possible website.

**Comment by vraravam** [comment]
@Gaibhne - could you please add some screenshots with markings as to what's extra or missing? i'm unable to visualize the issue

**Comment by Gaibhne** [comment]
Instgram as a dedicated service:

![image](https://user-images.githubusercontent.com/24731712/196216019-d7cf957b-40f8-4d38-96a4-416684cd159e.png)

Instagram via the 'Custom Website' service:

![image](https://user-images.githubusercontent.com/24731712/196216184-1622551a-452a-4fe1-b8da-97675fbc3419.png)

You can see that via 'Custom Website', it has a forced address bar at the top that is impossible to hide, even via `View`/`Toggle Navigation Bar`.

**Comment by vraravam** [comment]
Looks like you are using the default setting - please choose something else from the dropdown
<img width="643" alt="Screenshot 2022-10-17 at 8 54 55 PM" src="https://user-images.githubusercontent.com/69629/196218440-845a0396-a84a-419c-855d-06822f69a2f3.png">

**Comment by Gaibhne** [comment]
Thanks, I didn't realize there was a global setting like that!

**Comment by lenar** [comment]
"Never show.." is a good option, but it should be possible to specify this per (custom) service also.

**Comment by 392781** [comment]
This doesn't work.  I have "Never show" enabled and the titlebar still shows up.

**Comment by paulo-roger** [comment]
> This doesn't work. I have "Never show" enabled and the titlebar still shows up.

try `ctrl + b` or `alt` to show the menu bar and `view`

**Comment by vanmash** [comment]
on Macos `Command+b` hides it.
