### ISSUE TITLE
Bug: Google voice audio not working once call connects

### ISSUE THREAD

**Issue by beckerben** [ferdium/ferdium-app#683]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.1-nightly.23

### What Operating System are you using?

Windows

### Operating System Version

Windows 10 Enterprise 10.0.19042

### What arch are you using?

x64

### Expected Behavior

Using the google voice service, it used to work flawlessly but now I notice when I go to answer or make a call, as soon as the call is connected, I cannot hear anything.  The audio tests work just fine and I hear when I call it starts ringing but as soon as the party answers I don't hear anything and they don't hear me but the call stays connected it is just audio is lost.

This does not happen when calling in a browser on the same computer outside of ferdium.  This used to work in ferdium, not sure why it stopped working but suspect it was about a 5 weeks ago when I first noticed this.  I have continued upgrading the nightly build with hopes of a fix.

### Actual Behavior

Audio once a call connected should continue working.

### Steps to reproduce

Make a google voice call or answer a call.

### Debug link

https://debug.ferdium.org/23d7dbb7-9421-468d-ac86-4134db976b71

**Comment by SpecialAro** [comment]
Hello @beckerben. Thank you for logging this issue.


First, please edit your Issue Title so that it follows the guidelines.

Secondly, please take a look at this issue: https://github.com/ferdium/ferdium-app/issues/611

Try to change the WebRTC IP exposure settings to the ones described (restarting Ferdium after the change) and try again.

This was a breaking change (focused on security) introduced some weeks ago, so that might be due to that.

**Comment by beckerben** [comment]
@SpecialAro i must have missed entering the subject, I fixed that!

And changing the WebRTC IP Handling Policy to "Expose user public and local IPs" did indeed fix the issue, thank you!

**Comment by SpecialAro** [comment]
> @SpecialAro i must have missed entering the subject, I fixed that!

Thank you 😁



> And changing the WebRTC IP Handling Policy to "Expose user public and local IPs" did indeed fix the issue, thank you!

Beware that your public and local IPs will be exposed over to WebRTC on every Ferdium service (as this is a global feature).
