### ISSUE TITLE
Bug: Horizontal sidebar overlaps active service regardless of sidebar size

### ISSUE THREAD

**Issue by taingalls** [ferdium/ferdium-app#69]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.16

### What Operating System are you using?

macOS

### Operating System Version

macOS Monterey 12.3.1

### What arch are you using?

x64

### Last Known Working Ferdium version

6.0.0-nightly.10

### Expected Behavior

The sidebar when set to horizontal style should be directly above the active service .
<img width="256" alt="image" src="https://user-images.githubusercontent.com/26406250/166107838-0736d5eb-4063-418a-a2e9-4327ac8cc4be.png">

### Actual Behavior

The sidebar overlaps the active service regardless of the size of the sidebar.
![image](https://user-images.githubusercontent.com/26406250/166107862-e7e7650d-c650-459a-ad0d-94fa55eb3ba8.png)

### Steps to reproduce

Update to 6.0.0-nightly.16 and use any service.

**Comment by SpecialAro** [comment]
Fixed on https://github.com/ferdium/ferdium-app/pull/70. Wainting for confirmation on the next release to close the issue.

Thank you for raising this issue 😄

**Comment by SpecialAro** [comment]
Confirmed to be working. Closing this issue.
