### ISSUE TITLE
Bug: Notifications on custom website not showing

### ISSUE THREAD

**Issue by iztokinvest** [ferdium/ferdium-app#696]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.0

### What Operating System are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

Custom websites with notifications

### Actual Behavior

When a website title starts with (1) no notification is shown

### Steps to reproduce

1. Custom website receives a notification
2. The notification is not visible until the site is opened

**Comment by ladygamer** [comment]
I have the exact same problem

**Comment by vraravam** [comment]
Custom services are not coded for either notifications or unread badge counts. This will not be implemented due to the infinite combinations possible.
