### ISSUE TITLE
Bug: Google Calendar Description Links Open Twice

### ISSUE THREAD

**Issue by Julian88Tex** [ferdium/ferdium-app#712]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.0

### What Operating System are you using?

macOS

### Operating System Version

13.0

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

One tab opens

### Actual Behavior

Duplicate tabs open

<img width="528" alt="Screenshot 2022-10-26 at 2 13 24 PM" src="https://user-images.githubusercontent.com/459099/198139357-646c5b0e-14eb-4c6a-99f5-eb4e0487ba59.png">

### Steps to reproduce

1. Add a link to a Google Calendar event description
2. Save event
3. Click on link in description
<img width="401" alt="Screenshot 2022-10-26 at 2 13 32 PM" src="https://user-images.githubusercontent.com/459099/198139354-499cc465-3f8d-4b47-8ab2-153eacbaa508.png">

### Debug link

https://debug.ferdium.org/9281e678-4911-4397-ade9-ab95d4045e4c

### Additional information

• Confirmed this is not happening in just chrome using Google Calendar
• Cannot reproduce this with links in any other recipes or even other links in any location in Google Calendar like zoom links in location. Seems to specifically be happening with calendar description links only.

**Comment by vraravam** [comment]
I use google calendar within Ferdium extensively, and I have not been able to reproduce this issue. Can you please verify that you are using the latest version of the google-calendar recipe (2.3.0)? and that you do not have any custom modifications to the files in it?

**Comment by Julian88Tex** [comment]
@vraravam Thanks for asking yes 2.3.0. I just turned off and then on dark mode which seems to have fixed it so I'll go ahead and close this out. Maybe something temporary. Was happening for a few days though.
