### ISSUE TITLE
Bug: Discord Call RTC connecting (same as #611 but for macOS)

### ISSUE THREAD

**Issue by fseesink** [ferdium/ferdium-app#718]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.0

### What Operating System are you using?

macOS

### Operating System Version

12.6.1

### What arch are you using?

x64

### Expected Behavior

Using Discord in Ferdium and joining a call, expect to hear audio.

### Actual Behavior

No audio, and at the bottom just above my account, it shows

> RTC Connecting

perpetually.

### Steps to reproduce

1. Go to Discord in Ferdium
2. Call someone or join a group call

### Screenshots

![image](https://user-images.githubusercontent.com/48991/198748960-4d528a89-fb60-4a51-9e6a-61b63e103e32.png)

### Additional information

Looking at ferdium/ferdium-app#611, could not find any info there which helped unfortunately. :sad

**Comment by vraravam** [comment]
Have you tried this? https://github.com/ferdium/ferdium-app/issues/611#issuecomment-1263271328

**Comment by fseesink** [comment]
As I already wrote in `Additional information` above, I could not find any info there which helped.  Went into Ferdium's `Settings | Privacy` section and under `WebRTC IP Handling Policy` tried every option to no avail.

To be clear, if I simply run the native Discord client for macOS, audio works just fine.  And with Ferdium, it is not a matter of access/permissions, as all the usual dings and blips all sound just fine. And I DO see that the microphone appears to be working, in that when I talk, I see a circle light up around my name in the call.  Even the video comes up when I turn on the camera.  It is purely output audio I am having issues with on calls.

**Comment by SpecialAro** [comment]
@fseesink after trying every option did you restart Ferdium?

**Comment by fseesink** [comment]
@SpecialAro Yes.  Multiple times.  If you have a specific sequence you want me to try, let me know.

The issue clearly is with WebRTC connectivity specifically.  I just haven't been able to figure out why.  Everything else is working fine.

**Comment by SpecialAro** [comment]
@fseesink that issue happened specifically when we implemented that feature you saw on the settings about WevRTC IP.

It should be working if you followed every step described on the issue @vraravam pointed out.

The sequence would be: change the drop-down setting, restart Ferdium (full restart, not reload - closing Ferdium, making sure it's not running in the background - and then open it again)

I can also try later on macoOS so that I make sure I can reproduce your problem.

**Comment by SpecialAro** [comment]
<img width="254" alt="image" src="https://user-images.githubusercontent.com/37463445/198907863-ec35c0dd-a948-47b5-9c38-6543ec071909.png">

No issues with macOS 12.6 Monterey. Using this setting:
<img width="636" alt="image" src="https://user-images.githubusercontent.com/37463445/198907908-fc89df79-1647-4c14-b7af-d4a8a026be99.png">

**Comment by fseesink** [comment]
Well son of a gun!  Now I feel embarrassed.

Ok, when I launched Ferdium, went into settings, adjusted things as shown above, fully quit Ferdium, restarted Ferdium, and tested a call, sure enough it connected!  Great!

(Could've sworn I did this before.  But as late as it was, wouldn't be surprised if I changed settings, tested, then changed it back and then quit/restarted.  For sure I quit/restarted the app quite a few times.  But was a long week.)

Anyway, thanks.  That helps.  Very much appreciated.

Been really enjoying using Ferdium.  It has made having to use MS Teams more tolerable than the native app.  I still think Teams is a dumpster fire of an app, but at least it loads/quits quicker now. 😀  And being able to have multiple chat/collab apps together has been working quite nicely actually.  Currently I have 4 different ones and it's much quicker/cleaner than running all of their native apps separately.  Keep up the good work.

**Comment by ahydronous** [comment]
For anyone finding this through searching:

`Ferdium > Settings > Web RTC Handling Policy > Expose Public and Local IPs`.

For what its worth, I think the private WebRTC change done in the past should be reverted. Many users will be running into this and just uninstall Ferdium because they think its broken compared to service-in-browser or native app.
