### ISSUE TITLE
Feature: Use tauri instead of electron

### ISSUE THREAD

**Issue by mariocynicys** [ferdium/ferdium-app#747]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Not really a problem, but was thinking of having a lighter ferdium by using [tauri](https://tauri.app/), which has a very superb performance compared to electron.

Ferdium might get a significant performance gain and lesser memory footprint by switching to tauri. I know this can be such a big change but I think it's worth it.

### Proposed Solution

Moving to tauri. Relevant benchmarks for comparison can be found [here](https://tauri.app/v1/references/benchmarks).

### Alternatives Considered

None

**Comment by cino** [comment]
@mariocynicys Thanks for the suggestion, I have however been looking into Tauri for a while now and according to the latest issues i've read it's not possible. We are using Electron's Webview component to have a webpage in a webpage.

Sources:
- https://github.com/tauri-apps/tauri/issues/2975
- https://github.com/tauri-apps/tauri/issues/2709
- https://github.com/tauri-apps/tauri/issues/2975

So at this point, I'd love to have a Ferdium that could embrace the power of Tauri however, besides the fact that it's a really, really big change. It's not actually possible 

If you believe it is possible, we would love to hear about it but for now closing this issue :)

**Comment by ylluminate** [comment]
Has the landscape changed for this not being viable?

**Comment by MoonBox5** [comment]
@cino
> We are using Electron's Webview component to have a webpage in a webpage.
> (...)
> So at this point, I'd love to have a Ferdium that could embrace the power of Tauri however, besides the fact that it's a really, really big change. It's not actually possible
> 
> If you believe it is possible, we would love to hear about it but for now closing this issue :)

Tauri has made this possible now. Please revisit the idea of a Tauri rewrite.

Relevant Tauri PR: tauri-apps/tauri/pull/8280
Example: https://github.com/tauri-apps/tauri/tree/dev/examples/multiwebview

**Comment by ylluminate** [comment]
Wow... Very interesting. Are there any ways to estimate the resource (CPU + memory) savings that might be realized through this?

I've seen speculation that such a rewrite could considerably help Ferdium in running on lighter/older hardware more efficiently with less memory and CPU cycles as well as higher performance and battery life (not to mention potentially better/easier platform integration)...

**Comment by machiav3lli** [comment]
@vraravam I guess this is worth a second look considering that all the blockers are now solved?

**Comment by MoonBox5** [comment]
Not only is the Webview issue solved already, but it has been stable on Tauri 2.0+ for a while now.
Do revisit this issue please.

**Comment by Gizmo091** [comment]
Hello,

I vibe-coded a Tauri version: https://github.com/Gizmo091/Tauridium, but Tauri doesn't currently support handling Passkeys or biometric sign-in.
