### ISSUE TITLE
Bug: Ferdium is Down

### ISSUE THREAD

**Issue by iquirino** [ferdium/ferdium-app#749]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.0

### What Operating System are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Last Known Working Ferdium version

6.2.0

### Expected Behavior

It should show my services

### Actual Behavior

It is showing the red bar with "Could not load services and user information Try again"

### Steps to reproduce

1. Open the ferdium

### Screenshots

![image](https://user-images.githubusercontent.com/881117/201060736-8457b10c-b817-48ed-b329-ef154052367d.png)

### Additional information

It started last night

**Comment by iquirino** [comment]
Same issue with 6.2.1-nightly.43

**Comment by SpecialAro** [comment]
Hello @iquirino, thank you for logging this issue.

I'm currently running Ferdium on Windows 11 as you can see in the screenshot bellow.
![image](https://user-images.githubusercontent.com/37463445/201062339-db58b8b9-c2cb-4512-ac3a-44188a9d10ca.png)

Maybe there is something wrong on your side of things. Which Server are you using? Can you post the same screenshot I took above but for your settings (Help > About Ferdium)?

**Comment by iquirino** [comment]
Hello @SpecialAro:

Version: 6.2.1-nightly.43
Server: Ferdium Server
Electron: 21.2.2
Chrome: 106.0.5249.168
Node.js: 16.16.0
Platform: Windows 11
Arch: x64
Build date: Wed Nov 09 2022 01:12:26 GMT+0000 (Western European Standard Time)
Git SHA: 7e008dfb
Git branch: nightly

**Comment by SpecialAro** [comment]
Also, as per https://ferdium.github.io/ferdium-status/ , no downtime have been registered in the API endpoint. Could you try to `ping api.ferdium.org` on your terminal (Windows CMD) and post the results?

Can you open https://api.ferdium.org/ normally in a browser?

**Comment by iquirino** [comment]
![image](https://user-images.githubusercontent.com/881117/201063856-08ea4948-a3e0-4f13-8060-7e7361a157e8.png)
I tried from my PC and from my smartphone browser and I am having DNS_PROBE_FINISHED_NXDOMAIN.
I think it could be something related to DNS, because I'm unable to do this on my phone too..

**Comment by cino** [comment]
@iquirino Which DNS server are you using?

**Comment by iquirino** [comment]
I've added 2.58.59.67 api.ferdium.org to my hosts file and my ferdium is working again.
I tried with my provider DNS's and with 8.8.8.8 as primary and 0.0.0.0 as secondary and didn't works.

**Comment by SpecialAro** [comment]
Yep, that's definitely something wrong with your connection.

0.0.0.0 as secondary sounds wrong. Could you try with primary DNS 8.8.8.8 and secondary 8.8.4.4?

**Comment by SpecialAro** [comment]
> I've added 2.58.59.67 api.ferdium.org to my hosts file and my ferdium is working again.

This is a nice workaround, but you should really try to fix the DNS problem (because if we change the IP you lose the connection again)

**Comment by iquirino** [comment]
> I've added 2.58.59.67 api.ferdium.org to my hosts file and my ferdium is working again. I tried with my provider DNS's and with 8.8.8.8 as primary and 0.0.0.0 as secondary and didn't works.

I'm sorry, it is 1.1.1.1 =D

**Comment by iquirino** [comment]
With my provider default DNS it is not working.
With 8.8.8.8 and 8.8.4.4 or 1.1.1.1 didn't worked too.

**Comment by iquirino** [comment]
I think you could be having an Issue with DNSSEC.
Where are you hosting your domain servers?
https://dnssec-analyzer.verisignlabs.com/ferdium.org

**Comment by SpecialAro** [comment]
> With my provider default DNS it is not working.

I've had some instabilities with my provider DNS too, so I changed to 1.1.1.1 and 1.0.0.1 and it works properly now.

**Comment by SpecialAro** [comment]
> I think you could be having an Issue with DNSSEC. Where are you hosting your domain servers? https://dnssec-analyzer.verisignlabs.com/ferdium.org

I'm tagging @dqos on this issue so that he can have a look. @dqos it seems like we can't run away from this 🥲

**Comment by iquirino** [comment]
Hey guys, now I am able to ping it from my internet provider DNS. Have you changed anything? Maybe was something related with my provider.

**Comment by cino** [comment]
@iquirino Thanks for the response, for now closing this issue as it's unrelated to the ferdium server. Happy it's working again for you 👍

**Comment by tiagonunocosta** [comment]
I resolve my problem adding this line to my host file.

Steps for MacOs:
   - Open terminal app
   - sudo nano /etc/hosts
   - enter your password
   - add this line 2.58.59.67 api.ferdium.org
   - control+X

**Comment by SpecialAro** [comment]
> I resolve my problem adding this line to my host file.
> 
> Steps for MacOs:
> 
> * Open terminal app
> * sudo nano /etc/hosts
> * enter your password
> * add this line 2.58.59.67 api.ferdium.org
> * control+X

Hey @tiagonunocosta !
As per your name I assume you're from Portugal (if I'm wrong, I'm really sorry... disregard everything I say from here on).

I'm also from Portugal and this issue might be related to the DNS Server that our ISP is using (if you still have the default settings on your router for it). What I do is to manually change the DNS settings on my computer to 1.1.1.1 or 8.8.8.8 (rather than editing the hosts file, so that if Ferdium moves the IP, I'm still able to connect without editing). I've identified 3 users from Portugal and this seems to be a rule.

Small note: Don't change your DNS Settings on your router because this will cause malfunctions at the IPTV level (you're going to have problems on you TV Box connection - did that once, don't recommend it ahah)

**Comment by iquirino** [comment]
I'm Brazilian but I am currently in Portugal (1 year).
My provider is Vodafone and it is working well right now.
Guys, do you need some help to solve this issue?
I think you could try to move your DNS records to aws or something like that... I dont know which provider you are using, but I am really interested to help.
I use Ferdium at least 18 hours every day... So... it's how I can say thank you.

**Comment by rahpuser** [comment]
Hello guys, I know this issue is closed, but [api.ferdium.org](https://api.ferdium.org/) seems to be down again.

**Comment by tiagonunocosta** [comment]
![image](https://user-images.githubusercontent.com/17408764/210390117-b096027b-7ab3-4230-aaab-48c75ef37f9d.png)

**Comment by rahpuser** [comment]
here is the incident report https://github.com/ferdium/ferdium-status/issues/19
