### ISSUE TITLE
Bug: WhatsApp Badge Icon Is Showing Incorrect Unread Count

### ISSUE THREAD

**Issue by Julian88Tex** [ferdium/ferdium-app#756]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.0

### What Operating System are you using?

macOS

### Operating System Version

13.0 (22A380)

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Show the correct number of unread messages. In my case it should be 0 unread and therefore there should be no red badge icon.

### Actual Behavior

Unread badge Icon is showing 607. I'm not sure what this number is referring to.

### Steps to reproduce

Add WhatsApp to Ferdium and setup your account. This just starting occurring one day so not sure of any other steps.

### Screenshots

<img width="499" alt="Screenshot 2022-11-11 at 6 46 46 PM" src="https://user-images.githubusercontent.com/459099/201453121-f79a9a1b-612a-4de7-83c7-866870211a26.png">

Interesting I noticed that if you actually filter unread messages (which in my case shows no messages correctly) then the badge actually does update to correctly show no unread.
<img width="497" alt="Screenshot 2022-11-11 at 6 46 38 PM" src="https://user-images.githubusercontent.com/459099/201453122-883230a1-1268-4b88-95a9-3d1f8e6bfaa7.png">

### Additional information

https://debug.ferdium.org/d1dadc19-82b6-47d6-8f1e-4ec9db160918

**Comment by Dominiquini** [comment]
I'm having the exact same problem here on Windows 10 and Ferdium 6.2.1-nightly.44! But my counter qet stuck on '5580350'.

Thanks

**Comment by Dominiquini** [comment]
Duplicate from https://github.com/ferdium/ferdium-recipes/issues/230

**Comment by Julian88Tex** [comment]
@Dominiquini thanks. Closing as duplicate.
