### ISSUE TITLE
Bug: Unread marker on whatsapp service doesn't show the correct number

### ISSUE THREAD

**Issue by ursie** [ferdium/ferdium-app#757]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.0

### What Operating System are you using?

macOS

### Operating System Version

macOs Monterey 12.6.1

### What arch are you using?

x64

### Last Known Working Ferdium version

6.2.0

### Expected Behavior

I have 2 whatsapp accounts (services) integrated into my Ferdium Install.

I expect that the unread icon indicator show the actual unread message for that specific service

### Actual Behavior

I have 2 whatsapp accounts (services) integrated into my Ferdium Install.
I have updated my Chrome and macOs last night.

Since then I have a lot of unread messages on both whatsapp accounts in my Ferdium install. (account 1 over 1000 and on account 2 31). When I browse in one of those accounts through all chats the unread mark is constantly hopping between numbers (up and down)(see attached images).

<img width="111" alt="Screenshot 2022-11-12 at 10 22 41" src="https://user-images.githubusercontent.com/25615774/201467753-dca42ae8-f8d1-4202-917a-073e287939b4.png">
<img width="70" alt="Screenshot 2022-11-12 at 10 24 10" src="https://user-images.githubusercontent.com/25615774/201467805-129a9ec4-a92b-48a0-89bd-0ee4c7e413fd.png">

Hope the issue is clear

Version: 6.2.0
Server: No Server
Electron: 20.2.0
Chrome: 104.0.5112.124
Node.js: 16.15.0
Platform: macOS Monterey
Arch: x64
Build date: Thu Sep 22 2022 18:47:30 GMT+0200 (Central European Summer Time)
Git SHA: 84613b5b
Git branch: release

### Steps to reproduce

It's always there

### Debug link

https://debug.ferdium.org/9ac673eb-852d-4531-bb41-9488d56ec738

### Screenshots

<img width="111" alt="Screenshot 2022-11-12 at 10 22 41" src="https://user-images.githubusercontent.com/25615774/201467753-dca42ae8-f8d1-4202-917a-073e287939b4.png">
<img width="70" alt="Screenshot 2022-11-12 at 10 24 10" src="https://user-images.githubusercontent.com/25615774/201467805-129a9ec4-a92b-48a0-89bd-0ee4c7e413fd.png">

**Comment by cino** [comment]
Duplicate: https://github.com/ferdium/ferdium-recipes/issues/230
