### ISSUE TITLE
Bug: Cannot toggle "Include Pre-releases"

### ISSUE THREAD

**Issue by SpecialAro** [ferdium/ferdium-app#759]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.1-nightly.44

### What Operating System are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

Fresh installed Ferdium on a new machine using https://ferdium.org/download AutoSetup x64 or the latest nightly on GH and logged in to my Ferdium Server account.
At the `Settings` screen, on the `Updates` tab I should be able to toggle `Include Pre-releases`.

### Actual Behavior

Fresh installed Ferdium on a new machine using https://ferdium.org/download AutoSetup x64 or the latest nightly on GH and logged in to my Ferdium Server account.
At the `Settings` screen, on the `Updates` tab I'm not able to toggle `Include Pre-releases`.

This might be related to the typescript conversion we're making and with a misconfiguration of how the server handles my Profile.

### Steps to reproduce

1. Fresh install Ferdium
2. Go to `Settings`
3. Go to `Updates`
4. Try to toggle on `Include Pre-releases` (it stays off)

### Screenshots

![image](https://user-images.githubusercontent.com/37463445/201480079-8e030cff-ee2d-4838-b304-c0fe21878f0b.png)

**Comment by OskarEichler** [comment]
Same issue here, also not getting nightly updates anymore now so need to download and install manually.

**Comment by meiphoo7-Mae** [comment]
Also happening on Linux Appimage. I can't confirm however that it actually prevents nightly updates. I'm on nightly.46 which is the current one. Perhaps the switch doesn't reflect the current state but is still active somehow.

**Comment by vraravam** [comment]
This should be fixed by #750 . @SpecialAro - can you please verify and close?

**Comment by SpecialAro** [comment]
Yes! It is fixed. Forgot to close before... Thank you @vraravam 😄
