### ISSUE TITLE
Bug: Keyboard shortcut to back doesn't work

### ISSUE THREAD

**Issue by Stasky745** [ferdium/ferdium-app#760]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.0

### What Operating System are you using?

Other Linux

### Operating System Version

void linux 5.19.17_1

### What arch are you using?

x64

### Expected Behavior

Click `Ctrl+Left Arrow` and the page goes back.

### Actual Behavior

When you right click a page, the menu that pops up says `Back: Ctrl+Left Arrow`. If you click on this option, it goes back as intended, but using the `Ctrl+Left Arrow` on keyboard doesn't seem to work.

### Steps to reproduce

1. Go to LinkedIn
2. Open a link inside ferdium
3. Press `Ctrl+Left Arrow`
4. Nothing happens

**Comment by vraravam** [comment]
There are some services which capture the keyboard shortcuts, intercept them and perform their own actions. For eg, Discord does something similar. These cannot be overridden by Ferdium if so.

Are you sure focus is not within a text box?

**Comment by vraravam** [comment]
I have verified that this is working as expected. Each time the linkedin page loads, the focus is automatically shifted to the first text box (this seems to be behavior from LI, not us). Closing this ticket.
