### ISSUE TITLE
Feature: Make auto generation of system information for bug report

### ISSUE THREAD

**Issue by MurzNN** [ferdium/ferdium-app#77]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Now when creating a new bug report, users must fill manually the Ferdium version, operating system, architecture, etc, that's too annoying. 

### Proposed Solution

Good solution can be automate gathering this info in the app and copy it to clipboard, to easy paste it to the issue. And replace several separate fields in the bug filling form to the one textarea to paste the text.

For example, in "Help" menu we can create an item "Copy system information to clipboard" that will do the thing. 

### Alternatives Considered

Alternatively (or additionally) we can add "Copy system information" to the "About" window.

**Comment by vraravam** [comment]
Actually, all this information is available in the `About` dialog.
<img width="286" alt="Screenshot 2022-05-01 at 7 55 24 AM" src="https://user-images.githubusercontent.com/69629/166146951-c1fa78a5-074e-48d9-8a7b-c0b0f948761e.png">

(btw, at least on macos, the text in the above can be clicked, block-selected via the mouse, and copied to the clipboard using `Cmd+C` or even the right-click context-menu)

I have seen other electron apps where they implement a `Copy` button to paste into the bug report - but, that will still not solve the issue that there are multiple fields in the template fields - each one split and targeting a single attribute (eg: Ferdium version, OS, etc) in a single field.

In the current implementation, Ferdium uses a OS-native dialog for different OSes (I think some linux flavor). If we have to implement the `Copy` button, this needs to then be implemented as custom code or we could use something like [this](https://github.com/rhysd/electron-about-window) and ask for that author to implement such a `Copy` button functionality.

**Comment by vraravam** [comment]
The reason for the individual fields (even electron codebase has the same) is to be able to allow easier management of the tickets as they come - so that the volunteer contributors can effectively spend time after filtering. If everything is in a single textarea, that filteration is not possible. Sorry, we will not go back to a single textarea.

**Comment by MurzNN** [comment]
In "About" dialog on Linux (Kubuntu 22.04 with KDE), this text isn't selectable, so only can be screenshotted, that make filtering much more tricky :)
And if text will be copy-pastable in some standard form, it can be parsed via regexps to simplify and automate filtering of issues, and make it easier to report new issues without manually enter version information.

As example you can lookup VS Code About dialog, it looks like this:
![image](https://user-images.githubusercontent.com/336662/166157329-f9310cef-2ab4-4583-ba0a-cb980645f8e5.png)

**Comment by vraravam** [comment]
Yes, I was also referring to VS Code's `About` dialog. I think they have implemented it via custom code - not what the electron framework gives by default.

**Comment by MurzNN** [comment]
Hmm, what is the strange black hole is painted in top left corner of VS Code about window? :thinking:

**Comment by MurzNN** [comment]
Here https://github.com/lensapp/lens/pull/5335/files is the diff of how this feature is implemented in Lens, hope it can help with realization.
