### ISSUE TITLE
Bug: There are phantom notification badges in WhatsApp

### ISSUE THREAD

**Issue by SinTan1729** [ferdium/ferdium-app#774]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.0

### What Operating System are you using?

Other Linux

### Operating System Version

EndeavourOS

### What arch are you using?

x64

### Expected Behavior

There should be no notification badges when there are no notifications in WhatsApp.

### Actual Behavior

There are phantom badges even though there are no notifications/unread messages.

### Steps to reproduce

1. Add WhatsApp as a service.
2. Read all messages.

### Debug link

https://debug.ferdium.org/235f6518-8281-4292-9078-48878114cc42

### Screenshots

![Screenshot](https://user-images.githubusercontent.com/35728385/202208873-7f051a36-4cab-4a04-9c0b-7c534884572c.png)

**Comment by vraravam** [comment]
https://github.com/ferdium/ferdium-app/issues/773#issuecomment-1317077350
