### ISSUE TITLE
Bug: Mess in number of unread messages in Whatsapp

### ISSUE THREAD

**Issue by GitHub-Enrico** [ferdium/ferdium-app#776]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.0

### What Operating System are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

Ferdium shows the correct number of unread message in Whatsapp

### Actual Behavior

Ferdium shows a wrong number of unread message in Whatsapp. Also when no unread message are present, Ferdium shows that hundreds of messages are unread.

### Steps to reproduce

1. Look at the service icon in the screenshot above: no unread messages are present in the two Whatsapp accounts, but Ferdium shows 39 and 561 unread messages.

### Screenshots

![image](https://user-images.githubusercontent.com/118392140/202278443-83496725-ebbc-4476-a5f6-428e3345e6d8.png)

**Comment by SpecialAro** [comment]
https://github.com/ferdium/ferdium-app/issues/773#issuecomment-1317077350
