### ISSUE TITLE
Mastodon in Ferdium?

### ISSUE THREAD

**Issue by Andy-Kl** [ferdium/ferdium-app#779]
### Your issue

Hi, I hope I'm right here.
can I use Mastodon in Ferdium? What do I have to enter in "Team"?
Thanks for help

https://user-images.githubusercontent.com/8377249/202843983-1b551aeb-3c0b-4f52-8cb1-9c845f737eb6.mp4

**Comment by vraravam** [comment]
@Andy-Kl - such questions are better asked in the discord chat rooms. lets please not add noise into the issue tracker..

**Comment by zeorin** [comment]
FWIW I think this is a legit issue and we should re-open it, perhaps with the title "Mastodon Team field is unclear".

The fact that this UI is unclear (what is the "team" field for), is an issue. I landed here from a web search for "ferdium mastodon", which I searched for _because_ it's not clear what the field is for.

Had this question been answered here I would have been able to carry on with my day.

Even better, had this been recognized as a UI/UX issue and fixed I wouldn't have had to even search.

**Comment by vraravam** [comment]
@zeorin :
1. The "team" name came from among the earliest services supported ie Slack. Anyone who uses slack, would know what "team" stands for.
2. Our codebase does not support labels per-service. The labels / form fields are common - and are turned on based on what each service can do ie in this case the self-hosted nature.
3. As I mentioned, if there were questions about how to use / fill the form fields, its (imo) better to ask in the discord channels and get quick responses. We would like to keep the issue tracker in a lean state - to track bugs.
4. I disagree that this is a UI/UX issue based on point numbers 1 and 2.

We do welcome any contributions to fix either the documentation and/or the code to make this clearer.
