### ISSUE TITLE
Bug: "About" window crashes on snap package 

### ISSUE THREAD

**Issue by MurzNN** [ferdium/ferdium-app#78]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.20

### What Operating System are you using?

Ubuntu

### Operating System Version

Ubuntu 22.04

### What arch are you using?

x64

### Expected Behavior

When I choose menu item "Help » About Ferdium" - app should show the "About Ferdium" window.

### Actual Behavior

App instantly crashes with this output in console:
```
(ferdium:1407510): GdkPixbuf-WARNING **: 13:21:16.009: Cannot open pixbuf loader module file '/home/alexey_korepov/snap/ferdium/common/.cache/gdk-pixbuf-loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /home/alexey_korepov/snap/ferdium/common/.cache/gdk-pixbuf-loaders.cache
to make things work again for the time being.

(ferdium:1407510): GdkPixbuf-WARNING **: 13:21:16.009: Cannot open pixbuf loader module file '/home/alexey_korepov/snap/ferdium/common/.cache/gdk-pixbuf-loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /home/alexey_korepov/snap/ferdium/common/.cache/gdk-pixbuf-loaders.cache
to make things work again for the time being.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /snap/ferdium/3/data-dir/icons/Adwaita/48x48/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Aborted (core dumped)
```

### Steps to reproduce

1. Choose menu item "Help » About Ferdium"

**Comment by MurzNN** [comment]
In Ferdium, installed natively via deb packages - it works well without crash.

**Comment by NathanaelGandhi** [comment]
Initially, I was experiencing all the text not displaying correctly (squares), now it seems to work fine. 

Version: 6.0.0-nightly.24 snap --edge (Ubuntu 20.04 vm)

![image](https://user-images.githubusercontent.com/36506137/166483020-cd855a80-804f-4a34-8064-21f0cbf8fb6c.png)

**Comment by MurzNN** [comment]
Yeah, now it works well!
