### ISSUE TITLE
custom site does not save login data

### ISSUE THREAD

**Issue by rst-raphael** [ferdium/ferdium-app#780]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.0

### What Operating System are you using?

Windows

### Operating System Version

windows 11

### What arch are you using?

x64

### Last Known Working Ferdium version

6.2.0

### Expected Behavior

When configuring a custom website, the login data is not saved, being necessary to add it every time when opening Ferdium

### Actual Behavior

When setting up a custom website, login details are not saved.

### Steps to reproduce

1. Add a new service
2. Custom website
3. Add login data
4. Close Ferdium
5. When opening again, it is necessary to add the login data again

### Screenshots

![image](https://user-images.githubusercontent.com/61321277/202847933-14bd6d0b-c232-4533-a26e-f27d38a584da.png)
![image](https://user-images.githubusercontent.com/61321277/202847941-ef4d7a0b-8bfb-472f-9cb1-4f001eea7ea5.png)

**Comment by vraravam** [comment]
Please change the description to be in English - otherwise, the number of contributors who can help is drastically reduced.

**Comment by rst-raphael** [comment]
updated

**Comment by vraravam** [comment]
This is intended behavior, For custom sites, we do not save any data between restarts of Ferdium.
