### ISSUE TITLE
Bug: Tray icon not loaded in GNOME

### ISSUE THREAD

**Issue by zephyrus-ads** [ferdium/ferdium-app#781]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.1-beta.1

### What Operating System are you using?

Other Linux

### Operating System Version

Debian 11

### What arch are you using?

x64

### Expected Behavior

I would expect to see a ferdium tray icon in the system tray.

### Actual Behavior

Tray icon is not shown and loaded properly.
![Schermata del 2022-11-19 19-30-44](https://user-images.githubusercontent.com/88966497/202866182-f9600381-dea1-4c7f-b5e3-5c6f4c1129bf.png)

### Steps to reproduce

1. launch ferdium
2. look at system tray

**Comment by Alphrag** [comment]
Hi @zephyrus-ads how did you install Ferdium? I have no problems on my Debian 10 using Gnome.

**Comment by zephyrus-ads** [comment]
> Hi @zephyrus-ads how did you install Ferdium? I have no problems on my Debian 10 using Gnome.

Hi @Alphrag , just installed from snap source. The behavior was good up until the last update.

**Comment by zephyrus-ads** [comment]
It seems this behavior is only for snap package.

I've just remove it and install ferdium via deb package and the icon appeas in the tray icon.

**Comment by Alphrag** [comment]
Ah ok, thanks for letting us know, that is interesting. Maybe they changed something which means that we need to include the icon in another way. I'll have a look at it if I find the time.
