### ISSUE TITLE
Just tried most recently nightly and lost all services and no services load

### ISSUE THREAD

**Issue by ylluminate** [ferdium/ferdium-app#783]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.1-nightly.47

### What Operating System are you using?

macOS

### Operating System Version

12.6.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Ferdium version

6.2.1-nightly.46

### Expected Behavior

Services load that were already there + not see "Get started" button at startup.

### Actual Behavior

Error at bottom: "Could not load services and user information [Try again]" and "Get started" button in center. All of my services are gone.

### Steps to reproduce

Update and go.

### Screenshots

![image](https://p153.p0.n0.cdn.getcloudapp.com/items/rRu5qLYY/6b8085ba-b90a-4387-b421-1d1042ee737a.png?v=844d4268a1e14212f1bbbddeacd04c2b)

**Comment by vraravam** [comment]
Not sure which version you upgraded from. Many of us are running nightly 47 without issues. Please quit Ferdium completely, and retry a few times?

**Comment by SpecialAro** [comment]
Also, @ylluminate which Server are you using? Can you post a screenshot of the about window?

**Comment by ylluminate** [comment]
I upgraded from .46 due. I did kill all Ferdium processes (in macOS I went into Activity Monitor.app and then filtered based on "ferdi" and ran Force Quit on them all simultaneously.

Not using a server.

About box copied:
```
Version: 6.2.1-nightly.47
Server: No Server
Electron: 21.3.0
Chrome: 106.0.5249.181
Node.js: 16.16.0
Platform: macOS Monterey
Arch: arm64
Build date: Sat Nov 19 2022 20:11:42 GMT-0500 (Eastern Standard Time)
Git SHA: 7b4c0041
Git branch: nightly
```

Just no luck at all getting it to come back - went back two versions and then stepped back to this again upon reading your comments here above. Here's the screenshot again with the about box:
![image](https://p153.p0.n0.cdn.getcloudapp.com/items/E0uRWqDZ/ddc3b660-8b03-43e5-9f8c-eeafdab2c352.png?v=c854343e4ccdc71fd3b99de362c8ec7b)

**Comment by ylluminate** [comment]
Execution from shell yields the following:
```
$ /Applications/Ferdium.app/Contents/MacOS/Ferdium
objc[43156]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x2106a5b50) and /Applications/Ferdium.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x107396978). One of the two will be used. Which one is undefined.
[MobX] Since strict-mode is enabled, changing (observed) observable values without using an action is not allowed. Tried to modify: Settings@10.store
Ferdium Migration:  🧙‍  Running database migration wizard
info: serving app on http://localhost:46569
Ferdium Migration:  🔧  Nothing to migrate, already on the newest version
Checking for update
```

**Comment by ylluminate** [comment]
Updated to today's nightly .48 and everything seems to be resolved...
