### ISSUE TITLE
Bug: WhatsApp Notification Icon Showing Millions of Notification

### ISSUE THREAD

**Issue by 8227846265** [ferdium/ferdium-app#784]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.0

### What Operating System are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Last Known Working Ferdium version

6.2.0

### Expected Behavior

Notification dot work properly

### Actual Behavior

Notification is messed up

### Steps to reproduce

1. Just add WhatsApp
2. Login
3. Notification dot will become messed up

### Debug link

https://debug.ferdium.org/4b161ea7-6e64-416e-9366-9add1e3a9c07

### Screenshots

![image](https://user-images.githubusercontent.com/66582769/202890772-ae1006a6-1b6c-4d7a-ad49-c9bd5cf7c159.png)

**Comment by 8227846265** [comment]
Note
- The behavior of the notification dot is whenever you open a new chat message. The value of the total notification changes.

**Comment by Latschenharry** [comment]
![image](https://user-images.githubusercontent.com/12736979/202893651-25607927-8fc7-4684-95de-6de125d3881d.png)

Please search for the issue first. Its even pinned as the first issue

**Comment by vraravam** [comment]
Its VERY IRRITATING for those of us contributors when folks just dont search properly!
