### ISSUE TITLE
Bug: No discord talk sound at all in Arch linux.

### ISSUE THREAD

**Issue by Samueru-sama** [ferdium/ferdium-app#787]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.0

### What Operating System are you using?

Other Linux

### Operating System Version

Arch Linux Kernel 6.0.9

### What arch are you using?

x64

### Expected Behavior

For audio during calls to just work.

### Actual Behavior

Discord chat notification sounds for, however starting a call results in my microphone not working nor I can't listen to anything said by others, if I go to the voice and video setting in discord, I can see that the mic test volume bar is moving when I talk, but I can't hear anything either, I already tried all the input and output device options available with no result.

### Steps to reproduce

Open Ferdium, add the discord service and start a call.

### Additional information

I think that the issue is that with ferdium discord fails to create a WEBRTC VoiceEngine in pulseaudio, if I use the discord app instead, all the sounds come from a ''chromiun'' application just like in Ferdium, however calls actually create their own application named WEBRTC VoiceEngine and that's were all the voice conversation goes instead of the chromium one.

**Comment by SpecialAro** [comment]
Hello @Samueru-sama, thank you for logging this issue.

Have you tried changing the WebRTC IP settings in the Privacy tab of Ferdium settings, as described in https://github.com/ferdium/ferdium-app/issues/611#issuecomment-1263271328 ?

Thank you.

**Comment by Samueru-sama** [comment]
> Hello @Samueru-sama, thank you for logging this issue.
> 
> Have you tried changing the WebRTC IP settings in the Privacy tab of Ferdium settings, as described in [#611 (comment)](https://github.com/ferdium/ferdium-app/issues/611#issuecomment-1263271328) ?
> 
> Thank you.

Yes that was the issue, thanks a lot for the speedy reply.
