### ISSUE TITLE
Feature: add Simplified Chinese

### ISSUE THREAD

**Issue by SuperLangdon** [ferdium/ferdium-app#791]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

It looks like there are some issues that prevent all two (or three) variants of Chinese from being added to Ferdium, and I'm a native Chinese user, so I'd like to know the current work in progress, and what I can do about it?

### Proposed Solution

If it's a translation issue, I can take on the translation work for the next. 
If it's a problem involving Chinese variants, I can also help.

### Alternatives Considered

Please see above, and forgive my shallow technical knowledge please :).

**Comment by vraravam** [comment]
Thanks for your offer!
We accept all translations via contributions into https://crowdin.com/project/ferdium-app - would that be the route that your contribution also take? If so, please close this ticket. If it requires code changes (I would be surprised if that's the case, then we can discuss as part of this ticket)

**Comment by SuperLangdon** [comment]
> Thanks for your offer! We accept all translations via contributions into https://crowdin.com/project/ferdium-app - would that be the route that your contribution also take? If so, please close this ticket. If it requires code changes (I would be surprised if that's the case, then we can discuss as part of this ticket)

but looks like

**Comment by SuperLangdon** [comment]
> Thanks for your offer! We accept all translations via contributions into https://crowdin.com/project/ferdium-app - would that be the route that your contribution also take? If so, please close this ticket. If it requires code changes (I would be surprised if that's the case, then we can discuss as part of this ticket)

Thank you, I have requested to join the translation project in crowdin.
But it looks like Simplified Chinese has 41% translation progress, which is much larger than the 27% progress of Traditional Chinese which has been added to the client now, so why is Simplified Chinese not added to the client?
As for the code changes, I saw issue #185 and it looks like Simplified Chinese has not been added to the client after that, so I'm not sure if it has been fixed.

**Comment by vraravam** [comment]
I'm not a Chinese speaker, so could you please show me where you see that Simplified Chinese is at 41% vs Traditional chinese is at 27%? Is it the presence/absence of specific i18n files that are packaged into the application? Or is it that these are not even present in the GH repo itself?
btw, all the locales supported by Ferdium can be found here: https://github.com/ferdium/ferdium-app/tree/develop/src/i18n/locales

**Comment by SuperLangdon** [comment]
> I'm not a Chinese speaker, so could you please show me where you see that Simplified Chinese is at 41% vs Traditional chinese is at 27%? Is it the presence/absence of specific i18n files that are packaged into the application? Or is it that these are not even present in the GH repo itself?

> 

https://github.com/ferdium/ferdium-app/blob/develop/src/i18n/locales/zh-HANS.json
It looks like this is the language file for Simplified Chinese.

https://crowdin.com/project/ferdium-app
It looks like Simplified Chinese is 41% progress in translation.

**Comment by SuperLangdon** [comment]
> I'm not a Chinese speaker, so could you please show me where you see that Simplified Chinese is at 41% vs Traditional chinese is at 27%? Is it the presence/absence of specific i18n files that are packaged into the application? Or is it that these are not even present in the GH repo itself? btw, all the locales supported by Ferdium can be found here: https://github.com/ferdium/ferdium-app/tree/develop/src/i18n/locales

yep, I saw that and intend to complete the Chinese translation to 100% :)

**Comment by SuperLangdon** [comment]
<img width="671" alt="Snipaste_2022-11-23_13-06-22" src="https://user-images.githubusercontent.com/21187253/203472609-2768b416-7e43-4698-b77c-b34ee905850a.png">
But looks like Simplified Chinese (zh-hans) has not been added to the language options.

The only two "Chinese" options should be ZH-HANT and ZH-TW.

**Comment by vraravam** [comment]
That list is populated from: https://github.com/ferdium/ferdium-app/blob/develop/src/i18n/languages.ts
