### ISSUE TITLE
Bug: Cannot reposition Ferdium window on macOS

### ISSUE THREAD

**Issue by j7e** [ferdium/ferdium-app#793]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.0

### What Operating System are you using?

macOS

### Operating System Version

macOS Big Sur 11.7.1

### What arch are you using?

x64

### Expected Behavior

Clicking and dragging Ferdium's title bar would move and allow me to reposition the window frame.

### Actual Behavior

Ferdium is unresponsive to clicking and dragging the title bar, keeping the application window in its position (top-left corner of the Finder desktop).

### Steps to reproduce

1. Install Ferdium to the Applications folder.
2. Confirm permissions requests for microphone, webcam and screensharing.
3. Attempt to reposition the application window by clicking and dragging its title bar.

### Debug link

https://debug.ferdium.org/0107a5aa-5cb6-436b-848e-0d3c4594d95e

### Screenshots

![2022-11-23 10-28-43 2022-11-23 10_29_29](https://user-images.githubusercontent.com/43884657/203526073-b846d8ea-2220-438a-849c-a22b265c949e.gif)

**Comment by vraravam** [comment]
Fixed in https://github.com/ferdium/ferdium-app/pull/372 - please set the draggable area in your settings screen.
