### ISSUE TITLE
Bug: WhatsApp not loading on latest Nightly build

### ISSUE THREAD

**Issue by OskarEichler** [ferdium/ferdium-app#795]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.1-nightly.50

### What Operating System are you using?

macOS

### Operating System Version

macOS Ventura 13.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Ferdium version

6.2.1-nightly.49

### Expected Behavior

WhatsApp is stuck on loading screen

### Actual Behavior

WhatsApp should load

### Steps to reproduce

Try to load Whatsapp 

### Screenshots

![Screenshot 2022-11-24 at 15 41 51](https://user-images.githubusercontent.com/62393985/203722674-2eb5cab2-d286-4c85-9348-aedc1d277696.jpg)

### Additional information

Not sure if local problem just for me, or related to WhatsApp recipe or Ferdium. It was working until I updated earlier today.

**Comment by OskarEichler** [comment]
I deleted the service and create a new one and now it is stuck trying to load the QR code... seems like it can't connect! All other services work without any issues.

![Screenshot 2022-11-24 at 16 02 45](https://user-images.githubusercontent.com/62393985/203726535-8326245a-6cce-4a0d-b57f-7024438b4b91.jpg)

**Comment by warrendt** [comment]
Same happening with me

**Comment by JonLev** [comment]
This is definitively coming from a WhatsApp change, I tried other All-messaging-in-one app and the issue is the same. I sometimes have a message to update chrome, not sure if this is related.

**Comment by eitchtee** [comment]
Downgrading to 6.2.1-nightly.49 did not solve this issue. So probably not related to the latest nightly.

**Comment by gabriel-andreescu** [comment]
I'm on the stable release and this started happening to me now, after clicking the "update whatsapp" inside the service window.

**Comment by Systemedic** [comment]
I had this issue to. Deleted the app, deleted the files in appdata and installed the stable version. Problemn solved.

**Comment by carlosala** [comment]
It's fixed on [this commit](https://github.com/ferdium/ferdium-recipes/commit/79f531aca517b3e5d507d8709d47aa7f9a37359b), it's a matter of time for them to release the new version!

**Comment by starchild** [comment]
same issue here, awaiting nightly update

**Comment by vraravam** [comment]
Please try the latest [nightly 51](https://github.com/ferdium/ferdium-app/releases/tag/v6.2.1-nightly.51) and report back if the issue has been resolved. Thanks for trying Ferdium!

**Comment by OskarEichler** [comment]
Yep all working again - thanks so much for the quick resolution! Way to go team Ferdium!! ❤️

**Comment by starchild** [comment]
!! this nightly build completely breaks it for me - all services gone and won't allow me to add them back

"Could not load services and user information"

**Comment by JMVS** [comment]
> It's fixed on [this commit](https://github.com/ferdium/ferdium-recipes/commit/79f531aca517b3e5d507d8709d47aa7f9a37359b), it's a matter of time for them to release the new version!

Version: 6.2.0
Server: No Server
Electron: 20.2.0
Chrome: 104.0.5112.124
Node.js: 16.15.0
Platform: Windows 10
Arch: x64
Build date: Thu Sep 22 2022 14:13:21 GMT-0300 (hora estándar de Argentina)
Git SHA: 84613b5b
Git branch: release

I was having the same issue, updating package.json and webview.js with the new versions solved the issue!

You can modify these files of that recipe by hand (right-click on whatsapp then Edit -> Open user.js to get to the appropriate location if you don't know where that is).

https://github.com/ferdium/ferdium-recipes/blob/main/recipes/whatsapp/package.json
https://github.com/ferdium/ferdium-recipes/blob/main/recipes/whatsapp/webview.js

**Comment by JonLev** [comment]
Worked for me, thanks !

**Comment by tiagonunocosta** [comment]
A style have the problem in this version 

Version: 6.2.4-nightly.3
Server: Ferdium Server
Electron: 21.3.3
Chrome: 106.0.5249.199
Node.js: 16.16.0
Platform: macOS
Arch: arm64
Build date: Tue Jan 03 2023 00:57:38 GMT+0000 (Western European Standard Time)
Git SHA: 5b53ce20
Git branch: nightly

Can you yelp me please !!!!!!

![image](https://user-images.githubusercontent.com/17408764/210674930-4f9605b4-c52a-49a5-8f56-921e7bfb12f2.png)

**Comment by seiferflo** [comment]
> I deleted the service and create a new one and now it is stuck trying to load the QR code... seems like it can't connect! All other services work without any issues.
> 


Hi Same problem with fresh installation. QR Code doesn't load on first install of recipe, then I get the grey screen of whatsapp which never loads. No problem with any other application or whatsapp on my good old Ferdi.
