### ISSUE TITLE
Save skype image

### ISSUE THREAD

**Issue by rst-raphael** [ferdium/ferdium-app#796]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.0

### What Operating System are you using?

Windows

### Operating System Version

windows 11

### What arch are you using?

x64

### Last Known Working Ferdium version

6.2.0

### Expected Behavior

When receiving an image via skype, when clicking the right button, there is no option to download or save the file.

### Actual Behavior

When receiving an image via skype, when clicking the right button, there is no option to download or save the file, only open it in a new tab or forward it.

### Steps to reproduce

1 - Open a skype conversation
2 - Receive an image
3 - Right click to download or save

### Screenshots

![image](https://user-images.githubusercontent.com/61321277/203773347-db51e4d3-c525-4439-888c-18c6c5685bd9.png)

**Comment by schwixxer** [comment]
I have the same problem.

**Comment by vraravam** [comment]
That context menu is not something that we have injected. This must be default  behavior from skype. Have you tried this in a normal browser? If so, what's the behavior there?

**Comment by rst-raphael** [comment]
Acabei de testar! O comportamento no navegador é o mesmo, não tem opção para baixar. :(

**Comment by SpecialAro** [comment]
> Acabei de testar! O comportamento no navegador é o mesmo, não tem opção para baixar. :(

This translates to:
"I just tested it! The behaviour is the same with a browser, there is no option to download. :("

Therefore, I'm closing this issue since it doesn't have nothing to do with Ferdium.
