### ISSUE TITLE
Bug: Telegram Not Loading

### ISSUE THREAD

**Issue by mizzpenny** [ferdium/ferdium-app#801]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.1-nightly.52

### What Operating System are you using?

Windows

### Operating System Version

Windows 11 Education Version	22H2 Installed on	‎11/‎25/‎2022 OS build	22621.819 Experience	Windows Feature Experience Pack 1000.22636.1000.0

### What arch are you using?

x64

### Last Known Working Ferdium version

Can't remember

### Expected Behavior

Telegram to load when service is added

### Actual Behavior

Telegram does not load, has a spinning "Loading Telegram" box and then the page is white/blank

### Steps to reproduce

1. Service==>Add available services ==> Telegram
2.  Click enabled service==>Save Service
3. Telegram icon loaded, stuck on "Loading Telegram" and then white blank page

### Screenshots

![image](https://user-images.githubusercontent.com/21247675/204101117-9acf5e04-b515-4d15-9117-dcce71052fc9.png)

### Additional information

This was first noted 2-3 weeks ago on my OLD desktop via portable version, it was working and just randomly stopped working. I attributed this to desktop being old and other programs haven't fully been working lately.

On my New desktop, So far installed all the Windows update, Bitdefender, MS office, Chrome and then do a Ferdium Windows autosetup 6.2.1. nightly 52 x64 build.  Within Ferdium, I clicked "use Ferdirum without an account", and then start adding services and noticed this about Telegram. 

Tried clearing Cache per issue #553 . I can't figure out how to switch between  Telegram K andt Z per #553 as I only see 1 telegram service. I've tried adding a custom website and direct to both https://webz.telegram.org/ and https://webk.telegram.org/, which both yields the same blank page. Both websites loads in Chrome.

update: Was able to create a custom website for Telegram Z. The way I did it was to create a custom website with URL google.com, and then I typed in the webz link above. However, the QR code does not load
![image](https://user-images.githubusercontent.com/21247675/204104266-da135a55-9dc5-4960-b3ec-7f091c1ec28a.png).

Tried the same approach with Telegram K, and it's a blank page 
![image](https://user-images.githubusercontent.com/21247675/204104285-a1ae8a3f-3c55-47ce-82e9-3bf24fc37d55.png)

From reading issue #584, I have deleted the appdata within the Ferdium folder to have started  "Fresh" and just added the telegram service only. Still same issue.

**Comment by meiphoo7-Mae** [comment]
For the developers:
Same problem on Linux (Ubuntu 22). Reloading the service however does the trick.

And as a helpful gesture to a fellow user:
In the Telegram service you'll a 'hamburger' menu (3 horizontal lines) top left next to the search bar. If you click on it you'll see a drop down menu with new options including the possibility to switch to other Telegram services (in my case K and old because I use Z).

**Comment by mizzpenny** [comment]
> For the developers: Same problem on Linux (Ubuntu 22). Reloading the service however does the trick.
> 
> And as a helpful gesture to a fellow user: In the Telegram service you'll a 'hamburger' menu (3 horizontal lines) top left next to the search bar. If you click on it you'll see a drop down menu with new options including the possibility to switch to other Telegram services (in my case K and old because I use Z).

Thanks for replying, I don't see the 3 hamburger lines at all in my Ferdium. Definitely did try reloading (right click on telegram and hit reload), no change

![image](https://user-images.githubusercontent.com/21247675/204161996-68749ec6-f795-4cd8-a1c2-d0ed7fbf2539.png)
![image](https://user-images.githubusercontent.com/21247675/204162009-d021c75c-ea6f-498f-88fb-6d210a316f82.png)

**Comment by SpecialAro** [comment]
The hamburger is inside the Telegram app
<img width="427" alt="image" src="https://user-images.githubusercontent.com/37463445/204171501-8030d6d4-f8c1-416d-bef0-7b145b38574e.png">

I was not able to reproduce this issue on 6.2.1-beta.2 with macOS.

**Comment by vraravam** [comment]
Unable to reproduce. also, as @meiphoo7-Mae has commented, this seems to be worked around by reloading the service.

**Comment by gnought** [comment]
In my case, the root clause web.telegram.org can't be reached when it is resolved as IPv6 address. There is no SSL certificate returned by `openssl s_client -connect '[2001:67c:4e8:f004::9]:443'`

**Comment by z3t4m4n** [comment]
> In my case, the root clause web.telegram.org can't be reached when it is resolved as IPv6 address. There is no SSL certificate returned by `openssl s_client -connect '[2001:67c:4e8:f004::9]:443'`

If I remove ipv6 public address and default route from the interface the telegram service works again, this issue doesn't happen with flatpak's telegram standalone client (org.telegram.desktop).

(Ubuntu 23.10)
