### ISSUE TITLE
Bug: Display service name under the icon toggle always shows as disabled

### ISSUE THREAD

**Issue by meiphoo7-Mae** [ferdium/ferdium-app#804]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.1-nightly.53

### What Operating System are you using?

Ubuntu

### Operating System Version

Ubuntu 22

### What arch are you using?

x64

### Last Known Working Ferdium version

I didn't test this toggle before so I don't know

### Expected Behavior

The toggle should visually reflect its actual state:
Service names not shown -> Toggle left (disabled)
Service names shown -> Toggle right (enabled)

### Actual Behavior

The toggle is frozen in the disabled state. However clicking on it indeed toggles whether service names are shown or not shown so the toggle is functional sound but only visually wrong. I think this could be something similar as bug #759.

### Steps to reproduce

Go to Services > Service Icons Settings
Click the toggle Display service name under the icon repeatedly and see the service names appear and disappear while the toggle itself remains in the disabled state.

### Additional information

I checked the toggles because of the changes made in nightly.53. I did not check this particular toggle before so I don't know if this problem is new to nightly.53 or that it also occurred in earlier nightlies.

**Comment by Alphrag** [comment]
Oh, well spotted :eyes: There is indeed a `type: 'checkbox'` missing on the [edit settings file](https://github.com/cino/ferdium-app/blob/b0c6c0340755b87d288733917cc3fb1b24b2ae5c/src/containers/settings/EditSettingsScreen.tsx#L855) :slightly_smiling_face:

**Comment by ghost** [comment]
yes updating it will push that oneline

**Comment by ghost** [comment]
@Alphrag, if you are available, can you review merge and test!
i tested in local :)

**Comment by vraravam** [comment]
Closing as fixed in the upcoming 6.2.1-nightly.54
