### ISSUE TITLE
Custom service based on IP address doesn't work

### ISSUE THREAD

**Issue by zgrummedical** [ferdium/ferdium-app#812]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.1

### What Operating System are you using?

Windows

### Operating System Version

Windows 10 version

### What arch are you using?

x64

### Last Known Working Ferdium version

none

### Expected Behavior

Custom Website service - using as the address a local IP address - such as NAS etc does not load. 

### Actual Behavior

blank screen

### Steps to reproduce

1. Add Custom Web Site
2.  Enter local IP address such as https://192.168.20.55:5001/
3. 3. save and click on the service
4. Blank screen

### Debug link

{"host":{"platform":"win32","release":"10.0.19045","screens":[{"id":2779098405,"bounds":{"x":3072,"y":0,"width":3072,"height":1728},"workArea":{"x":3072,"y":0,"width":2938,"height":1688},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:SRGB, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":3072,"height":1728},"displayFrequency":60,"workAreaSize":{"width":2938,"height":1688},"scaleFactor":1.25,"rotation":0,"internal":false,"touchSupport":"unknown"},{"id":2528732444,"bounds":{"x":0,"y":0,"width":3072,"height":1728},"workArea":{"x":0,"y":0,"width":3072,"height":1688},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:SRGB, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":3072,"height":1728},"displayFrequency":60,"workAreaSize":{"width":3072,"height":1688},"scaleFactor":1.25,"rotation":0,"internal":false,"touchSupport":"unknown"}]},"ferdium":{"version":"6.2.1","electron":"21.3.1","installedRecipes":[{"id":"android-messages","version":"2.3.1"},{"id":"basecamp","version":"1.2.0"},{"id":"canvas","version":"1.1.0"},{"id":"clubhouse","version":"1.2.0"},{"id":"discord","version":"1.7.9"},{"id":"franz-custom-website","version":"1.3.0"},{"id":"gmail","version":"1.5.1"},{"id":"google-contacts","version":"1.3.0"},{"id":"google-duo","version":"1.1.0"},{"id":"google-voice","version":"0.5.0"},{"id":"googlekeep","version":"1.3.0"},{"id":"home-assistant","version":"1.0.1"},{"id":"iCloud","version":"1.3.0"},{"id":"instagram","version":"2.4.1"},{"id":"lastpass","version":"2.3.0"},{"id":"linkedin","version":"1.4.0"},{"id":"messenger","version":"1.7.6"},{"id":"office365-owa","version":"1.6.2"},{"id":"onenote","version":"1.3.0"},{"id":"pomodoro-tracker","version":"1.3.0"},{"id":"skype","version":"3.5.3"},{"id":"telegram","version":"3.3.5"},{"id":"trello","version":"1.3.0"},{"id":"twitter","version":"1.3.0"},{"id":"udemy","version":"1.1.0"},{"id":"wechat","version":"1.2.0"},{"id":"whatsapp","version":"3.4.8"},{"id":"wire","version":"1.1.0"},{"id":"youtube","version":"1.2.0"},{"id":"zoom","version":"1.3.5"},{}],"devRecipes":[],"services":[{"id":"816a4804-3700-4bc7-ae7d-d41cfec41737","recipe":"telegram","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true,"isProgressbarEnabled":false},{"id":"b3f30dbe-d7bb-454d-8d88-7ca6fd8c263a","recipe":"whatsapp","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true,"isProgressbarEnabled":false},{"id":"f8a6f001-180a-4a4f-857f-1d44892aa274","recipe":"franz-custom-website","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"f63eec0e-6cbe-4b14-a451-26461826fcd6","recipe":"franz-custom-website","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"a00611b5-9d1e-4b01-bc02-8ac85f6d58b3","recipe":"franz-custom-website","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"6f20eda5-2659-45ee-8797-87eba6f220cd","recipe":"franz-custom-website","isAttached":true,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"c5cdd87b-714d-4716-8122-1ffd0f0ecad9","recipe":"franz-custom-website","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"e0187687-092c-47e1-ae8e-f9e862418b98","recipe":"udemy","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"b452be84-f232-4b3b-9a6f-b6fd59f3978e","recipe":"google-duo","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"6b98ba93-eb8d-4778-b74b-ce3560047c38","recipe":"skype","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"c1db063a-284e-4c85-b1bb-cfbda863af3e","recipe":"twitter","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"2654254a-e3f1-4a30-a758-c8da79cca04c","recipe":"wechat","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"ab9e1257-1d8a-4ba2-bd52-87cdb34983ba","recipe":"youtube","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"6d202300-41a4-4025-a1ce-d56c67c758a2","recipe":"android-messages","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"e5333530-2e87-40c3-aaea-e32ee435d945","recipe":"pomodoro-tracker","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"7b34020b-b245-43ae-8e79-f60521045cff","recipe":"android-messages","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"efd3732f-3c2d-4b98-a609-6207b09cde4e","recipe":"google-voice","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"f6d3845a-0033-47d0-a68a-8c87941d3604","recipe":"google-voice","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"0ab3fa02-e46c-4dfe-8a14-84abb276c857","recipe":"google-voice","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"0d8b158b-0319-453b-9eeb-5b39561b05db","recipe":"google-voice","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"716fd314-6156-4fdd-b0d6-16571825a3fe","recipe":"google-voice","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"93ef0ec6-dadf-43e6-a4f6-72d546c4b3c2","recipe":"google-voice","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true,"isProgressbarEnabled":true},{"id":"a846b2b7-a00b-4c23-8e4a-3452d0f6ea4b","recipe":"franz-custom-website","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"62c1f666-cce5-4e7b-9007-6c34b023c982","recipe":"franz-custom-website","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"3536a1e7-69da-4a5b-9687-5f42dbdb5f73","recipe":"franz-custom-website","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"4114c65a-c7a5-44f4-a836-c947fc30f592","recipe":"franz-custom-website","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"00d8f6e6-2040-46a6-839d-579553f37e97","recipe":"franz-custom-website","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"2a777fed-ba27-4b4a-9228-4a765a75ed5a","recipe":"franz-custom-website","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"8310ae6f-3030-4b78-b0ef-9e65324d3401","recipe":"gmail","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"cd6b4925-5a01-45eb-914f-b412d376013a","recipe":"gmail","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"1c8d4b8b-6bcf-4d4d-aa75-611024440dcf","recipe":"gmail","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"93f20b06-2522-4d1e-a59e-4b517a54ba63","recipe":"gmail","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"cad5616e-a420-4369-bffa-04d6e6e0027a","recipe":"franz-custom-website","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"ea55dd7e-56c3-40f1-bab6-b7a02e866024","recipe":"franz-custom-website","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true,"isProgressbarEnabled":false},{"id":"79695be7-609a-4eaf-b11f-e974ef761759","recipe":"franz-custom-website","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"14aea26d-e4e6-4d6e-906a-6a4066c8a0c0","recipe":"franz-custom-website","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"25b4f8e9-c29f-4d1d-89a9-5a09b9ec8e58","recipe":"franz-custom-website","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"2d49e110-b318-4607-ba3d-6fffa099ed30","recipe":"franz-custom-website","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"e15115ea-8be7-444e-b952-72b8040e8916","recipe":"franz-custom-website","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"5931b19a-8800-4e07-b8b2-50f553fa60a2","recipe":"franz-custom-website","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"4315b331-fdef-4b02-b2b4-4632d367df48","recipe":"whatsapp","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true,"isProgressbarEnabled":true},{"id":"883c0d52-1ba6-4abe-9811-3825951b3db0","recipe":"telegram","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"52a5715c-7c58-4050-9277-67c7eca4bd59","recipe":"messenger","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"85e36897-74ae-4400-9f06-0e9159eea507","recipe":"discord","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"47aa9a7c-bb92-4d6c-8233-3be5f2ceb57d","recipe":"trello","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"819fd6ac-cc54-4f16-99cb-3090586f76ea","recipe":"wire","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"66e6c0c6-8cb0-45fa-a736-dc2608dd0b37","recipe":"basecamp","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"879b9a3e-4702-4bd5-9f97-9a5b27891e6a","recipe":"gmail","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"6b8d33e7-d207-4dcc-b51b-e94d45bfdacc","recipe":"googlekeep","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"70d87cd0-cbdc-4801-955a-4d3bf2def6cf","recipe":"home-assistant","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true,"isProgressbarEnabled":false},{"id":"99644caf-3c46-4052-a478-6c967eff9ae1","recipe":"instagram","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"2eb840f3-6ce6-4f7a-a4c0-4dd3c417296d","recipe":"onenote","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"581c9a45-849f-4a1b-9f75-ec17f103a77d","recipe":"twitter","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"5dcd2a74-2939-40ac-95d1-7d6359a63ada","recipe":"zoom","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"ea30ab4d-990c-4748-9df1-09145afd7da4","recipe":"trello","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":"","isProgressbarEnabled":false},{"id":"7b460507-9541-4dfc-8069-a6050cd3f44f","recipe":"whatsapp","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":"","isProgressbarEnabled":false},{"id":"e02bb5e4-d57e-4c92-a7df-f24498d66289","recipe":"telegram","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":"","isProgressbarEnabled":false},{"id":"d53e39d9-bad3-4b5d-8ec9-123ec932f053","recipe":"discord","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":"","isProgressbarEnabled":false},{"id":"bc0a09b0-26f4-4921-bfa7-9a0ed44a4c75","recipe":"wire","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":"","isProgressbarEnabled":false},{"id":"b0d30c3f-2963-408a-a189-926b89fb7874","recipe":"basecamp","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":"","isProgressbarEnabled":false},{"id":"191773d1-9207-4baa-a00a-2b0c3441812f","recipe":"gmail","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":"","isProgressbarEnabled":false},{"id":"7a559871-a75f-45d2-95c4-e192e5b28a9d","recipe":"iCloud","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":"","isProgressbarEnabled":false},{"id":"0a526fce-11b2-4a4e-99ae-49c0df2f3647","recipe":"lastpass","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":true},{"id":"602a089c-4ab6-410b-9bd0-9d3b5bc93126","recipe":"linkedin","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":"","isProgressbarEnabled":false},{"id":"8eb1adbe-6c10-4a84-9003-dd0115fce98b","recipe":"instagram","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":"","isProgressbarEnabled":false},{"id":"b08e0837-c677-466d-9a7b-063e84ed73df","recipe":"onenote","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":"","isProgressbarEnabled":false},{"id":"59c30981-73f0-4ce8-9520-0d1cbea68125","recipe":"twitter","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":"","isProgressbarEnabled":false},{"id":"25d3a35b-ddef-49b0-bd0c-7c3a4bb0c005","recipe":"zoom","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":"","isProgressbarEnabled":false},{"id":"bfe3ace2-fd7a-476a-b13f-5f9aadeaf656","recipe":"office365-owa","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true,"isProgressbarEnabled":true},{"id":"df2c268b-9598-4c71-8a48-9623eb0eb3be","recipe":"google-contacts","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false}],"messages":[{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getInfo"},"error":{},"response":{},"server":"https://api.ferdium.org"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"https://api.ferdium.org"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"https://api.ferdium.org"},{"type":"error","info":["error","Warning: Failed setTodosWebview type: The setTodosWebview `webview` is marked as required in `<<anonymous>>`, but its value is `undefined`."]},{"type":"error","info":["error",{"isTrusted":true}]},{"type":"error","info":["error",{"isTrusted":true}]},{"type":"error","info":["error",{"isTrusted":true}]},{"type":"error","info":["error",{"isTrusted":true}]},{"type":"error","info":["error",{"isTrusted":true}]},{"type":"error","info":["error",{"isTrusted":true}]},{"type":"error","info":["error",{"isTrusted":true}]},{"type":"error","info":["error",{"isTrusted":true}]},{"type":"error","info":["error",{"isTrusted":true}]},{"type":"error","info":["error",{"isTrusted":true}]},{"type":"error","info":["error",{"isTrusted":true}]},{"type":"error","info":["error",{"isTrusted":true}]},{"type":"error","info":["error",{"isTrusted":true}]},{"type":"error","info":["error",{"isTrusted":true}]},{"type":"error","info":["error",{"isTrusted":true}]},{"type":"error","info":["error",{"isTrusted":true}]},{"type":"error","info":["error",{"isTrusted":true}]},{"type":"error","info":["error",{"isTrusted":true}]},{"type":"error","info":["error",{"isTrusted":true}]},{"type":"error","info":["error",{"isTrusted":true}]}],"workspaces":[{"id":"feba3c35-96e4-4971-a93a-180c2f3a0451","services":["883c0d52-1ba6-4abe-9811-3825951b3db0","4315b331-fdef-4b02-b2b4-4632d367df48","c5cdd87b-714d-4716-8122-1ffd0f0ecad9","7b34020b-b245-43ae-8e79-f60521045cff","70d87cd0-cbdc-4801-955a-4d3bf2def6cf","52a5715c-7c58-4050-9277-67c7eca4bd59","819fd6ac-cc54-4f16-99cb-3090586f76ea","0a526fce-11b2-4a4e-99ae-49c0df2f3647","602a089c-4ab6-410b-9bd0-9d3b5bc93126"]},{"id":"04628c98-c4f8-4fa5-93e1-fbb3b86b44a0","services":["e5333530-2e87-40c3-aaea-e32ee435d945","816a4804-3700-4bc7-ae7d-d41cfec41737","b3f30dbe-d7bb-454d-8d88-7ca6fd8c263a","47aa9a7c-bb92-4d6c-8233-3be5f2ceb57d","6b8d33e7-d207-4dcc-b51b-e94d45bfdacc","25b4f8e9-c29f-4d1d-89a9-5a09b9ec8e58","6d202300-41a4-4025-a1ce-d56c67c758a2","b08e0837-c677-466d-9a7b-063e84ed73df","5931b19a-8800-4e07-b8b2-50f553fa60a2","2eb840f3-6ce6-4f7a-a4c0-4dd3c417296d","602a089c-4ab6-410b-9bd0-9d3b5bc93126","ea55dd7e-56c3-40f1-bab6-b7a02e866024","5dcd2a74-2939-40ac-95d1-7d6359a63ada","bfe3ace2-fd7a-476a-b13f-5f9aadeaf656","879b9a3e-4702-4bd5-9f97-9a5b27891e6a","70d87cd0-cbdc-4801-955a-4d3bf2def6cf","7a559871-a75f-45d2-95c4-e192e5b28a9d","0a526fce-11b2-4a4e-99ae-49c0df2f3647","8eb1adbe-6c10-4a84-9003-dd0115fce98b","df2c268b-9598-4c71-8a48-9623eb0eb3be","b452be84-f232-4b3b-9a6f-b6fd59f3978e","52a5715c-7c58-4050-9277-67c7eca4bd59","85e36897-74ae-4400-9f06-0e9159eea507","66e6c0c6-8cb0-45fa-a736-dc2608dd0b37","99644caf-3c46-4052-a478-6c967eff9ae1","79695be7-609a-4eaf-b11f-e974ef761759","e15115ea-8be7-444e-b952-72b8040e8916"]},{"id":"9b89cd16-3b66-45bc-9bfb-6fa3db7dd09b","services":["716fd314-6156-4fdd-b0d6-16571825a3fe","0ab3fa02-e46c-4dfe-8a14-84abb276c857","f6d3845a-0033-47d0-a68a-8c87941d3604","efd3732f-3c2d-4b98-a609-6207b09cde4e","8310ae6f-3030-4b78-b0ef-9e65324d3401","cd6b4925-5a01-45eb-914f-b412d376013a","93f20b06-2522-4d1e-a59e-4b517a54ba63","1c8d4b8b-6bcf-4d4d-aa75-611024440dcf"]},{"id":"dd1d1930-f90d-4fb2-bbdf-5faad360c439","services":["a846b2b7-a00b-4c23-8e4a-3452d0f6ea4b","62c1f666-cce5-4e7b-9007-6c34b023c982","3536a1e7-69da-4a5b-9687-5f42dbdb5f73","4114c65a-c7a5-44f4-a836-c947fc30f592","00d8f6e6-2040-46a6-839d-579553f37e97","2a777fed-ba27-4b4a-9228-4a765a75ed5a","0a526fce-11b2-4a4e-99ae-49c0df2f3647"]},{"id":"33c3e0e6-deb4-4fa0-a876-d634f756e34a","services":["cad5616e-a420-4369-bffa-04d6e6e0027a"]},{"id":"8a4c6e0f-6433-4230-a620-6430045c1126","services":["f63eec0e-6cbe-4b14-a451-26461826fcd6","6f20eda5-2659-45ee-8797-87eba6f220cd","a00611b5-9d1e-4b01-bc02-8ac85f6d58b3"]}],"windowSettings":{"width":2565,"height":1148,"x":444,"y":120,"displayBounds":{"x":0,"y":0,"width":3072,"height":1728},"isMaximized":false,"isFullScreen":false},"settings":{"autoLaunchOnStart":false,"autoLaunchInBackground":false,"runInBackground":true,"reloadAfterResume":true,"reloadAfterResumeTime":10,"enableSystemTray":true,"startMinimized":true,"confirmOnQuit":true,"minimizeToSystemTray":true,"closeToSystemTray":true,"privateNotifications":false,"clipboardNotifications":true,"notifyTaskBarOnMessage":true,"showDisabledServices":true,"showServiceName":true,"showMessageBadgeWhenMuted":true,"showDragArea":false,"enableSpellchecking":true,"enableTranslator":false,"spellcheckerLanguage":"en-us","darkMode":false,"navigationBarManualActive":false,"splitMode":false,"splitColumns":3,"fallbackLocale":"en-US","beta":false,"isAppMuted":false,"enableGPUAcceleration":true,"enableGlobalHideShortcut":false,"server":"https://api.ferdium.org","predefinedTodoServer":"isUsingCustomTodoService","autohideMenuBar":false,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernateOnStartup":false,"hibernationStrategy":3600,"wakeUpStrategy":300,"wakeUpHibernationStrategy":0,"wakeUpHibernationSplay":false,"inactivityLock":0,"automaticUpdates":true,"universalDarkMode":true,"userAgentPref":"","adaptableDarkMode":true,"accentColor":"#7367F0","progressbarAccentColor":"#7367F0","serviceRibbonWidth":80,"sidebarServicesLocation":0,"iconSize":0,"sentry":true,"navigationBarBehaviour":"always","webRTCIPHandlingPolicy":"disable_non_proxied_udp","searchEngine":"google","translatorLanguage":"en","translatorEngine":"LibreTranslate","useHorizontalStyle":true,"hideCollapseButton":false,"isMenuCollapsed":true,"hideRecipesButton":false,"hideSplitModeButton":false,"useGrayscaleServices":false,"grayscaleServicesDim":50,"hideWorkspacesButton":false,"hideNotificationsButton":false,"hideSettingsButton":false,"alwaysShowWorkspaces":true,"liftSingleInstanceLock":false,"enableLongPressServiceHint":false,"isTodosFeatureEnabled":true,"customTodoServer":"https://trello.com/b/EJxsCU0j/alberto-to-do-from-team","locale":"en-US","keepAllWorkspacesLoaded":false,"proxyFeatureEnabled":false,"onlyShowFavoritesInUnreadCount":false},"features":{"needToWaitToProceed":false,"isSpellcheckerPremiumFeature":false,"isSpellcheckerIncludedInCurrentPlan":true,"isServiceProxyEnabled":true,"isServiceProxyIncludedInCurrentPlan":true,"isServiceProxyPremiumFeature":true,"isWorkspacePremiumFeature":false,"isWorkspaceEnabled":true,"isAnnouncementsEnabled":true,"isSettingsWSEnabled":false,"isServiceLimitEnabled":false,"serviceLimitCount":0,"isCommunityRecipesPremiumFeature":false,"isCommunityRecipesIncludedInCurrentPlan":true,"isCustomUrlIncludedInCurrentPlan":true,"isMagicBarEnabled":true,"isTeamManagementIncludedInCurrentPlan":true,"isTodosEnabled":true,"isTodosIncludedInCurrentPlan":true,"defaultTrialPlan":"franz-pro-yearly","subscribeURL":"https://ferdium.org","planSelectionURL":"https://ferdium.org","hasInlineCheckout":true,"isPlanSelectionEnabled":false,"isTrialStatusBarEnabled":false,"canSkipTrial":true,"pricingConfig":{"currency":"$","currencyID":"USD","plans":{"personal":{"monthly":{"id":"ferdium-free","price":0,"billed":0},"yearly":{"id":"ferdium-completely-free","price":0,"billed":0}},"pro":{"monthly":{"id":"ferdium-still-free","price":0,"billed":0},"yearly":{"id":"ferdium-forever-free","price":0,"billed":0}}}}},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}

**Comment by vraravam** [comment]
Please add proper title when logging bugs

**Comment by vraravam** [comment]
Unable to replicate the issue. Tried on macos with the latest nightly 6.2.2-nightly.1 and pointed to http://192.168.29.1/

**Comment by vraravam** [comment]
Also tried with syncthing (which opens a local server with a port, and again unable to replicate the issue. Closing
