### ISSUE TITLE
Bug: Npm build error when updating from 6.2.0-1 to 6.2.1-1

### ISSUE THREAD

**Issue by Minoo7** [ferdium/ferdium-app#820]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.1-1

### What Operating System are you using?

Other Linux

### Operating System Version

Manjaro sway

### What arch are you using?

x64

### Last Known Working Ferdium version

6.2.0-1

### Expected Behavior

Trying to achieve successful update of ferdium.

### Actual Behavior

Building ferdium...
Running as unit: run-u530.service
Press ^] three times within 1s to disconnect TTY.
==> Making package: ferdium 6.2.1-1 (mån  5 dec 2022 16:14:29)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning ferdium git repo...
Cloning into bare repository '/var/cache/private/pamac/ferdium/ferdium'...
remote: Enumerating objects: 59941, done.
remote: Counting objects: 100% (951/951), done.
remote: Compressing objects: 100% (444/444), done.
remote: Total 59941 (delta 652), reused 734 (delta 497), pack-reused 58990
Receiving objects: 100% (59941/59941), 123.65 MiB | 12.85 MiB/s, done.
Resolving deltas: 100% (44359/44359), done.
==> Validating source files with sha512sums...
    ferdium ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of ferdium git repo...
Cloning into 'ferdium'...
done.
Switched to a new branch 'makepkg'
==> Starting prepare()...
HEAD is now at a961c78e Merge branch 'develop' into release
Submodule 'recipes' (https://github.com/ferdium/ferdium-recipes.git) registered for path 'recipes'
HEAD is now at a961c78e Merge branch 'develop' into release
Cloning into '/var/cache/private/pamac/ferdium/src/ferdium/recipes'...
Submodule path 'recipes': checked out 'ff551ee3375f35335f30c8bc8c6c5b7645d12cfe'
==> Starting pkgver()...
==> Starting build()...
Downloading and installing node v16.18.1...
Downloading https://nodejs.org/dist/v16.18.1/node-v16.18.1-linux-x64.tar.xz...
################################################################# 100,0%
Computing checksum with sha256sum
Checksums matched!
Now using node v16.18.1 (npm v8.19.2)
Creating default alias: default -> 16.18.1 (-> v16.18.1)
Found '/var/cache/private/pamac/ferdium/src/ferdium/.nvmrc' with version <16.18.1>
Now using node v16.18.1 (npm v8.19.2)
npm WARN using --force Recommended protections disabled.
npm WARN using --force Recommended protections disabled.
npm ERR! code EROFS
npm ERR! syscall mkdir
npm ERR! path /.npm
npm ERR! errno -30
npm ERR! rofs EROFS: read-only file system, mkdir '/.npm'
npm ERR! rofs Often virtualized file systems, or other file systems
npm ERR! rofs that don't support symlinks, give this error.

npm ERR! Log files were not written due to an error writing to the directory: /.npm/_logs
npm ERR! You can rerun the command with `--loglevel=verbose` to see the logs in your terminal
==> ERROR: A failure occurred in build().
    Aborting...
Finished with result: exit-code
Main processes terminated with: code=exited/status=4
Service runtime: 40.624s
CPU time consumed: 49.877s

### Steps to reproduce

sudo pamac update

**Comment by SpecialAro** [comment]
Hello @Minoo7 !

We are now using `pnpm` instead of `npm`, that is probably why it is failing. Can you confirm and close the issue please?

Thank you!

**Comment by Minoo7** [comment]
Ok does that mean I have to fully reinstall/build ferdium or how would I solve this problem for me without losing my current settings/services? Thank you for answering

**Comment by vraravam** [comment]
your setting/services are totally different if you are running the packaged app, and so should not be affected by rebuilding from scratch. btw, why are you building from source? Doesn't the linux packaged builds work for your OS/arch?

**Comment by vraravam** [comment]
@Minoo7 - could you please confirm if this ticket can be closed? Was your question answered?

On second thought, closing this ticket since the development requirements have moved on and the stacktrace refers to a filesystem read-write error - which cannot be controlled by us.
