### ISSUE TITLE
`safeParseInt()` is not parsing hybrid numbers

### ISSUE THREAD

**Issue by eandersons** [ferdium/ferdium-app#823]
### Your issue

Within this issue with "hybrid number" I am meaning something like "1.4K".

Recently I encountered a case when one of messaging channels suddenly had an increased activity resulting in a lot of unread messages - channel notifications count badge contained the value "1.4K", but in service badge this was added as "1".

First of all, I am not completely sure if this really is an issue because a number like "1.4K" is not an exact integer as "1.4K" can be any value within range from 1400 to 1499 (actually I am not sure about this, but there is some range of values that can be associated with "1.4K" anyway).

Whether or not this is an issue depends on which result is considered to be more correct - 1 or 1450.
In my opinion, 1450 would be a better outcome, because the deviation would not be bigger than 50, which currently is at least 1400 instead.

If this is considered to be an issue, I could try to create a pull request which would resolve it.

**Comment by vraravam** [comment]
`Ferdium.safeParseInt` is supposed to only handle null and undefined and default to 0 in those cases. It does not understand semantic numerics. Closing this ticket.
