### ISSUE TITLE
Bug: Scrolling on Telegram is broken

### ISSUE THREAD

**Issue by Netherquark** [ferdium/ferdium-app#835]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.2

### What Operating System are you using?

Other Linux

### Operating System Version

Nobara/Fedora 36 6.0.10-201.fc36.x86_64 x86_64 GNU/Linux

### What arch are you using?

x64

### Last Known Working Ferdium version

Just started using Ferdium, not sure

### Expected Behavior

Scrolling the chat view works in Telegram, after using the built in telegram service recipe and logging in

### Actual Behavior

I can only scroll in the contacts view, no scrollbar appears in the chat view so I can't view previous messages.

### Steps to reproduce

1. Install Ferdium (on Fedora) using Flatpak
2. Click on the Telegram recipe
3. Log into Telegram
4. Open a group/personal chat
5. Can't scroll

### Debug link

https://debug.ferdium.org/387080c9-8cc7-4119-8908-db7f8c3f4a70

### Screenshots

-

### Additional information

Running Ferdium with Flatpak on Nobara 36

**Comment by vraravam** [comment]
Please add a screenshot - I'm unable to visualize the issue. Also, have you made the Ferdium window smaller to test out whether the scrollbar appears for smaller windows? (this is just to test whether scrollbar appears and behaves as desired)

**Comment by Netherquark** [comment]
will send a screen recording displaying the issue soon

**Comment by Netherquark** [comment]
seems like the issue disappeared on re-adding tele, sorry for the trouble!
