### ISSUE TITLE
Bug: Sidebar icon size increased

### ISSUE THREAD

**Issue by Dalgam** [ferdium/ferdium-app#84]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.23

### What Operating System are you using?

Other Linux

### Operating System Version

Fedora 36, Windows 11 

### What arch are you using?

x64

### Last Known Working Ferdium version

6.0.0-nightly.16

### Expected Behavior

Icons to keep their styling/size between version.

### Actual Behavior

Icon styling/size changed at some point 

### Steps to reproduce

1. Update Ferdium 

### Screenshots

| Nightly 16       | Nightly 23         | 
| ------------- |:-------------:| 
| ![image](https://user-images.githubusercontent.com/7426323/166203676-90bdd3c6-b1c8-4dc4-8215-081136faf2e5.png)     | ![image](https://user-images.githubusercontent.com/7426323/166203705-080c7dd9-95e3-4a42-9892-ca45dd10d72b.png)|

**Comment by SpecialAro** [comment]
Should be fixed on the next nightly. Thank you for raising this bug issue!
