### ISSUE TITLE
Bug: macOS UI elements overlapping Ferdium UI/services elements

### ISSUE THREAD

**Issue by nickterhaar** [ferdium/ferdium-app#840]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.3-nightly.7

### What Operating System are you using?

macOS

### Operating System Version

macOS Ventura 13.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Ferdium version

6.2.2

### Expected Behavior

The macOS UI elements should have some margins around it so it wont overlap the UI of Ferdium

### Actual Behavior

macOS UI elements overlapping Ferdium services UI elements

### Steps to reproduce

Just open Ferdium 6.2.3-nightly.7

### Screenshots

<img width="71" alt="image" src="https://user-images.githubusercontent.com/2932357/207824650-7515f5fe-fc4a-42e9-bf17-9d45d7da70d0.png">

**Comment by SpecialAro** [comment]
Also seeing this on Windows
![image](https://user-images.githubusercontent.com/37463445/207838743-966eac50-adf9-4a34-bd7c-3c940aaaef98.png)

PR #841 should fix this
