### ISSUE TITLE
Bug: Error in Language Settings

### ISSUE THREAD

**Issue by meiphoo7-Mae** [ferdium/ferdium-app#844]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.3-nightly.7

### What Operating System are you using?

Ubuntu

### Operating System Version

Ubuntu 22

### What arch are you using?

x64

### Last Known Working Ferdium version

I don't know

### Expected Behavior

It should show the correct language.

### Actual Behavior

I'm one of the translators of the Dutch language and I noticed something that seems incorrect to me.
In the language dropdown (Settings > Language > Language Settings) the usual format is:
**localized language name (language name in English)**

However for my language (notice the blue bar in the attached screenshot) it says:
**Dutch, Flemish**

This is incorrect because Flemish is a different language. Right below this entry it says:
**Vlaams**

Vlaams is in fact Flemish.

So these two entries should read:
**Nederlands (Dutch)
Vlaams (Flemish)**

Crowdin recognizes both languages separately so it must be a bug in the dropdown and I can't find these entries on crowdin so they seem to be hardcoded in the source code of Ferdium.

### Steps to reproduce

There's nothing special required to reproduce the bug.

### Screenshots

![Screenshot_20221215_194548](https://user-images.githubusercontent.com/95827976/207946130-8e4103ad-9492-4b49-8277-baa87fa8f44b.jpg)

**Comment by vraravam** [comment]
Will be fixed in the upcoming 6.2.3-nightly.8

**Comment by meiphoo7-Mae** [comment]
Thank you.
