### ISSUE TITLE
Bug: vBulletin (jazzguitar.be) forum actions handled incorrectly

### ISSUE THREAD

**Issue by RJVB** [ferdium/ferdium-app#848]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.2

### What Operating System are you using?

Ubuntu

### Operating System Version

14.04

### What arch are you using?

x64

### Last Known Working Ferdium version

6.2.0

### Expected Behavior

1) Clicking on `Reply` or `Reply with Quote` should open the reply/post editor in Ferdium

2) Clickig on the `Multi-Quote` (
![image](https://user-images.githubusercontent.com/1756884/208108374-3afe6cf8-525e-4dfe-9b53-7682d9894a59.png)) button should only result in that button getting a tick mark (
![image](https://user-images.githubusercontent.com/1756884/208108574-3fe9e3f6-7e1e-41d2-8e33-610a041e5e3b.png)), NOT in opening the reply/post editor.

### Actual Behavior

1) The reply/post editor is opened in a browser widow

2) idem

### Steps to reproduce

0. Create a (free) account on the `jazzguitar.be` forum or, I suspect,any other vBulletin forum
1. Log in to that account and open a discussion thread
2. Click on one of the buttons.

### Debug link

https://debug.ferdium.org/b1c3ccb3-a594-42ac-8735-da44d9b8518f

### Additional information

Apparently I skipped 6.2.1 ; I ran the portable/AppImage 6.2.0 version after extracting it.

Sample links  corresponding to the "buttons" in question:
`Reply`: https://www.jazzguitar.be/forum/newreply.php?do=newreply&p=1236977&noquote=1
`Reply-with-quote`: https://www.jazzguitar.be/forum/newreply.php?do=newreply&p=1236977
`Multi-quote`: https://www.jazzguitar.be/forum/newreply.php?do=newreply&p=1236977

**Comment by RJVB** [comment]
Setting links to be opened in Ferdium for this service will work around 1) but not around 2).

**Comment by vraravam** [comment]
Is this working correctly from a normal browser?

**Comment by RJVB** [comment]
>Is this working correctly from a normal browser?

It is (evidently I dare say), and it was in the previous Ferdi[um] versions I used. It's not an issue with a new version or configuration of the forum software, if that's what you were thinking.

**Comment by RJVB** [comment]
In fact, I just notice that the issue is worse than I realised: most links are opened in a browser now. I can click on a post title (say from the New Posts page) and it will open in Ferdium.

For instance, clicking on `https://www.jazzguitar.be/forum/guitar-amps-gizmos/93548-wax-protectant.html` on `https://www.jazzguitar.be/forum/search.php?searchid=2411212` will open the thread i question in Ferdium. But click on the title of that thread (`https://www.jazzguitar.be/forum/guitar-amps-gizmos/93548-wax-protectant.html`) on top of the thread page and the page will open in my browser.
As you see those are the same links so it beats me why they're not handled the same way.
Similarly, trying to load the new posts page via `https://www.jazzguitar.be/forum/search.php?do=getnew&contenttype=vBForum_Post` or the list of threads I'm subscribed to (`https://www.jazzguitar.be/forum/subscription.php`) will cause the browser to be activated. 

I'm not (yet) seeing any of this happening on a phpbb forum (but I have made a special service recipe for that one). Another vBulletin forum I am a member of (acousticguitarforum.com) does have the same issues though certain links do behave as expected.

Can this be related to local service cached data or whatever?

**Comment by vraravam** [comment]
Link handling was changed in some manner a few months ago (maybe around/prior to 6.2.0 or 6.2.1 as you mentioned). Since then, the usage patterns have more-or-less normalized.

Unfortunately, we cannot revert back to the older implementation at this point. Also, since this seems to be only an issue in a custom service, we cannot provide a solution that would work for you within the context of a custom service.

If you think this needs specific link/url handlng, I would request you to create a new service recipe and contribute it as a PR into the https://github.com/ferdium/ferdium-recipes repo. You can find documentation on how to create a recipe using the code generator from its README file.

**Comment by RJVB** [comment]
>Unfortunately, we cannot revert back to the older implementation at this point.

Could you provide the old implementation as an option the service settings, or simply in the advanced tab? I haven't noticed any differences in my other services but there are so many bundled services that it's hard to imagine none would suffer comparable undesirable regressions.

>If you think this needs specific link/url handlng, I would request you to create a new service recipe and contribute it as a PR into the https://github.com/ferdium/ferdium-recipes repo. You can find documentation on how to create a recipe using the code generator from its README file.

How is a dedicated recipe going to help me if you do not want to revert back to the old implementation?

Also, this affects every vBulletin forum to some degree. So the logical thing to do in terms of a service recipe would be to create a generic one for vBulletin forums, where the URL is a parameter. That's not currently possible as far as I know but it would be a prerequisite for forum services anyway: different users will want to land on different forum landing pages - the front page (index), a subforum index, the page showing only new posts or yet something else, and vBulletin allows to filter out different subforum (categories) via the URL.

It simply looks like I'll have to go back to and stay on 6.2.0 for as long as possible...

**Comment by RJVB** [comment]
Well, this is weird. I've reverted back to 6.2.0 and now that version also doesn't work anymore with vBulletin forums. I'd almost doubt myself but that is my step-in version when coming from Ferdi, and you'd say I would have noticed this kind of big difference in behaviour. My old Ferdi version still works just fine though (AND it shows custom service icons, yay!)

**Comment by vraravam** [comment]
Only reverting to an older version of Ferdium (without wiping out the recipes folder in your Ferdium profile) is not going to rollback the recipe to the older version. Please do both simultaneously before starting Ferdium.

**Comment by RJVB** [comment]
The handling of URLs is something programmed in the recipe?? I'm not talking about the user setting of option whether link should be opened in Ferdium. That option was always off for me, and yet forum links opened in Ferdium (I presume that the distinction here is whether or not URLs refer to a different server or domain).

**Comment by RJVB** [comment]
On Monday December 26 2022 06:48:18 Vijay Aravamudhan wrote:
>Only reverting to an older version of Ferdium (without wiping out the recipes folder in your Ferdium profile) is not going to rollback the recipe to the older version. Please do both simultaneously before starting Ferdium.

OK, I think I see the culprit now.

Is it not possible to edit my own `~/.config/Ferdium/recipes/franz-custom-website/webview.js` file, and write-protect it and/or its directory?

Making custom services would have the advantage that I get icons in the side-bar again, but I'd lose the navigation toolbar. I like having that one above my forum services...
