### ISSUE TITLE
Bug: Opening Ferdium from the TaskBar Icon in Windows keeps loading forever

### ISSUE THREAD

**Issue by FANMixco** [ferdium/ferdium-app#857]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.2

### What Operating System are you using?

Windows

### Operating System Version

Windows 11 22H2

### What arch are you using?

x64

### Expected Behavior

Whenever I click on the systray icon or the **Taskbar** or **Start** menu icon, all should open Ferdium properly.

### Actual Behavior

If I open Ferdium from the **Taskbar** or **Start** menu icon while it's in the systray, it keeps loading forever.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/1666156/209008113-84d35091-ec2b-4f74-b4a9-06e43f13550f.gif)

### Steps to reproduce

1. Open Ferdium.
2. Enable **Minimize Ferdium to system tray**.
3. Enable **Always show Ferdium in System tray**.
4. Minimize Ferdium.
5. Open Ferdium from **Taskbar** or **Start** menu icon

### Screenshots

![ezgif com-gif-maker](https://user-images.githubusercontent.com/1666156/209008113-84d35091-ec2b-4f74-b4a9-06e43f13550f.gif)

**Comment by vraravam** [comment]
Fixed by #838 . Please switch to the latest nightly to get this fix.
