### ISSUE TITLE
Feature: API for getting total message count

### ISSUE THREAD

**Issue by marie-bnl** [ferdium/ferdium-app#863]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I use Ferdium and I would love to have a message count in my desktop environment's status bar. More generally, it would without a doubt be really beneficial to be able to get this sort of informations from other programs.

### Proposed Solution

The idea would be to create an API, no matter its form (an HTTP server, a command line feature, a file, tell me...). 

For instance, one endpoint would be something like `messages_count` and just return the number in plain text.

### Alternatives Considered

Actually I don't see any clean alternatives, maybe you could hack around by looking at the data in RAM or things like that, which seem utterly complicated.

### Additional Information

I don't know if this sort of API already exist, but I did my research and found nothing. If it doesn't, let's discuss how we could implement it with as less performance overhead as possible. If it does, consider this issue a request for documentation

**Comment by marie-bnl** [comment]
What appears to me in first sight as a good way to implement it would be IPC, [~~which Electron does seem to have integrated support for~~](https://www.electronjs.org/docs/latest/tutorial/ipc)

**Comment by MurzNN** [comment]
@kris7t Thank you for the implementation, very useful!
