### ISSUE TITLE
Feature: Open links in app

### ISSUE THREAD

**Issue by davidbenucci** [ferdium/ferdium-app#87]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Open external links in Ferdium and not in default browser

### Proposed Solution

See Rambox behaviour

### Alternatives Considered

None

**Comment by vraravam** [comment]
@davidbenucci - different services/websites behave differently. While we ideate on the best acceptable behavior across the board, i would suggest that you use the right-click context menu and use "Open link in Ferdium" option.

**Comment by davidbenucci** [comment]
Thanks for you reply. But could it be an option in the general settings that defines a default behaviour for all the ferdium apps? Thanks.

**Comment by MurzNN** [comment]
Also some apps, eg Telegram Web client, overrides right click to show their own menu, is there any way to force show native Ferdium menu? 

In Mozilla Firefox this can be done via shift+rightClick, but this trick doesn't work in Chromium-based browsers, and seems in Electron too :(

**Comment by MurzNN** [comment]
Also will be good to have an option "Open link in Ferdium in new window".

**Comment by vraravam** [comment]
> Also will be good to have an option "Open link in Ferdium in new window".

There have been other discussions on the topic of multiple ferdium windows. That is almost akin to a complete rewrite - and will not be supported any time that I am aware of.

**Comment by vraravam** [comment]
> In Mozilla Firefox this can be done via shift+rightClick, but this trick doesn't work in Chromium-based browsers, and seems in Electron too :(

As you mentioned, this is not a feature that chromium/electron supports, and we would not be implementing this in Ferdium either.

**Comment by vraravam** [comment]
> Thanks for you reply. But could it be an option in the general settings that defines a default behaviour for all the ferdium apps? Thanks.

Yes, if/when we develop this feature, a common/global setting (that applies to all configured services) would make sense.

**Comment by vraravam** [comment]
This _might_ be fixed by #154

**Comment by SpecialAro** [comment]
Is this fixed yet? I think so!

**Comment by vraravam** [comment]
@davidbenucci - can we close this?

**Comment by davidbenucci** [comment]
The feature "Open in link in Ferdium" works (even if Ferdium use the same windows of the main service, eg. Gmail) but If I set the optin "Open link in Ferdium" in service settings and reload the service, the default behaviour remains opening the default browser and not Ferdium..

**Comment by vraravam** [comment]
[As per the implementation](https://github.com/ferdium/ferdium-recipes/pull/30/files), this is only implemented for Discord, Skype, Steamchat and zoom. If needed for other services, please raise specific requests in the ferdium-recipes repo.

**Comment by ylluminate** [comment]
Problematic behavior in Discord now: https://github.com/ferdium/ferdium-app/issues/474

**Comment by SlanDF** [comment]
@SpecialAro should this be closed?

**Comment by SpecialAro** [comment]
> @SpecialAro should this be closed?

I think it can be. But let me ask @davidbenucci if he's happy with the implementation so far, or if we should keep this open (maybe to implement an overall open-in Ferdium, instead of recipe specific)

**Comment by cino** [comment]
Closing this issue since there is no response since the 13th of Juli.

**Comment by LMeiraba** [comment]
please make it work for google services like gmail, drive, etc

**Comment by guradia** [comment]
A logical thing should be to open URLs that 1:1 point to the Host of an added Service inside that service's tab.

Example:
Having a Link in Zulip to Asana ... the Options are:
- external browser (default) ... not useful
- inside the Zulipt tab ... not usefult either (since it's obviously not sharing the login, unless using the sandbox in not recommended ways)

I would be fine with a setting of the kind "URL patterns to capture for Service A".
