### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by View-my-Git-Lab-krafi** [ferdium/ferdium-app#873]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.3

### What Operating System are you using?

Other Linux

### Operating System Version

fedora 37

### What arch are you using?

x64

### Expected Behavior

facebook and messesnger , if i click on call icon it didnt respond anything.. 

i want to ask another question is there any way to add plugin ? like vimium add blocker?
i seen a telegram notification saying you loged in with chrome browser.. but chrome is not open source...... does ferdium chrome in background ?

### Actual Behavior

facebook and messesnger , if i click on call icon it didnt respond anything.. 

i want to ask another question is there any way to add plugin ? like vimium add blocker?
i seen a telegram notification saying you loged in with chrome browser.. but chrome is not open source...... does ferdium chrome in background ?

### Steps to reproduce

....

**Comment by SpecialAro** [comment]
Hello @kazi-ar-rafi 

Please check the steps provided here (https://github.com/ferdium/ferdium-app/issues/611) and see if it fixes Facebook and Messenger for you.

Also, next time, before raising an issue you should follow the guidelines provided.

For your extensions question:
https://github.com/ferdium/ferdium-app/issues/187

Ferdium uses Electron which uses Chromium.

I'm closing this issue as it didn't follow the guidelines to be opened.
