### ISSUE TITLE
Is it possible to open 2 instances of ferdium-app ?

### ISSUE THREAD

**Issue by JPnux** [ferdium/ferdium-app#881]
### Your issue

Hi,

I am on Linux Ubuntu and I use virtual desktops.
Is it possible to open Ferdium on desktop 1 for personal stuff and another Ferdium with another services for work per example on desktop 2 ?

Thank you

**Comment by SpecialAro** [comment]
Hello!

It is not possible to open two instances of Ferdium (as a second click would trigger Ferdium to open its window).

For that you can configure and use workspaces inside Ferdium.
