### ISSUE TITLE
Feature: Open links in new tabs within the same service container

### ISSUE THREAD

**Issue by ms-2525** [ferdium/ferdium-app#891]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Kindly add a feature whereby we can open new tabs in the service container and say pin multiple pages in the same service. So 1 service can have different pinned tabs.

I would come in very handy because many time i have to refer to the mail contents and the mail attachments side by side. Currently i have to open the attachment in ferdium and close it again and again to see both the mail and attachment. 

Also when using onedrive, i want the office web version to open in new tab. 

If i select "open in default browser" , then i have to login again on the browser and to open personal mails/onedrive, i have to first switch to incognito mode or guest mode and then open.

This feature is present in "Biscuit Browser" but that project is i think no longer in development and because of that the chrome version is too old and some websites are not visible properly.

I have also attached an image of the biscuit browser to demonstrate the new feature

![image](https://user-images.githubusercontent.com/89872047/212838367-79ffbd7f-8810-4ff4-81e2-99cdce529b97.png)

### Proposed Solution

Add an option to open link in new tabs within the same service container

### Alternatives Considered

.

### Additional Information

(Can refer to Biscuit Brower as it has the feature that i am talking about)

**Comment by vraravam** [comment]
Thanks for raising this ticket, but _please do not submit duplicate tickets_. There are multiple other tickets asking for the same feature.
