### ISSUE TITLE
Bug: Notifications on Element counted twice

### ISSUE THREAD

**Issue by svoop** [ferdium/ferdium-app#896]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.3

### What Operating System are you using?

Windows

### Operating System Version

macOS 13.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Notifications should be counted only once.

### Actual Behavior

Notifications of rooms marked as "favourite" are counted twice.

### Steps to reproduce

1. Right click on a room and choose "Favourited"
2. Wait until you receive a notification on that room
3. Element displays notification bubble (1) on the group which contains the room as well as bubble (1) on the "Favourites" group (the button with the star).
4. Ferdium displays (2) notifications. 

### Screenshots

<img width="482" alt="image" src="https://user-images.githubusercontent.com/7255/213493890-8c4916c1-0d33-41c7-96b6-03b7a1b3a66c.png">

In this screenshot, the two notifications in the "Favourites" group [★] refer to the same two messages as the two notifications on group [B].

### Additional information

Apparently, the notifications from Element are simply added by Ferdium. That's okay, but the number from the "Favourites" group (the button with the star) must be ignored in order to avoid duplicates.

**Comment by bacciotti** [comment]
The same occurs with me, but with all services. Example: I've got one unread email on Gmail, but there is this red bullet with the number 2.

**Comment by grafuls** [comment]
Same for me on Gmail.
Worth noting that I have 2 gmail services active and that this is the only service that duplicates the count for me, I have an element service too but the count is always right there.
Also noticed that when I have more than 10 unread emails then count gets corrected so if I have 11 unread emails the counter correctly shows 11 instead of 22 but when the count is 10 or less it shows doubled.

**Comment by MartinX3** [comment]
I think I have the same issue.  
In Arch Linux with XFCE I have a little icon in the taskbar where it shows the list of unread notifications.
Every Whatsapp message I got there is listed twice now.

**Comment by mikymaione** [comment]
Same problem, with Whatsapp, Element, Telegram, Instagram. All notifications in Gnome 46 (Fedora 40) are duplicated.

**Comment by edikici** [comment]
I can confirm that commit [0ed2bac](https://github.com/ferdium/ferdium-app/commit/0ed2bacd83a05ce3190bfa7124a04a0de6abf9fc) fixes the double notification issue for me (Windows 10), at least for WhatsApp and Teams.
