### ISSUE TITLE
Updates including pre-releases does not work.

### ISSUE THREAD

**Issue by leoheck** [ferdium/ferdium-app#899]
### Your issue

Any idea if this feature is working? It never told me there are new versions of it. 

![image](https://user-images.githubusercontent.com/1277920/213793129-eda66a9a-9dec-4917-aa7b-a473664e77f2.png)

**Comment by vraravam** [comment]
Can you please check in the developer console? No one has reported the in-app updater not working in the recent past. Also, please specify what OS version, etc that you are using. I am on a mac, and I have not had any issues till date.

**Comment by leoheck** [comment]
I am using Ubuntu 22.10 with Gnome and the package was the .deb 

Where and how updates are notified? I never even saw a notification about it even using it every day.

Where is the developer console? What should I check there?

**Comment by SpecialAro** [comment]
@leoheck you can open the dev console if you press `CTRL + ALT + I`, or `View > Toggle Developer Tools`. It is, in fact super rare that this is happening.

**Comment by leoheck** [comment]
~Since the next time I have the new version of the software. But if the check still useful, here it it.~

Actually I am still using the old version
```
Version: 6.2.3-nightly.3
Server: No Server
Electron: 21.3.3
Chrome: 106.0.5249.199
Node.js: 16.16.0
Platform: Linux 5.19
Arch: x64
Build date: Thu Dec 08 2022 22:00:51 GMT-0300 (Brasilia Standard Time)
Git SHA: 8ab1d10f
Git branch: nightly
```

I have the console open now, what should I look there?

Edit: Fix info about the current version of my Ferdium

**Comment by leoheck** [comment]
This is what I am currently seeing

![image](https://user-images.githubusercontent.com/1277920/214064663-8723e072-5e29-4a7d-9034-e45985e8649e.png)

**Comment by SpecialAro** [comment]
Can you manually update from GH using the nightlies and try to update once a new one appears?

It is strange that you're having Sentry errors given that we disabled it entirely until we find a fix for another issue.

**Comment by leoheck** [comment]
Using this one now
```
Version: 6.2.4-nightly.10
Server: No Server
Electron: 22.0.3
Chrome: 108.0.5359.179
Node.js: 16.17.1
Platform: Linux 5.19
Arch: x64
Build date: Thu Jan 19 2023 21:57:19 GMT-0300 (Brasilia Standard Time)
Git SHA: 8b4a70f6
Git branch: nightly
```

I downloaded AppImage last time, and the deb version was still being loaded at the startup

But using the new one is actually working. See:
![image](https://user-images.githubusercontent.com/1277920/215639700-42c9c954-783c-4c82-b52b-146f0d945138.png)

**Comment by leoheck** [comment]
After, the update worked fine.
```
Version: 6.2.5-nightly.0
Server: No Server
Electron: 22.1.0
Chrome: 108.0.5359.179
Node.js: 16.17.1
Platform: Linux 5.19
Arch: x64
Build date: Sun Jan 29 2023 22:50:21 GMT-0300 (Brasilia Standard Time)
Git SHA: 1da95eb1
Git branch: nightly
```
