### ISSUE TITLE
Bug: Can't add new services (or import old ones) when using Ferdium from snap

### ISSUE THREAD

**Issue by 3v1n0** [ferdium/ferdium-app#90]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.24

### What Operating System are you using?

Ubuntu

### Operating System Version

20.04

### What arch are you using?

x64

### Expected Behavior

I can add new services

### Actual Behavior

Nothing is added, `dmesg` spawn various apparmour `DENIED` accesses

### Steps to reproduce

1. Open the app
2. Add new service
3. Nothing is selected

Alternatively, import old services from `export.ferdi-data` file

### Additional information

```
[157230.876045] audit: type=1326 audit(1651589474.806:11111): auid=1000 uid=1000 gid=1000 ses=3 subj=snap.ferdium.ferdium pid=1015456 comm="ferdium" exe="/snap/ferdium/7/ferdium" sig=0 arch=c000003e syscall=330 compat=0 ip=0x7f86d3c044e7 code=0x50000
[157230.895345] audit: type=1326 audit(1651589474.822:11112): auid=1000 uid=1000 gid=1000 ses=3 subj=snap.ferdium.ferdium pid=1015457 comm="ferdium" exe="/snap/ferdium/7/ferdium" sig=0 arch=c000003e syscall=330 compat=0 ip=0x7ffa1e4d44e7 code=0x50000
[157231.110968] audit: type=1326 audit(1651589475.038:11113): auid=1000 uid=1000 gid=1000 ses=3 subj=snap.ferdium.ferdium pid=1015482 comm="ferdium" exe="/snap/ferdium/7/ferdium" sig=0 arch=c000003e syscall=330 compat=0 ip=0x7f0abef944e7 code=0x50000
[157231.125334] audit: type=1326 audit(1651589475.054:11114): auid=1000 uid=1000 gid=1000 ses=3 subj=snap.ferdium.ferdium pid=1015483 comm="ferdium" exe="/snap/ferdium/7/ferdium" sig=0 arch=c000003e syscall=330 compat=0 ip=0x7f192274d4e7 code=0x50000
[157236.082786] audit: type=1326 audit(1651589480.010:11115): auid=1000 uid=1000 gid=1000 ses=3 subj=snap.ferdium.ferdium pid=1015405 comm="ferdium" exe="/snap/ferdium/7/ferdium" sig=0 arch=c000003e syscall=326 compat=0 ip=0x7f596682e539 code=0x50000
[157239.795856] audit: type=1326 audit(1651589483.722:11116): auid=1000 uid=1000 gid=1000 ses=3 subj=snap.ferdium.ferdium pid=1015405 comm="ferdium" exe="/snap/ferdium/7/ferdium" sig=0 arch=c000003e syscall=326 compat=0 ip=0x7f596682e539 code=0x50000
```

**Comment by 3v1n0** [comment]
Not sure if https://github.com/ferdium/ferdium-app/commit/0d5ad8c09e59383ebbde3158555dec42ec0663c1 will help here.

In any case further permissions should be probably included as per https://snapcraft.io/docs/supported-interfaces

**Comment by NathanaelGandhi** [comment]
Comparing interface, plug & slot between ferdi & ferdium suggest they are the same, I don't think the AppArmour policies have been extended differently in ferdium snap to the ferdi snap as this is meant to be "expressed in the metadata as plugs and slots" - https://snapcraft.io/docs/security-sandboxing

![image](https://user-images.githubusercontent.com/36506137/166496489-7a8cff38-52fc-4510-916d-cf43cfcaa037.png)

**Comment by NathanaelGandhi** [comment]
Looks like electron-builder uses core18 for snap builds. Snapcraft recommends core20 https://snapcraft.io/docs/base-snaps. 

I couldn't find much information on a workaround (that I understood). Here is the related electron-builder issue: https://github.com/electron-userland/electron-builder/issues/5257

**Comment by mcplayerteam** [comment]
Confirmed still an issue in nightly 32 on Manjaro (from snap only, AppImage works fine)

**Comment by TurkerTunali** [comment]
I  use 6.0. nightly.49. I've used 2-3 days then this happened.

https://user-images.githubusercontent.com/710051/170821533-e4a990c8-caa6-4f86-8db0-e3e95505cb73.mp4

My debug info: https://debug.ferdium.org/9bbf3213-5c12-4d59-9c89-c73f64755214

![image](https://user-images.githubusercontent.com/710051/170821566-7c9d8b59-c2c3-47b8-8ad6-181b106c72c1.png)

**Comment by TurkerTunali** [comment]
This also happens in deb version.

**Comment by NathanaelGandhi** [comment]
Adding services works as expected using ferdium_6.0.0-nightly.51_amd64.deb on Ubuntu 20.04.4 LTS x86_64 (vm)
![image](https://user-images.githubusercontent.com/36506137/171879334-3bc7a519-2309-4b8e-a78a-0d3c13d87cea.png)

Also works using snap ferdium (edge) 6.0.0-nightly.52 on Ubuntu 20.04.4 LTS x86_64 (vm)
![image](https://user-images.githubusercontent.com/36506137/171880255-57cd2ea6-0fb2-4534-a20f-6a327d28cdc3.png)

Also works using snap ferdium (beta) 6.0.0-beta.1 on Ubuntu 20.04.4 LTS x86_64 (vm)
![image](https://user-images.githubusercontent.com/36506137/171880663-e61f1b4d-2cce-4002-9d0a-ef47f49ae4c9.png)

Is anyone aware of the changes that fixed the original issue? What tests are still required for this issue to be closed?

**Comment by 3v1n0** [comment]
Ok, also snap works now... BUT it requires you to cleanup your `~/snap/ferdium` first.

**Comment by NathanaelGandhi** [comment]
Appears to have been identified in #167

**Comment by TurkerTunali** [comment]
I still can't add new services. It is fresh install and before install I've deleted the ~/snap/ferdium folder.

![image](https://user-images.githubusercontent.com/710051/172059694-92b2bf72-93bd-47ec-af40-939ab2cf0ae4.png)

https://debug.ferdium.org/1b5057b8-a7cf-4b77-9b73-f23805c386b4

**Comment by NathanaelGandhi** [comment]
I can add services fine using the same snap. I did not delete any folders, just removed all ferdium installs.
![image](https://user-images.githubusercontent.com/36506137/172077096-61f936fb-4043-49f4-b966-c59a42b147f5.png)

1. snap remove ferdium
2. snap install --edge ferdium
snap connect ferdium:camera
snap connect ferdium:pulseaudio

EDIT: New install command
2. snap install --edge ferdium
snap connect ferdium:camera
snap connect ferdium:record-audio

**Comment by LucienMorey** [comment]
I can also add services just fine after removing the snap and reinstalling without deleting folders

**Comment by NathanaelGandhi** [comment]
@TurkerTunali are you still experiencing this issue?

**Comment by 3v1n0** [comment]
Ah, FYI, importing worked but I had to restart ferdium once done it. As nothing appeared promptly.

PS: You can probably release next stable build to the snap stable channel :)

**Comment by TurkerTunali** [comment]
@NathanaelGandhi I still have some problems. After adding a few services, I can't add any more.

https://user-images.githubusercontent.com/710051/173037223-35b8a8cb-4970-46f6-a850-29706fab1b05.mp4

https://debug.ferdium.org/b044e516-d7f5-4d12-ba8c-bf735b11e200

**Comment by NathanaelGandhi** [comment]
@TurkerTunali I cant seem to replicate your issue using 6.0.0-nightly.56
![image](https://user-images.githubusercontent.com/36506137/173061745-e4691c52-7a99-4738-b1d0-fc1901e92a5c.png)

Maybe this is related to the network lag issue identified in #157.
Please try installing the latest nightly and adding services with a longer pause between them. Additionally, if the issue persists does restarting ferdium at that point and then adding additional services still work?

**Comment by NathanaelGandhi** [comment]
@3v1n0 
> PS: You can probably release next stable build to the snap stable channel :)

I think it would be best to wait for [6.0.0 milestone](https://github.com/ferdium/ferdium-app/milestone/1) to be completed. As I understand it, the build will be automatically published to the stable channel when the run is completed with the stable flag.

**Comment by TurkerTunali** [comment]
> does restarting ferdium

No.  Sometimes it deletes every service and doesn't allow me to add. Sometimes services works as expected but I can't add any new service.
