### ISSUE TITLE
Bug: Ferdium reports unread messages for whatsapp even if there aren't any

### ISSUE THREAD

**Issue by robert-elles** [ferdium/ferdium-app#902]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.0

### What Operating System are you using?

Other Linux

### Operating System Version

Nixos latest

### What arch are you using?

x64

### Expected Behavior

The service app icon shows only the number of actual new messages

### Actual Behavior

The whatsapp icon shows incorrect number of new messages. This number even changes when I scroll through the list of chats.

### Steps to reproduce

Just open whatsapp in ferdium

**Comment by SpecialAro** [comment]
Hello @robert-elles,

You are not using the latest updated app. Please update and it will, almost for sure, fix you issue.

https://github.com/ferdium/ferdium-app/releases/tag/v6.2.3

Also, in the future, make sure you enable in-app updates:
![image](https://user-images.githubusercontent.com/37463445/214029008-ee232fe6-b686-4bfa-b42a-3e57bd91880b.png)
