### ISSUE TITLE
As posted in ferdi before, Why not to port Signal

### ISSUE THREAD

**Issue by ArturoRoaBorbolla** [ferdium/ferdium-app#903]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Signal is an Electrone app why not to port it?

### Proposed Solution

Port Signal to Ferdium

### Alternatives Considered

None

**Comment by SpecialAro** [comment]
@ArturoRoaBorbolla please read this: https://github.com/ferdium/ferdium-recipes/issues/46

**Comment by dbieber** [comment]
Heads up @SpecialAro that link either doesn't exist or isn't public; Issues is disabled on the ferdium-recipes repo.

**Comment by vraravam** [comment]
I have re-enabled Issues in the ferdium-recipes repo @dbieber

**Comment by dbieber** [comment]
Thanks -- I can confirm the link is working now 👍
