### ISSUE TITLE
Feature: Introduce kbar to switch between applications and workspaces

### ISSUE THREAD

**Issue by siamak-haschemi** [ferdium/ferdium-app#917]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Ferdium should have a way to globally switch to an application/service by it's name.

### Proposed Solution

I propose to add a kbar to Ferdium. Here are some links what a kbar is:

- https://kbar.vercel.app/
- https://cmdk.paco.me/
- https://maggieappleton.com/command-bar

The first use case I see is to switch between applications within a workspace. But also switching between workspaces.

Care has to be taken that other applications (like Github and Slack) also use the key-combination Cmd+K for this feature.

### Alternatives Considered

In order to navigate to a specific application/service, users currently have to 
- switch to the workspace where the service is using the key combination Option+Command+<number> (number has to be memorized)
- switch to the application/service with using the key combination Command+<number> (number has to be memorized)

**Comment by vraravam** [comment]
This is present already with the "quick switch" mode (`Cmd+S`)

**Comment by siamak-haschemi** [comment]
Ok, thank you. I am sorry that I missed that.
