### ISSUE TITLE
Bug: Custom service icons don't work when using ferdium-server

### ISSUE THREAD

**Issue by typoworx-de** [ferdium/ferdium-app#928]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.4

### What Operating System are you using?

macOS

### Operating System Version

13.1

### What arch are you using?

x64

### Last Known Working Ferdium version

works without using ferdium-server (locally only)

### Expected Behavior

It should be able to use service custom-icons using local ferdium (without ferdium-server) and even with ferdium-server.

### Actual Behavior

It's not possible to customize service-icons!

Using Ferdium with a ferdium-server causes service-icons cannot be customized. After selecting custom-icon for a service the chosen image (working in preview before saving) disappears. Trying to edit the service the previously chosen image is gone, replaced with "missing image" icon.

I'm not shure if this is a ferdium-server or ferdium-app (client) issue.

### Steps to reproduce

Ferdium using local (without ferdium-server) has been tested to work. I've tested this on my Macbook and Ubuntu/Linux Workstation using latest Ferdium (6.2.4) release.

To reproduce the bug:

1. Install Ferdium-App
2. Use a Ferdium-Server
3. Create a service and customize service-icon.
4. Save the service.
5. Logo disappears in service menu-bar.
6. Editing the service the logo is also lost (but can be deleted)

### Screenshots

**Before saving** after choosing custom Icon:
![image](https://user-images.githubusercontent.com/1282298/216571250-280467b7-c3d9-4e88-85e4-a99f748c92c5.png)

**After saving**, the menu-place where this service is/should be is gray (same like background) with no logo or outline where the custom icon should appear!
![image](https://user-images.githubusercontent.com/1282298/216573754-0e265889-1b78-42f2-aed3-02807b5fb383.png)
(notice the red marks are manually added by me)

**Trying to edit the service** looks like this. Notice the custom-icon looks "lost".
![image](https://user-images.githubusercontent.com/1282298/216571627-fb5fa889-776f-40a5-9611-4517fb461004.png)

**Comment by typoworx-de** [comment]
As I'm not shure it's a client or server issue, I'll link the ticket I yesterday created for ferdium-server:
https://github.com/ferdium/ferdium-server/issues/64

**Comment by typoworx-de** [comment]
As I've setup a private ferdium-server instance for my company I also tested now with official ferdium-server. Surprisingly there the custom service-icons work!

**Comment by rafiazman** [comment]
I'm on the same version & OS and face this issue as well.

**Comment by muddro1** [comment]
Same issue here. Ferdium 6.2.4 and ferdium-server

**Comment by rplanchuelo** [comment]
Same issue,  Ferdium 6.2.6 and ferdium-server (Docker version), in Linux

**Comment by typoworx-de** [comment]
Is there anything new on this? I've sit out this problem a while, but now I need this to get working. I've downloaded the git-master and tried to fix some stuff that I saw when the container started like obviously mismatched node-js version (for ferdium-server vs. receipts) and there was a notice about missing module image-size. I've patched the docker-image to use a node-js version that seems to match both requirements and installed the missing "image size" module. These errors are gone now, but the service custom-icons still disappear trying to use them.

I also patched the docker entrypoint.sh to make shure the path /app/tmp exists and it is writeable/owned by node-user (as well as /app and /app/data). But even this didn't fix it. I noticed trying to use custom service-icons the images are uploaded now on the ferdium-server node.

I'm neither a ferdium-server nor a nodejs expert (I'm coding some other stuff). I don't know where the problem ist, but I think anyone who understands ferdium-server and nodejs better should be able to figure out what's wrong?!

**Comment by typoworx-de** [comment]
I figured out at least in my case it was not only a problem of ferdium-server, but the client-app!

This ferdium-app release works for me including custom service-icons using my own ferdium-server (recent version!):

Version: 6.2.2
Server: Custom Server
Electron: 21.3.3
Chrome: 106.0.5249.199
Node.js: 16.16.0
Platform: Linux 5.15
Arch: x64
Build date: Mon Dec 05 2022 04:09:43 GMT+0100 (Mitteleuropäische Normalzeit)
Git SHA: 8700f5ca
Git branch: release

**Comment by typoworx-de** [comment]
I've done some debugging on this annyoing issue. I noticed (at least for me) the most recent ferdium-app (client-app) had some bug in chaning the service-icons.

Testing with an older release (6.2.2) the app reacts on changing the service-icon, but it still disappears showing no service-icon (not even the default one).

I've enabled the chrome-debugger in Ferdium-App and noticed this pointing the debugger to this place:
 
![image](https://github.com/ferdium/ferdium-app/assets/1282298/dc673d95-76ac-4b09-bc14-64ede5043d6b)

The image-container in DOM looks like this:
`<div class="image-upload__preview" style="background-image: url('my-custom-ferdium-server.com/v1/icon/63795208-c9b0-4293-ae02-6ddcf83da582ff139e5c-d222-4b69-97ce-528ed1ec5ab2.png');"></div>`

Changing the background-image url by adding 'https://' the icon appears! Obviously there's a bug in the client app which forgets to add the right protocol for the HTTP(s) URI to the ferdium-server URL?!

Just for notice when adding the custom-server I added ```https://``` and it was not even possible to forget it there as it's validated.

**Comment by typoworx-de** [comment]
According to my last update on debugging I've tested the same ferdium-app (client) version against the official ferdium-server (not custom server!). And there the custom service-icons are working from scratch :thinking:

**Comment by SpecialAro** [comment]
Hi @typoworx-de! 

In fact, this issue might be solved in the latest tag of ferdium-server, in this commit https://github.com/ferdium/ferdium-server/commit/cc3e1dfbf6afff83601935d32b9165d4d15d567f .

You would have to manually re-upload all the non-working custom icons, but they should work afterwards (if you are using docker, make sure to mount the `/app/tmp` (to a docker volume or host directory) so that the uploaded icons persist when restarting/rebuilding the container.

As per your comment in https://github.com/ferdium/ferdium-server/issues/64#issuecomment-1755020532 I can see that you wrongly setting the `APP_URL` env var. It should be, for instance, `- APP_URL=https://api.ferdium.org` -> include the protocol.
This is, in fact, how we have it in the official ferdium server.

I'm closing this (and https://github.com/ferdium/ferdium-server/issues/64) issue(s). If you find any difficulty feel free to ping me on discord on to comment below to re-open them.
