### ISSUE TITLE
Bug: Fresh install/config can't add some services - does nothing when adding

### ISSUE THREAD

**Issue by DomingoMontoya** [ferdium/ferdium-app#936]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.5-nightly.1

### What Operating System are you using?

Other Linux

### Operating System Version

OpenSuSE Tumbleweed Linux/KDE

### What arch are you using?

x64

### Expected Behavior

Ability to add all services

### Actual Behavior

Some services will not add.

### Steps to reproduce

When I select to add some services, and hit the save button at the bottom, it does not add the services to my services, and the number of services I have installed does not increment.

I started up Ferdium for the first time, in a long time, from flatpak and noticed it on stable branch. I then uninstalled the flatpak and wiped the .var/app/org.ferdi* folder and tried again, to no avail.

I downloaded stable appimage - same problem.

Downloaded the nightly appimage - same problem.

Services that I have noticed will not add:

Element
Google Calandar
Bitwarden

### Additional information

As I was writing this - I noticed that changing the url of the service allows it to be added. I added a / to the bitwarden url.

**Comment by vraravam** [comment]
The url validation logic might have changed over time, and this was not verified against all the service recipes. Could you please recall what services you were trying to add (which didn't get added) and send that list here? It would help us fix them. TIA

**Comment by taneharre** [comment]
Element and Cinny are two.

Version: 6.2.4
Server: No Server
Electron: 22.1.0
Chrome: 108.0.5359.179
Node.js: 16.17.1
Platform: Linux 5.10
Arch: x64
Build date: Sat Jan 28 2023 00:30:47 GMT+0100 (Central European Standard Time)
Git SHA: 68e85c3e
Git branch: release
