### ISSUE TITLE
Bug: WhatsApp starting in Light Mode

### ISSUE THREAD

**Issue by not-sample-text** [ferdium/ferdium-app#939]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.4

### What Operating System are you using?

Windows

### Operating System Version

Windows 10 20H2

### What arch are you using?

x64

### Expected Behavior

WhatsApp starting up in **Dark Mode**.

### Actual Behavior

WhatsApp starts up in **Light Mode** even if **Dark Mode** is enabled.
To get it working again, I have to "disable" **Dark Mode** and reenable it.

### Steps to reproduce

1. Open WhatsApp.
2. See **Dark Mode** doesn't work...

### Debug link

https://debug.ferdium.org/a5d2c6d0-2bc9-4123-afef-a15a270c2ce9

**Comment by vraravam** [comment]
I am using WA within Ferdium almost 20 hrs a day. ie its not in hibernation mode or anything. I have it set to dark mode, and I don't experience this issue. I'm running the latest nightly build `6.2.5-nightly.4`. The only other difference that I can see is that I'm on an m1 mac.

**Comment by SpecialAro** [comment]
@not-sample-text can you manually change the setting on the WhatsApp settings?

**Comment by not-sample-text** [comment]
> @not-sample-text can you manually change the setting on the WhatsApp settings?

I should've checked that first, huh?
Problem solved, thank you!

**Comment by Cozynezz** [comment]
dark mode didnt work for me on whattsapp, can anyone tell me why?
