### ISSUE TITLE
Bug: Gmail hangs with "Loading..." when deleting individual emails

### ISSUE THREAD

**Issue by theretohere** [ferdium/ferdium-app#947]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.4

### What Operating System are you using?

Other Linux

### Operating System Version

Linux Mint 21.1

### What arch are you using?

x64

### Expected Behavior

For every email. In Gmail, click on an email to open and read it. Click the garbage can to delete it. Email window closes, you are returned to the list of emails or to the next message depending on your gmail settings.

### Actual Behavior

For some emails. In Gmail, click on an email to open and read it. Click the garbage can to delete it. The message "Loading..." appears at the top of the gmail widnow. Nothing more happens. I have let the window sit there for over 60 mintues with no change. Have to press the "Mail" icon in Gmail to get my mail list to show again.

### Steps to reproduce

1. Click Gmail
2. Click on an email to open and read it. 
3. Click the garbage can in Gmail to delete the currently open email. 
4. The message "Loading..." appears at the top of the gmail widnow. 
5. Have to press the "Mail" icon in Gmail to get my mail list to show again.

### Additional information

I do not see a pattern to the emails where this happens. But it happens multiple times per day.

**Comment by btsweber** [comment]
I see the same problem just started today.

**Comment by mcmxcdev** [comment]
I cannot reproduce this, tried by deleting various emails, also tried bulk deleting multiple emails.

Let me know if this still occurs and I will reopen the ticket.
