### ISSUE TITLE
[Recipe Request]: Line

### ISSUE THREAD

**Issue by bgwarner** [ferdium/ferdium-app#950]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-recipes/issues) for a feature request that matches the one I want to file, without success.

### Name of the service

Line

### URL of the service

https://www.line.me

### Features you want implemented

Hi All, thank you for all of your hard work and efforts with Ferdium. 
I'm trying to add Line, but I'm stumbling around in the dark as the only coding I know is basic HTML from the early 2000s. If anyone can figure it out, that would be great! I know it's not super popular in a lot of places, but Line is huge in Japan, and I'm sure there are other people who would love to have it in their Ferdium. 

Much obliged to those of you who know more than me (everyone) and think they can make it work. If not, I appreciate you taking the time to look.

**Comment by SpecialAro** [comment]
Hi @bgwarner ! I'm closing this issue because Line doesn't have a webapp (therefore it is not possible to integrate it with Ferdium).
