### ISSUE TITLE
[Bug]: Wire doesn't load

### ISSUE THREAD

**Issue by spacemolly** [ferdium/ferdium-app#952]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-recipes/issues) for a feature request that matches the one I want to file, without success.

### Ferdium Version

6.2.4

### Recipe Name

Wire

### Recipe Version

Unknown

### Last Known working version of the recipe

Unknown

### Steps to reproduce

Create a new Wire service. No need to login.

### Expected Behavior

Load Wire login screen.

### Actual Behavior

Wire has a new web app and it doesn't load in Wire. Message is:

This browser is not supported.
Download the latest version of Google Chrome, Mozilla Firefox, Opera or Microsoft Edge.

### Screenshots

<img width="1013" alt="Screenshot 2023-02-05 at 10 30 43" src="https://user-images.githubusercontent.com/82213431/216813871-6bdc38ed-a364-4c9d-9ec6-c094d7620d30.png">

### Additional Information

Presumably has to do with headers not being accepted by Wires web app.

**Comment by mcmxcdev** [comment]
Couldn't reproduce, the recipe seems to work fine with Ferdium 6.5.3-nightly.3:

![image](https://github.com/ferdium/ferdium-app/assets/16797721/54082470-ebe9-4f9d-b9e0-94b8dc6e73c8)
