### ISSUE TITLE
[Bug]: Posteo recipe signing out on reload

### ISSUE THREAD

**Issue by magnouvean** [ferdium/ferdium-app#953]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-recipes/issues) for a feature request that matches the one I want to file, without success.

### Ferdium Version

6.2.4

### Recipe Name

Posteo

### Recipe Version

1.0.0

### Steps to reproduce

1. Create posteo service and log in
2. Reload the service

### Expected Behavior

The user being logged in after reload

### Actual Behavior

The user is logged out on reload

### Additional Information

I am pretty sure this should be as simple as changing the recipe url from https://posteo.de to https://posteo.de/webmail, as that works on normal web browsers (this is the correct url for posteo webmail, posteo.de just takes you to their homepage, which is not what we want)

**Comment by martin-braun** [comment]
Please re-open, the issue is not fixed for me. Posteo logs me out when I re-open Ferdium. Also, badges seem not to work on this recipe, so I don't see when I've gotten a new mail unless I switch to the service.

**Comment by magnouvean** [comment]
Yeah I had the same problem, although it didn't log out on reload for me. If I recall correctly there is no way to have posteo stay logged in for a long period of time, as it will automatically log out after a while. I think this is the case for the web client as well (for "privacy" reasons or something), thus making it hard to fix in ferdium.
