### ISSUE TITLE
Feature: icon desaturation & brightness dimming

### ISSUE THREAD

**Issue by ylluminate** [ferdium/ferdium-app#96]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Just an idea, icons are generally too bright and get in the way visually at present. Having such different and varying colors often deters from the user interface and thus reducing focus on services. 

Moving these into the visual background by making them less eye drawing subdued greyscale would create UI consistence, appeal and less eye / focus strain. Example:
![example](https://p153.p0.n0.cdn.getcloudapp.com/items/kpuJqm5m/b4c8acd5-1349-4f7b-9f7a-998f07f070d1.jpg?v=c4c9589f93e76fad6061d7d0077ffa34)

### Proposed Solution

A couple of options might be possible:
1. implement a function to desaturate and increase contrast of icons to greyscale and then dim them so they're not pure white, but are a grey. 
2. allow/facilitate alternate icon sets to be provided during service/recipe definition. Basically each service could have different theme options and thus provide their own "dark" or muted appearance for improve appeal when desired.

### Alternatives Considered

Alternative provided above.

**Comment by SpecialAro** [comment]
Hey @ylluminate ! Thank you for your feature request. Seems a pretty cool feature to have.

You mean like this?
![image](https://user-images.githubusercontent.com/37463445/166903862-abc2721f-a7ec-45ba-9d89-04aac700b926.png)
![image](https://user-images.githubusercontent.com/37463445/166904437-3093770c-3a54-4f7f-8aca-41becfaae46a.png)

I can implement (the 1. above) it pretty easily if that's what you want.

The 2. might be a little more hard working.

**Comment by ylluminate** [comment]
Hi @SpecialAro, thanks for getting back on this. Yeah, that would be fine/good. I think the automated filtering method is simpler/easier, but I wanted to provide an alternative option as well.  I think people may still like to insert their own custom images (as I did) for clarity/recognition sometimes, but of course that will always be an option so doing it programmatically as you've shown seems ideal and looks nice enough to work for most cases.

One other thing, how did you center your icons?  I don't actually want to center mine (I like them left justified by the other service control area, but I do think it's interesting and wasn't aware of being able to center them - so I'm simply curious.

**Comment by SpecialAro** [comment]
I can make a PR with a toggle on the appearance menu to make the icons grayscale and dimmed. Users can still use their own custom images but need to be careful not to toggle this feature on, otherwise it would make changes to the custom icons as well.

I just centered the icons with the newest feature on the latest nightly (Settings > Appearance > Sidebar Services Icons Location > Center): https://github.com/ferdium/ferdium-app/releases/tag/v6.0.0-nightly.26
