### ISSUE TITLE
[Recipe Request]: Pixelfed

### ISSUE THREAD

**Issue by fabiocosta0305** [ferdium/ferdium-app#963]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-recipes/issues) for a feature request that matches the one I want to file, without success.

### Name of the service

Pixelfed (Federated ActivePub Instagram-like service)

### URL of the service

http://pixelfed.social

### Features you want implemented

I want it more integrated, with notification and so. Nowadays need to use it as a webpage

**Comment by nanawel** [comment]
For the record, this is a self-hostable app, but atm the recipe forces you to go to **[pixelfed.social](https://pixelfed.social/)**.

If you want it to work with the instance of your choice, you have to
- close Ferdium
- edit `~/.config/Ferdium/recipes/pixelfed/package.json` and set the right URL
- open it again

It should work for now, but a field just like what is available on Mastodon service would be nice.
