### ISSUE TITLE
[Bug]: Unable to login in YouTube Music because entry of text not possible in login screen.

### ISSUE THREAD

**Issue by subham2024** [ferdium/ferdium-app#964]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-recipes/issues) for a feature request that matches the one I want to file, without success.

### Ferdium Version

6.2.3

### Recipe Name

YouTube Music

### Recipe Version

1.3.0

### Last Known working version of the recipe

Not Applicable.

### Steps to reproduce

1. Add YouTube Music service.
2. Click on Sign In button in right top corner.
3. Click on field to enter "Email or phone" , where cursor for entering texts DOES NOT appear.

### Expected Behavior

Cursor should appear for entering email id or phone number for logging in YouTube Music from keyboard. 

### Actual Behavior

Nothing happens on clicking text field for entering email id or phone number

### Additional Information

Operating System : Arch Linux

**Comment by mcmxcdev** [comment]
Cannot reproduce this on Ubuntu 23.04 using YouTube Music recipe v1.4.0:

[Screencast from 2023-09-20 16-07-00.webm](https://github.com/ferdium/ferdium-app/assets/16797721/4c6859b9-af31-4e50-beb9-ab6926d737f2)

Is this still an issue?

**Comment by subham2024** [comment]
I have stopped using ferdium and Arch Linux. So i don't know whether this issue still persists.

**Comment by mcmxcdev** [comment]
Oh I see, I will consider it resolved then!

I hope you can give Ferdium another chance at some point ;)
